<?php

declare(strict_types=1);

return [
    [
        'slug' => 'bluesky_now_live',
        'category' => 'product_launch',
        'name' => 'No ar',
        'description' => 'Anuncie um lançamento no clima aberto e descentralizado do Bluesky.',
        'content' => "No ar: [feature/produto] do {{brand_name}}.\n\nO que mudou: [resumo em uma linha].\n\nPra quem é: [quem se beneficia].\n\nLink → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_thought',
        'category' => 'industry_tip',
        'name' => 'Pensamento curto',
        'description' => 'Uma observação concisa que soa natural no Bluesky.',
        'content' => "[Observação sobre seu setor, contada em uma ou duas frases.]\n\nSimples, mas vale dizer em voz alta.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_invite',
        'category' => 'engagement',
        'name' => 'Convite à comunidade',
        'description' => 'Chame a comunidade pra um tema ou conversa.',
        'content' => "Se você se importa com [tema], a gente quer ouvir você.\n\nO que tem rondado sua cabeça ultimamente?\n\n- time {{brand_name}}",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_changelog_drop',
        'category' => 'product_launch',
        'name' => 'Changelog novo',
        'description' => 'Post de changelog direto pra um release.',
        'content' => "v[versão] saiu.\n\n• [mudança 1]\n• [mudança 2]\n• [bug fix]\n\nSem migrations. Notas completas: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_open_beta',
        'category' => 'product_launch',
        'name' => 'Beta aberto',
        'description' => 'Convide usuários pra um beta público.',
        'content' => "Beta aberto: [feature] tá no ar pra quem quiser testar.\n\nTem partes meio ásperas. É justamente o ponto. Bug reports são bem-vindos.\n\nInscreva-se: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_api_release',
        'category' => 'product_launch',
        'name' => 'Release de API',
        'description' => 'Anuncie uma nova API ou feature pra desenvolvedores.',
        'content' => "Novo: [endpoint/SDK] do {{brand_name}}.\n\nDocs: [link]\nRepo de exemplo: [link]\n\nSe faltar algo nas docs, fala pra gente. A gente conserta mais rápido do que você espera.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_promo_discount',
        'category' => 'promotion',
        'name' => 'Janela de desconto',
        'description' => 'Promo com prazo, dita de forma direta.',
        'content' => "[X]% off em [plano/produto] até [data].\n\nSem cadastro de email. Sem popup. Só o código: [CÓDIGO]\n\n[link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_promo_lifetime',
        'category' => 'promotion',
        'name' => 'Lifetime deal',
        'description' => 'Oferta lifetime/early-bird voltada pra builders.',
        'content' => "Lifetime deal no {{brand_name}}: [preço] uma vez, sem mensalidade.\n\nLimitado a [número] vagas. Depois disso voltamos pro mensal.\n\nPegue uma: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_promo_referral',
        'category' => 'promotion',
        'name' => 'Bônus por indicação',
        'description' => 'Oferta de indicação direta.',
        'content' => "Indique um amigo pro {{brand_name}}, vocês dois ganham [recompensa].\n\nSem níveis. Sem ranking. Só mande seu link: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_one_thing',
        'category' => 'educational',
        'name' => 'Uma coisa que aprendi',
        'description' => 'Uma lição concreta, contada de forma simples.',
        'content' => "Uma coisa que aprendi trabalhando com [tema]:\n\n[lição concreta, uma ou duas frases].\n\nÓbvio em retrospecto. Não era óbvio antes.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_misconception',
        'category' => 'educational',
        'name' => 'Mito comum',
        'description' => 'Corrija um mito difundido na sua área.',
        'content' => "Crença comum: [mito sobre sua área].\n\nO que é verdade de fato: [correção].\n\nA diferença importa quando [cenário específico].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_quick_how',
        'category' => 'educational',
        'name' => 'Tutorial rápido',
        'description' => 'Tutorial curto sobre uma tarefa específica.',
        'content' => "Como [tarefa específica] no [ferramenta]:\n\n1. [passo]\n2. [passo]\n3. [passo]\n\nÉ isso. Sem config escondida.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_tradeoff',
        'category' => 'educational',
        'name' => 'Explicando um tradeoff',
        'description' => 'Mostre um tradeoff real do seu domínio.',
        'content' => "[Opção A] vs [Opção B] é basicamente um tradeoff entre [coisa 1] e [coisa 2].\n\nSe você se importa mais com [coisa 1], escolhe A. Se [coisa 2], escolhe B. A maioria dos times escolhe A e se arrepende depois.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_stack',
        'category' => 'behind_the_scenes',
        'name' => 'Nossa stack',
        'description' => 'Nota honesta sobre a stack vinda de dentro do time.',
        'content' => "Nossa stack no {{brand_name}}: [tech 1], [tech 2], [tech 3].\n\nEscolhemos [tech 1] por [motivo]. A gente se arrepende de ter escolhido [tech] por [motivo]. Provavelmente trocamos no próximo trimestre.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_postmortem',
        'category' => 'behind_the_scenes',
        'name' => 'Mini postmortem',
        'description' => 'Nota curta e transparente sobre um incidente.',
        'content' => "[Serviço/feature] ficou fora do ar por [duração] hoje.\n\nCausa: [explicação simples].\nFix: [o que fizemos].\n\nAdicionamos [proteção] pra que a mesma coisa não aconteça do mesmo jeito de novo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_decision',
        'category' => 'behind_the_scenes',
        'name' => 'Por que escolhemos X',
        'description' => 'Explique uma decisão recente de design ou produto.',
        'content' => "Por que escolhemos [decisão] em vez de [alternativa]:\n\n[motivo em uma frase].\n\nNão é a escolha popular. Mas combina com como nossos usuários trabalham de verdade.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_numbers',
        'category' => 'behind_the_scenes',
        'name' => 'Números que acompanhamos',
        'description' => 'Compartilhe uma métrica real e o que ela significa.',
        'content' => "Um número que a gente acompanha de verdade no {{brand_name}}: [métrica].\n\nMês passado foi [valor]. Na semana anterior, [valor].\n\nÉ a métrica que nos diz se [resultado] é real.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_testimonial_quote',
        'category' => 'testimonial',
        'name' => 'Citação de um usuário',
        'description' => 'Citação curta de um usuário, sem enfeite.',
        'content' => "De um usuário esta semana:\n\n\"[citação curta e específica sobre o produto].\"\n\n- [primeiro nome], [cargo]\n\nÉ esse tipo de feedback que mantém a gente construindo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_testimonial_workflow',
        'category' => 'testimonial',
        'name' => 'Como um cliente usa',
        'description' => 'História específica do workflow de um usuário.',
        'content' => "[Cliente/time] usa o {{brand_name}} pra [tarefa específica].\n\nAntes: [jeito antigo].\nAgora: [jeito novo].\n\nNão é dramático. Só menos atrito todo dia.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_testimonial_result',
        'category' => 'testimonial',
        'name' => 'Resultado concreto',
        'description' => 'Um resultado específico e mensurável de um cliente.',
        'content' => "[Cliente] reduziu [tarefa] de [tempo antigo] pra [tempo novo] usando o {{brand_name}}.\n\nUma mudança de workflow. Sem novas contratações.\n\nEstudo completo: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_take',
        'category' => 'industry_tip',
        'name' => 'Opinião meio impopular',
        'description' => 'Uma opinião real sobre algo do seu setor.',
        'content' => "Opinião moderada: [opinião sobre seu setor].\n\nSei que é impopular. Já mudei de ideia sobre isso duas vezes. Por enquanto acho que se sustenta.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_pattern',
        'category' => 'industry_tip',
        'name' => 'Um padrão que vejo sempre',
        'description' => 'Padrão observado entre times ou projetos.',
        'content' => "Um padrão que vejo sempre em [setor/cargo]:\n\n[padrão em uma frase].\n\nGeralmente funciona até [marco] e aí para de funcionar discretamente.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_anti_advice',
        'category' => 'industry_tip',
        'name' => 'Conselho que eu pularia',
        'description' => 'Anti-conselho: conselho comum que não se sustenta.',
        'content' => "Conselho que se ouve muito: [conselho comum].\n\nNa prática isso desmorona quando [cenário]. A versão que funciona de verdade é [conselho revisado].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_link_share',
        'category' => 'industry_tip',
        'name' => 'Link com contexto',
        'description' => 'Compartilhe um link com um motivo real pra ler.',
        'content' => "Vale a leitura: [título do artigo/post].\n\nPor quê: [uma coisa específica que o texto acerta].\n\n[link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_announce',
        'category' => 'event',
        'name' => 'Anúncio de evento',
        'description' => 'Anuncie um evento ou talk que vem aí.',
        'content' => "[Nome do evento] em [data] às [hora/timezone].\n\nTema: [o que vamos cobrir].\nFormato: [talk / Q&A / demo].\n\nGratuito, sem cadastro: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_speaking',
        'category' => 'event',
        'name' => 'Vou palestrar',
        'description' => 'Avise que você vai palestrar em uma conferência.',
        'content' => "Vou palestrar no [evento] em [data].\n\nTalk: [título ou tema da talk em palavras simples].\n\nSe você estiver por lá, dá um oi. Especialmente se você discordar da talk.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_recap',
        'category' => 'event',
        'name' => 'Recap do evento',
        'description' => 'Recap curto depois de um evento ou meetup.',
        'content' => "Recap rápido do [evento]:\n\n• [o que funcionou]\n• [o que nos surpreendeu]\n• [o que vamos fazer diferente da próxima vez]\n\nValeu a quem apareceu.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_office_hours',
        'category' => 'event',
        'name' => 'Office hours',
        'description' => 'Convite pra office hours abertas ou AMA.',
        'content' => "Office hours abertas nesta [dia] às [hora/timezone].\n\nTraga perguntas reais sobre [tema]. Prefiro responder as difíceis do que as fáceis.\n\nLink pra entrar: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_engagement_question',
        'category' => 'engagement',
        'name' => 'Pergunta real',
        'description' => 'Uma pergunta genuína, não engagement bait.',
        'content' => "Pergunta genuína pra quem trabalha com [tema]:\n\n[pergunta específica].\n\nNão é retórica. Tô travado nisso e curioso pra saber como os outros lidam.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_engagement_poll_lite',
        'category' => 'engagement',
        'name' => 'Dois lados',
        'description' => 'Um ou/ou leve pra puxar respostas.',
        'content' => "Dois lados sobre [tema]:\n\nA: [opção A]\nB: [opção B]\n\nQual você usa de verdade no dia a dia, e o que te fez escolher?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_engagement_show_us',
        'category' => 'engagement',
        'name' => 'Mostra teu setup',
        'description' => 'Convide usuários a mostrar o setup ou workflow deles.',
        'content' => "Mostra teu [setup / workflow / config] pra [tarefa].\n\nResponda com um screenshot ou uma linha. A gente tá juntando bons padrões pra compartilhar de volta.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
