<?php

declare(strict_types=1);

return [
    [
        'slug' => 'fb_story_announcement',
        'category' => 'product_launch',
        'name' => 'Aviso rápido',
        'description' => 'Chame atenção para uma novidade com um Story de 24h no Facebook.',
        'content' => "Aviso da {{brand_name}}.\n\n[Destaque em uma linha]\n\nLink no perfil.",
        'image_count' => 1,
        'image_keywords' => ['announcement', 'launch'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_promo',
        'category' => 'promotion',
        'name' => 'Promo relâmpago',
        'description' => 'Oferta por tempo limitado em formato Story.',
        'content' => "Só hoje.\n\n[Desconto]% off na {{brand_name}}.\n\nToque para comprar.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'urgency'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_question',
        'category' => 'engagement',
        'name' => 'Pergunta rápida',
        'description' => 'Pergunte algo aos seguidores para gerar respostas e reações.',
        'content' => "Rapidinho.\n\n[Pergunta para o seu público]\n\nResponda este Story.",
        'image_count' => 1,
        'image_keywords' => ['question', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_new_drop',
        'category' => 'product_launch',
        'name' => 'Novidade no ar',
        'description' => 'Apresente um produto novo com um toque visual.',
        'content' => "Chegou.\n\n[Nome do produto] da {{brand_name}}.\n\nToque para ver.",
        'image_count' => 1,
        'image_keywords' => ['new product', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_preorder',
        'category' => 'product_launch',
        'name' => 'Pré-venda aberta',
        'description' => 'Abra a pré-venda com um Story curto.',
        'content' => "Pré-venda aberta.\n\n[Produto] envia em [data].\n\nLink na bio.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_launch_day',
        'category' => 'product_launch',
        'name' => 'Dia do lançamento',
        'description' => 'Marque o lançamento ao vivo com CTA de um toque.',
        'content' => "Ao vivo agora.\n\n[Produto] saindo hoje.\n\nToque para garantir.",
        'image_count' => 1,
        'image_keywords' => ['launch', 'product reveal'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_back_in_stock',
        'category' => 'product_launch',
        'name' => 'Voltou ao estoque',
        'description' => 'Avise os seguidores que um produto esgotado voltou.',
        'content' => "Voltou ao estoque.\n\n[Produto] na {{brand_name}}.\n\nVai rápido. Toque pra ver.",
        'image_count' => 1,
        'image_keywords' => ['restock', 'available'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bogo',
        'category' => 'promotion',
        'name' => 'Compre 1 leve 2',
        'description' => 'Empurre uma oferta compre 1 leve 2 no Story.',
        'content' => "Compre 1, leve 2.\n\nEsta semana na {{brand_name}}.\n\nToque para comprar.",
        'image_count' => 1,
        'image_keywords' => ['bogo', 'sale'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_free_shipping',
        'category' => 'promotion',
        'name' => 'Frete grátis',
        'description' => 'Divulgue uma janela de frete grátis.',
        'content' => "Frete grátis.\n\n48h só na {{brand_name}}.\n\nUse o código [CODE].",
        'image_count' => 1,
        'image_keywords' => ['shipping', 'delivery box'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_last_chance',
        'category' => 'promotion',
        'name' => 'Última chance',
        'description' => 'Aviso final de desconto que está acabando.',
        'content' => "Última chance.\n\n[Desconto]% off acaba hoje à noite.\n\nToque na {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'sale ending'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_coupon_drop',
        'category' => 'promotion',
        'name' => 'Cupom liberado',
        'description' => 'Solte um código de cupom em um Story de 24h.',
        'content' => "Código [CODE].\n\n[Desconto]% off na {{brand_name}}.\n\nSome em 24h.",
        'image_count' => 1,
        'image_keywords' => ['coupon', 'promo code'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_quick_tip',
        'category' => 'educational',
        'name' => 'Dica rápida',
        'description' => 'Compartilhe uma dica útil.',
        'content' => "Dica rápida.\n\n[Uma dica prática].\n\nSalve este Story.",
        'image_count' => 1,
        'image_keywords' => ['tip', 'advice'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_did_you_know',
        'category' => 'educational',
        'name' => 'Você sabia',
        'description' => 'Surpreenda os seguidores com um fato rápido.',
        'content' => "Você sabia?\n\n[Fato curioso].\n\nMais no blog da {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['fact', 'lightbulb'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_myth_buster',
        'category' => 'educational',
        'name' => 'Mito ou verdade',
        'description' => 'Derrube um mito comum em uma única tacada.',
        'content' => "Mito: [crença comum].\n\nVerdade: [a real].\n\nToque pra entender.",
        'image_count' => 1,
        'image_keywords' => ['myth', 'truth'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_one_minute_lesson',
        'category' => 'educational',
        'name' => 'Aula de 1 minuto',
        'description' => 'Lição curta com CTA de toque.',
        'content' => "Aula de 60 segundos.\n\n[Tema] da {{brand_name}}.\n\nToque para assistir.",
        'image_count' => 1,
        'image_keywords' => ['lesson', 'teaching'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_workspace',
        'category' => 'behind_the_scenes',
        'name' => 'Bastidor do escritório',
        'description' => 'Mostre o lugar onde tudo acontece.',
        'content' => "Hoje na {{brand_name}}.\n\n[O que está rolando agora].\n\nToque para ver mais.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'office'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_team',
        'category' => 'behind_the_scenes',
        'name' => 'Conheça o time',
        'description' => 'Apresente um membro do time de forma rápida.',
        'content' => "Conheça [nome].\n\n[Cargo na {{brand_name}}].\n\nToque para dar um oi.",
        'image_count' => 1,
        'image_keywords' => ['team', 'employee'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_process',
        'category' => 'behind_the_scenes',
        'name' => 'Como é feito',
        'description' => 'Espiada rápida de como algo é produzido.',
        'content' => "Como [produto] é feito.\n\nEtapa [n] na {{brand_name}}.\n\nToque pro vídeo completo.",
        'image_count' => 1,
        'image_keywords' => ['production', 'process'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_packing',
        'category' => 'behind_the_scenes',
        'name' => 'Embalando pedidos',
        'description' => 'Mostre os pedidos saindo da casa.',
        'content' => "Embalando pedidos.\n\n[Número] saindo hoje.\n\nObrigado pelo apoio.",
        'image_count' => 1,
        'image_keywords' => ['packing', 'shipping'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_customer_quote',
        'category' => 'testimonial',
        'name' => 'Citação de cliente',
        'description' => 'Mostre uma frase curta de cliente.',
        'content' => "\"[Frase do cliente].\"\n\n- [nome]\n\nToque para ler mais.",
        'image_count' => 1,
        'image_keywords' => ['quote', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_five_star',
        'category' => 'testimonial',
        'name' => 'Avaliação 5 estrelas',
        'description' => 'Destaque uma avaliação 5 estrelas.',
        'content' => "5 estrelas.\n\n\"[Avaliação curta]\", [nome]\n\nMais na {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['five stars', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_before_after',
        'category' => 'testimonial',
        'name' => 'Antes e depois',
        'description' => 'Mostre um antes/depois com um único CTA.',
        'content' => "Antes. Depois.\n\n[Nome do cliente] usando {{brand_name}}.\n\nToque pra ver a história.",
        'image_count' => 1,
        'image_keywords' => ['before after', 'transformation'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_industry_trend',
        'category' => 'industry_tip',
        'name' => 'Tendência do setor',
        'description' => 'Solte uma sacada rápida de tendência.',
        'content' => "Tendência.\n\n[Tendência do setor em uma linha].\n\nToque pra nossa visão.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_pro_hack',
        'category' => 'industry_tip',
        'name' => 'Truque pro',
        'description' => 'Compartilhe um truque rápido de profissional.',
        'content' => "Truque pro.\n\n[Macete em uma linha].\n\nMais dicas na {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['hack', 'shortcut'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_mistake_to_avoid',
        'category' => 'industry_tip',
        'name' => 'Erro a evitar',
        'description' => 'Avise sobre um erro comum.',
        'content' => "Pare de fazer isso.\n\n[Erro comum].\n\nToque pra solução.",
        'image_count' => 1,
        'image_keywords' => ['warning', 'mistake'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_save_date',
        'category' => 'event',
        'name' => 'Reserve a data',
        'description' => 'Plante um save the date em um Story de 24h.',
        'content' => "Reserve a data.\n\n[Evento] em [data].\n\nConfirme presença na bio.",
        'image_count' => 1,
        'image_keywords' => ['calendar', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_today',
        'category' => 'event',
        'name' => 'Evento hoje',
        'description' => 'Lembrete de evento no mesmo dia.',
        'content' => "Hoje.\n\n[Evento] às [hora].\n\nToque pelo link.",
        'image_count' => 1,
        'image_keywords' => ['event', 'live'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_live_starting',
        'category' => 'event',
        'name' => 'Indo ao vivo',
        'description' => 'Leve os seguidores até a live.',
        'content' => "Indo ao vivo.\n\n[Tema] em [minutos] minutos.\n\nToque pra entrar na {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['live stream', 'broadcast'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_recap',
        'category' => 'event',
        'name' => 'Resumo do evento',
        'description' => 'Resumo rápido no dia seguinte.',
        'content' => "Foi assim o [evento].\n\nValeu por vir.\n\nResumo completo na página.",
        'image_count' => 1,
        'image_keywords' => ['event recap', 'crowd'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_poll_this_or_that',
        'category' => 'engagement',
        'name' => 'Esta ou aquela',
        'description' => 'Story estilo enquete com duas opções.',
        'content' => "[Opção A] ou [Opção B]?\n\nResponda com sua escolha.\n\nLemos todas.",
        'image_count' => 1,
        'image_keywords' => ['poll', 'choice'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_dm_us',
        'category' => 'engagement',
        'name' => 'Manda DM',
        'description' => 'Convide seguidores a mandar mensagem.',
        'content' => "Manda DM.\n\n[Motivo pra falar com a {{brand_name}}].\n\nA gente responde rápido.",
        'image_count' => 1,
        'image_keywords' => ['message', 'chat'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_caption_this',
        'category' => 'engagement',
        'name' => 'Legenda essa',
        'description' => 'Pedido de legenda em aberto.',
        'content' => "Legenda essa.\n\n[Contexto da imagem].\n\nManda a sua melhor.",
        'image_count' => 1,
        'image_keywords' => ['fun', 'reaction'],
        'slides' => null,
    ],
];
