<?php

declare(strict_types=1);

return [
    [
        'slug' => 'facebook_special_offer',
        'category' => 'promotion',
        'name' => 'Oferta especial',
        'description' => 'Divulgue uma oferta especial no Facebook com uma chamada clara para ação.',
        'content' => "🎉 Oferta especial da {{brand_name}}.\n\n[Resumo da oferta], válida só até [data].\n\nClique no link para garantir a sua: [link]\n\nFicou com alguma dúvida? Manda nos comentários, a gente lê todas.",
        'image_count' => 1,
        'image_keywords' => ['offer', 'sale', 'promotion'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_community_story',
        'category' => 'behind_the_scenes',
        'name' => 'História da comunidade',
        'description' => 'Compartilhe a história de um cliente ou momento da equipe para criar conexão.',
        'content' => "Conheça [nome].\n\n[História curta, 2 a 4 frases, sobre como essa pessoa usa a {{brand_name}} ou o que ela traz para a nossa comunidade.]\n\nÉ por isso que a gente faz o que faz. ❤️",
        'image_count' => 1,
        'image_keywords' => ['people', 'story', 'community'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_event_invite',
        'category' => 'event',
        'name' => 'Convite para evento',
        'description' => 'Convide seus seguidores para um próximo evento ou webinar.',
        'content' => "📅 Anota na agenda.\n\nA {{brand_name}} vai realizar [nome do evento] em [data] às [hora].\n\nVamos falar sobre:\n• [Tópico 1]\n• [Tópico 2]\n• [Tópico 3]\n\nA participação é gratuita. Garanta seu lugar → [link]",
        'image_count' => 1,
        'image_keywords' => ['event', 'calendar', 'invitation'],
        'slides' => null,
    ],

    // Product launch (4)
    [
        'slug' => 'facebook_new_product_reveal',
        'category' => 'product_launch',
        'name' => 'Revelação de novo produto',
        'description' => 'Anuncie um produto totalmente novo para a sua comunidade no Facebook.',
        'content' => "Depois de [número] meses de trabalho, finalmente a gente pode falar sobre isso.\n\nApresentamos [nome do produto], o(a) [descrição curta] que criamos porque [motivo]. Nosso time ouvia a mesma coisa das pessoas dessa comunidade: [pedido recorrente]. Então fizemos.\n\nA {{brand_name}} envia o primeiro lote em [data]. O link está no primeiro comentário.\n\nO que você quer saber sobre ele? Deixa sua pergunta aqui embaixo que a gente responde uma por uma essa semana.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_product_restock',
        'category' => 'product_launch',
        'name' => 'Anúncio de reposição de produto',
        'description' => 'Avise seus seguidores que um produto esgotado voltou ao estoque.',
        'content' => "Voltou.\n\nO [nome do produto] esgotou em [período] da última vez, e muita gente ficou na lista de espera. Repusemos hoje de manhã com [quantidade] unidades.\n\nSe você perdeu antes, esse é o seu lembrete: [link]\n\nPara quem já tem um, o que você diria para alguém que está pensando em comprar?",
        'image_count' => 1,
        'image_keywords' => ['product', 'restock', 'shelf'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_feature_release',
        'category' => 'product_launch',
        'name' => 'Lançamento de novo recurso',
        'description' => 'Anuncie um novo recurso adicionado a um produto que já existe.',
        'content' => "Atualização pequena, diferença grande.\n\nA {{brand_name}} acabou de liberar [nome do recurso]. Vocês pediram nos comentários mais vezes do que a gente conseguia contar, então aí está: [explicação em uma frase do que ele faz].\n\nJá está disponível para todo mundo a partir de hoje. Não precisa atualizar nada.\n\nSe você testar essa semana, conta o que achou. A gente já está anotando ideias para o próximo lançamento.",
        'image_count' => 1,
        'image_keywords' => ['feature', 'update', 'screen'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_preorder_open',
        'category' => 'product_launch',
        'name' => 'Anúncio de pré-venda',
        'description' => 'Abra a pré-venda de um produto que ainda vai ser lançado.',
        'content' => "A pré-venda está aberta.\n\nO [nome do produto] começa a ser entregue em [data], e essa comunidade vai poder pedir antes. O preço de pré-venda é [preço] até [prazo], e tem só [quantidade] vagas no primeiro lote.\n\nO link está aqui: [link]\n\nSe você tem dúvida sobre [preocupação comum: entrega / tamanho / especificações], pergunta nos comentários. A gente fica por aqui a tarde toda.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product', 'package'],
        'slides' => null,
    ],

    // Promotion (3)
    [
        'slug' => 'facebook_flash_sale',
        'category' => 'promotion',
        'name' => 'Alerta de promoção relâmpago',
        'description' => 'Anuncie uma promoção relâmpago de curta duração com senso de urgência.',
        'content' => "Promoção relâmpago, só hoje.\n\n[Desconto] em [produto/categoria] até meia-noite. Use o cupom [CÓDIGO] no checkout.\n\nEsse é o menor preço que vamos oferecer essa temporada, e só voltamos a fazer em [próxima data].\n\nLink no primeiro comentário. Marca um amigo que está de olho nisso.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_holiday_promo',
        'category' => 'promotion',
        'name' => 'Promoção de feriado',
        'description' => 'Faça uma promoção temática de feriado com tom amigável.',
        'content' => "Feliz [nome do feriado] de todos nós da {{brand_name}}.\n\nPara dizer obrigado por fazer parte desse ano, estamos dando [desconto] em [produto/categoria] de [data inicial] até [data final]. Use o cupom [CÓDIGO].\n\nSeja lá o que você está comemorando essa semana, que seja bom. Conta nos comentários como você vai passar o feriado.",
        'image_count' => 1,
        'image_keywords' => ['holiday', 'celebration', 'gift'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_bundle_deal',
        'category' => 'promotion',
        'name' => 'Promoção de combo',
        'description' => 'Promova um combo de produtos com economia.',
        'content' => "Dois favoritos nossos, melhores juntos.\n\n[Produto A] + [Produto B] agora viraram combo, e o combo te dá [valor] de economia em comparação com comprar separado. Juntamos os dois porque os clientes não paravam de pedir os dois no mesmo carrinho.\n\nGaranta o seu aqui: [link]\n\nSe você já tem um deles, o outro é a peça que faltava. Pode confiar.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'products', 'package'],
        'slides' => null,
    ],

    // Educational (4)
    [
        'slug' => 'facebook_how_to_guide',
        'category' => 'educational',
        'name' => 'Guia passo a passo',
        'description' => 'Ensine seu público a fazer algo útil.',
        'content' => "Como [tarefa] em menos de [tempo].\n\n1. [Passo 1 com um detalhe real, não uma instrução vaga]\n2. [Passo 2]\n3. [Passo 3]\n4. [Passo 4]\n\nA parte que a maioria pula é o [número do passo]. Se você só fizer uma coisa, faça essa.\n\nQual é a dúvida sobre [tema] que você sempre adia para pesquisar? Pergunta aqui embaixo que a gente responde na próxima semana.",
        'image_count' => 1,
        'image_keywords' => ['tutorial', 'guide', 'how to'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_myth_buster',
        'category' => 'educational',
        'name' => 'Mito vs. verdade',
        'description' => 'Desmonte um mito comum do seu setor.',
        'content' => "Tem um mito sobre [tema] que não vai embora.\n\nO mito: [crença comum].\n\nO que acontece de verdade: [explicação correta, 2 a 3 frases com um exemplo ou número específico].\n\nA gente escuta isso há anos. Se você também acreditava, está em boa companhia, a maioria acreditava. Agora você sabe.\n\nQuais outros mitos do [setor] te tiram do sério?",
        'image_count' => 1,
        'image_keywords' => ['fact check', 'information', 'thinking'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_quick_tip',
        'category' => 'educational',
        'name' => 'Dica rápida',
        'description' => 'Compartilhe uma dica curta que seu público pode usar hoje.',
        'content' => "Dica rápida que você pode usar hoje.\n\nSe você [situação comum], experimente [ação específica] em vez de [abordagem usual]. O motivo: [explicação em uma frase de por que funciona].\n\nA gente começou a fazer isso com [exemplo] e mudou a forma como a gente [resultado]. Mudança pequena, diferença real.\n\nTesta essa semana e conta como foi.",
        'image_count' => 1,
        'image_keywords' => ['tip', 'lightbulb', 'idea'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_common_mistake',
        'category' => 'educational',
        'name' => 'Erro comum para evitar',
        'description' => 'Ajude seus leitores a evitar um erro comum no seu campo.',
        'content' => "O erro mais comum que a gente vê em [tema]: [erro específico].\n\nGeralmente acontece quando [contexto]. O resultado é [consequência], e quando você percebe, [prejuízo].\n\nO que fazer no lugar: [alternativa clara]. Leva [tempo/esforço] a mais no começo e te poupa [benefício] depois.\n\nSe você já fez isso, não está sozinho. A gente também já fez. Qual é um erro que você queria que alguém tivesse te avisado antes?",
        'image_count' => 1,
        'image_keywords' => ['mistake', 'warning', 'lesson'],
        'slides' => null,
    ],

    // Behind the scenes (4)
    [
        'slug' => 'facebook_team_intro',
        'category' => 'behind_the_scenes',
        'name' => 'Apresentação de membro do time',
        'description' => 'Apresente um membro da equipe para a comunidade.',
        'content' => "Diga oi para [nome].\n\n[Nome] é nosso(a) [cargo] e está com a {{brand_name}} há [tempo]. É por causa dele(a) que [coisa específica que essa pessoa cuida ou melhorou], e se você já mandou e-mail para o suporte, é bem provável que ele(a) tenha respondido.\n\nCuriosidade: [um detalhe humano, hobby, talento estranho, lanche favorito].\n\nManda um oi nos comentários para receber.",
        'image_count' => 1,
        'image_keywords' => ['team', 'portrait', 'workplace'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_workspace_tour',
        'category' => 'behind_the_scenes',
        'name' => 'Tour pelo espaço de trabalho',
        'description' => 'Mostre aos seguidores onde você trabalha ou cria.',
        'content' => "Uma espiada no lugar onde o trabalho acontece.\n\nEsse é o(a) [nome da sala/espaço] da {{brand_name}}. [Um detalhe específico, a iluminação, a bagunça, o canto que todo mundo disputa]. A gente passa a maior parte do dia aqui, e dá para perceber.\n\n[Segundo detalhe, algo visível na foto que tem uma história por trás].\n\nE o seu espaço de trabalho, está como agora? Resposta honesta, com xícaras de café e tudo mais.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'office', 'studio'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_making_of',
        'category' => 'behind_the_scenes',
        'name' => 'Bastidores do processo',
        'description' => 'Mostre como um produto ou trabalho é feito.',
        'content' => "Já se perguntou como o(a) [produto/serviço] é feito de verdade?\n\nComeça com [primeiro passo] e termina com [último passo]. No meio tem muito de [descrição honesta, teste, refazer, repensar]. A versão que você acaba comprando geralmente é a [número] tentativa.\n\nAqui vai um registro do lote dessa semana. O(a) [detalhe específico] é a parte que ninguém vê mas todo mundo nota quando está bem feita.\n\nDúvidas sobre o processo? Pode mandar.",
        'image_count' => 1,
        'image_keywords' => ['workshop', 'process', 'craft'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_milestone_celebration',
        'category' => 'behind_the_scenes',
        'name' => 'Comemoração de marco',
        'description' => 'Comemore um marco importante com a comunidade.',
        'content' => "Hoje é [marco, aniversário, número de clientes, qualquer coisa real].\n\nA gente começou a {{brand_name}} há [tempo] com [detalhe honesto da origem, a mesa da cozinha, um cliente, um notebook emprestado]. O plano era simples e meio ingênuo: [objetivo original].\n\n[Marco] depois, a gente segue por aqui, principalmente por causa das pessoas dessa comunidade que continuaram aparecendo. Obrigado, de verdade.\n\nConta nos comentários, quando você nos descobriu pela primeira vez?",
        'image_count' => 1,
        'image_keywords' => ['celebration', 'milestone', 'anniversary'],
        'slides' => null,
    ],

    // Testimonial (3)
    [
        'slug' => 'facebook_customer_quote',
        'category' => 'testimonial',
        'name' => 'Depoimento de cliente',
        'description' => 'Compartilhe um depoimento de cliente nas próprias palavras.',
        'content' => "\"[Frase direta do cliente, mantenha específica, com a voz dele(a), com um resultado ou sentimento real.]\"\n\n- [Nome do cliente], [cidade ou função]\n\nA gente recebeu essa mensagem [tempo] atrás e perguntou se podia compartilhar. [Primeiro nome] disse sim. Somos gratos por palavras assim e por todo mundo que tira um minuto para mandar.\n\nSe a {{brand_name}} fez parte da sua história também, a gente adoraria ouvir nos comentários.",
        'image_count' => 1,
        'image_keywords' => ['testimonial', 'happy customer', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_before_after_story',
        'category' => 'testimonial',
        'name' => 'História de antes e depois',
        'description' => 'Conte uma história de transformação de cliente.',
        'content' => "Antes: [situação do cliente quando encontrou a {{brand_name}}, descreva em 2 a 3 frases honestas].\n\nDepois: [o que mudou, com um resultado específico e prazo].\n\n[Nome do cliente] mandou essa atualização no mês passado, e é o tipo de coisa que faz todo mundo no escritório ficar quieto por um segundo. Não foi a gente que fez o trabalho, foi ele(a). A gente só ajudou onde dava.\n\nSe você está em dúvida sobre [hesitação comum], histórias assim podem ser o motivo para começar.",
        'image_count' => 1,
        'image_keywords' => ['transformation', 'progress', 'result'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_review_highlight',
        'category' => 'testimonial',
        'name' => 'Destaque de avaliação',
        'description' => 'Destaque uma avaliação recente com contexto.',
        'content' => "Avaliação 5 estrelas de [nome do cliente] essa semana:\n\n\"[Tire uma frase real e específica da avaliação, não o elogio genérico, a parte com o detalhe de verdade.]\"\n\nA gente guarda avaliações assim e relê nos dias difíceis. Obrigado, [primeiro nome].\n\nSe você tem alguns minutos e a {{brand_name}} te ajudou, deixar uma avaliação aqui é a coisa mais gentil que você pode fazer pela gente: [link]",
        'image_count' => 1,
        'image_keywords' => ['review', 'stars', 'feedback'],
        'slides' => null,
    ],

    // Industry tip (3)
    [
        'slug' => 'facebook_industry_insight',
        'category' => 'industry_tip',
        'name' => 'Insight do setor',
        'description' => 'Compartilhe um insight útil do seu setor.',
        'content' => "Uma coisa que a gente percebeu trabalhando em [setor] esse ano:\n\n[Observação específica, uma mudança, um padrão, uma descoberta contraintuitiva. 2 a 3 frases com um número ou exemplo.]\n\nA gente não acha que isso vai voltar atrás tão cedo, e os negócios que se prepararem agora vão ter menos dificuldade do que os que esperarem.\n\nVocê está vendo a mesma coisa? Curioso para saber como tem sido a sua experiência.",
        'image_count' => 1,
        'image_keywords' => ['insight', 'industry', 'analysis'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_pro_tip',
        'category' => 'industry_tip',
        'name' => 'Dica de quem já viveu',
        'description' => 'Compartilhe uma dica aprendida na prática.',
        'content' => "Uma dica de profissional que a gente aprendeu da maneira difícil:\n\nQuando você [cenário comum], sempre [ação específica]. A gente costumava pular esse passo porque parecia trabalho a mais, até que [história, o que deu errado].\n\nAgora é a primeira coisa que a gente faz, sempre. Leva [tempo] e evita [problema].\n\nQual dica você daria para alguém começando agora em [área]?",
        'image_count' => 1,
        'image_keywords' => ['expertise', 'professional', 'advice'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_industry_trend',
        'category' => 'industry_tip',
        'name' => 'Tendência do setor explicada',
        'description' => 'Explique uma tendência em linguagem simples.',
        'content' => "Todo mundo em [setor] está falando de [tendência]. Aqui vai o que isso significa de verdade, em palavras simples.\n\n[Explicação em 2 a 3 frases, sem jargão, com um exemplo concreto.]\n\nSe vai dar no que prometem, é outra história. Nossa opinião: [opinião honesta, o que levar a sério, o que ignorar].\n\nE você, o que acha? Curioso para saber onde a comunidade está nessa.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry', 'explainer'],
        'slides' => null,
    ],

    // Event (3)
    [
        'slug' => 'facebook_event_recap',
        'category' => 'event',
        'name' => 'Resumo do evento',
        'description' => 'Compartilhe um resumo depois que o evento acabou.',
        'content' => "[Nome do evento] acabou e a gente ainda está se recuperando.\n\n[Número] de vocês apareceram, fizeram boas perguntas e ficaram até tarde. Destaques: [momento 1], [momento 2] e a parte em que [coisa específica engraçada ou marcante].\n\nUm muito obrigado para todo mundo que veio. Se você perdeu, a gente gravou a sessão principal e o link está no primeiro comentário.\n\nQual foi seu momento preferido do dia? Marca alguém que você conheceu lá.",
        'image_count' => 1,
        'image_keywords' => ['event', 'recap', 'crowd'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_event_countdown',
        'category' => 'event',
        'name' => 'Contagem regressiva para evento',
        'description' => 'Crie expectativa conforme o evento se aproxima.',
        'content' => "Faltam [número] dias para [nome do evento].\n\nSe você ainda não garantiu seu lugar, a hora é agora. Sobraram [número] vagas, e na última semana elas costumam acabar rápido.\n\nO que esperar em [data]: [um detalhe real], [outro detalhe real] e tempo para conversar de verdade com as pessoas, não só ficar olhando slides.\n\nGaranta seu ingresso aqui: [link]\n\nQuem vai? Comenta para a gente saber quem procurar.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'event', 'tickets'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_workshop_announcement',
        'category' => 'event',
        'name' => 'Anúncio de workshop',
        'description' => 'Anuncie um workshop prático.',
        'content' => "Vamos fazer um workshop sobre [tema].\n\n[Data] às [hora]. Vagas limitadas a [número] pessoas porque é mão na massa, não webinar. Você sai de lá com [resultado específico, uma coisa pronta, uma configuração funcionando, um plano escrito].\n\nPara quem é: [público]. Para quem não é: [aviso honesto].\n\nDetalhes e inscrição: [link]\n\nDúvidas se faz sentido para você? Pergunta nos comentários.",
        'image_count' => 1,
        'image_keywords' => ['workshop', 'learning', 'hands on'],
        'slides' => null,
    ],

    // Engagement (3)
    [
        'slug' => 'facebook_question_prompt',
        'category' => 'engagement',
        'name' => 'Pergunta para a comunidade',
        'description' => 'Faça uma pergunta reflexiva para a comunidade.',
        'content' => "Pergunta sincera para a comunidade.\n\nQuando você [situação comum relacionada à {{brand_name}}], como você costuma [decisão específica]? A gente está perguntando porque vê o mesmo assunto aparecer nas DMs, e tem uma intuição de que a nossa resposta não é a única boa.\n\nNão tem resposta errada. A gente lê todos os comentários.",
        'image_count' => 1,
        'image_keywords' => ['question', 'conversation', 'people talking'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_this_or_that',
        'category' => 'engagement',
        'name' => 'Enquete isso ou aquilo',
        'description' => 'Faça um post divertido no estilo isso ou aquilo.',
        'content' => "Resolve um debate que a gente tem tido a semana toda.\n\n[Opção A] ou [Opção B]?\n\nSem pensar muito. Primeira reação, nos comentários.\n\nPara constar, o time está dividido [número] a [número]. A gente conta o lado vencedor na sexta.",
        'image_count' => 1,
        'image_keywords' => ['choice', 'comparison', 'options'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_fill_in_blank',
        'category' => 'engagement',
        'name' => 'Complete a frase',
        'description' => 'Convide os seguidores a completar uma frase.',
        'content' => "Complete a frase:\n\nUma coisa que eu queria ter sabido antes de [tema] é __________.\n\nA gente começa: [sua resposta honesta, com uma história real junto].\n\nAgora é sua vez. As melhores respostas que a gente recebe nesse tipo de pergunta acabam ajudando alguém que vai ler depois, então não segura.",
        'image_count' => 1,
        'image_keywords' => ['conversation', 'thinking', 'community'],
        'slides' => null,
    ],
];
