<?php

declare(strict_types=1);

return [
    [
        'slug' => 'feature_launch_carousel',
        'category' => 'product_launch',
        'name' => 'Lançamento de funcionalidade',
        'description' => 'Anuncie uma nova funcionalidade do produto em um carrossel de 5 slides.',
        'content' => 'A {{brand_name}} acabou de lançar algo que estamos animados pra mostrar. Arraste para ver o que tem de novo.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'O que tem de novo', 'body' => 'Uma olhada rápida na atualização mais recente.', 'image_keywords' => ['product', 'launch']],
            ['title' => 'Como funciona', 'body' => 'Três passos e você já está usando.', 'image_keywords' => ['workflow']],
            ['title' => 'Por que isso importa', 'body' => 'Mais rápido, mais simples, com menos cliques.', 'image_keywords' => ['speed']],
            ['title' => 'Pra quem é', 'body' => 'Feito para times que entregam.', 'image_keywords' => ['team']],
            ['title' => 'Experimente agora', 'body' => 'Disponível hoje. Link na bio.', 'image_keywords' => ['phone', 'app']],
        ],
    ],
    [
        'slug' => 'five_tips_carousel',
        'category' => 'educational',
        'name' => 'Carrossel de 5 dicas',
        'description' => 'Compartilhe cinco dicas práticas em um carrossel para arrastar.',
        'content' => '5 coisas que eu queria ter sabido antes sobre [tópico]. Salve pra ler depois. 👇',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Dica #1', 'body' => '[Primeira dica, seja específico e prático.]', 'image_keywords' => ['idea', 'lightbulb']],
            ['title' => 'Dica #2', 'body' => '[Segunda dica, use um exemplo real se puder.]', 'image_keywords' => ['notebook']],
            ['title' => 'Dica #3', 'body' => '[Terceira dica, seja curto.]', 'image_keywords' => ['focus']],
            ['title' => 'Dica #4', 'body' => '[Quarta dica, algo surpreendente ou que vai contra o senso comum.]', 'image_keywords' => ['surprise']],
            ['title' => 'Dica #5', 'body' => '[Quinta dica, termine forte com um aprendizado.]', 'image_keywords' => ['success']],
        ],
    ],
    [
        'slug' => 'process_reveal_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Revelação do processo',
        'description' => 'Mostre aos seguidores como você cria seu produto ou serviço.',
        'content' => 'Já se perguntou como [produto/serviço] é feito? Arraste para ver cada etapa. ✨',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Tudo começa com pesquisa', 'body' => 'Todo projeto começa entendendo o problema a fundo.', 'image_keywords' => ['research', 'desk']],
            ['title' => 'Design e iteração', 'body' => 'A gente prototipa rápido e testa muito.', 'image_keywords' => ['design', 'sketch']],
            ['title' => 'Construindo de verdade', 'body' => 'Capricho e precisão em cada detalhe.', 'image_keywords' => ['craft', 'build']],
            ['title' => 'O resultado final', 'body' => 'Qualidade que você sente assim que usa.', 'image_keywords' => ['product', 'final']],
        ],
    ],
    [
        'slug' => 'quick_stat_carousel',
        'category' => 'industry_tip',
        'name' => 'Carrossel de estatísticas rápidas',
        'description' => 'Apresente dados do setor em um carrossel visual.',
        'content' => 'Os números de [setor] que todo profissional de marketing precisa acompanhar este ano. 📊',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Dado #1', 'body' => '[X]% de [público] dizem [descoberta]. Fonte: [fonte]', 'image_keywords' => ['chart', 'data']],
            ['title' => 'Dado #2', 'body' => '[Y]% de aumento em [métrica] ano após ano.', 'image_keywords' => ['growth', 'graph']],
            ['title' => 'Dado #3', 'body' => 'Até [ano], [projeção].', 'image_keywords' => ['future', 'trend']],
            ['title' => 'O que isso significa pra você', 'body' => '[Conclusão prática com base nos dados acima.]', 'image_keywords' => ['action', 'plan']],
        ],
    ],
    [
        'slug' => 'event_recap_carousel',
        'category' => 'event',
        'name' => 'Resumo do evento',
        'description' => 'Recapitule os destaques de um evento ou conferência recente.',
        'content' => 'Acabamos de encerrar [Nome do Evento] e foi incrível. Veja os destaques. 🙌',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Tudo começou com…', 'body' => '[Momento de abertura ou destaque da palestra principal.]', 'image_keywords' => ['conference', 'stage']],
            ['title' => 'A palestra que todo mundo comentou', 'body' => '[Insight principal da palestra que se destacou.]', 'image_keywords' => ['presentation', 'crowd']],
            ['title' => 'Conexão com a comunidade', 'body' => '[Destaque de networking ou momentos com participantes.]', 'image_keywords' => ['networking', 'people']],
            ['title' => 'Até a próxima', 'body' => 'Siga a {{brand_name}} para novidades sobre nosso próximo evento.', 'image_keywords' => ['celebration']],
        ],
    ],
    [
        'slug' => 'product_lineup_carousel',
        'category' => 'product_launch',
        'name' => 'Revelação da linha de produtos',
        'description' => 'Revele uma linha completa de produtos, um item por slide.',
        'content' => 'Fizemos [número] coisas novas. Aqui vai a linha completa da {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'conheça a linha', 'body' => '[Número] peças novas, pensadas em conjunto. Cada uma resolve um problema específico.', 'image_keywords' => ['products', 'lineup']],
            ['title' => 'peça um', 'body' => '[Nome do produto 1]. Ideal para [caso de uso].', 'image_keywords' => ['product', 'studio']],
            ['title' => 'peça dois', 'body' => '[Nome do produto 2]. Combina com a peça um se você quer [benefício].', 'image_keywords' => ['object', 'detail']],
            ['title' => 'peça três', 'body' => '[Nome do produto 3]. A que ficamos refazendo até ficar do jeito certo.', 'image_keywords' => ['craft', 'closeup']],
            ['title' => 'compre o lançamento', 'body' => 'Disponível em [data]. Link na bio.', 'image_keywords' => ['shop', 'phone']],
        ],
    ],
    [
        'slug' => 'before_after_launch_carousel',
        'category' => 'product_launch',
        'name' => 'Antes e depois do lançamento',
        'description' => 'Mostre o upgrade da versão antiga para a nova.',
        'content' => 'Mesma ideia, refeita. Veja o que mudou no novo [produto] da {{brand_name}}.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'antes', 'body' => '[A versão antiga. O que ela fazia bem e onde deixava a desejar.]', 'image_keywords' => ['old', 'product']],
            ['title' => 'depois', 'body' => '[A nova versão. Uma frase sobre a maior mudança.]', 'image_keywords' => ['new', 'product']],
            ['title' => 'o que arrumamos', 'body' => '[Problema específico que os clientes contaram, e como resolvemos.]', 'image_keywords' => ['detail', 'redesign']],
            ['title' => 'já disponível', 'body' => 'Encontre na loja. Link na bio.', 'image_keywords' => ['store', 'phone']],
        ],
    ],
    [
        'slug' => 'spec_breakdown_carousel',
        'category' => 'product_launch',
        'name' => 'Carrossel de especificações',
        'description' => 'Detalhe as especificações do produto em vários slides.',
        'content' => 'A ficha técnica completa do [produto]. Tudo que tem dentro, em um carrossel.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'conheça [produto]', 'body' => 'Feito para [caso de uso]. Disponível em [data].', 'image_keywords' => ['product', 'reveal']],
            ['title' => 'materiais', 'body' => '[Detalhes dos materiais. De onde vem. Por que importa pro toque final.]', 'image_keywords' => ['materials', 'texture']],
            ['title' => 'dimensões', 'body' => '[Tamanho, peso, notas de caimento. Os números que as pessoas vão querer antes de comprar.]', 'image_keywords' => ['measurement', 'detail']],
            ['title' => 'como se comporta', 'body' => '[Número de desempenho principal. Bateria, autonomia, força de fixação, o que fizer sentido.]', 'image_keywords' => ['performance', 'test']],
            ['title' => 'o que vem na caixa', 'body' => '[Liste os itens: produto, acessórios, manual, etc.]', 'image_keywords' => ['unboxing', 'box']],
            ['title' => 'compre o seu', 'body' => 'Link na bio. Envio em [prazo].', 'image_keywords' => ['shipping', 'parcel']],
        ],
    ],
    [
        'slug' => 'flash_sale_carousel',
        'category' => 'promotion',
        'name' => 'Promoção relâmpago',
        'description' => 'Promova uma oferta por tempo limitado em vários slides.',
        'content' => '[Desconto]% de desconto nas próximas [horas] horas na {{brand_name}}. Leia todos os slides para não perder.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'promoção relâmpago no ar', 'body' => '[Desconto]% off até [data e hora final]. Sem código.', 'image_keywords' => ['sale', 'tag']],
            ['title' => 'o que está incluso', 'body' => '[Categorias em promoção, exceções se houver. Seja honesto sobre o que não entra.]', 'image_keywords' => ['products', 'shop']],
            ['title' => 'os mais queridos', 'body' => '[Dois ou três campeões de venda que as pessoas pegam primeiro quando tem promoção.]', 'image_keywords' => ['favorites', 'shelf']],
            ['title' => 'compre antes que acabe', 'body' => 'Link na bio. Quando o estoque acabar, acabou.', 'image_keywords' => ['phone', 'cart']],
        ],
    ],
    [
        'slug' => 'bundle_deal_carousel',
        'category' => 'promotion',
        'name' => 'Carrossel de combo',
        'description' => 'Explique uma oferta de combo slide por slide.',
        'content' => 'Três coisas, um preço. Economize [valor] comprando juntas na {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'o combo', 'body' => '[Descrição rápida do que tem no combo e o total que se economiza.]', 'image_keywords' => ['bundle', 'box']],
            ['title' => 'item um', 'body' => '[Primeiro item do combo e o que ele faz sozinho.]', 'image_keywords' => ['product', 'one']],
            ['title' => 'item dois', 'body' => '[Segundo item e por que combina com o primeiro.]', 'image_keywords' => ['product', 'two']],
            ['title' => 'item três', 'body' => '[Terceiro item. O que amarra o combo.]', 'image_keywords' => ['product', 'three']],
            ['title' => 'leve o combo', 'body' => 'Economize [valor]. Disponível enquanto durar o estoque.', 'image_keywords' => ['bag', 'shopping']],
        ],
    ],
    [
        'slug' => 'first_order_discount_carousel',
        'category' => 'promotion',
        'name' => 'Desconto na primeira compra',
        'description' => 'Receba novos clientes com um desconto na primeira compra.',
        'content' => 'Novo por aqui? Use o código [CÓDIGO] para [desconto]% off na sua primeira compra na {{brand_name}}.',
        'image_count' => 3,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'oferta de boas-vindas', 'body' => '[Desconto]% off na primeira compra. Código: [CÓDIGO]. Válido por [duração].', 'image_keywords' => ['welcome', 'gift']],
            ['title' => 'por onde as pessoas começam', 'body' => '[Um ou dois produtos que são bons pontos de partida pra novos clientes.]', 'image_keywords' => ['bestseller', 'product']],
            ['title' => 'como usar', 'body' => 'Adicione ao carrinho, cole [CÓDIGO] no checkout. Link na bio.', 'image_keywords' => ['checkout', 'phone']],
        ],
    ],
    [
        'slug' => 'free_shipping_carousel',
        'category' => 'promotion',
        'name' => 'Final de semana com frete grátis',
        'description' => 'Promova um período limitado de frete grátis.',
        'content' => 'Frete grátis na {{brand_name}} só neste final de semana. Sem valor mínimo.',
        'image_count' => 3,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'final de semana com frete grátis', 'body' => 'De [sexta] a [domingo]. Sem código, sem pedido mínimo.', 'image_keywords' => ['shipping', 'box']],
            ['title' => 'pra onde enviamos', 'body' => '[Regiões ou países incluídos. Deixe claro qualquer exceção.]', 'image_keywords' => ['map', 'globe']],
            ['title' => 'aproveite o final de semana', 'body' => 'Toque no link na bio antes da meia-noite de [domingo] [fuso horário].', 'image_keywords' => ['cart', 'phone']],
        ],
    ],
    [
        'slug' => 'beginner_guide_carousel',
        'category' => 'educational',
        'name' => 'Carrossel guia para iniciantes',
        'description' => 'Ensine um tópico do zero até o primeiro resultado prático.',
        'content' => '[Tópico] para quem está começando do zero. Salve pra ler depois. 👇',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'comece por aqui', 'body' => 'Se [tópico] parece muito, esta é a versão que me ajudou quando eu era iniciante.', 'image_keywords' => ['beginner', 'notes']],
            ['title' => 'o que é, na real', 'body' => '[Definição simples. Sem jargão. Uma frase basta.]', 'image_keywords' => ['concept', 'sketch']],
            ['title' => 'por que importa', 'body' => '[O motivo concreto pelo qual um iniciante se daria o trabalho de aprender isso.]', 'image_keywords' => ['question', 'curious']],
            ['title' => 'primeira coisa pra tentar', 'body' => '[Uma ação pequena e específica que dá pra fazer em menos de 10 minutos.]', 'image_keywords' => ['hands', 'desk']],
            ['title' => 'erro comum', 'body' => '[A armadilha em que a maioria dos iniciantes cai. Seja específico.]', 'image_keywords' => ['mistake', 'fix']],
            ['title' => 'pra onde ir depois', 'body' => '[Um livro, canal ou recurso da {{brand_name}} pro próximo passo.]', 'image_keywords' => ['library', 'resource']],
        ],
    ],
    [
        'slug' => 'common_mistakes_carousel',
        'category' => 'educational',
        'name' => 'Erros comuns',
        'description' => 'Mostre erros comuns e como corrigi-los.',
        'content' => '5 erros que eu vejo o tempo todo com [tópico]. O número 3 eu tive que aprender da pior forma.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'os erros', 'body' => 'Cinco coisas que as pessoas fazem errado com [tópico], e o que fazer no lugar.', 'image_keywords' => ['mistake', 'pen']],
            ['title' => 'erro 1', 'body' => '[Primeiro erro. Depois a correção em uma frase.]', 'image_keywords' => ['error', 'paper']],
            ['title' => 'erro 2', 'body' => '[Segundo erro e a correção.]', 'image_keywords' => ['confused', 'desk']],
            ['title' => 'erro 3', 'body' => '[Terceiro erro. O que pega as pessoas de surpresa.]', 'image_keywords' => ['surprised', 'thought']],
            ['title' => 'erro 4', 'body' => '[Quarto erro e a correção.]', 'image_keywords' => ['process', 'workspace']],
            ['title' => 'erro 5', 'body' => '[Erro final. Termine com o que você faria no lugar.]', 'image_keywords' => ['solution', 'check']],
        ],
    ],
    [
        'slug' => 'glossary_carousel',
        'category' => 'educational',
        'name' => 'Carrossel glossário',
        'description' => 'Defina cinco termos do seu setor em linguagem simples.',
        'content' => '5 termos de [setor] explicados sem o jargão. Salve pra ler depois.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'jargão decifrado', 'body' => 'Cinco palavras de [setor] que as pessoas usam como se todo mundo já soubesse.', 'image_keywords' => ['dictionary', 'book']],
            ['title' => '[termo 1]', 'body' => '[Definição simples. Uma frase de exemplo.]', 'image_keywords' => ['letters', 'text']],
            ['title' => '[termo 2]', 'body' => '[Definição simples. Uma frase de exemplo.]', 'image_keywords' => ['letters', 'paper']],
            ['title' => '[termo 3]', 'body' => '[Definição simples. Uma frase de exemplo.]', 'image_keywords' => ['note', 'pen']],
            ['title' => '[termo 4]', 'body' => '[Definição simples. Uma frase de exemplo.]', 'image_keywords' => ['definition', 'page']],
            ['title' => '[termo 5]', 'body' => '[Definição simples. Uma frase de exemplo.]', 'image_keywords' => ['glossary', 'open book']],
        ],
    ],
    [
        'slug' => 'step_by_step_tutorial_carousel',
        'category' => 'educational',
        'name' => 'Tutorial passo a passo',
        'description' => 'Mostre um pequeno tutorial em passos claros.',
        'content' => 'Como [tarefa] em [número] passos. Salve pra ter na próxima vez.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'o que você vai precisar', 'body' => '[Liste as ferramentas ou materiais. Seja breve.]', 'image_keywords' => ['tools', 'supplies']],
            ['title' => 'passo 1', 'body' => '[Primeiro passo. Ação específica, não um objetivo.]', 'image_keywords' => ['hands', 'work']],
            ['title' => 'passo 2', 'body' => '[Segundo passo. Como deve estar antes de seguir adiante.]', 'image_keywords' => ['progress', 'desk']],
            ['title' => 'passo 3', 'body' => '[Terceiro passo. Cite o erro mais comum aqui.]', 'image_keywords' => ['focus', 'detail']],
            ['title' => 'pronto', 'body' => '[Como deve ficar o resultado final. Uma ideia de foto.]', 'image_keywords' => ['finished', 'result']],
        ],
    ],
    [
        'slug' => 'team_intro_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Conheça o time',
        'description' => 'Apresente os membros do time, um slide por vez.',
        'content' => 'Os rostos por trás da {{brand_name}}. Arraste pra conhecer quem faz tudo acontecer.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'o time', 'body' => 'Somos [número] pessoas em [localidades]. Aqui está quem faz o quê.', 'image_keywords' => ['team', 'office']],
            ['title' => '[nome 1]', 'body' => '[Cargo. Uma coisa que essa pessoa toca e uma que gosta de fazer fora do trabalho.]', 'image_keywords' => ['portrait', 'work']],
            ['title' => '[nome 2]', 'body' => '[Cargo. Um detalhe que mostra a personalidade, não só o cargo.]', 'image_keywords' => ['portrait', 'desk']],
            ['title' => '[nome 3]', 'body' => '[Cargo. Algo específico que ela fez este mês.]', 'image_keywords' => ['portrait', 'studio']],
            ['title' => 'manda um oi', 'body' => 'Direct aberto. A gente responde em pessoa.', 'image_keywords' => ['phone', 'chat']],
        ],
    ],
    [
        'slug' => 'workspace_tour_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Tour pelo espaço',
        'description' => 'Faça um tour pelo seu estúdio, cozinha ou escritório em vários slides.',
        'content' => 'Um tour por onde a {{brand_name}} é feita de verdade. Menos arrumado do que você imagina.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'onde a coisa acontece', 'body' => '[Local, tamanho, que tipo de espaço é, em uma frase.]', 'image_keywords' => ['studio', 'workshop']],
            ['title' => 'a bancada de trabalho', 'body' => '[O que vive na bancada ou mesa principal na maioria dos dias.]', 'image_keywords' => ['workbench', 'tools']],
            ['title' => 'o canto que ninguém vê', 'body' => '[Detalhe honesto: uma estante bagunçada, uma parede de post-its, a estação de café.]', 'image_keywords' => ['corner', 'mess']],
            ['title' => 'o lugar favorito', 'body' => '[A cadeira, a janela, a luz que deixa o dia melhor.]', 'image_keywords' => ['light', 'window']],
            ['title' => 'volte logo', 'body' => 'Mais espiadinhas vindo. Siga a {{brand_name}} pra próxima.', 'image_keywords' => ['camera', 'door']],
        ],
    ],
    [
        'slug' => 'a_day_in_the_life_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Um dia na rotina',
        'description' => 'Mostre um dia de trabalho, da manhã à noite.',
        'content' => 'Um dia de verdade na {{brand_name}}, hora por hora. Sem montagem.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => '7h30', 'body' => '[Como o dia realmente começa. Café, caminhada, e-mails, o que for.]', 'image_keywords' => ['morning', 'coffee']],
            ['title' => '9h', 'body' => '[Primeira coisa na agenda de trabalho. Seja específico sobre o que é feito.]', 'image_keywords' => ['desk', 'laptop']],
            ['title' => '12h30', 'body' => '[Almoço. Onde, com quem, ou sozinho ouvindo podcast.]', 'image_keywords' => ['lunch', 'food']],
            ['title' => '14h', 'body' => '[Bloco da tarde. A coisa que exige mais foco no dia.]', 'image_keywords' => ['focus', 'work']],
            ['title' => '17h30', 'body' => '[Encerrando. Qual costuma ser a última tarefa antes de desligar.]', 'image_keywords' => ['evening', 'office']],
            ['title' => 'fora do horário', 'body' => '[Como o dia termina. Corrida, jantar, filhos, leitura, o que for verdade.]', 'image_keywords' => ['sunset', 'home']],
        ],
    ],
    [
        'slug' => 'mistakes_we_made_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Erros que cometemos',
        'description' => 'Compartilhe três erros reais e o que aprendeu com eles.',
        'content' => '3 coisas que a gente errou este ano na {{brand_name}}. Compartilho porque esconder seria estranho.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'por que postar isso', 'body' => 'Vitórias recebem bastante atenção. Os erros são onde costumam estar as lições.', 'image_keywords' => ['notebook', 'writing']],
            ['title' => 'erro 1', 'body' => '[O que tentamos. Por que não deu certo. O que fizemos depois.]', 'image_keywords' => ['error', 'desk']],
            ['title' => 'erro 2', 'body' => '[O segundo. Seja honesto sobre o custo, em dinheiro ou tempo.]', 'image_keywords' => ['budget', 'paper']],
            ['title' => 'erro 3 + o que vem agora', 'body' => '[Terceiro erro e uma coisa que está mudando por causa dele.]', 'image_keywords' => ['plan', 'reset']],
        ],
    ],
    [
        'slug' => 'customer_story_carousel',
        'category' => 'testimonial',
        'name' => 'História de cliente',
        'description' => 'Conte uma única história de cliente ao longo dos slides.',
        'content' => 'Uma história de um dos clientes da {{brand_name}}. Postado com a permissão dele.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'conheça [nome]', 'body' => '[Nome, o que faz, onde mora. Duas frases curtas.]', 'image_keywords' => ['portrait', 'person']],
            ['title' => 'o problema', 'body' => '[A situação antes de usar a {{brand_name}}. Específica, não abstrata.]', 'image_keywords' => ['problem', 'thinking']],
            ['title' => 'o que ele tentou', 'body' => '[Como encontrou a {{brand_name}} e como foi o primeiro uso.]', 'image_keywords' => ['discover', 'try']],
            ['title' => 'o que mudou', 'body' => '[O resultado. Um número se você tiver, uma história se não tiver.]', 'image_keywords' => ['result', 'change']],
            ['title' => 'nas palavras dele', 'body' => '"[Citação direta do cliente. Curta e real.]"', 'image_keywords' => ['quote', 'speech']],
        ],
    ],
    [
        'slug' => 'three_reviews_carousel',
        'category' => 'testimonial',
        'name' => 'Carrossel com três avaliações',
        'description' => 'Junte três avaliações reais em um carrossel.',
        'content' => 'Três avaliações de clientes reais este mês na {{brand_name}}.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'o que as pessoas estão dizendo', 'body' => 'Três citações sem editar deste mês. Nomes completos preservados quando solicitado.', 'image_keywords' => ['stars', 'review']],
            ['title' => 'avaliação 1', 'body' => '"[Citação direta do cliente.]", [primeiro nome, localidade]', 'image_keywords' => ['speech', 'quote']],
            ['title' => 'avaliação 2', 'body' => '"[Citação direta do cliente.]", [primeiro nome, localidade]', 'image_keywords' => ['feedback', 'note']],
            ['title' => 'avaliação 3', 'body' => '"[Citação direta do cliente.]", [primeiro nome, localidade]', 'image_keywords' => ['testimonial', 'paper']],
        ],
    ],
    [
        'slug' => 'before_after_results_carousel',
        'category' => 'testimonial',
        'name' => 'Resultados antes e depois',
        'description' => 'Mostre um resultado de cliente em slides de antes e depois.',
        'content' => 'Um resultado real de um cliente usando [produto/serviço] na {{brand_name}}. Mesma pessoa, [período] de diferença.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'o ponto de partida', 'body' => '[Onde estava no começo. A versão honesta, não a polida.]', 'image_keywords' => ['before', 'start']],
            ['title' => 'o que ele fez', 'body' => '[O que usou e com que frequência. Seja específico sobre a rotina.]', 'image_keywords' => ['process', 'routine']],
            ['title' => 'o resultado', 'body' => '[Onde está agora. Números se for relevante, foto se for visual.]', 'image_keywords' => ['after', 'result']],
            ['title' => 'nas palavras dele', 'body' => '"[Uma citação curta sobre o que mais surpreendeu.]"', 'image_keywords' => ['quote', 'smile']],
        ],
    ],
    [
        'slug' => 'industry_myth_busting_carousel',
        'category' => 'industry_tip',
        'name' => 'Derrubando mitos do setor',
        'description' => 'Derrube três mitos sobre o seu setor.',
        'content' => '3 coisas que as pessoas ainda acreditam sobre [setor] e que não são verdade.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'mitos, desmontados', 'body' => 'Três crenças sobre [setor] que se repetem em todo lugar e ainda erram a mão.', 'image_keywords' => ['question', 'thinking']],
            ['title' => 'mito 1', 'body' => 'Mito: [crença comum]. Verdade: [como é de fato, com um detalhe].', 'image_keywords' => ['truth', 'note']],
            ['title' => 'mito 2', 'body' => 'Mito: [crença comum]. Verdade: [a correção em uma frase].', 'image_keywords' => ['fact', 'paper']],
            ['title' => 'mito 3', 'body' => 'Mito: [crença comum]. Verdade: [a correção]. O porquê está nos comentários.', 'image_keywords' => ['comment', 'phone']],
        ],
    ],
    [
        'slug' => 'industry_trend_carousel',
        'category' => 'industry_tip',
        'name' => 'Carrossel de tendência do setor',
        'description' => 'Apresente uma tendência que está moldando o setor este ano.',
        'content' => 'O que está realmente se mexendo em [setor] este ano, em linguagem simples.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'a tendência', 'body' => '[Nomeie a tendência em palavras simples. Uma frase sobre o que é.]', 'image_keywords' => ['trend', 'graph']],
            ['title' => 'por que agora', 'body' => '[A causa específica. Uma regulação, uma mudança técnica, uma mudança de comportamento.]', 'image_keywords' => ['cause', 'news']],
            ['title' => 'quem sente primeiro', 'body' => '[O público ou tipo de empresa que sente antes dos outros.]', 'image_keywords' => ['audience', 'people']],
            ['title' => 'o que fazer', 'body' => '[Uma coisa concreta pra testar neste trimestre, não um princípio vago.]', 'image_keywords' => ['action', 'plan']],
            ['title' => 'um número pra acompanhar', 'body' => '[Uma métrica específica, com fonte.]', 'image_keywords' => ['metric', 'data']],
        ],
    ],
    [
        'slug' => 'pro_tip_carousel',
        'category' => 'industry_tip',
        'name' => 'Carrossel de dica de profissional',
        'description' => 'Compartilhe uma única dica de profissional com contexto e passos.',
        'content' => 'Uma coisa que eu diria pra mim mesmo mais novo sobre [tópico]. Salve se ajudar.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'a dica', 'body' => '[A versão de uma frase. Curta o suficiente pra lembrar.]', 'image_keywords' => ['tip', 'note']],
            ['title' => 'por que funciona', 'body' => '[O motivo. Use um exemplo pequeno, não uma afirmação grande.]', 'image_keywords' => ['idea', 'thought']],
            ['title' => 'como usar', 'body' => '[Os passos. No máximo três. Específicos.]', 'image_keywords' => ['steps', 'list']],
            ['title' => 'uma coisa pra evitar', 'body' => '[O erro que as pessoas cometem ao aplicar essa dica.]', 'image_keywords' => ['warning', 'caution']],
        ],
    ],
    [
        'slug' => 'event_announcement_carousel',
        'category' => 'event',
        'name' => 'Anúncio de evento',
        'description' => 'Anuncie um evento próximo com os detalhes principais.',
        'content' => 'Vamos sediar [Nome do Evento] em [data]. Tudo que você precisa saber está nos slides.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => '[nome do evento]', 'body' => '[Data, local ou online, pra quem é, em uma linha.]', 'image_keywords' => ['event', 'invite']],
            ['title' => 'o que está programado', 'body' => '[A agenda em tópicos diretos, sem marketing.]', 'image_keywords' => ['agenda', 'schedule']],
            ['title' => 'quem vai falar', 'body' => '[Nomes e bios em uma linha. No máximo três.]', 'image_keywords' => ['speakers', 'panel']],
            ['title' => 'como participar', 'body' => '[Gratuito ou pago, link, prazo se houver. Seja específico.]', 'image_keywords' => ['ticket', 'register']],
            ['title' => 'garanta seu lugar', 'body' => '[Lembrete final + chamada pro link na bio.]', 'image_keywords' => ['phone', 'tap']],
        ],
    ],
    [
        'slug' => 'event_speakers_carousel',
        'category' => 'event',
        'name' => 'Revelação dos palestrantes',
        'description' => 'Revele os palestrantes, um por slide.',
        'content' => 'Palestrantes do [Nome do Evento]. Os ingressos estão abertos na {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'palestrantes revelados', 'body' => 'O lineup do [Nome do Evento] em [data]. Arraste pra conhecer.', 'image_keywords' => ['lineup', 'stage']],
            ['title' => '[palestrante 1]', 'body' => '[Nome, cargo. A coisa principal sobre a qual vai falar.]', 'image_keywords' => ['portrait', 'speaker']],
            ['title' => '[palestrante 2]', 'body' => '[Nome, cargo. O tema da palestra em uma linha.]', 'image_keywords' => ['portrait', 'mic']],
            ['title' => '[palestrante 3]', 'body' => '[Nome, cargo. O que os participantes vão levar.]', 'image_keywords' => ['portrait', 'panel']],
            ['title' => 'ingressos na bio', 'body' => '[Data, local, link de inscrição.]', 'image_keywords' => ['ticket', 'register']],
        ],
    ],
    [
        'slug' => 'workshop_invitation_carousel',
        'category' => 'event',
        'name' => 'Convite para workshop',
        'description' => 'Convide as pessoas para um workshop prático.',
        'content' => 'Workshop prático na {{brand_name}} em [data]. Vagas limitadas. Veja o que tem dentro.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'workshop em [data]', 'body' => '[Tema em uma linha. Online ou presencial, com local e horário.]', 'image_keywords' => ['workshop', 'class']],
            ['title' => 'o que você vai fazer', 'body' => '[Três atividades concretas. Use verbos, não adjetivos.]', 'image_keywords' => ['hands', 'making']],
            ['title' => 'o que você vai levar', 'body' => '[O resultado: uma coisa pronta, um rascunho, uma decisão, um plano.]', 'image_keywords' => ['notebook', 'result']],
            ['title' => 'reserve sua vaga', 'body' => '[Vagas restantes, preço se houver, link na bio.]', 'image_keywords' => ['chair', 'register']],
        ],
    ],
    [
        'slug' => 'this_or_that_carousel',
        'category' => 'engagement',
        'name' => 'Esse ou aquele',
        'description' => 'Faça aos seguidores uma série de perguntas de escolha.',
        'content' => 'Esse ou aquele, edição [tópico]. Conta nos comentários quais você escolhe.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'escolha um', 'body' => 'Cinco escolhas rápidas. Comente as respostas em ordem.', 'image_keywords' => ['choice', 'fork']],
            ['title' => '[opção a] ou [opção b]', 'body' => '[Contexto rápido se precisar.]', 'image_keywords' => ['split', 'options']],
            ['title' => '[opção c] ou [opção d]', 'body' => '[Contexto rápido se precisar.]', 'image_keywords' => ['versus', 'choice']],
            ['title' => '[opção e] ou [opção f]', 'body' => '[Contexto rápido se precisar.]', 'image_keywords' => ['compare', 'pick']],
            ['title' => 'sua vez', 'body' => 'Deixa as respostas aí embaixo. Eu leio cada comentário.', 'image_keywords' => ['comment', 'phone']],
        ],
    ],
    [
        'slug' => 'unpopular_opinion_carousel',
        'category' => 'engagement',
        'name' => 'Opinião impopular',
        'description' => 'Compartilhe uma opinião real e convide à discordância.',
        'content' => 'Uma opinião impopular sobre [tópico]. Me conta nos comentários onde estou errado.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'opinião impopular', 'body' => '[A opinião em uma frase curta e clara.]', 'image_keywords' => ['opinion', 'speech']],
            ['title' => 'por que penso assim', 'body' => '[O motivo. Uma história pequena ou um número, não só sentimentos.]', 'image_keywords' => ['reason', 'thinking']],
            ['title' => 'onde posso estar errado', 'body' => '[Honesto sobre a parte mais fraca do argumento.]', 'image_keywords' => ['doubt', 'question']],
            ['title' => 'me conta', 'body' => 'Concorda, discorda, está em cima do muro, deixa nos comentários.', 'image_keywords' => ['comment', 'discussion']],
        ],
    ],
    [
        'slug' => 'fill_in_the_blank_carousel',
        'category' => 'engagement',
        'name' => 'Complete a frase',
        'description' => 'Provoque os seguidores com três frases para completar.',
        'content' => 'Complete as frases. Quero ler as suas respostas.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'complete as frases', 'body' => 'Três provocações rápidas sobre [tópico]. Comente as respostas em ordem.', 'image_keywords' => ['blank', 'pen']],
            ['title' => 'frase 1', 'body' => 'A melhor [coisa] que eu [verbo] este ano foi ____.', 'image_keywords' => ['idea', 'thought']],
            ['title' => 'frase 2', 'body' => 'O que eu quero fazer mais em [tópico] é ____.', 'image_keywords' => ['plan', 'goal']],
            ['title' => 'frase 3', 'body' => 'Uma pessoa que me ensinou sobre [tópico] foi ____.', 'image_keywords' => ['mentor', 'people']],
        ],
    ],
    [
        'slug' => 'q_and_a_carousel',
        'category' => 'engagement',
        'name' => 'Carrossel de perguntas e respostas',
        'description' => 'Responda cinco perguntas reais do seu público.',
        'content' => 'Você perguntou, eu respondi. Cinco perguntas reais que chegaram no direct.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'perguntas respondidas', 'body' => 'Peguei cinco desta semana. Anonimizei onde precisei.', 'image_keywords' => ['questions', 'mail']],
            ['title' => 'p1', 'body' => 'P: [pergunta parafraseada]. R: [resposta em uma ou duas frases].', 'image_keywords' => ['answer', 'note']],
            ['title' => 'p2', 'body' => 'P: [pergunta parafraseada]. R: [resposta].', 'image_keywords' => ['reply', 'speech']],
            ['title' => 'p3', 'body' => 'P: [pergunta parafraseada]. R: [resposta].', 'image_keywords' => ['question', 'mark']],
            ['title' => 'p4', 'body' => 'P: [pergunta parafraseada]. R: [resposta].', 'image_keywords' => ['chat', 'bubble']],
            ['title' => 'p5', 'body' => 'P: [pergunta parafraseada]. R: [resposta]. Manda mais nos comentários.', 'image_keywords' => ['comments', 'phone']],
        ],
    ],
];
