<?php

declare(strict_types=1);

return [
    [
        'slug' => 'limited_time_offer_feed',
        'category' => 'promotion',
        'name' => 'Oferta por tempo limitado',
        'description' => 'Divulgue uma promoção com prazo no Instagram Feed.',
        'content' => "⏰ Não perca. {{brand_name}} está com [desconto]% off em [produto/serviço], só hoje.\n\nClique no link da bio para garantir o seu antes que acabe.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'offer', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'team_behind_the_scenes_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Bastidores do time',
        'description' => 'Humanize sua marca mostrando o time em ação.',
        'content' => "É assim que é um dia normal na {{brand_name}}. 👀\n\nA gente acredita que bom trabalho acontece quando as pessoas se sentem em casa. Aqui vai uma espiada nos bastidores.\n\n#{{brand_name}} #BehindTheScenes",
        'image_count' => 1,
        'image_keywords' => ['office', 'team', 'workspace'],
        'slides' => null,
    ],

    // Product launch
    [
        'slug' => 'new_product_drop_feed',
        'category' => 'product_launch',
        'name' => 'Lançamento de novo produto',
        'description' => 'Anuncie o lançamento de um produto novo no feed.',
        'content' => "Chegou. [Nome do produto] acaba de entrar na {{brand_name}}.\n\nA gente passou [meses/semanas] nesse projeto. Cada detalhe foi testado pelo time antes de liberar para o público.\n\nClique no link da bio e seja um dos primeiros a testar.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'pre_order_announcement_feed',
        'category' => 'product_launch',
        'name' => 'Anúncio de pré-venda',
        'description' => 'Abra pré-vendas para um produto que está chegando.',
        'content' => "Pré-vendas abertas. [Nome do produto] começa a ser enviado em [data].\n\nO primeiro lote tem [número] unidades. Quando acabarem, a próxima leva só sai em [data posterior].\n\nReserve o seu pelo link da bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'package', 'box'],
        'slides' => null,
    ],
    [
        'slug' => 'feature_highlight_launch_feed',
        'category' => 'product_launch',
        'name' => 'Destaque de funcionalidade',
        'description' => 'Mostre uma funcionalidade específica de um produto novo.',
        'content' => "O que mais nos deixa orgulhosos no [nome do produto]: [funcionalidade específica].\n\nForam [número] protótipos até acertar. Os testadores nos disseram que isso mudou a forma como eles [caso de uso], então a gente continuou ajustando até parecer óbvio.\n\nVeja em ação pelo link da bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'detail', 'closeup'],
        'slides' => null,
    ],
    [
        'slug' => 'product_restock_feed',
        'category' => 'product_launch',
        'name' => 'Produto reposto',
        'description' => 'Anuncie a volta ao estoque de um item popular.',
        'content' => "Voltou ao estoque. [Nome do produto] esgotou em [tempo] na última vez, então a gente fez mais.\n\nSe você perdeu antes, agora é a hora. O estoque é limitado de novo, e a gente espera mais uma corrida rápida.\n\nGaranta o seu pelo link da bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'shelf', 'inventory'],
        'slides' => null,
    ],

    // Promotion
    [
        'slug' => 'flash_sale_feed',
        'category' => 'promotion',
        'name' => 'Flash sale',
        'description' => 'Crie urgência com um flash sale curto.',
        'content' => "Flash sale. [Desconto]% off em tudo nas próximas [horas] horas.\n\nNão precisa de cupom no checkout. O desconto já está aplicado no site inteiro.\n\nLink na bio. Coloca um cronômetro.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'bundle_deal_feed',
        'category' => 'promotion',
        'name' => 'Combo promocional',
        'description' => 'Divulgue uma oferta de combo com vários produtos.',
        'content' => "Compre [item A] e [item B] juntos e economize [valor].\n\nÉ a mesma combinação que nosso time usa toda semana, então a gente montou como kit. Sai mais barato do que comprar separado.\n\nLink na bio.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'products', 'gift'],
        'slides' => null,
    ],
    [
        'slug' => 'free_shipping_feed',
        'category' => 'promotion',
        'name' => 'Frete grátis',
        'description' => 'Anuncie frete grátis por uma janela limitada.',
        'content' => "Frete grátis em todos os pedidos esta semana.\n\nSem mínimo, sem cupom, sem letrinha miúda no rodapé que você precisa apertar os olhos para ler. Escolhe o que quer e a gente cobre a entrega.\n\nLink na bio. Termina [dia].",
        'image_count' => 1,
        'image_keywords' => ['shipping', 'package', 'delivery'],
        'slides' => null,
    ],
    [
        'slug' => 'first_order_discount_feed',
        'category' => 'promotion',
        'name' => 'Desconto na primeira compra',
        'description' => 'Receba novos clientes com desconto na primeira compra.',
        'content' => "Primeira vez na {{brand_name}}? Ganhe [desconto]% off no seu primeiro pedido.\n\nUse o código [CÓDIGO] no checkout. Vale para qualquer produto da loja, inclusive o [nome do bestseller] que todo mundo pergunta.\n\nLink na bio.",
        'image_count' => 1,
        'image_keywords' => ['welcome', 'shop', 'discount'],
        'slides' => null,
    ],

    // Educational
    [
        'slug' => 'quick_how_to_tip_feed',
        'category' => 'educational',
        'name' => 'Dica rápida de como fazer',
        'description' => 'Compartilhe uma dica prática do seu nicho.',
        'content' => "Uma coisinha que facilita [tarefa]: [dica em uma frase].\n\nA gente começou a fazer isso depois de [motivo ou história]. Economizou [tempo/dinheiro/esforço] em uma semana.\n\nSalva esse post para depois. Link na bio para o guia completo.",
        'image_count' => 1,
        'image_keywords' => ['notebook', 'desk', 'work'],
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake_feed',
        'category' => 'educational',
        'name' => 'Erro comum',
        'description' => 'Aponte um erro frequente e como corrigir.',
        'content' => "O erro que mais vemos com [tópico]: [o erro].\n\nÉ fácil de cometer. A maioria das pessoas nem percebe que isso custa [consequência] até alguém apontar.\n\nA solução é simples: [a solução]. Tenta essa semana e vê o que muda.",
        'image_count' => 1,
        'image_keywords' => ['warning', 'thinking', 'desk'],
        'slides' => null,
    ],
    [
        'slug' => 'myth_vs_truth_feed',
        'category' => 'educational',
        'name' => 'Mito vs verdade',
        'description' => 'Desconstrua um mito comum do seu setor.',
        'content' => "Mito: [crença comum sobre seu setor].\n\nVerdade: [a realidade, com um detalhe que comprova].\n\nA gente também acreditava no mito. Aí monitoramos por [período] e os dados disseram outra coisa. Salva se você já ouviu a mesma história.",
        'image_count' => 1,
        'image_keywords' => ['question', 'thinking', 'idea'],
        'slides' => null,
    ],
    [
        'slug' => 'glossary_term_feed',
        'category' => 'educational',
        'name' => 'Termo do glossário explicado',
        'description' => 'Explique um termo do setor em linguagem simples.',
        'content' => "[Termo]: o que isso significa de verdade.\n\nA maioria dos guias explica com mais jargão. Aqui vai a versão direta: [definição em uma frase].\n\nUm exemplo real do nosso trabalho: [exemplo curto]. Salva esse post se você fica balançando a cabeça em reuniões sem perguntar.",
        'image_count' => 1,
        'image_keywords' => ['book', 'glossary', 'study'],
        'slides' => null,
    ],

    // Behind the scenes
    [
        'slug' => 'workspace_tour_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Tour pelo espaço de trabalho',
        'description' => 'Mostre o lugar onde o trabalho acontece.',
        'content' => "Onde o trabalho acontece.\n\nEsse é [sala/espaço] da {{brand_name}}. A planta no canto sobreviveu a três mudanças de escritório. O quadro branco não é apagado desde [mês].\n\nNão é polido, mas é nosso.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'desk', 'studio'],
        'slides' => null,
    ],
    [
        'slug' => 'how_its_made_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Como é feito',
        'description' => 'Mostre uma etapa do seu processo de produção.',
        'content' => "Esse é o passo [número] de como a gente faz [produto].\n\nLeva uns [tempo] e fazemos à mão. Sem atalhos por aqui, principalmente porque a gente tentou um atalho uma vez e arruinou um lote inteiro.\n\nMais sobre o processo no link da bio.",
        'image_count' => 1,
        'image_keywords' => ['craft', 'making', 'workshop'],
        'slides' => null,
    ],
    [
        'slug' => 'team_member_intro_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Apresentação de membro do time',
        'description' => 'Apresente um integrante do time.',
        'content' => "Conheça [nome], nosso(a) [cargo] na {{brand_name}}.\n\n[Nome] entrou no time há [tempo] e cuida de [área]. Fora do trabalho, dá para encontrá-lo(a) [hobby ou interesse].\n\nSe você mandou e-mail para o suporte recentemente, tem uma boa chance de ter sido [nome] respondendo.",
        'image_count' => 1,
        'image_keywords' => ['portrait', 'team', 'person'],
        'slides' => null,
    ],
    [
        'slug' => 'a_day_in_the_life_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Um dia na vida',
        'description' => 'Mostre como é um dia normal na empresa.',
        'content' => "Uma terça normal na {{brand_name}}.\n\nDe manhã o ambiente é tranquilo, basicamente e-mails e uma daily. À tarde fica barulhento quando [atividade] começa. Lá pelas 17h alguém já quebrou alguma coisa e outra pessoa já consertou.\n\nSinceramente, esse é o trabalho inteiro.",
        'image_count' => 1,
        'image_keywords' => ['office', 'work', 'coffee'],
        'slides' => null,
    ],

    // Testimonial
    [
        'slug' => 'customer_quote_feed',
        'category' => 'testimonial',
        'name' => 'Citação de cliente',
        'description' => 'Compartilhe uma citação forte de cliente.',
        'content' => "\"[Citação do cliente nas próprias palavras].\", [Nome do cliente], [cidade ou cargo]\n\nEssa chegou semana passada e a gente precisou compartilhar. Obrigado(a) [primeiro nome].\n\nSe a {{brand_name}} te ajudou com [resultado], a gente adoraria saber. Responda ou manda DM.",
        'image_count' => 1,
        'image_keywords' => ['quote', 'happy', 'customer'],
        'slides' => null,
    ],
    [
        'slug' => 'before_after_result_feed',
        'category' => 'testimonial',
        'name' => 'Resultado antes e depois',
        'description' => 'Destaque uma transformação real de cliente.',
        'content' => "Antes: [ponto de partida].\nDepois: [resultado, com número se possível].\n\n[Nome do cliente] trabalhou com a gente por [período]. A mudança não foi de uma hora para outra, mas dá para ver onde as coisas viraram.\n\nLink na bio se você quer um resultado parecido.",
        'image_count' => 1,
        'image_keywords' => ['transformation', 'result', 'progress'],
        'slides' => null,
    ],
    [
        'slug' => 'star_rating_review_feed',
        'category' => 'testimonial',
        'name' => 'Avaliação cinco estrelas',
        'description' => 'Destaque uma avaliação cinco estrelas recente.',
        'content' => "★★★★★\n\n\"[Trecho da avaliação, duas a três frases].\"\n\n[Primeiro nome] deixou essa ontem. A gente lê toda avaliação que chega, as gentis e as duras.\n\nDeixe a sua pelo link da bio.",
        'image_count' => 1,
        'image_keywords' => ['stars', 'review', 'rating'],
        'slides' => null,
    ],
    [
        'slug' => 'case_study_snapshot_feed',
        'category' => 'testimonial',
        'name' => 'Resumo de case',
        'description' => 'Antecipe um case de sucesso de cliente.',
        'content' => "Como [cliente ou empresa] usou a {{brand_name}} para [resultado].\n\nEm [período], saíram de [ponto inicial] para [resultado]. O case completo conta o que tentaram primeiro e o que finalmente funcionou.\n\nLink na bio para ver o case.",
        'image_count' => 1,
        'image_keywords' => ['case study', 'meeting', 'results'],
        'slides' => null,
    ],

    // Industry tip
    [
        'slug' => 'one_tool_we_use_feed',
        'category' => 'industry_tip',
        'name' => 'Uma ferramenta que usamos',
        'description' => 'Recomende uma ferramenta que você usa de verdade.',
        'content' => "Uma ferramenta que usamos toda semana: [nome da ferramenta].\n\nTestamos [número] alternativas antes de ficar com essa. O que conquistou a gente foi [funcionalidade específica], não o marketing da página inicial.\n\nNão é publi. É só útil.",
        'image_count' => 1,
        'image_keywords' => ['tools', 'software', 'laptop'],
        'slides' => null,
    ],
    [
        'slug' => 'industry_trend_take_feed',
        'category' => 'industry_tip',
        'name' => 'Opinião sobre tendência do setor',
        'description' => 'Dê uma opinião honesta sobre uma tendência atual.',
        'content' => "Todo mundo em [setor] está falando sobre [tendência].\n\nOpinião sincera: serve para [caso de uso], não serve para [outro caso de uso]. A gente testou em um projeto pequeno antes de assumir, e essa é a versão que recomendamos.\n\nQual foi a sua experiência? Conta nos comentários.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry', 'analysis'],
        'slides' => null,
    ],
    [
        'slug' => 'pricing_advice_feed',
        'category' => 'industry_tip',
        'name' => 'Conselho sobre preço',
        'description' => 'Compartilhe uma lição de preço da sua experiência.',
        'content' => "O que a gente errou em precificação: [o erro].\n\nCobramos pouco demais por [período] até alguém apontar que os números não fechavam. Subimos os preços [percentual], perdemos [número] clientes, mantivemos o restante e ganhamos mais.\n\nSe você está travado nisso, o link da bio tem nossa análise de preços.",
        'image_count' => 1,
        'image_keywords' => ['money', 'price', 'calculator'],
        'slides' => null,
    ],
    [
        'slug' => 'workflow_tip_feed',
        'category' => 'industry_tip',
        'name' => 'Dica de fluxo de trabalho',
        'description' => 'Compartilhe uma melhoria pequena no fluxo de trabalho.',
        'content' => "Uma mudança pequena no fluxo que economizou horas: [a mudança].\n\nAntes, [forma antiga]. Depois, [forma nova]. Levou uma semana para a gente se acostumar e nunca mais voltamos atrás.\n\nSe você testar, conta como foi.",
        'image_count' => 1,
        'image_keywords' => ['workflow', 'productivity', 'planner'],
        'slides' => null,
    ],

    // Event
    [
        'slug' => 'event_announcement_feed',
        'category' => 'event',
        'name' => 'Anúncio de evento',
        'description' => 'Anuncie um evento que está chegando.',
        'content' => "Marca na agenda.\n\n{{brand_name}} vai realizar [nome do evento] em [data] em [local ou online].\n\nVão ter [palestrantes, formato ou o que esperar]. As vagas estão limitadas a [número] desta vez.\n\nConfirme presença pelo link da bio.",
        'image_count' => 1,
        'image_keywords' => ['event', 'invitation', 'calendar'],
        'slides' => null,
    ],
    [
        'slug' => 'webinar_invite_feed',
        'category' => 'event',
        'name' => 'Convite para webinar',
        'description' => 'Divulgue um webinar que está chegando.',
        'content' => "Webinar gratuito: [tema]. [Data] às [horário].\n\n[Nome do host] vai passar por [pontos principais] e depois responder perguntas ao vivo nos últimos [minutos].\n\nSe não conseguir comparecer, se inscreva mesmo assim e a gente envia a gravação.\n\nLink na bio.",
        'image_count' => 1,
        'image_keywords' => ['webinar', 'laptop', 'presentation'],
        'slides' => null,
    ],
    [
        'slug' => 'meetup_recap_feed',
        'category' => 'event',
        'name' => 'Resumo do meetup',
        'description' => 'Resuma um evento presencial recente.',
        'content' => "[Número] pessoas, [cidade], uma sala.\n\nO meetup de ontem reuniu gente que trabalha com [área]. A melhor conversa da noite foi sobre [tema], começou no café e nunca terminou de fato.\n\nObrigado a todo mundo que apareceu. O próximo é em [data].",
        'image_count' => 1,
        'image_keywords' => ['meetup', 'crowd', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'live_stream_reminder_feed',
        'category' => 'event',
        'name' => 'Lembrete de live',
        'description' => 'Lembre seguidores de uma live que vem aí.',
        'content' => "Live [dia] às [horário].\n\nA gente vai falar sobre [tema]. Sem roteiro, só perguntas e o que o chat jogar para a gente.\n\nLiga as notificações para não perder. Ou não liga, o replay vai ficar no perfil depois.",
        'image_count' => 1,
        'image_keywords' => ['live', 'broadcast', 'camera'],
        'slides' => null,
    ],

    // Engagement
    [
        'slug' => 'this_or_that_feed',
        'category' => 'engagement',
        'name' => 'Esse ou aquele',
        'description' => 'Faça uma pergunta simples de escolha entre dois.',
        'content' => "[Opção A] ou [Opção B]?\n\nA gente discute isso no escritório toda semana. Curioso para ver qual lado vence aqui.\n\nVote nos comentários. Não tem resposta errada, mas tem uma certa.",
        'image_count' => 1,
        'image_keywords' => ['choice', 'options', 'vote'],
        'slides' => null,
    ],
    [
        'slug' => 'fill_in_the_blank_feed',
        'category' => 'engagement',
        'name' => 'Complete a frase',
        'description' => 'Provoque os seguidores com uma frase para completar.',
        'content' => "Complete a frase: \"A primeira coisa que faço toda manhã é ___.\"\n\nA gente perguntou para o time e recebeu de \"checar o Slack\" até \"evitar checar o Slack\". Curioso para saber onde você se encaixa.\n\nDeixe a sua nos comentários.",
        'image_count' => 1,
        'image_keywords' => ['question', 'morning', 'coffee'],
        'slides' => null,
    ],
    [
        'slug' => 'comment_question_feed',
        'category' => 'engagement',
        'name' => 'Pergunta nos comentários',
        'description' => 'Faça uma pergunta aberta para gerar comentários.',
        'content' => "Pergunta para a galera: qual foi o melhor [item relacionado ao tema] que você testou esse ano?\n\nA gente está montando uma lista e quer escolhas reais, não as cinco que todo mundo cita.\n\nDeixe a sua aí embaixo. Compartilhamos as favoritas semana que vem.",
        'image_count' => 1,
        'image_keywords' => ['conversation', 'community', 'chat'],
        'slides' => null,
    ],
    [
        'slug' => 'tag_a_friend_feed',
        'category' => 'engagement',
        'name' => 'Marca um amigo',
        'description' => 'Incentive marcações com um cenário identificável.',
        'content' => "Marca o amigo que [cenário identificável].\n\nTodo mundo tem um. Talvez você seja um. De qualquer jeito, esse post é para essa pessoa.\n\nPontos extras se ele te marcar de volta.",
        'image_count' => 1,
        'image_keywords' => ['friends', 'people', 'fun'],
        'slides' => null,
    ],
];
