<?php

declare(strict_types=1);

return [
    [
        'slug' => 'story_announcement',
        'category' => 'product_launch',
        'name' => 'Aviso rápido',
        'description' => 'Chame atenção para um lançamento ou novidade com um Story de 24 horas.',
        'content' => "Novidade na {{brand_name}}.\n\nToque no link para ver o que mudou.",
        'image_count' => 1,
        'image_keywords' => ['announcement', 'launch'],
        'slides' => null,
    ],
    [
        'slug' => 'story_poll_question',
        'category' => 'engagement',
        'name' => 'Enquete rápida',
        'description' => 'Use um Story para fazer uma pergunta rápida e engajar a audiência.',
        'content' => "O que mais importa quando você escolhe um [produto/serviço]?\n\nToque para votar.",
        'image_count' => 1,
        'image_keywords' => ['question', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'story_flash_promo',
        'category' => 'promotion',
        'name' => 'Promoção relâmpago',
        'description' => 'Oferta por tempo limitado em formato de Story com urgência.',
        'content' => "Só por 24 horas.\n\n[Desconto]% off na {{brand_name}}.\n\nArraste para cima.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'urgency'],
        'slides' => null,
    ],

    // product_launch
    [
        'slug' => 'story_product_drop',
        'category' => 'product_launch',
        'name' => 'Lançamento de produto',
        'description' => 'Avise que um produto novo entrou no ar hoje.',
        'content' => "Está no ar.\n\n[Nome do produto] acabou de sair.\n\nLink na bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'new'],
        'slides' => null,
    ],
    [
        'slug' => 'story_feature_shipped',
        'category' => 'product_launch',
        'name' => 'Recurso liberado',
        'description' => 'Conte aos seguidores sobre um recurso novo que você acabou de soltar.',
        'content' => "Acabamos de soltar [recurso].\n\nVá testar.",
        'image_count' => 1,
        'image_keywords' => ['update', 'feature', 'app'],
        'slides' => null,
    ],
    [
        'slug' => 'story_waitlist_open',
        'category' => 'product_launch',
        'name' => 'Lista de espera aberta',
        'description' => 'Convide seguidores a entrar na lista de espera.',
        'content' => "Lista de espera aberta.\n\n[Vagas] vagas restantes.\n\nLink na bio.",
        'image_count' => 1,
        'image_keywords' => ['waitlist', 'signup'],
        'slides' => null,
    ],
    [
        'slug' => 'story_preorder_live',
        'category' => 'product_launch',
        'name' => 'Pré-venda no ar',
        'description' => 'Estimule pré-vendas de um produto que vem por aí.',
        'content' => "Pré-vendas abertas.\n\nEnviamos em [data].\n\nToque para garantir a sua.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product'],
        'slides' => null,
    ],

    // promotion
    [
        'slug' => 'story_weekend_sale',
        'category' => 'promotion',
        'name' => 'Promoção de fim de semana',
        'description' => 'Empurre uma promoção rápida de fim de semana.',
        'content' => "Promoção de fim de semana.\n\n[Desconto]% off em tudo.\n\nTermina domingo.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'weekend', 'discount'],
        'slides' => null,
    ],
    [
        'slug' => 'story_code_drop',
        'category' => 'promotion',
        'name' => 'Cupom de desconto',
        'description' => 'Compartilhe um cupom para os seguidores usarem no checkout.',
        'content' => "Use [CUPOM] no checkout.\n\n[Desconto]% off.\n\nVálido até [data].",
        'image_count' => 1,
        'image_keywords' => ['coupon', 'code', 'discount'],
        'slides' => null,
    ],
    [
        'slug' => 'story_last_chance',
        'category' => 'promotion',
        'name' => 'Última chance',
        'description' => 'Lembrete final antes da promoção acabar.',
        'content' => "Última chance.\n\n[Oferta] termina à meia-noite.",
        'image_count' => 1,
        'image_keywords' => ['deadline', 'sale', 'urgent'],
        'slides' => null,
    ],
    [
        'slug' => 'story_bundle_deal',
        'category' => 'promotion',
        'name' => 'Combo promocional',
        'description' => 'Divulgue um combo por um preço menor.',
        'content' => "Combo promocional.\n\n[Item A] + [Item B] por [preço].\n\nToque para garantir.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'deal', 'product'],
        'slides' => null,
    ],

    // educational
    [
        'slug' => 'story_quick_tip',
        'category' => 'educational',
        'name' => 'Dica rápida',
        'description' => 'Compartilhe uma dica curta na tela.',
        'content' => "Dica rápida:\n\n[Uma dica curta e prática].",
        'image_count' => 1,
        'image_keywords' => ['tip', 'advice', 'learning'],
        'slides' => null,
    ],
    [
        'slug' => 'story_did_you_know',
        'category' => 'educational',
        'name' => 'Você sabia',
        'description' => 'Traga um fato surpreendente.',
        'content' => "Você sabia?\n\n[Fato surpreendente sobre seu nicho].",
        'image_count' => 1,
        'image_keywords' => ['fact', 'knowledge'],
        'slides' => null,
    ],
    [
        'slug' => 'story_common_mistake',
        'category' => 'educational',
        'name' => 'Erro comum',
        'description' => 'Aponte um erro que sua audiência costuma cometer.',
        'content' => "Pare de [erro comum].\n\nFaça [abordagem melhor] no lugar.",
        'image_count' => 1,
        'image_keywords' => ['mistake', 'advice', 'tip'],
        'slides' => null,
    ],
    [
        'slug' => 'story_one_word_lesson',
        'category' => 'educational',
        'name' => 'Lição em uma palavra',
        'description' => 'Uma única palavra seguida de um porquê curto.',
        'content' => "[Uma palavra].\n\nÉ a diferença entre [resultado A] e [resultado B].",
        'image_count' => 1,
        'image_keywords' => ['lesson', 'word', 'idea'],
        'slides' => null,
    ],

    // behind_the_scenes
    [
        'slug' => 'story_workspace_peek',
        'category' => 'behind_the_scenes',
        'name' => 'Espiada no ambiente',
        'description' => 'Foto rápida de onde o trabalho acontece.',
        'content' => "Onde o trabalho acontece.\n\n[Legenda curta sobre seu espaço].",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'desk', 'office'],
        'slides' => null,
    ],
    [
        'slug' => 'story_meet_the_team',
        'category' => 'behind_the_scenes',
        'name' => 'Conheça o time',
        'description' => 'Apresente um membro do time em uma linha.',
        'content' => "Conheça [nome].\n\n[Função na {{brand_name}}].",
        'image_count' => 1,
        'image_keywords' => ['team', 'people', 'portrait'],
        'slides' => null,
    ],
    [
        'slug' => 'story_in_progress',
        'category' => 'behind_the_scenes',
        'name' => 'Em andamento',
        'description' => 'Mostre algo que ainda está pela metade.',
        'content' => "Em andamento.\n\n[No que você está trabalhando agora].",
        'image_count' => 1,
        'image_keywords' => ['process', 'work', 'progress'],
        'slides' => null,
    ],
    [
        'slug' => 'story_packing_orders',
        'category' => 'behind_the_scenes',
        'name' => 'Pedidos saindo',
        'description' => 'Mostre os pedidos saindo para entrega.',
        'content' => "Pedidos de hoje.\n\nObrigado por confiar na {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['packaging', 'orders', 'shipping'],
        'slides' => null,
    ],

    // testimonial
    [
        'slug' => 'story_customer_quote',
        'category' => 'testimonial',
        'name' => 'Depoimento do cliente',
        'description' => 'Compartilhe um depoimento curto na tela.',
        'content' => "\"[Depoimento curto do cliente].\"\n\n- [Nome do cliente]",
        'image_count' => 1,
        'image_keywords' => ['testimonial', 'review', 'quote'],
        'slides' => null,
    ],
    [
        'slug' => 'story_review_screenshot',
        'category' => 'testimonial',
        'name' => 'Print de avaliação',
        'description' => 'Repostar um print de uma avaliação ótima.',
        'content' => "Avaliações assim alegram a semana.\n\nObrigado, [primeiro nome do cliente].",
        'image_count' => 1,
        'image_keywords' => ['review', 'screenshot', 'feedback'],
        'slides' => null,
    ],
    [
        'slug' => 'story_before_after_user',
        'category' => 'testimonial',
        'name' => 'Antes e depois do cliente',
        'description' => 'Destaque o resultado de um cliente.',
        'content' => '[Primeiro nome do cliente] saiu de [antes] para [depois] em [tempo].',
        'image_count' => 1,
        'image_keywords' => ['result', 'transformation', 'customer'],
        'slides' => null,
    ],

    // industry_tip
    [
        'slug' => 'story_industry_myth',
        'category' => 'industry_tip',
        'name' => 'Mito do setor',
        'description' => 'Desmonte uma crença comum no seu mercado.',
        'content' => "Mito: [crença comum].\n\nRealidade: [a verdade].",
        'image_count' => 1,
        'image_keywords' => ['myth', 'industry', 'truth'],
        'slides' => null,
    ],
    [
        'slug' => 'story_industry_stat',
        'category' => 'industry_tip',
        'name' => 'Dado do setor',
        'description' => 'Solte um dado que prende atenção.',
        'content' => "[Dado].\n\nFoi por isso que criamos a {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['statistic', 'data', 'industry'],
        'slides' => null,
    ],
    [
        'slug' => 'story_tool_we_use',
        'category' => 'industry_tip',
        'name' => 'Ferramenta que usamos',
        'description' => 'Recomende uma ferramenta para sua audiência testar.',
        'content' => "Ferramenta que usamos todo dia:\n\n[Nome da ferramenta].\n\nMotivo: [um motivo curto].",
        'image_count' => 1,
        'image_keywords' => ['tool', 'software', 'recommendation'],
        'slides' => null,
    ],
    [
        'slug' => 'story_red_flag',
        'category' => 'industry_tip',
        'name' => 'Sinal de alerta',
        'description' => 'Avise os seguidores sobre um sinal de alerta no seu setor.',
        'content' => "Sinal de alerta em [setor]:\n\n[O sinal a observar].",
        'image_count' => 1,
        'image_keywords' => ['warning', 'industry', 'advice'],
        'slides' => null,
    ],

    // event
    [
        'slug' => 'story_event_today',
        'category' => 'event',
        'name' => 'Evento hoje',
        'description' => 'Lembrete de última hora para um evento do mesmo dia.',
        'content' => "Hoje à noite.\n\n[Nome do evento] às [horário].\n\nToque no link.",
        'image_count' => 1,
        'image_keywords' => ['event', 'reminder'],
        'slides' => null,
    ],
    [
        'slug' => 'story_event_countdown',
        'category' => 'event',
        'name' => 'Contagem regressiva',
        'description' => 'Crie expectativa com uma contagem regressiva.',
        'content' => "[X] dias para [nome do evento].\n\nResponda VAI para receber o lembrete.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'story_live_now',
        'category' => 'event',
        'name' => 'Ao vivo agora',
        'description' => 'Avise os seguidores que você está ao vivo ou no palco.',
        'content' => "Ao vivo agora.\n\n[Tema ou local].\n\nVenha dar um oi.",
        'image_count' => 1,
        'image_keywords' => ['live', 'streaming', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'story_event_recap',
        'category' => 'event',
        'name' => 'Resumo do evento',
        'description' => 'Resumo rápido depois do evento acabar.',
        'content' => "[Nome do evento] terminou.\n\nObrigado a todos que foram.",
        'image_count' => 1,
        'image_keywords' => ['event', 'recap', 'crowd'],
        'slides' => null,
    ],

    // engagement
    [
        'slug' => 'story_this_or_that',
        'category' => 'engagement',
        'name' => 'Isto ou aquilo',
        'description' => 'Enquete de duas opções para toques rápidos.',
        'content' => "[Opção A] ou [Opção B]?\n\nToque para votar.",
        'image_count' => 1,
        'image_keywords' => ['poll', 'choice', 'vote'],
        'slides' => null,
    ],
    [
        'slug' => 'story_question_box',
        'category' => 'engagement',
        'name' => 'Caixinha de perguntas',
        'description' => 'Abra espaço para perguntas.',
        'content' => "Me pergunte qualquer coisa sobre [tema].\n\nResponda com sua pergunta.",
        'image_count' => 1,
        'image_keywords' => ['questions', 'ama', 'conversation'],
        'slides' => null,
    ],
    [
        'slug' => 'story_emoji_slider',
        'category' => 'engagement',
        'name' => 'Slider de emoji',
        'description' => 'Use o sticker de slider para medir uma sensação.',
        'content' => "Qual seu nível de empolgação com [coisa]?\n\nMova o slider.",
        'image_count' => 1,
        'image_keywords' => ['slider', 'reaction', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'story_dm_prompt',
        'category' => 'engagement',
        'name' => 'Chamada para DM',
        'description' => 'Estimule os seguidores a mandar uma palavra-chave no DM.',
        'content' => "Quer [recurso]?\n\nResponda [palavra-chave] e eu te envio.",
        'image_count' => 1,
        'image_keywords' => ['dm', 'message', 'engagement'],
        'slides' => null,
    ],
];
