<?php

declare(strict_types=1);

return [
    [
        'slug' => 'product_launch_announcement',
        'category' => 'product_launch',
        'name' => 'Anúncio de lançamento de produto',
        'description' => 'Post curto no LinkedIn anunciando um novo produto.',
        'content' => "Novidade pra compartilhar: {{brand_name}} acabou de lançar [Nome do Produto].\n\nPor que isso importa pra [seu público]:\n→ [Benefício 1]\n→ [Benefício 2]\n→ [Benefício 3]\n\nSaiba mais em [link]. Adoraríamos receber seu feedback.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'how_to_guide',
        'category' => 'educational',
        'name' => 'Guia passo a passo',
        'description' => 'Post educativo passo a passo para o LinkedIn.',
        'content' => "Como [alcançar X] em [prazo], um guia passo a passo.\n\nPasso 1: [Ação]\nPasso 2: [Ação]\nPasso 3: [Ação]\nPasso 4: [Ação]\n\nO ponto que a maioria das pessoas ignora: [insight].\n\nQual passo você acha mais difícil? Conta nos comentários.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'customer_quote',
        'category' => 'testimonial',
        'name' => 'Depoimento de cliente',
        'description' => 'Compartilhe um depoimento marcante de cliente no LinkedIn.',
        'content' => "\"[Frase do cliente sobre o resultado que ele alcançou com seu produto ou serviço.]\"\n- [Nome do Cliente], [Cargo] na [Empresa]\n\nÉ exatamente por isso que construímos a {{brand_name}}. Resultados reais para times reais.\n\nLeia a história completa → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'industry_insight',
        'category' => 'industry_tip',
        'name' => 'Insight do setor',
        'description' => 'Compartilhe uma visão atual ou opinião forte sobre seu setor.',
        'content' => "Uma coisa que a maioria do pessoal de [setor] entende errado:\n\n[Afirmação contraintuitiva ou opinião forte]\n\nPor quê? Porque [motivo].\n\nA forma mais inteligente de fazer: [caminho melhor].\n\nNa {{brand_name}}, vimos isso acontecer com centenas de [clientes/times]. Os dados são claros.\n\nQual é a sua opinião?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_announcement',
        'category' => 'event',
        'name' => 'Anúncio de evento',
        'description' => 'Anuncie um webinar ou evento ao vivo que está chegando.',
        'content' => "📅 Reserve a data: a {{brand_name}} vai realizar [Nome do Evento] no dia [Data] às [Horário].\n\nO que esperar:\n✔ [Tema 1]\n✔ [Tema 2]\n✔ [Tema 3]\n\nVagas limitadas. Inscreva-se agora → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'community_question',
        'category' => 'engagement',
        'name' => 'Pergunta para a comunidade',
        'description' => 'Provoque a discussão com uma pergunta aberta para sua rede.',
        'content' => "Se você pudesse dar um único conselho pra alguém começando agora em [setor/cargo], qual seria?\n\nO meu: [sua resposta, seja honesto e específico]\n\nDeixa o seu nos comentários. Bora montar uma thread que vale salvar.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Product launch (3) =====
    [
        'slug' => 'feature_release_notes',
        'category' => 'product_launch',
        'name' => 'Notas de lançamento de feature',
        'description' => 'Mostre à sua rede o que foi entregue e por que importa.',
        'content' => "Subimos [Nome da Feature] hoje.\n\nResumindo: ela faz [o que faz] pra [pra quem é]. Levou [prazo] do primeiro rascunho até a produção.\n\nO que mudou de verdade:\n• [Capacidade um, em linguagem direta]\n• [Capacidade dois, com um exemplo real]\n• [O que tiramos fora, e por quê]\n\nDebatemos [tradeoff] por semanas. No fim, escolhemos [decisão] porque [motivo]. Se você teria feito a outra escolha, quero entender o seu raciocínio.\n\nDocs e um vídeo de 4 minutos estão em [link]. Reportes de bug são bem-vindos, lemos cada um.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'beta_invitation',
        'category' => 'product_launch',
        'name' => 'Convite para beta privado',
        'description' => 'Convide sua rede para um beta fechado com expectativas claras.',
        'content' => "Estamos abrindo [Produto/Feature] em beta privado pra um grupo pequeno. Procurando uns [N] testadores.\n\nO perfil ideal:\n• Você atua em [cargo/setor]\n• Você usa hoje [ferramenta ou fluxo] e sente [atrito específico]\n• Você tem 30 minutos por semana pra quebrar coisas e nos contar\n\nO que você ganha: acesso antecipado, contato direto com o time da {{brand_name}} e voz no que vamos construir depois. O que a gente ganha: feedback honesto, mesmo quando dói.\n\nSe encaixa em você, comenta aqui ou me chama no DM. Vamos enviar os convites nesta [dia/semana].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'milestone_update',
        'category' => 'product_launch',
        'name' => 'Marco do produto',
        'description' => 'Compartilhe um marco relevante do produto ou da empresa com números concretos.',
        'content' => "Marco discreto que batemos essa semana: a {{brand_name}} passou de [número / métrica].\n\nPra contextualizar, quando começamos [prazo] atrás, tínhamos [número inicial]. A maior parte do crescimento veio de [canal ou fator específico], não do que a gente esperava.\n\nAlgumas coisas que aprendi no caminho:\n1. [Lição um, com os números]\n2. [Lição dois, o que faríamos diferente]\n3. [Lição três sobre o time]\n\nObrigado às [N] pessoas que apostaram na gente quando isso ainda era cru. Seguimos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Promotion (3) =====
    [
        'slug' => 'limited_time_offer',
        'category' => 'promotion',
        'name' => 'Oferta por tempo limitado',
        'description' => 'Promova um desconto ou oferta com prazo, sem cara de spam.',
        'content' => "Rodando uma promo de [% de desconto] na {{brand_name}} até [data].\n\nNão é truque de Black Friday. Tivemos um [mês/trimestre] fraco e queremos trazer [N] novos [usuários/clientes] antes de [fim do período]. Esse é o motivo honesto.\n\nSe você estava em cima do muro: [link]. Se você assinou nos últimos 30 dias, me manda um email que aplico o mesmo desconto retroativamente. É o certo a fazer.\n\nA oferta termina em [data] às [hora, fuso].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'free_resource_offer',
        'category' => 'promotion',
        'name' => 'Recurso gratuito',
        'description' => 'Ofereça um download ou template útil como isca de baixa fricção.',
        'content' => "Passei o fim de semana transformando nosso [tipo de recurso, checklist, template, playbook] interno em algo que dá pra compartilhar.\n\nÉ o mesmo [documento] que nosso time usa pra [caso de uso específico]. Sem firula: [N] páginas, sem enrolação, sem formulário de email.\n\nComenta com a palavra \"[palavra-chave]\" que te mando o link no DM. Se preferir pegar direto: [link].\n\nAviso: ele tem opinião. Se você discordar do meu ponto sobre [assunto específico], me conta. É assim que melhoro pra v2.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'partnership_announcement',
        'category' => 'promotion',
        'name' => 'Anúncio de parceria',
        'description' => 'Anuncie uma parceria ou integração com benefício claro pro cliente.',
        'content' => "{{brand_name}} agora está integrada com [Nome do Parceiro].\n\nO efeito prático pra [público]: você consegue [fluxo ou capacidade específica] sem [a gambiarra anterior]. Economiza cerca de [tempo/dinheiro] por [período] com base no grupo de teste inicial.\n\nEscolhemos [Parceiro] porque o time deles é obcecado por [valor compartilhado] do mesmo jeito que o nosso. Nem todo pedido de integração entra, e a maioria não entra.\n\nA configuração leva uns [N] minutos. Tutorial aqui: [link]. Se você já usa as duas ferramentas, queremos ouvir como foi.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Educational (3) =====
    [
        'slug' => 'lesson_learned',
        'category' => 'educational',
        'name' => 'Lição de um erro',
        'description' => 'Ensine contando um erro específico e o que mudou por causa dele.',
        'content' => "Errei na casa de [N] dígitos no [ano/trimestre] passado e quero escrever sobre isso enquanto ainda dói.\n\nO contexto: estávamos [situação]. A decisão: [o que você fez]. O raciocínio na época: [por que parecia certo].\n\nO que aconteceu de verdade: [resultado, em termos concretos]. Perdemos [custo específico, dinheiro, tempo, clientes, confiança].\n\nO que eu deveria ter feito: [caminho melhor]. O motivo de eu não ter feito é [motivo honesto, ego, pressa, falta de dado].\n\nTrês coisas que mudei na minha forma de trabalhar por causa disso:\n1. [Mudança um]\n2. [Mudança dois]\n3. [Mudança três]\n\nSe você já passou por isso, sabe como é. Conta a sua nos comentários.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'framework_breakdown',
        'category' => 'educational',
        'name' => 'Framework ou modelo mental destrinchado',
        'description' => 'Explique um framework ou modelo mental específico com um exemplo concreto.',
        'content' => "Sempre volto pra um modelo mental quando penso em [tema/problema]: [Nome do Framework].\n\nA ideia é simples. [Resumo do framework em uma frase.]\n\nComo eu uso na prática: quando travo em [situação específica], me pergunto [pergunta específica que o framework provoca]. Semana passada, isso me empurrou pra [decisão que você tomou por causa dele].\n\nOnde ele falha: [limitação honesta]. Não é resposta universal pra [tipo de problema], e tratar como se fosse é o caminho pra [resultado ruim].\n\nSe quiser ler a fonte original, é [autor/livro/link]. A versão acima é a minha, com ajustes de algumas centenas de usos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'tool_comparison',
        'category' => 'educational',
        'name' => 'Comparação honesta de ferramentas',
        'description' => 'Compare duas ou três ferramentas ou abordagens com tradeoffs reais.',
        'content' => "Usei [Ferramenta A], [Ferramenta B] e [Ferramenta C] pra [tarefa] nos últimos [prazo]. Onde cada uma realmente vence.\n\n[Ferramenta A] é a escolha certa quando [situação específica]. É a mais rápida em [tarefa específica] e a pior em [tarefa específica]. Usamos pra [caso de uso].\n\n[Ferramenta B] parece menos polida, mas faz [coisa] melhor que qualquer outra que testei. Vale o desconforto se [critério].\n\n[Ferramenta C] é a escolha sem graça. Isso é elogio. É confiável, a doc foi escrita por humanos, e o time não solta breaking changes na sexta.\n\nMeu stack atual na {{brand_name}}: [resposta real]. O seu pode ser diferente se [motivo].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Behind the scenes (3) =====
    [
        'slug' => 'team_culture_glimpse',
        'category' => 'behind_the_scenes',
        'name' => 'Momento de cultura do time',
        'description' => 'Compartilhe um momento pequeno e específico que mostra como o time trabalha de verdade.',
        'content' => "Coisinha que aconteceu na {{brand_name}} essa semana.\n\n[Pessoa do time ou cargo] notou [problema ou detalhe específico]. Daria pra ter subido assim mesmo. Em vez disso, [ação específica], o que atrasou [coisa] em [prazo].\n\nNinguém pediu. Não tinha ticket no Jira. O cliente não saberia.\n\nEssa é a parte de construir uma empresa que não cabe na página de vagas. O trabalho que ninguém vê, feito direito mesmo assim, porque é assim que as pessoas daqui são. Penso muito nisso.\n\nSe você quer trabalhar com gente assim: [link]. Se já trabalha, manda um DM pra essa pessoa.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'how_we_built_it',
        'category' => 'behind_the_scenes',
        'name' => 'Como construímos',
        'description' => 'Conte a história real por trás de uma entrega recente, incluindo os becos sem saída.',
        'content' => "Como construímos [Feature/Produto] na {{brand_name}}, incluindo as partes que normalmente ficam de fora.\n\nComeçamos com [plano original]. Levamos [prazo] pra perceber que esse plano estava errado. O problema real era [problema de verdade], que só ficou visível depois de [evento gatilho].\n\nA versão 2 foi [o que tentamos depois]. Funcionou na demo e quebrou em produção em [escala ou condição]. Reescrevemos o [componente específico] duas vezes.\n\nO que de fato subiu: [solução atual]. É [reconhecimento do tradeoff, mais lenta, mais simples, menos elegante] do que a gente queria construir, e é a versão que resolve o problema do cliente.\n\nDescritivo completo com os diagramas de arquitetura: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'day_in_the_life',
        'category' => 'behind_the_scenes',
        'name' => 'Um dia no time',
        'description' => 'Mostre como é um dia real pra alguém do time.',
        'content' => "Olhei a agenda de [dia da semana] e contei: [N] reuniões, [N] horas de trabalho focado, [N] interrupções pras quais eu deveria ter dito não.\n\nO trabalho que importou de verdade:\n• [Tarefa um, e por que importou]\n• [Tarefa dois, incluindo o que te surpreendeu]\n• [Tarefa três]\n\nO que parecia urgente e não era: [exemplo honesto]. Continuo caindo nessa e estou cansado disso.\n\nAntes eu achava que a meta era um dia perfeito. Hoje acho que a meta é umas poucas horas reais e a disciplina pra protegê-las. Curioso pra saber como vocês lidam com [desafio específico do post].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Testimonial (3) =====
    [
        'slug' => 'before_after_story',
        'category' => 'testimonial',
        'name' => 'Antes e depois de cliente',
        'description' => 'Conte a história de um cliente com números concretos do antes e depois.',
        'content' => "História rápida de um cliente da {{brand_name}} que vale compartilhar.\n\n[Cliente/Empresa] chegou na gente [prazo] atrás. O cenário na época: [métrica dolorosa específica, horas por semana, taxa de erro, churn, custo]. Já tinha tentado [abordagem anterior] e o número não tinha se mexido.\n\n[Prazo] depois, a mesma métrica está em [novo número]. A peça que fez mais diferença, segundo [Nome, cargo]: [mudança específica em como eles trabalham].\n\nO que eu gosto nessa história: não foi uma feature mágica. Foi [básico, mudança de processo, default que viraram, reunião que mataram]. A maioria das vitórias é assim e a gente não fala disso o suficiente.\n\nEstudo de caso completo com os detalhes bagunçados: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'unsolicited_review',
        'category' => 'testimonial',
        'name' => 'Avaliação espontânea de cliente',
        'description' => 'Compartilhe um feedback orgânico de cliente com uma reação reflexiva.',
        'content' => "Recebi isso na nossa caixa de entrada ontem, de [Nome do Cliente] da [Empresa]:\n\n\"[Frase honesta e específica, incluindo qualquer pequena crítica ou tradeoff que ele mencionou. Avaliações reais não são só elogio.]\"\n\nAlgumas reações honestas da minha parte. A parte sobre [elogio específico] é a coisa em que mais trabalhamos, então essa pegou. A parte sobre [reclamação ou desejo específico] é justa, e já está no roadmap pra [prazo].\n\nA gente não paga por avaliação e não pede por elas. Quando uma aparece assim, leio duas vezes. Obrigado, [Nome].\n\nSe você tem uma história com a {{brand_name}}, boa, ruim ou no meio do caminho, quero ouvir.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'team_member_spotlight',
        'category' => 'testimonial',
        'name' => 'Destaque de pessoa do time',
        'description' => 'Coloque uma pessoa do time em evidência por uma contribuição concreta.',
        'content' => "Quero falar de [Nome], [cargo] na {{brand_name}}, por um minuto.\n\n[Nome] entrou [prazo] atrás. O que ele(a) toca hoje: [área ou sistema específico]. O que ele(a) fez que pouca gente faria: [história específica, decisão dura, conserto sem glamour, tradeoff em que empurrou de volta].\n\nO resultado: [resultado concreto, com número se você tiver]. O motivo de ter dado certo: o instinto de [Nome] sobre [qualidade específica], que ainda estou aprendendo com ele(a).\n\nIsso não é falsa modéstia. É um obrigado, em plataforma pública, porque essa parte do trabalho costuma acontecer no silêncio. [Nome], o time é melhor com você nele.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Industry tip (3) =====
    [
        'slug' => 'data_point_take',
        'category' => 'industry_tip',
        'name' => 'Dado e o que ele significa',
        'description' => 'Compartilhe um dado recente de fonte real e a sua interpretação.',
        'content' => "[Fonte, relatório, estudo, dataset público] divulgou esse número semana passada: [estatística específica].\n\nA maior parte das interpretações que vi enquadra como [interpretação comum]. Acho que isso erra o ponto.\n\nQuando você corta os mesmos dados por [dimensão, segmento, geografia, tamanho de empresa, período], o quadro vira. [Subgrupo específico] está [comportamento específico], enquanto [outro subgrupo] está [comportamento diferente]. O número da manchete junta essas duas histórias numa média que não descreve nenhuma.\n\nA implicação prática pra [público]: [recomendação específica]. Não [conselho comum], porque ele se apoia numa média que não existe.\n\nLink pros dados brutos: [link]. Me diga onde estou errado.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'contrarian_take',
        'category' => 'industry_tip',
        'name' => 'Opinião contrária com argumento',
        'description' => 'Confronte uma crença comum do seu setor com um argumento específico.',
        'content' => "Opinião impopular em [setor]: [tese contrária].\n\nO conselho padrão diz [sabedoria convencional]. Segui isso por [prazo] e o resultado foi [resultado ruim ou medíocre específico].\n\nPor que isso não funciona tão bem quanto dizem: [motivo específico, incentivo, custo escondido, viés de sobrevivência, mercado mudou]. A versão que funciona pra [público] se parece mais com [abordagem alternativa].\n\nPra registro, foi o caminho que tomamos na {{brand_name}} depois de [evento gatilho]. Números desde então: [resultado específico]. Não estou dizendo que todo mundo deveria fazer assim. Estou dizendo que \"porque todo mundo diz\" é um motivo ruim pra continuar fazendo a mesma coisa.\n\nEm que pé você está nessa?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'trend_watch',
        'category' => 'industry_tip',
        'name' => 'Tendência que vale acompanhar',
        'description' => 'Coloque luz numa tendência menor antes que ela vire mainstream.',
        'content' => "Tendência discreta em [setor] que acho que vai virar pauta de todo mundo em [prazo]: [tendência específica].\n\nO sinal que estou observando: [evidência concreta, padrão de contratação, novos entrantes, mudança de preço, o que os clientes estão pedindo]. Três [empresas/times] diferentes na nossa rede fizeram [coisa específica] nos últimos [período], cada uma por conta própria.\n\nPor que acho que isso importa de fato e não é só hype: [motivo ancorado em incentivos, não em vibe]. O que me faria mudar de ideia: [contrassinal específico que eu observaria].\n\nSe você é [público], o movimento prático hoje é [ação específica]. Não um pivô que aposta a empresa. Só o suficiente pra você não ser pego de calça curta em [prazo].\n\nO que você está vendo?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Event (3) =====
    [
        'slug' => 'event_recap',
        'category' => 'event',
        'name' => 'Resumo de evento com lições',
        'description' => 'Resuma um evento que você frequentou com pontos específicos.',
        'content' => "Voltei do [Nome do Evento]. Três coisas ficaram comigo, e uma que ainda estou debatendo na cabeça.\n\nO que se sustentou: [sessão ou palestrante específico], que defendeu que [argumento específico]. A parte que eu ainda não tinha considerado: [insight específico].\n\nO que vou levar pra {{brand_name}}: [mudança concreta que você fará por causa do evento]. Pequena o suficiente pra começar semana que vem, grande o suficiente pra fazer diferença.\n\nO ponto em que discordei: [opinião específica de uma sessão]. O argumento estava bem montado, mas ignora [realidade específica]. Vou escrever isso direito.\n\nSe você estava lá, o que escapou? Sempre tem mais coisa nas conversas de corredor do que no palco principal.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'speaking_announcement',
        'category' => 'event',
        'name' => 'Anúncio de palestra',
        'description' => 'Avise que você ou alguém do time vai palestrar num evento.',
        'content' => "Vou palestrar no [Nome do Evento] no dia [data] em [local / online].\n\nO tema: \"[Título da Palestra]\". O resumo curto: [uma ou duas frases sobre o que o público vai levar de fato].\n\nO que eu não vou fazer: passar boas práticas genéricas de [tema]. Já tem palestra demais assim. O que eu vou fazer: mostrar [dado, framework ou caso] específico da {{brand_name}} que mudou como pensamos sobre [problema específico], incluindo as partes que não funcionaram.\n\nSe for estar lá, me procure, prefiro ter uma conversa de verdade do que ficar trocando cartão. Inscrições: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'webinar_invitation',
        'category' => 'event',
        'name' => 'Convite para webinar',
        'description' => 'Convide sua rede para um webinar com agenda clara e honesta.',
        'content' => "Vou apresentar um webinar de [duração, ex.: 45 minutos] com [Nome do Co-host, cargo] no dia [data].\n\nTema: [tema específico, como uma pergunta que seu público realmente faz]. Não é demo de produto. Vamos passar por [framework, dataset ou fluxo específico] que usamos na {{brand_name}}.\n\nAgenda inicial:\n• [Horário], [Tema, com um detalhe que mostra o conteúdo real]\n• [Horário], [Tema]\n• [Horário], Q&A ao vivo. Respondemos tudo, inclusive as perguntas desconfortáveis.\n\nO replay vai pra todo mundo que se inscreveu, mesmo se não der pra assistir ao vivo. Inscrição: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Engagement (3) =====
    [
        'slug' => 'poll_post',
        'category' => 'engagement',
        'name' => 'Enquete com opinião',
        'description' => 'Faça uma pergunta direta de A ou B que revela opiniões reais.',
        'content' => "Curioso pra ver como o pessoal de [público] está se dividindo nessa.\n\nQuando você decide [decisão específica], você tende a:\n\nA) [Opção A, descrita de forma concreta]\nB) [Opção B, descrita de forma concreta]\n\nNada de \"depende\" nos comentários, por favor. Escolhe uma e me diz por quê em uma frase.\n\nMinha resposta: [sua escolha honesta]. O motivo: [uma ou duas frases vindas de experiência real]. Eu defendia o oposto por [prazo] até [coisa que mudou minha cabeça].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'hot_take_invitation',
        'category' => 'engagement',
        'name' => 'Convite para opinião forte',
        'description' => 'Convide a rede a dividir uma opinião polêmica da área dela.',
        'content' => "Qual é uma opinião sua sobre [setor/cargo] que faz as pessoas te olharem torto em conferência?\n\nA minha: [opinião sua que é levemente polêmica na sua área, dita sem rodeios]. Já errei em muita coisa, mas nessa eu seguro a posição.\n\nNão estou atrás das opiniões seguras que já têm 500 carrosséis no LinkedIn. As que você diria no jantar depois do painel, quando já parou de performar.\n\nManda. Vou estar nos comentários debatendo de boa-fé.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'crowdsourced_advice',
        'category' => 'engagement',
        'name' => 'Pedido de conselho coletivo',
        'description' => 'Peça à sua rede ajuda com um problema real e específico.',
        'content' => "Pedindo o cérebro coletivo num problema real que estamos tentando resolver na {{brand_name}}.\n\nContexto: [situação específica em 2-3 frases, suficiente pra alguém qualificado ajudar de verdade]. A restrição que faz a resposta óbvia não servir: [restrição específica].\n\nO que já tentei: [opção um, e por que não encaixou]; [opção dois, e o que ela me ensinou]. Então não estou atrás dessas.\n\nSe você já resolveu algo parecido, o que funcionou? Comentário é ótimo, mas DM está aberto se for daquelas coisas que prefere não falar em público. Vou escrever sobre o que decidirmos fazer e marcar quem ajudou a moldar.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
