<?php

declare(strict_types=1);

return [
    [
        'slug' => 'company_milestone',
        'category' => 'behind_the_scenes',
        'name' => 'Marco da empresa',
        'description' => 'Comemore um marco da empresa pela página da marca.',
        'content' => "Hoje a {{brand_name}} chegou a [marco, ex.: 1.000 clientes, 5 anos, \$X de ARR].\n\nIsso não aconteceu por causa de uma única pessoa. Aconteceu porque [time / clientes / comunidade] apareceram todos os dias.\n\nObrigado a todo mundo que fez parte dessa caminhada. Estamos só começando.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'hiring_announcement',
        'category' => 'engagement',
        'name' => 'Estamos contratando',
        'description' => 'Anuncie vagas abertas e convide candidaturas pela página da empresa.',
        'content' => "A {{brand_name}} está contratando.\n\nEstamos buscando [vaga(s)] para entrar com a gente em [time/missão].\n\nO que oferecemos:\n→ [Destaque 1]\n→ [Destaque 2]\n→ [Destaque 3]\n\nSe parece com você (ou com alguém que você conhece), candidate-se ou compartilhe → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'thought_leadership_page',
        'category' => 'industry_tip',
        'name' => 'Visão sobre o setor',
        'description' => 'Compartilhe a posição da empresa sobre uma tendência ou mudança no setor.',
        'content' => "O cenário de [setor] está mudando.\n\nO que a gente tem visto na {{brand_name}}:\n\n1. [Observação]\n2. [Observação]\n3. [Observação]\n\nO que isso significa para [público]: [implicação].\n\nO que vocês estão notando aí?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== product_launch =====
    [
        'slug' => 'new_feature_release',
        'category' => 'product_launch',
        'name' => 'Lançamento de nova funcionalidade',
        'description' => 'Anuncie uma nova funcionalidade específica e o problema que ela resolve.',
        'content' => "Hoje colocamos [nome da funcionalidade] no ar.\n\nA versão curta: [descrição em uma linha do que ela faz].\n\nA versão mais longa: nossos clientes vinham repetindo [dor específica]. Tentamos [solução paliativa anterior] por uns [período de tempo] e nunca ficou bom. Então reescrevemos [área] do zero.\n\nAlgumas coisas que mudaram:\n[Comportamento antes] virou [comportamento depois].\n[Etapa manual] agora roda automaticamente.\n[Limite] caiu.\n\nSe quiser testar, a documentação está aqui: [link]. Se achar algo quebrado, nosso time está nos comentários.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'beta_open_signups',
        'category' => 'product_launch',
        'name' => 'Beta aberto para inscrições',
        'description' => 'Convide clientes e prospectos para um beta público ou privado.',
        'content' => "O acesso beta para [produto/funcionalidade] está aberto.\n\nPassamos [período de tempo] rodando com [número] testadores privados. O retorno foi bom o suficiente para a gente abrir mais a porta.\n\nPara quem é: [descrição específica do usuário, ex.: times rodando >X campanhas/mês].\nPara quem ainda não é: [exclusão honesta, ex.: empresas que precisam de SSO].\n\nVamos limitar essa próxima rodada a [número] empresas para o time conseguir acompanhar cada conta de perto. As vagas vão por ordem de chegada.\n\nPeça acesso: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'integration_partnership',
        'category' => 'product_launch',
        'name' => 'Integração com parceiro',
        'description' => 'Anuncie uma nova integração ou parceria técnica.',
        'content' => "A {{brand_name}} agora se conecta com [parceiro].\n\nSe você usa os dois, pode parar com [etapa manual]. A integração lida com [fluxo de dados específico] de forma automática.\n\nO que mudou para nossos clientes em comum:\nNada de exportar [dados] e reimportar do outro lado.\n[Gatilho] em [parceiro] agora cria [ação] na {{brand_name}}.\nO mapeamento de campos é editável, então configurações personalizadas continuam funcionando.\n\nObrigado ao time da [parceiro] pelas conversas sobre a API. Guia de configuração: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'product_redesign',
        'category' => 'product_launch',
        'name' => 'Lançamento do redesign do produto',
        'description' => 'Anuncie uma reformulação relevante de UI ou produto.',
        'content' => "Redesenhamos [produto/área]. Está no ar para todo mundo hoje.\n\nNosso time de design ficou meio quieto por aqui nos últimos meses por causa disso. A [área] antiga foi crescendo de forma orgânica e acabou com [problema específico, ex.: quatro maneiras diferentes de iniciar um novo projeto]. Os clientes nos avisaram. Concordamos.\n\nO que está diferente:\nUma ação principal por tela, em vez de três.\n[Elemento antigo] foi para [novo lugar] para parar de atrapalhar.\n[Padrão específico] que ninguém usava saiu.\n\nSe alguma coisa parecer estranha nos primeiros dias, é normal. Responda aqui ou fale com nosso time em [contato] que a gente resolve.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== promotion =====
    [
        'slug' => 'limited_time_offer',
        'category' => 'promotion',
        'name' => 'Oferta por tempo limitado',
        'description' => 'Anuncie um desconto ou oferta de preço com prazo claro.',
        'content' => "[Oferta, ex.: 25% de desconto no primeiro ano da {{brand_name}}] vai até [data específica].\n\nA gente raramente faz desconto. Esse aqui está ligado a [motivo, aniversário, fim de trimestre, marco do produto] e não vamos repetir nas mesmas condições nos próximos [período de tempo].\n\nPara quem vale: [elegibilidade, novos clientes, planos anuais, plano específico].\nPara quem não vale: [exclusão honesta].\n\nUse [código] no checkout, ou fale com nosso time se quiser ajuda para escolher um plano: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'free_resource_offer',
        'category' => 'promotion',
        'name' => 'Material gratuito',
        'description' => 'Promova um guia, modelo ou relatório gratuito.',
        'content' => "Fizemos um [recurso, guia, modelo, relatório de benchmark] gratuito para [público].\n\nEle aborda [tópico específico 1], [tópico específico 2] e os [número] erros que mais aparecem quando trabalhamos com [tipo de cliente alvo]. Cerca de [número] páginas, sem barreira de e-mail além do nome e e-mail corporativo.\n\nPor que é gratuito: [motivo honesto, ex.: criamos primeiro para nossos clientes, e é o tipo de coisa que rende mais quando está em mais mãos].\n\nBaixe aqui: [link]. Conta para a gente o que está faltando que a gente atualiza na próxima versão.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'referral_program_launch',
        'category' => 'promotion',
        'name' => 'Anúncio de programa de indicação',
        'description' => 'Promova um programa de indicação para clientes pela página da empresa.',
        'content' => "Lançamos um programa de indicação para clientes da {{brand_name}}.\n\nSe você indicar uma empresa que vire cliente pagante, os dois lados ganham [benefício específico, ex.: um mês grátis, \$X de crédito, liberação de funcionalidade]. Sem níveis. Sem ranking. Sem caneca.\n\nA gente resistiu por um tempo a fazer isso porque a maioria dos programas de indicação parece pirâmide disfarçada. Acabamos chegando aqui porque nosso maior canal de crescimento no ano passado foi cliente falando com cliente, e ficou estranho não dividir o ganho.\n\nDetalhes e seu link de indicação: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== educational =====
    [
        'slug' => 'how_we_solve_problem',
        'category' => 'educational',
        'name' => 'Como abordamos um problema',
        'description' => 'Mostre como a empresa lida com um problema recorrente dos clientes.',
        'content' => "Uma pergunta que a gente recebe toda semana: [pergunta específica].\n\nA forma como pensamos sobre isso na {{brand_name}}:\n\nA maioria dos times começa com [movimento inicial comum]. Funciona até bater em [ponto específico de falha]. Quando isso acontece, você fica preso adicionando [solução paliativa] toda vez que algo muda.\n\nUm caminho diferente: [abordagem alternativa]. O preço é [custo honesto, ex.: configuração mais lenta, mais reflexão no início, mais difícil de explicar para alguém novo]. O lado bom é que [benefício específico] deixa de ser um incêndio recorrente.\n\nEscrevemos a versão longa aqui: [link]. Discorda? Os comentários estão abertos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'customer_data_insight',
        'category' => 'educational',
        'name' => 'Insight de dados de clientes',
        'description' => 'Compartilhe um padrão útil observado na base de clientes.',
        'content' => "Olhamos [métrica/comportamento] em [número] contas {{brand_name}} no último trimestre.\n\nUma coisa chamou atenção: [achado específico com número, ex.: times que fizeram X na primeira semana tiveram 3x mais chance de continuar ativos no sexto mês].\n\nEsperávamos o oposto. Nossa hipótese inicial era [suposição antiga], em parte por causa de [motivo]. Os dados não concordaram.\n\nAlguns ressaltos: isso é correlação, não causa. A amostra puxa para [segmento]. E [período de tempo] é curto.\n\nMesmo assim, se você é novo na {{brand_name}}, [recomendação prática] provavelmente vale a pena na primeira semana.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake_breakdown',
        'category' => 'educational',
        'name' => 'Detalhamento de erro comum',
        'description' => 'Explique um erro recorrente e como evitá-lo.',
        'content' => "O erro mais comum que vemos quando times adotam [ferramenta/processo/prática]: [erro específico].\n\nGeralmente acontece assim. Um time começa com [configuração]. Em poucas semanas, eles adicionam [solução paliativa] porque [motivo]. No terceiro mês, a paliativa virou o sistema, e ninguém lembra mais o porquê.\n\nO conserto não é [resposta óbvia]. O conserto é voltar e perguntar se [suposição original] alguma vez foi verdade no caso de vocês. Metade das vezes, não foi.\n\nEscrevemos isso porque cometemos o mesmo erro internamente em [ano]. Detalhamento completo: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'tool_comparison',
        'category' => 'educational',
        'name' => 'Comparação honesta de ferramentas',
        'description' => 'Compare abordagens ou ferramentas para um caso específico, incluindo onde a empresa perde.',
        'content' => "Quando usar a {{brand_name}}, e quando não usar?\n\nA gente recebe a primeira metade dessa pergunta o tempo todo. Aqui vai a segunda metade.\n\nUse a {{brand_name}} quando [situação específica, ex.: você tem mais de X de Y, ou precisa da capacidade Z].\n\nNão use a {{brand_name}} quando [exclusão honesta, ex.: você é um único usuário com menos de X, ou seu fluxo é totalmente [categoria adjacente]]. Nesses casos, [concorrente ou abordagem alternativa] encaixa melhor de verdade, e a gente fala isso numa call de vendas.\n\nDetalhamento completo, com comparação lado a lado: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== behind_the_scenes =====
    [
        'slug' => 'team_offsite_recap',
        'category' => 'behind_the_scenes',
        'name' => 'Resumo do offsite do time',
        'description' => 'Resuma um offsite ou all-hands recente do time.',
        'content' => "Fechamos nosso offsite em [cidade] semana passada.\n\n[Número] pessoas, [número] dias, um quadro branco que apanhou bastante. Cerca de um terço da empresa se encontrou pessoalmente pela primeira vez, o que acontece quando você cresce [de X para Y] em um ano.\n\nGastamos mais tempo em [tópico] do que tinha sido planejado e menos em [outro tópico] do que esperávamos. A conversa mais difícil foi sobre [tópico honesto, ex.: o que paramos de fazer no segundo semestre]. Não resolvemos por completo. Tudo bem.\n\nO próximo é em [local] em [mês]. Até lá, vamos ser [número] pessoas. Não sei como vai ser.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'office_or_remote_culture',
        'category' => 'behind_the_scenes',
        'name' => 'Como trabalhamos',
        'description' => 'Compartilhe o modelo de trabalho da empresa de forma honesta.',
        'content' => "Como a {{brand_name}} trabalha de verdade, já que perguntam.\n\nSomos [totalmente remotos / híbridos / com base em X e times remotos] em [número] fusos horários. Sem dias obrigatórios no escritório. Fazemos um all-hands por semana e um update assíncrono nas sextas.\n\nAs partes que a gente gosta: blocos de trabalho focado, contratação por várias regiões, agendas mais limpas.\n\nAs partes mais difíceis: o onboarding leva mais tempo do que levaria pessoalmente. Ideias novas às vezes morrem em DM. A sobreposição de horário com [região] é dura.\n\nNão estamos dizendo que é o modelo certo para toda empresa. É o que funciona para a nossa hoje.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'engineering_decision',
        'category' => 'behind_the_scenes',
        'name' => 'Resumo de decisão de engenharia',
        'description' => 'Compartilhe uma decisão técnica ou de produto interna e o raciocínio.',
        'content' => "No mês passado [tomamos uma decisão específica, ex.: saímos do X, reescrevemos Y, matamos a funcionalidade Z].\n\nA versão curta do porquê: [motivo em uma linha].\n\nA versão mais longa. A configuração antiga estava boa quando tínhamos [número] clientes. Em [escala atual], começou a aparecer em [sintoma específico]. Tentamos [conserto intermediário] por uns [período de tempo] até concordar que não ia segurar.\n\nO preço que aceitamos pagar: [custo honesto, ex.: duas semanas de releases mais lentos, breaking change para algumas integrações].\n\nEstamos contando porque queríamos que outros times falassem mais sobre esse tipo de decisão e não só sobre as vitórias.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mistake_postmortem',
        'category' => 'behind_the_scenes',
        'name' => 'Postmortem público',
        'description' => 'Compartilhe um erro, queda ou falha recente de forma honesta.',
        'content' => "Em [data], a {{brand_name}} teve [problema específico, ex.: uma queda, um bug de cobrança, um problema de dados afetando X% das contas] por cerca de [duração].\n\nO que aconteceu: [resumo técnico ou operacional em um parágrafo].\n\nQuem foi afetado: [escopo honesto, incluindo os clientes que não foram].\n\nO que fizemos: [conserto imediato e mitigação].\n\nO que estamos mudando para não acontecer da mesma forma de novo: [mudança específica, e não um genérico 'vamos fazer melhor'].\n\nSe você foi afetado e ainda não falamos diretamente, responda ou escreva para [contato]. Devemos uma conversa mais longa para algumas pessoas.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== testimonial =====
    [
        'slug' => 'customer_quote_short',
        'category' => 'testimonial',
        'name' => 'Citação curta de cliente',
        'description' => 'Compartilhe uma citação curta e específica de cliente na página da empresa.',
        'content' => "De uma conversa recente com [primeiro nome do cliente], [cargo] na [empresa]:\n\n\"[Citação do cliente, com referência a um resultado, número ou mudança específica. Evite elogios genéricos do tipo 'ótimo produto'.]\"\n\nPerguntamos se podíamos compartilhar. Disseram que sim.\n\nO contexto por trás da citação: [uma ou duas frases sobre o que estavam tentando fazer e o que mudou].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'case_study_recap',
        'category' => 'testimonial',
        'name' => 'Resumo de case',
        'description' => 'Resuma um case de cliente publicado.',
        'content' => "Novo case: [nome do cliente].\n\nAntes da {{brand_name}}, o time deles estava [situação específica, ex.: rodando X manualmente, gastando Y horas/semana em Z]. Depois de [período de tempo] usando a {{brand_name}}, [resultado específico com número].\n\nAlgumas coisas que eles fizeram e que outros clientes nem sempre tentam:\n[Tática específica do cliente].\n[Outra tática].\n[Nota honesta: algo que ainda estão entendendo].\n\nVersão completa com o fluxo real do time deles e prints: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'unexpected_use_case',
        'category' => 'testimonial',
        'name' => 'Uso inesperado do produto',
        'description' => 'Destaque um uso criativo ou inesperado do produto pelos clientes.',
        'content' => "A gente não construiu a {{brand_name}} pensando em [caso de uso inesperado], mas tem cliente usando assim.\n\n[Cliente ou segmento de clientes] começou a [comportamento específico] uns [período de tempo] atrás. Notamos por causa de [sinal, ex.: pico de uso em uma funcionalidade específica, ticket de suporte pedindo X]. Quando perguntamos a eles, a resposta foi: [raciocínio do cliente parafraseado].\n\nNão está no nosso roadmap. Pode entrar em breve. Se você está fazendo algo parecido, nosso time de produto adoraria saber. Responde aqui ou escreve para [contato].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== industry_tip =====
    [
        'slug' => 'contrarian_take',
        'category' => 'industry_tip',
        'name' => 'Opinião contrária',
        'description' => 'Defenda uma posição clara contra uma ideia popular do setor.',
        'content' => "Uma opinião que a gente leva bronca em conferências: [posição contrária, dita sem rodeios].\n\nO argumento de sempre é [posição popular]. Não está errado em todos os casos. Está errado na maioria dos casos que vemos, e o motivo é o seguinte.\n\n[Motivo 1 com exemplo específico].\n[Motivo 2 com exemplo específico].\n\nA contestação que sempre recebemos: [contra-argumento bem feito]. Faz sentido, e concordamos que vale quando [condição específica]. Fora dessa condição, o conselho de sempre custa caro para os times sem ninguém perceber.\n\nA gente aceita estar errado nessa. Conta para a gente nos comentários por que estamos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'industry_benchmark',
        'category' => 'industry_tip',
        'name' => 'Benchmark do setor',
        'description' => 'Compartilhe um benchmark ou métrica agregada da base de clientes.',
        'content' => "Benchmark rápido para [público].\n\nEm [número] contas {{brand_name}} de [setor/segmento] no último trimestre, a mediana de [métrica] foi [valor]. O percentil 90 foi [valor]. Os 25% mais baixos ficaram abaixo de [valor].\n\nSe você está abaixo da mediana, o motivo mais comum que vemos é [motivo específico]. O conserto raramente é [resposta óbvia]. Costuma ser [conserto real].\n\nSe você está acima do percentil 90, provavelmente já faz [comportamento específico], e a gente queria muito conversar com você sobre isso. Responde ou manda DM para a página.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'trend_we_disagree_with',
        'category' => 'industry_tip',
        'name' => 'Tendência com a qual discordamos',
        'description' => 'Conteste uma prática em alta no setor com argumentos.',
        'content' => "Metade dos posts de [setor] que vemos esse mês é sobre [prática em alta].\n\nA gente não vai adotar isso na {{brand_name}}, e provavelmente não vamos.\n\nO discurso é [enquadramento popular]. A versão honesta, na nossa experiência, é que funciona em [cenário restrito] e falha sem barulho em [cenário comum] por causa de [motivo específico]. Testamos uma versão disso internamente por [período de tempo] e o resultado foi [resultado específico].\n\nNão estou dizendo que ninguém deva fazer. Estou dizendo que para [público alvo], o tempo rende mais em [alternativa].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'practical_framework',
        'category' => 'industry_tip',
        'name' => 'Framework prático',
        'description' => 'Compartilhe um framework ou regra simples que o time usa internamente.',
        'content' => "Uma regra de bolso que nosso time usa para decidir [decisão específica]:\n\nSe [condição A], faça [opção 1].\nSe [condição B], faça [opção 2].\nSe não dá para saber em qual você está, provavelmente está em [opção 1] complicando à toa.\n\nIsso não é um framework com nome. Saiu de uns [período de tempo] errando a mesma decisão de jeitos um pouco diferentes. Poupa uma ou duas discussões por semana.\n\nÚtil? Inútil? Conta como vocês decidem.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== event =====
    [
        'slug' => 'event_announcement',
        'category' => 'event',
        'name' => 'Anúncio de evento',
        'description' => 'Anuncie um evento, webinar ou workshop da empresa.',
        'content' => "Vamos receber [nome do evento] em [data] às [horário/fuso].\n\nFormato: [virtual / presencial em cidade / híbrido].\nPara quem é: [público específico, ex.: heads de marketing em SaaS B2B, 20-200 pessoas].\nO que vamos abordar: [tópico 1] e [tópico 2]. Sem keynote. Sem desfile de fornecedor.\n\nVamos limitar a inscrição em [número] para o Q&A funcionar de verdade. Pelos eventos passados, é na segunda metade que aparecem as coisas boas.\n\nInscreva-se: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_recap',
        'category' => 'event',
        'name' => 'Resumo de evento',
        'description' => 'Resuma um evento recente que a empresa organizou ou participou.',
        'content' => "[Nome do evento] terminou em [data]. Algumas coisas que vale anotar antes de esquecer.\n\nA sala ficou mais animada em [momento ou tópico específico]. Nossa hipótese era que [tópico A] ia dominar. Não dominou. [Tópico B] dominou, e a gente devia ter previsto.\n\nA pergunta mais útil que recebemos: [pergunta parafraseada]. Nossa resposta foi honesta, mas fraca. Se foi você que perguntou, a gente te deve uma resposta melhor, responde aqui.\n\nObrigado a [parceiro / espaço / palestrantes] por fazerem o evento acontecer. As gravações saem semana que vem: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'conference_attendance',
        'category' => 'event',
        'name' => 'Participação em conferência',
        'description' => 'Anuncie que o time vai estar em uma conferência futura.',
        'content' => "A {{brand_name}} vai estar na [conferência] em [cidade] de [data] a [data].\n\nVamos em [número] pessoas. Esse ano não vamos ter estande. Tentamos no ano passado e as conversas mais úteis aconteceram longe dele.\n\nSe quiser conversar:\n[Nome de pessoa do time] está por lá [dias/horários], com mais interesse em [tópico].\n[Outra pessoa do time] vai apresentar sobre [tópico] em [dia].\nJantar em [data], grupo pequeno, responde se quiser entrar.\n\nReserve um horário aqui: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== engagement =====
    [
        'slug' => 'open_question_to_audience',
        'category' => 'engagement',
        'name' => 'Pergunta aberta ao público',
        'description' => 'Faça uma pergunta real e específica para o público da página.',
        'content' => "Uma pergunta de verdade para [público] essa semana.\n\nQuando [situação específica, ex.: você está escopando um projeto novo, escolhendo um fornecedor, decidindo o que cortar], como você decide na prática?\n\nNão a versão que entra num slide. A versão que envolve [fator honesto, ex.: quem está disponível naquela semana, em que humor o CFO está, qual ferramenta o time já conhece].\n\nA gente vem rodando uma versão interna dessa pergunta na {{brand_name}} há um mês e as respostas estão mais interessantes que qualquer framework que vimos. Manda a sua que a gente compartilha o que ouviu.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'we_want_your_feedback',
        'category' => 'engagement',
        'name' => 'Pedido de feedback',
        'description' => 'Peça opinião do público sobre uma decisão de roadmap específica.',
        'content' => "Estamos travados em uma coisa e queremos a sua opinião.\n\nPara a próxima versão da {{brand_name}}, estamos escolhendo entre dois caminhos para [área].\n\nOpção A: [direção específica, com o trade-off].\nOpção B: [direção específica, com o trade-off].\n\nOs dois são reais. Nenhum é obviamente certo. Os clientes que perguntamos estão divididos quase meio a meio, que é o pior cenário possível para um time de produto que quer entregar.\n\nSe tiver opinião, principalmente uma forte, responde aqui ou manda DM para a página. Nosso time de produto lê tudo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'community_spotlight',
        'category' => 'engagement',
        'name' => 'Destaque da comunidade',
        'description' => 'Destaque um cliente, parceiro ou membro da comunidade fazendo algo interessante.',
        'content' => "Destaque para [nome], [cargo] na [empresa].\n\nA gente reparou em [trabalho ou post específico] semana passada e acabou repassando dentro do time da {{brand_name}}. Versão curta do porquê: [motivo específico, o que fizeram que era diferente, útil ou na contramão].\n\nVá seguir, se ainda não segue. Não temos nenhum acordo comercial aqui. Eles só estão fazendo o tipo de trabalho que a gente queria ver mais gente fazendo de forma pública em [setor].\n\n[Link para o post / perfil].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'year_in_review',
        'category' => 'engagement',
        'name' => 'Retrospectiva do ano',
        'description' => 'Retrospectiva honesta de fim de ano pela página da empresa.',
        'content' => "Uma retrospectiva curta da {{brand_name}}.\n\nO bom: [vitória específica com número]. [Outra vitória específica, de preferência um resultado de cliente, e não uma métrica de vaidade].\n\nO difícil: [erro honesto, ex.: uma aposta de produto que não deu certo, uma meta de contratação que não batemos, uma meta que definimos em janeiro e abandonamos sem alarde em junho].\n\nO surpreendente: [coisa inesperada que importou, um segmento de cliente que decolou, uma funcionalidade que ninguém tinha pedido e virou peça-chave].\n\nObrigado aos [número] clientes, [número] pessoas do time e a quem respondia nossos posts às 23h pedindo para a gente entregar. O ano que vem vai ser mais estranho que esse.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
