<?php

declare(strict_types=1);

return [
    [
        'slug' => 'mastodon_release_note',
        'category' => 'product_launch',
        'name' => 'Notas da release',
        'description' => 'Compartilhe uma atualização aberta e transparente sobre uma release.',
        'content' => "Notas da release de {{brand_name}}:\n\n→ [O que foi entregue]\n→ [Por que importa]\n→ [O que vem a seguir]\n\nFeedback é bem-vindo. Responda ou abra uma issue.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_lessons_learned',
        'category' => 'educational',
        'name' => 'Lições aprendidas',
        'description' => 'Compartilhe algo que você aprendeu, no estilo direto do Mastodon.',
        'content' => "Algo que aprendemos em {{brand_name}} esta semana:\n\n[Lição, seja específico.]\n\nA conclusão: [princípio].\n\nTalvez seja útil para outra pessoa construindo [coisa parecida].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_open_question',
        'category' => 'engagement',
        'name' => 'Pergunta aberta',
        'description' => 'Faça uma pergunta ao fediverso e colete perspectivas.',
        'content' => "Pergunta para o fediverso:\n\n[Pergunta aberta relevante para seu público.]\n\nBoosts são bem-vindos se seus seguidores tiverem algo a dizer.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // product_launch
    [
        'slug' => 'mastodon_version_bump',
        'category' => 'product_launch',
        'name' => 'Nova versão',
        'description' => 'Anuncie uma nova versão com o diff que realmente importa.',
        'content' => "{{brand_name}} [versão] saiu.\n\nO que mudou:\n- [Correção ou recurso]\n- [Correção ou recurso]\n- [Breaking change, se houver]\n\nNotas de upgrade: [link ou instrução curta].\n\nSe algo quebrar, conte para a gente. A gente lê toda resposta.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_new_feature_in_public',
        'category' => 'product_launch',
        'name' => 'Recurso novo em público',
        'description' => 'Lance um recurso e explique por que foi feito assim.',
        'content' => "Adicionamos [recurso] em {{brand_name}} hoje.\n\nPor quê: [o motivo real, em uma frase].\n\nComo funciona: [descrição curta e concreta].\n\nO código está aqui: [link]. Pull requests são bem-vindos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_beta_invite',
        'category' => 'product_launch',
        'name' => 'Convite para beta',
        'description' => 'Convide o fediverso para um beta com expectativas honestas.',
        'content' => "Procuramos beta testers para [recurso] em {{brand_name}}.\n\nEstá rústico. Algumas coisas vão quebrar. Queremos saber quais.\n\nInscrição: [link]\n\nSem NDA, sem lista de marketing, sem upsell. Só precisamos de usuários reais.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_self_host_release',
        'category' => 'product_launch',
        'name' => 'Release para self-host',
        'description' => 'Avise quem faz self-host sobre uma release com os detalhes operacionais.',
        'content' => "Aviso a quem faz self-host de {{brand_name}}: [versão] foi taggeada.\n\nMigrations: [sim/não, estimativa de tempo]\nMudanças de config: [lista ou nenhuma]\nBreaking: [lista ou nenhuma]\n\nDocs: [link]. Issues: [link]. Boosts são bem-vindos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // promotion
    [
        'slug' => 'mastodon_paid_plan_honest',
        'category' => 'promotion',
        'name' => 'Plano pago, sem rodeios',
        'description' => 'Mencione um plano pago sem soar como propaganda.',
        'content' => "{{brand_name}} agora tem plano pago. O que você ganha: [recurso], [recurso], [recurso].\n\nO plano gratuito continua fazendo [o que sempre fez]. Não estamos tirando nada.\n\nDetalhes: [link]. Perguntas são bem-vindas.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_sponsor_us',
        'category' => 'promotion',
        'name' => 'Patrocine a gente',
        'description' => 'Peça patrocínio ou doações de forma transparente.',
        'content' => "{{brand_name}} é sustentado por [número] horas de trabalho voluntário e [custo de hosting] por mês.\n\nSe você usa e quer contribuir, o link de patrocínio está aqui: [link].\n\nA gente publica um detalhamento dos gastos a cada trimestre. Sem tiers, sem brindes, só o trabalho.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_discount_for_indies',
        'category' => 'promotion',
        'name' => 'Desconto para indies',
        'description' => 'Ofereça um desconto sem dark patterns.',
        'content' => "{{brand_name}} está com [desconto] de desconto para devs solo e pequenas cooperativas até [data].\n\nSem cupom, sem cadastro de email. O preço é só mais baixo se você escolher o tier [nome do plano]. Use se ajudar.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // educational
    [
        'slug' => 'mastodon_quick_explainer',
        'category' => 'educational',
        'name' => 'Explicação rápida',
        'description' => 'Explique um conceito em linguagem clara, sem enrolação.',
        'content' => "Explicação rápida: [conceito].\n\n[Definição em uma frase.]\n\n[Uma frase sobre por que importa na prática.]\n\nSe quiser a versão longa, escrevemos aqui: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_misconception',
        'category' => 'educational',
        'name' => 'Mal-entendido comum',
        'description' => 'Corrija um mal-entendido comum com exemplos concretos.',
        'content' => "Muita gente acha que [crença comum sobre seu tema].\n\nNão é bem assim. [A situação real, com um exemplo específico.]\n\nIsso importa porque [consequência prática].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_reading_list',
        'category' => 'educational',
        'name' => 'Lista de leitura',
        'description' => 'Compartilhe uma lista de leitura curta e opinativa.',
        'content' => "Coisas que andamos lendo em {{brand_name}}:\n\n- [Título], de [autor]: [motivo em uma linha].\n- [Título], de [autor]: [motivo em uma linha].\n- [Título], de [autor]: [motivo em uma linha].\n\nResponda com o que você anda lendo. Sempre procurando indicações novas.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_how_we_decided',
        'category' => 'educational',
        'name' => 'Como decidimos',
        'description' => 'Mostre o caminho de uma decisão técnica ou de produto.',
        'content' => "Como escolhemos [ferramenta ou abordagem] em {{brand_name}}:\n\nTentamos [opção A]. Deu [problema]. Tentamos [opção B]. Tinha [tradeoff].\n\nFicamos com [opção escolhida] porque [motivo]. Não é perfeito. O que ainda incomoda é [ponto fraco].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // behind_the_scenes
    [
        'slug' => 'mastodon_dev_log',
        'category' => 'behind_the_scenes',
        'name' => 'Dev log',
        'description' => 'Compartilhe o que você de fato fez essa semana.',
        'content' => "Dev log, semana de [data]:\n\nSegunda: [coisa].\nTerça: [coisa].\nQuarta: [coisa que deu errado].\nQuinta: [conserto].\nSexta: [entregou ou adiou].\n\nEsta semana é mais [próximo foco].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_postmortem',
        'category' => 'behind_the_scenes',
        'name' => 'Postmortem curto',
        'description' => 'Compartilhe um postmortem em linguagem simples.',
        'content' => "{{brand_name}} teve uma indisponibilidade em [data]. A versão curta:\n\nO que quebrou: [sistema].\nPor quê: [causa raiz].\nDuração: [tempo].\nComo consertamos: [ação].\n\nWriteup completo com timeline: [link]. Desculpa pelo transtorno.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_tooling_setup',
        'category' => 'behind_the_scenes',
        'name' => 'Nosso ferramental',
        'description' => 'Mostre as ferramentas que você de fato usa.',
        'content' => "O que {{brand_name}} usa, caso você tenha curiosidade:\n\n- Editor: [editor]\n- Linguagem: [linguagem]\n- Banco: [banco]\n- Hosting: [host]\n- CI: [ci]\n\nNada exótico. Stack chata é stack produtiva.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_team_intro',
        'category' => 'behind_the_scenes',
        'name' => 'Quem somos',
        'description' => 'Apresente as pessoas por trás do projeto.',
        'content' => "Apresentação rápida: {{brand_name}} é [número] pessoas.\n\n[Nome] cuida de [área].\n[Nome] cuida de [área].\n[Nome] cuida de [área].\n\nA gente está espalhado por [regiões]. Contratamos abertamente quando contratamos, o que é raro. Olá.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // testimonial
    [
        'slug' => 'mastodon_user_quote',
        'category' => 'testimonial',
        'name' => 'Citação de usuário',
        'description' => 'Compartilhe uma citação real, com permissão e contexto.',
        'content' => "[Username] mandou isto sobre {{brand_name}}, postado com permissão:\n\n\"[Citação real.]\"\n\nIsso fez nossa semana. Obrigado [@username] por ter tirado um tempo pra escrever.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_use_case_share',
        'category' => 'testimonial',
        'name' => 'Como alguém usa',
        'description' => 'Destaque uma forma específica de alguém usar sua ferramenta.',
        'content' => "[Pessoa ou organização] usa {{brand_name}} para [caso de uso específico].\n\nO que contaram pra gente: \"[citação curta e específica].\"\n\nSe você tem um setup que vale a pena compartilhar, responda ou mande DM. A gente gosta de coletar esses casos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_thanks_contributor',
        'category' => 'testimonial',
        'name' => 'Obrigado a um contribuidor',
        'description' => 'Dê crédito a um contribuidor pelo nome.',
        'content' => "Agradecimento a [@username] por [contribuição específica] em {{brand_name}}.\n\nEsse tipo de trabalho não é glamouroso e é o motivo de o projeto seguir andando. Muito obrigado.\n\nO PR está aqui: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // industry_tip
    [
        'slug' => 'mastodon_practical_tip',
        'category' => 'industry_tip',
        'name' => 'Dica prática',
        'description' => 'Compartilhe uma dica real e específica.',
        'content' => "Dica para quem trabalha com [tópico]:\n\n[Uma dica concreta em linguagem simples.]\n\nA gente descobriu isso na marra depois de [contexto curto]. Talvez economize algumas horas de outra pessoa.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_unpopular_opinion',
        'category' => 'industry_tip',
        'name' => 'Opinião impopular',
        'description' => 'Compartilhe uma posição contrária em que você acredita de verdade.',
        'content' => "Opinião que nos coloca em apuros: [crença contrária na sua área].\n\nMotivo: [o caso específico em que isso vale].\n\nA gente aceita estar errado. Se você discorda, responda com o caso que a gente lê.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_anti_pattern',
        'category' => 'industry_tip',
        'name' => 'Antipattern',
        'description' => 'Aponte um antipattern comum com cuidado.',
        'content' => "Antipattern que vemos muito em [domínio]: [o padrão].\n\nPor que machuca: [modo de falha específico].\n\nO que fazer no lugar: [alternativa]. Nem sempre, mas na maioria das vezes.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_stop_doing_this',
        'category' => 'industry_tip',
        'name' => 'Pare de fazer isso',
        'description' => 'Confronte um hábito que custa tempo das pessoas.',
        'content' => "Empurrão amigável: pare de [hábito comum] ao trabalhar com [domínio].\n\nIsso custa [custo específico] e a alternativa é [alternativa], que dá [esforço].\n\nA gente fez isso por anos. A mudança é pequena e o retorno é real.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // event
    [
        'slug' => 'mastodon_event_announce',
        'category' => 'event',
        'name' => 'Anúncio de evento',
        'description' => 'Anuncie um evento sem hype.',
        'content' => "{{brand_name}} estará em [evento] no dia [data] em [cidade].\n\n[Palestrante ou pessoa do time] vai falar sobre [tópico] às [horário].\n\nSe você estiver por perto, passa pra dar um oi. Boosts são bem-vindos para quem do fediverso pode estar na cidade.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_meetup_call',
        'category' => 'event',
        'name' => 'Chamada para meetup',
        'description' => 'Convide pessoas para um encontro da comunidade.',
        'content' => "Chamada da comunidade {{brand_name}} nesta [dia] às [horário UTC].\n\nPauta: [tópico], [tópico], Q&A aberto.\n\nLink: [link do vídeo]. As notas saem depois em [link]. Sem barreira de login.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_event_recap',
        'category' => 'event',
        'name' => 'Resumo de evento',
        'description' => 'Resuma um evento com aprendizados concretos.',
        'content' => "De volta de [evento]. Três coisas que ficaram com a gente:\n\n1. [Aprendizado específico].\n2. [Aprendizado específico].\n3. [Aprendizado específico].\n\nOs slides da nossa palestra estão no ar: [link]. Obrigado a quem passou na nossa mesa.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // engagement
    [
        'slug' => 'mastodon_what_are_you_using',
        'category' => 'engagement',
        'name' => 'O que você está usando',
        'description' => 'Pergunte que ferramentas ou setups as pessoas usam.',
        'content' => "Curioso sobre o que o fediverso anda usando para [tarefa específica] em [ano].\n\nA gente está em [setup atual] e é [avaliação honesta]. Quero saber por o que você trocaria e por quê.\n\nResponda com a ferramenta e uma frase sobre o tradeoff.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_show_your_work',
        'category' => 'engagement',
        'name' => 'Mostre seu trabalho',
        'description' => 'Convide as pessoas a mostrarem o que estão construindo.',
        'content' => "Thread de mostre-e-conte: o que você está construindo esta semana?\n\nA gente começa. {{brand_name}} está trabalhando em [coisa]. Está em [estágio] e a gente está travado em [problema].\n\nResponda com o seu. Boosts ajudam outras pessoas a encontrar.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
