<?php

declare(strict_types=1);

return [
    [
        'slug' => 'pinterest_how_to',
        'category' => 'educational',
        'name' => 'Pin de tutorial',
        'description' => 'Pin passo a passo que gera salvamentos e cliques.',
        'content' => "Como [alcançar resultado] em [tempo/esforço].\n\nUm guia simples de {{brand_name}}.\n\nPasso 1: [Ação]\nPasso 2: [Ação]\nPasso 3: [Ação]\n\nTutorial completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['tutorial', 'how-to', 'guide'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_inspiration',
        'category' => 'behind_the_scenes',
        'name' => 'Painel de inspiração',
        'description' => 'Pin inspirador em torno de um tema ou estética.',
        'content' => "Inspiração de [tema], selecionada por {{brand_name}}.\n\nSalve este pin para depois.\n\nMais em → [link]",
        'image_count' => 1,
        'image_keywords' => ['inspiration', 'aesthetic', 'mood'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_product_showcase',
        'category' => 'product_launch',
        'name' => 'Vitrine de produto',
        'description' => 'Destaque um produto com uma descrição que convida ao clique.',
        'content' => "[Nome do produto] da {{brand_name}}.\n\n[Descrição curta focada em benefício, o que é, por que importa.]\n\nCompre o look → [link]",
        'image_count' => 1,
        'image_keywords' => ['product', 'showcase', 'lifestyle'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_new_arrival',
        'category' => 'product_launch',
        'name' => 'Pin de novidade',
        'description' => 'Anuncie um produto novo com palavras-chave de busca.',
        'content' => "Novidade da {{brand_name}}: [nome do produto].\n\n[Uma frase sobre o que é e para quem é.]\n\nPrincipais características:\n- [Característica 1]\n- [Característica 2]\n- [Característica 3]\n\nDisponível em [cores/tamanhos/opções].\n\nCompre a coleção [categoria] → [link]",
        'image_count' => 1,
        'image_keywords' => ['new product', 'launch', 'collection'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_collection_drop',
        'category' => 'product_launch',
        'name' => 'Pin de lançamento de coleção',
        'description' => 'Apresente uma coleção curada de produtos.',
        'content' => "A coleção [nome da coleção] chegou.\n\n{{brand_name}} montou [número] peças em torno de [tema ou estação].\n\nO que tem dentro:\n- [Tipo de item 1]\n- [Tipo de item 2]\n- [Tipo de item 3]\n\nFeita para [uso ou público].\n\nVeja a coleção completa → [link]",
        'image_count' => 1,
        'image_keywords' => ['collection', 'lookbook', 'curated'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_pre_order',
        'category' => 'product_launch',
        'name' => 'Pin de pré-venda',
        'description' => 'Gere salvamentos e pré-vendas de um produto que vem aí.',
        'content' => "Pré-venda aberta: [nome do produto].\n\nEnvio começa em [data]. Quem fizer pré-venda em {{brand_name}} ganha [vantagem: acesso antecipado, item bônus, preço travado].\n\nPor que comprar na pré-venda:\n- [Motivo 1]\n- [Motivo 2]\n\nReserve o seu → [link]",
        'image_count' => 1,
        'image_keywords' => ['pre-order', 'launch', 'early access'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_seasonal_sale',
        'category' => 'promotion',
        'name' => 'Pin de promoção sazonal',
        'description' => 'Divulgue uma promoção sazonal com desconto claro.',
        'content' => "Promoção de [estação] na {{brand_name}}: [desconto]% off em [categoria].\n\nVálido até [data final].\n\nO que está em promoção:\n- [Categoria 1]\n- [Categoria 2]\n- [Categoria 3]\n\nUse o cupom [CÓDIGO] no checkout.\n\nAproveite a promoção → [link]",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'seasonal shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_bundle_deal',
        'category' => 'promotion',
        'name' => 'Pin de combo',
        'description' => 'Pin de combo com preços em tópicos.',
        'content' => "O combo [nome do combo] da {{brand_name}}.\n\nLeve [item 1] + [item 2] + [item 3] juntos e economize [valor].\n\nO que está incluso:\n- [Item 1] (normalmente [preço])\n- [Item 2] (normalmente [preço])\n- [Item 3] (normalmente [preço])\n\nPreço do combo: [preço].\n\nGaranta o combo → [link]",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'value pack', 'savings'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_free_shipping',
        'category' => 'promotion',
        'name' => 'Pin de frete grátis',
        'description' => 'Pin com oferta centrada em frete grátis.',
        'content' => "Frete grátis em todos os pedidos da {{brand_name}}.\n\nSem mínimo, sem cupom. Até [data final].\n\nO que colocar no carrinho:\n- [Mais vendido 1]\n- [Mais vendido 2]\n- [Mais vendido 3]\n\nCompre agora → [link]",
        'image_count' => 1,
        'image_keywords' => ['free shipping', 'offer', 'deal'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_clearance',
        'category' => 'promotion',
        'name' => 'Pin de queima de estoque',
        'description' => 'Gire o estoque de queima com um pin que vale salvar.',
        'content' => "Queima de estoque na {{brand_name}}: até [desconto]% off.\n\nÚltimas remarcações em [categoria]. Quando acabar, acabou.\n\nDestaques:\n- [Item 1], [preço]\n- [Item 2], [preço]\n- [Item 3], [preço]\n\nVeja a queima de estoque → [link]",
        'image_count' => 1,
        'image_keywords' => ['clearance', 'final sale', 'markdown'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_recipe',
        'category' => 'educational',
        'name' => 'Pin de receita',
        'description' => 'Pin de receita que vale salvar, com ingredientes e modo de preparo.',
        'content' => "[Nome da receita], pronta em [tempo].\n\nDireto da cozinha de {{brand_name}}.\n\nIngredientes:\n- [Ingrediente 1]\n- [Ingrediente 2]\n- [Ingrediente 3]\n- [Ingrediente 4]\n\nModo de preparo:\n1. [Passo 1]\n2. [Passo 2]\n3. [Passo 3]\n\nRende [número] porções. Receita completa → [link]",
        'image_count' => 1,
        'image_keywords' => ['recipe', 'food', 'cooking'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_checklist',
        'category' => 'educational',
        'name' => 'Pin de checklist',
        'description' => 'Pin prático de checklist feito para salvar.',
        'content' => "O checklist de [tema] da {{brand_name}}.\n\n[Uma frase sobre para quem é.]\n\nO checklist:\n- [Item 1]\n- [Item 2]\n- [Item 3]\n- [Item 4]\n- [Item 5]\n\nSalve este pin para ter à mão quando precisar.\n\nBaixe a versão para imprimir → [link]",
        'image_count' => 1,
        'image_keywords' => ['checklist', 'planner', 'printable'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_beginners_guide',
        'category' => 'educational',
        'name' => 'Pin de guia para iniciantes',
        'description' => 'Pin explicativo amigável para quem está começando.',
        'content' => "[Tema] para iniciantes.\n\nSe você é novo em [tema], comece por aqui. {{brand_name}} reuniu o básico.\n\nO que você precisa saber:\n1. [Conceito 1]\n2. [Conceito 2]\n3. [Conceito 3]\n\nErro comum de iniciante: [erro].\n\nLeia o guia completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['beginner guide', 'basics', 'tutorial'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_diy_tutorial',
        'category' => 'educational',
        'name' => 'Pin de tutorial DIY',
        'description' => 'Pin de projeto faça-você-mesmo com lista de materiais.',
        'content' => "DIY [nome do projeto] em [tempo].\n\nUm projeto de fim de semana de {{brand_name}}.\n\nO que você precisa:\n- [Material 1]\n- [Material 2]\n- [Material 3]\n- [Ferramenta 1]\n\nOs passos:\n1. [Passo 1]\n2. [Passo 2]\n3. [Passo 3]\n\nCusto estimado: [valor].\n\nTutorial completo com fotos → [link]",
        'image_count' => 1,
        'image_keywords' => ['DIY', 'craft project', 'handmade'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_studio_tour',
        'category' => 'behind_the_scenes',
        'name' => 'Pin de tour pelo estúdio',
        'description' => 'Leve os seguidores para dentro do espaço de trabalho.',
        'content' => "Por dentro do estúdio de {{brand_name}}.\n\n[Uma frase sobre o que acontece aqui.]\n\nTrês coisas que você vai notar:\n- [Detalhe 1]\n- [Detalhe 2]\n- [Detalhe 3]\n\n[Uma observação sobre o espaço, a equipe ou a rotina.]\n\nMais fotos do estúdio → [link]",
        'image_count' => 1,
        'image_keywords' => ['studio', 'workspace', 'creative space'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_process_pin',
        'category' => 'behind_the_scenes',
        'name' => 'Pin de processo de produção',
        'description' => 'Mostre o ofício por trás do produto.',
        'content' => "Como {{brand_name}} faz [produto].\n\nDe [matéria-prima] até a peça pronta, cada etapa acontece [onde].\n\nO processo:\n1. [Etapa 1]\n2. [Etapa 2]\n3. [Etapa 3]\n4. [Etapa 4]\n\nTempo total por peça: [duração].\n\nVeja o processo completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['handmade', 'craft', 'process'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_founder_story',
        'category' => 'behind_the_scenes',
        'name' => 'Pin de história do fundador',
        'description' => 'Pin pessoal sobre a origem da marca.',
        'content' => "Como {{brand_name}} começou.\n\n[Nome do fundador] lançou [marca] em [ano] depois de [momento de origem].\n\n[Duas frases curtas sobre o porquê e os primeiros tempos.]\n\nO que é diferente no nosso jeito de trabalhar:\n- [Valor 1]\n- [Valor 2]\n\nLeia a história completa → [link]",
        'image_count' => 1,
        'image_keywords' => ['founder story', 'small business', 'brand story'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_customer_review',
        'category' => 'testimonial',
        'name' => 'Pin de avaliação de cliente',
        'description' => 'Pin com citação direta de um cliente real.',
        'content' => "\"[Avaliação do cliente sobre o produto].\"\n- [Primeiro nome do cliente], [cidade ou contexto]\n\nClientes da {{brand_name}} deixam avaliações assim toda semana.\n\nO que [primeiro nome do cliente] comprou: [nome do produto].\nPor que comprou: [motivo].\n\nVeja mais avaliações → [link]",
        'image_count' => 1,
        'image_keywords' => ['customer review', 'testimonial', 'social proof'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_before_after',
        'category' => 'testimonial',
        'name' => 'Pin de antes e depois',
        'description' => 'Pin de transformação visual.',
        'content' => "Antes e depois com [produto ou serviço] da {{brand_name}}.\n\nAntes: [estado inicial].\nDepois: [resultado final].\nTempo: [duração].\n\nO que [nome do cliente] usou:\n- [Item 1]\n- [Item 2]\n\n[Uma frase sobre a reação do cliente.]\n\nVeja mais antes e depois → [link]",
        'image_count' => 1,
        'image_keywords' => ['before and after', 'transformation', 'results'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_case_study',
        'category' => 'testimonial',
        'name' => 'Pin de estudo de caso',
        'description' => 'Mini estudo de caso com números concretos.',
        'content' => "Estudo de caso: como [nome do cliente] usou {{brand_name}} para [resultado].\n\nA situação: [uma frase].\nO que tentaram: [produto ou serviço].\nO resultado: [número ou resultado específico] em [prazo].\n\nPor que funcionou:\n- [Motivo 1]\n- [Motivo 2]\n\nLeia o estudo de caso completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['case study', 'results', 'success story'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_pro_tip',
        'category' => 'industry_tip',
        'name' => 'Pin de dica de profissional',
        'description' => 'Pin com uma única dica e ganho claro.',
        'content' => "Dica de profissional: [dica em uma frase].\n\nA maioria das pessoas [erro comum]. A solução é [a técnica de fato].\n\nPor que funciona: [uma frase com o motivo].\n\nQuando usar: [contexto ou cenário].\n\nMais dicas de [tema] de {{brand_name}} → [link]",
        'image_count' => 1,
        'image_keywords' => ['pro tip', 'expert advice', 'industry tips'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_common_mistakes',
        'category' => 'industry_tip',
        'name' => 'Pin de erros comuns',
        'description' => 'Lista de erros que o leitor pode evitar.',
        'content' => "[Número] erros de [tema] para evitar.\n\n{{brand_name}} vê isso toda semana. Salve o pin para não repetir.\n\nOs erros:\n1. [Erro 1], faça assim: [solução]\n2. [Erro 2], faça assim: [solução]\n3. [Erro 3], faça assim: [solução]\n\nLeia a análise completa → [link]",
        'image_count' => 1,
        'image_keywords' => ['common mistakes', 'tips', 'expert advice'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_industry_stat',
        'category' => 'industry_tip',
        'name' => 'Pin de estatística do setor',
        'description' => 'Pin baseado em dado que ancora um insight útil.',
        'content' => "[Estatística com número]% de [público] [comportamento].\nFonte: [fonte, ano].\n\nO que isso significa para você: [uma frase sobre a implicação].\n\nTrês formas como clientes da {{brand_name}} respondem:\n- [Tática 1]\n- [Tática 2]\n- [Tática 3]\n\nLeia o relatório completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['industry data', 'statistics', 'research'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_workshop',
        'category' => 'event',
        'name' => 'Pin de workshop',
        'description' => 'Pin para divulgar um workshop presencial ou online.',
        'content' => "[Nome do workshop] com {{brand_name}}.\n\n[Data] · [horário] · [local ou online].\n\nO que você vai aprender:\n- [Aprendizado 1]\n- [Aprendizado 2]\n- [Aprendizado 3]\n\nPara quem é: [público].\nVagas: [número] limitadas.\nPreço: [valor].\n\nReserve sua vaga → [link]",
        'image_count' => 1,
        'image_keywords' => ['workshop', 'class', 'learning event'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_pop_up',
        'category' => 'event',
        'name' => 'Pin de loja pop-up',
        'description' => 'Atraia público para uma loja pop-up.',
        'content' => "Loja pop-up de {{brand_name}} em [cidade].\n\n[Período] · [endereço] · [horário].\n\nO que você vai encontrar:\n- [Categoria 1]\n- [Categoria 2]\n- [Exclusivo da loja]\n\n[Uma frase sobre o que faz o dia valer a visita.]\n\nVeja como chegar e detalhes → [link]",
        'image_count' => 1,
        'image_keywords' => ['pop-up shop', 'event', 'in-person shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_webinar',
        'category' => 'event',
        'name' => 'Pin de webinar',
        'description' => 'Divulgue um webinar gratuito ou pago.',
        'content' => "Webinar gratuito: [tema].\n\nApresentado por {{brand_name}} em [data] às [horário, fuso].\n\nO que vamos cobrir:\n- [Tópico 1]\n- [Tópico 2]\n- [Tópico 3]\n\nPara quem é: [público].\nGravação: enviada para todos que se inscreverem.\n\nGaranta sua vaga → [link]",
        'image_count' => 1,
        'image_keywords' => ['webinar', 'online event', 'training'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_holiday_event',
        'category' => 'event',
        'name' => 'Pin de evento de feriado',
        'description' => 'Pin de evento ou promoção temática de feriado.',
        'content' => "Evento de [feriado] da {{brand_name}}.\n\n[Data] · [local ou online].\n\nNa programação:\n- [Atividade 1]\n- [Atividade 2]\n- [Atividade 3]\n\nO que esperar: [uma frase].\nConfirme presença até [data].\n\nProgramação completa e RSVP → [link]",
        'image_count' => 1,
        'image_keywords' => ['holiday event', 'seasonal', 'celebration'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_question_pin',
        'category' => 'engagement',
        'name' => 'Pin de pergunta',
        'description' => 'Pin com pergunta que convida a comentar.',
        'content' => "[Pergunta aberta para o público].\n\n{{brand_name}} quer saber. Deixe sua resposta nos comentários.\n\nAlgumas pistas para pensar:\n- [Pista 1]\n- [Pista 2]\n- [Pista 3]\n\nVamos compartilhar as respostas mais interessantes na próxima semana.\n\nEntre na conversa → [link]",
        'image_count' => 1,
        'image_keywords' => ['question', 'community', 'discussion'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_this_or_that',
        'category' => 'engagement',
        'name' => 'Pin de isto ou aquilo',
        'description' => 'Pin de preferência lado a lado.',
        'content' => "Isto ou aquilo: [opção A] ou [opção B].\n\n{{brand_name}} quer saber qual é o seu lado. Não tem resposta errada.\n\nA favor de [opção A]: [uma frase].\nA favor de [opção B]: [uma frase].\n\nVote nos comentários. Vamos contar os votos.\n\nMais enquetes → [link]",
        'image_count' => 1,
        'image_keywords' => ['poll', 'this or that', 'preference'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_giveaway',
        'category' => 'engagement',
        'name' => 'Pin de sorteio',
        'description' => 'Pin que anuncia um sorteio com regras claras.',
        'content' => "Sorteio de {{brand_name}}: ganhe [prêmio].\n\nUm vencedor escolhido em [data].\n\nComo participar:\n1. Salve este pin.\n2. Siga {{brand_name}} no Pinterest.\n3. Comente com [pista].\n\nAberto para: [região].\nValor: [valor].\n\nRegulamento completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['giveaway', 'contest', 'prize'],
        'slides' => null,
    ],
];
