<?php

declare(strict_types=1);

return [
    [
        'slug' => 'threads_hot_take',
        'category' => 'industry_tip',
        'name' => 'Opinião polêmica',
        'description' => 'Um post curto e opinativo feito pra gerar respostas.',
        'content' => "Opinião impopular: [afirmação contraintuitiva sobre seu setor].\n\nPor que eu acho isso →\n\n[Raciocínio breve em 1 ou 2 frases.]\n\nTô errado?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_quick_tip',
        'category' => 'educational',
        'name' => 'Dica rápida',
        'description' => 'Uma dica acionável, em tom curto e amigável.',
        'content' => "Dica rápida da {{brand_name}}:\n\n[Uma dica única, específica e acionável.]\n\nParece simples. Muda tudo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_question',
        'category' => 'engagement',
        'name' => 'Pergunta aberta',
        'description' => 'Pergunte algo pra comunidade pra puxar conversa.',
        'content' => "Pergunta sincera pra comunidade da {{brand_name}}:\n\n[Pergunta, aberta e específica o bastante pra responder.]\n\nNão tem resposta errada. Curioso pra ler as suas.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // PRODUCT LAUNCH
    [
        'slug' => 'threads_product_launch_soft',
        'category' => 'product_launch',
        'name' => 'Lançamento discreto',
        'description' => 'Anúncio casual e despretensioso de algo novo.',
        'content' => "ok então. a gente lançou [nome do produto] hoje.\n\ntô trabalhando nisso há [tempo de duração] e meio que não acredito que tá no ar.\n\n[uma coisa específica que ele faz e que você tem orgulho].\n\nse você testar, me conta o que quebra.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_product_launch_story',
        'category' => 'product_launch',
        'name' => 'Por que a gente fez',
        'description' => 'História pessoal por trás do produto ou recurso novo.',
        'content' => "comecei a construir [nome do produto] porque [frustração pessoal específica].\n\nachei que ia levar um fim de semana. levou [tempo real].\n\ntá no ar agora em {{brand_name}}. honestamente ainda surpreso que funciona.\n\nadoraria saber o que você acha depois de mexer um pouco.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_product_launch_feature',
        'category' => 'product_launch',
        'name' => 'Recurso novo',
        'description' => 'Anuncia um único recurso dentro de um produto existente.',
        'content' => "coisa pequena mas tô estranhamente animado.\n\n{{brand_name}} agora [faz essa coisa específica].\n\no motivo: o pessoal ficava pedindo [a necessidade por trás]. então a gente fez.\n\ntá no ar. testa lá e me conta se é útil de verdade ou só uma coisa nova agora.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // PROMOTION
    [
        'slug' => 'threads_promo_discount',
        'category' => 'promotion',
        'name' => 'Desconto casual',
        'description' => 'Jeito tranquilo de mencionar uma promoção ou desconto.',
        'content' => "rolando [valor do desconto] off em [produto ou plano] essa semana em {{brand_name}}.\n\nnão vou fazer aquela parada de contagem regressiva. só achei melhor mencionar uma vez e deixar o pessoal decidir.\n\ncódigo: [código]. termina [data].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_promo_bundle',
        'category' => 'promotion',
        'name' => 'Combo',
        'description' => 'Promove um combo em tom relaxado.',
        'content' => "juntei [item um] e [item dois] num combo porque o pessoal ficava comprando os dois no mesmo pedido de qualquer jeito.\n\no par sai por [preço] em {{brand_name}}, que é tipo [economia] menos do que comprar separado.\n\né isso. é o post.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_promo_last_chance',
        'category' => 'promotion',
        'name' => 'Última chance',
        'description' => 'Empurrãozinho amigável de que uma oferta tá acabando.',
        'content' => "aviso amigável: [nome da oferta] termina [data ou hora].\n\nnão tô tentando ser chato. alguns de vocês pediram pra eu lembrar, então considera esse o lembrete.\n\nlink na bio se você quiser. zero ressentimento se não.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // EDUCATIONAL
    [
        'slug' => 'threads_edu_mistake',
        'category' => 'educational',
        'name' => 'Erro que eu cometi',
        'description' => 'Ensinar compartilhando um erro pessoal.',
        'content' => "cometi o mesmo erro [número] vezes antes de sacar isso:\n\n[o erro em uma frase].\n\na solução é [a solução real em palavras simples]. nada chique. só tive que parar de fazer aquilo.\n\npostando caso você esteja preso no mesmo loop.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_misconception',
        'category' => 'educational',
        'name' => 'Mito comum',
        'description' => 'Corrigir uma crença comum mas errada.',
        'content' => "o pessoal vive me falando [crença comum no seu setor].\n\nnão é assim que funciona.\n\n[o que acontece de verdade, em palavras simples].\n\npode ser óbvio pra alguns de vocês. aparentemente não pra maioria do pessoal que me mandou e-mail semana passada.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_resource',
        'category' => 'educational',
        'name' => 'Indicação de recurso',
        'description' => 'Recomenda um recurso útil com contexto pessoal.',
        'content' => "se você tá tentando aprender [tópico], para de assistir vídeo de 4 horas no youtube e lê [recurso específico].\n\nadiei isso por meses porque o título é chato. é a única coisa que realmente fez sentido pra mim.\n\né essa a indicação.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_step_breakdown',
        'category' => 'educational',
        'name' => 'Passo a passo rápido',
        'description' => 'Mini passo a passo em tom de conversa.',
        'content' => "a parada de [tarefa] em 4 linhas pra quem fica perguntando:\n\n1. [passo um]\n2. [passo dois]\n3. [passo três]\n4. [passo quatro]\n\né esse o processo todo. você não precisa de um curso pra isso.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // BEHIND THE SCENES
    [
        'slug' => 'threads_bts_morning',
        'category' => 'behind_the_scenes',
        'name' => 'Rotina da manhã',
        'description' => 'Espiada casual em como começa um dia de trabalho.',
        'content' => "hoje em {{brand_name}}:\n\n- café\n- olhei pra [problema específico] por uma hora\n- percebi que o bug tava na linha [número]\n- arrumei em 4 minutos\n\na proporção de pensar pra fazer nesse trabalho é genuinamente amaldiçoada.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_decision',
        'category' => 'behind_the_scenes',
        'name' => 'Decisão que a gente tomou',
        'description' => 'Compartilha uma decisão interna e o raciocínio.',
        'content' => "decidimos [decisão específica] essa semana.\n\na outra opção era [alternativa]. metade do time queria essa. eu meio que ainda quero.\n\nmas [o motivo real dessa decisão ter ganho].\n\nme pergunta daqui 3 meses se foi a escolha certa.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_messy_progress',
        'category' => 'behind_the_scenes',
        'name' => 'Progresso bagunçado',
        'description' => 'Atualização honesta no meio do projeto.',
        'content' => "estado atual de [nome do projeto]:\n\n- [porcentagem] pronto\n- [coisa específica que tá funcionando]\n- [coisa específica que não tá funcionando]\n- [número] abas abertas que tô com medo de fechar\n\nlanço quando parar de me envergonhar.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_team_moment',
        'category' => 'behind_the_scenes',
        'name' => 'Momento do time',
        'description' => 'Pequeno momento humano do time.',
        'content' => "[nome de alguém do time] acabou de mandar uma mensagem no slack que dizia \"[citação curta engraçada ou perspicaz]\" e agora a gente não consegue parar de citar.\n\nconstruir {{brand_name}} com essas pessoas é metade do motivo de eu ainda gostar do trabalho.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // TESTIMONIAL
    [
        'slug' => 'threads_testimonial_quote',
        'category' => 'testimonial',
        'name' => 'Frase de cliente',
        'description' => 'Compartilha uma frase real de cliente com contexto leve.',
        'content' => "recebi esse e-mail de [primeiro nome ou iniciais] ontem:\n\n\"[citação direta do cliente, 1 a 2 frases]\"\n\nli duas vezes. essa é a parte do trabalho que não aparece nas métricas.\n\nobrigado por usar {{brand_name}}. de verdade.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_testimonial_outcome',
        'category' => 'testimonial',
        'name' => 'Resultado de cliente',
        'description' => 'Fala sobre um resultado real de cliente sem se gabar.',
        'content' => "[primeiro nome do cliente] me falou ontem que [resultado específico] depois de usar {{brand_name}} por [período de tempo].\n\nnão pedi pra ela compartilhar. ela só mandou o print e disse \"achei que você ia querer ver isso.\"\n\né. quis mesmo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_testimonial_unexpected',
        'category' => 'testimonial',
        'name' => 'Uso inesperado',
        'description' => 'Destaca um jeito surpreendente de usar o produto.',
        'content' => "não esperava por essa.\n\numa pessoa usando {{brand_name}} pra [uso inesperado]. não foi pra isso que a gente fez. aparentemente funciona.\n\nparte favorita de lançar coisas é descobrir o que o pessoal realmente faz com elas.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // INDUSTRY TIP
    [
        'slug' => 'threads_industry_observation',
        'category' => 'industry_tip',
        'name' => 'Observação do setor',
        'description' => 'Compartilha um padrão que você vem notando na sua área.',
        'content' => "coisa que eu venho notando em [setor]:\n\n[observação específica em uma frase].\n\npode ser uma mudança real. pode ser viés de seleção de quem eu falo. me conta se você tá vendo também.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_lesson',
        'category' => 'industry_tip',
        'name' => 'Lição da experiência',
        'description' => 'Uma lição duramente aprendida, sem enrolação.',
        'content' => "[número] anos em [setor] e a lição que mais demorou pra eu acreditar de verdade:\n\n[a lição em uma frase].\n\nainda me pego ignorando. aí algo quebra. aí eu lembro.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_pushback',
        'category' => 'industry_tip',
        'name' => 'Discordando do senso comum',
        'description' => 'Discorda educadamente de um conselho comum.',
        'content' => "o conselho padrão em [setor] é [conselho comum].\n\ntô fazendo o oposto há [período de tempo]. funciona melhor pra mim, pelo menos.\n\n[breve motivo].\n\nnão tô dizendo que todo mundo deveria. só que a regra não é uma regra.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_prediction',
        'category' => 'industry_tip',
        'name' => 'Previsão discreta',
        'description' => 'Faz uma previsão sem se exibir.',
        'content' => "previsão pequena:\n\nem [prazo de tempo], [mudança específica no seu setor] vai ser normal.\n\nposso estar muito errado. salvando isso pra voltar e rir de mim depois.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // EVENT
    [
        'slug' => 'threads_event_announcement',
        'category' => 'event',
        'name' => 'Anúncio de evento',
        'description' => 'Anuncia um evento próximo de forma casual.',
        'content' => "{{brand_name}} vai fazer [nome do evento] em [data].\n\n[uma ou duas frases sobre o que é de verdade e quem ia se interessar].\n\n[local ou link]. avisa um amigo se parecer a praia dele.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_event_recap',
        'category' => 'event',
        'name' => 'Recap de evento',
        'description' => 'Resumo honesto depois de um evento.',
        'content' => "voltei do [nome do evento].\n\na melhor parte foi [momento ou conversa específica].\n\na parte mais estranha foi [observação honesta].\n\nse você tava lá e a gente não conseguiu conversar, me chama. sempre tem mais coisa pra falar depois que o painel acaba.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_event_invite',
        'category' => 'event',
        'name' => 'Convite pessoal',
        'description' => 'Convite direto que parece pessoal.',
        'content' => "vou fazer um [tipo de evento] pequeno pela {{brand_name}} em [data] e quero você lá de verdade.\n\né [duração] e a gente vai falar sobre [tópico específico].\n\nconfirma em [link] se quiser entrar. tô limitando em [número] pra ficar uma conversa de verdade.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ENGAGEMENT
    [
        'slug' => 'threads_engagement_recommendation',
        'category' => 'engagement',
        'name' => 'Pedido de indicação',
        'description' => 'Pergunta pro público por indicações.',
        'content' => "procurando indicações:\n\n[coisa específica que você precisa de indicações].\n\njá testei [opção a] e [opção b]. preciso de algo que [restrição específica].\n\nmelhor resposta ganha minha gratidão eterna. é esse o prêmio.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_engagement_this_or_that',
        'category' => 'engagement',
        'name' => 'Isso ou aquilo',
        'description' => 'Pergunta binária rápida pra puxar respostas.',
        'content' => "[opção a] ou [opção b].\n\nsem meio termo. sem \"depende\". escolhe uma e me conta por quê.\n\na versão {{brand_name}} desse debate tá rolando no chat do time e a gente tá profundamente, profundamente dividido.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_engagement_confession',
        'category' => 'engagement',
        'name' => 'Confissão pequena',
        'description' => 'Compartilha algo pequeno e relacionável.',
        'content' => "confissão pequena.\n\neu ainda [hábito levemente embaraçoso ligado ao seu trabalho ou vida].\n\nme fala que não sou o único. ou me fala que sou o único. de qualquer jeito eu queria saber.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
