<?php

declare(strict_types=1);

return [
    [
        'slug' => 'flash_sale',
        'category' => 'promotion',
        'name' => 'Promoção relâmpago',
        'description' => 'Post curto no X para promoção relâmpago com urgência.',
        'content' => "🔥 Promoção relâmpago na {{brand_name}}!\n\n[Desconto]% off em [produto/serviço], só nas próximas 24h.\n\nSem cupom → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'success_story',
        'category' => 'testimonial',
        'name' => 'Caso de sucesso',
        'description' => 'Formato breve de caso de sucesso para o X.',
        'content' => "\"[Frase curta do cliente.]\"\n- @[handle]\n\nÉ por isso que a gente faz o que faz na {{brand_name}}. 🙌",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'this_or_that_poll',
        'category' => 'engagement',
        'name' => 'Isso ou aquilo',
        'description' => 'Engaje o público com uma escolha binária simples.',
        'content' => "Pergunta rápida pra galera da {{brand_name}}:\n\n[Opção A] ou [Opção B]?\n\nResponde aí com a sua escolha e o porquê 👇",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // product_launch
    [
        'slug' => 'shipped_today',
        'category' => 'product_launch',
        'name' => 'Saiu hoje',
        'description' => 'Aviso casual de release com uma mudança concreta.',
        'content' => "Saiu hoje: [feature].\n\nFaz [coisa específica] pra você parar de [gambiarra chata].\n\nJá tá no ar na {{brand_name}}.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'new_feature_one_liner',
        'category' => 'product_launch',
        'name' => 'Feature em uma linha',
        'description' => 'Pitch de uma frase para uma nova feature.',
        'content' => "{{brand_name}} agora [faz coisa específica].\n\nSe você tá [fazendo gambiarra dolorosa], testa: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'beta_invite',
        'category' => 'product_launch',
        'name' => 'Convite pro beta',
        'description' => 'Chamada aberta para testadores beta.',
        'content' => "Vamos abrir o beta de [feature] essa semana.\n\nProcurando [número] pessoas que [caso de uso].\n\nResponde aí se for o seu caso.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'finally_built_it',
        'category' => 'product_launch',
        'name' => 'Finalmente saiu',
        'description' => 'Tom honesto de "demorou mas saiu".',
        'content' => "Finalmente fizemos [feature]. O pessoal pedia desde [período].\n\nJá tá no ar na {{brand_name}} hoje. Desculpa a demora.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // promotion
    [
        'slug' => 'weekend_deal',
        'category' => 'promotion',
        'name' => 'Oferta de fim de semana',
        'description' => 'Post de desconto só no fim de semana.',
        'content' => "Só no fim de semana: [desconto] off em [produto] na {{brand_name}}.\n\nCupom [CODE]. Vale até domingo à meia-noite. É só isso.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'free_shipping',
        'category' => 'promotion',
        'name' => 'Frete grátis',
        'description' => 'Aviso de janela de frete grátis.',
        'content' => "Frete grátis em todo pedido na {{brand_name}} acima de R$[valor] essa semana.\n\nSem cupom, sem pegadinha. Volta ao normal segunda.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'last_call',
        'category' => 'promotion',
        'name' => 'Última chamada',
        'description' => 'Horas finais de uma promoção.',
        'content' => "Última chamada. [Nome da promo] acaba hoje às [hora].\n\nSe você tem {{brand_name}} no carrinho, é o preço mais baixo do ano: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bundle_offer',
        'category' => 'promotion',
        'name' => 'Oferta de combo',
        'description' => 'Pitch de combo como oferta econômica.',
        'content' => "Combo novo na {{brand_name}}: [Produto A] + [Produto B] por [preço].\n\nFica [valor] mais barato que separado. Só [quantidade] unidades.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // educational
    [
        'slug' => 'one_thing_we_learned',
        'category' => 'educational',
        'name' => 'Uma coisa que aprendemos',
        'description' => 'Compartilhe uma única lição concreta.',
        'content' => "Uma coisa que aprendemos na {{brand_name}} esse mês:\n\n[Descoberta]. Achávamos [suposição antiga], mas [dado] mostrou o contrário.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake',
        'category' => 'educational',
        'name' => 'Erro comum',
        'description' => 'Aponte um erro que as pessoas cometem.',
        'content' => "A maioria erra em [tópico] porque [erro comum].\n\nO que funciona: [contra-abordagem]. Testamos com [número] clientes.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'quick_tip',
        'category' => 'educational',
        'name' => 'Dica rápida',
        'description' => 'Dica pequena e prática.',
        'content' => "Dica rápida se você usa {{brand_name}}:\n\n[Ação] antes de [passo]. Economiza uns [tempo/resultado] pra maioria.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'myth_vs_reality',
        'category' => 'educational',
        'name' => 'Mito vs realidade',
        'description' => 'Derrube um mito do setor.',
        'content' => "Mito: [crença comum sobre tópico].\n\nRealidade: [contra-fato com número]. A gente vê isso nos dados da {{brand_name}} toda semana.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // behind_the_scenes
    [
        'slug' => 'how_we_built_it',
        'category' => 'behind_the_scenes',
        'name' => 'Como construímos',
        'description' => 'Espiada casual nos bastidores.',
        'content' => "Como fizemos [feature] na {{brand_name}}:\n\nComeçamos com [primeira tentativa]. Quebrou. Trocamos por [abordagem 2]. Foi essa que subiu.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'team_at_work',
        'category' => 'behind_the_scenes',
        'name' => 'Time em ação',
        'description' => 'Foto do que o time tá fazendo agora.',
        'content' => "O que o time da {{brand_name}} tá fazendo agora:\n\n[Pessoa/cargo] debugando [problema]. [Pessoa/cargo] no [outro projeto]. Nível de café: alto.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mistake_we_made',
        'category' => 'behind_the_scenes',
        'name' => 'Erro que cometemos',
        'description' => 'Postmortem honesto em um tweet.',
        'content' => "A gente errou na {{brand_name}} semana passada.\n\n[O que quebrou]. Causou [impacto] pra [número] clientes. Resolvemos [como]. Desculpa quem foi afetado.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'office_moment',
        'category' => 'behind_the_scenes',
        'name' => 'Momento do escritório',
        'description' => 'Cena pequena e humana do escritório.',
        'content' => "Cena aleatória do escritório da {{brand_name}}:\n\n[Cena, ex.: designer brigando com dev por 2px de border-radius]. É assim quase todo dia, juro.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // testimonial
    [
        'slug' => 'customer_dm',
        'category' => 'testimonial',
        'name' => 'DM de cliente',
        'description' => 'Compartilhe uma DM real de cliente.',
        'content' => "Recebi essa DM de um cliente da {{brand_name}} hoje:\n\n\"[Frase curta sobre o que mudou pra ele].\"\n\nÉ a parte do trabalho que não enjoa.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'before_and_after',
        'category' => 'testimonial',
        'name' => 'Antes e depois',
        'description' => 'Números concretos de antes/depois de um cliente.',
        'content' => "[Cliente] antes da {{brand_name}}: [métrica].\n\n[Cliente] depois de [período]: [nova métrica].\n\nNada mais mudou no setup dele.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'one_line_review',
        'category' => 'testimonial',
        'name' => 'Review de uma linha',
        'description' => 'Frase curta de um cliente.',
        'content' => "\"[Frase específica do cliente, no máximo 12 palavras.]\"\n\n- [Cliente], [cargo] na [empresa]\n\nA gente não pediu pra ele escrever isso.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // industry_tip
    [
        'slug' => 'hot_take',
        'category' => 'industry_tip',
        'name' => 'Opinião polêmica',
        'description' => 'Opinião forte sobre o setor.',
        'content' => "Opinião polêmica: a maioria em [setor] acha que [crença comum].\n\nDepois de [tempo] tocando a {{brand_name}}, eu penso o contrário. [Motivo].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'overrated_underrated',
        'category' => 'industry_tip',
        'name' => 'Superestimado subestimado',
        'description' => 'Junte algo superestimado e algo subestimado.',
        'content' => "Superestimado em [setor]: [prática comum].\n\nSubestimado: [prática ignorada].\n\nA gente parou com a primeira na {{brand_name}} faz um ano.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'unpopular_opinion',
        'category' => 'industry_tip',
        'name' => 'Opinião impopular',
        'description' => 'Compartilhe uma observação contrária.',
        'content' => "Opinião impopular: [afirmação contrária sobre o setor].\n\nClientes da {{brand_name}} provam isso todo mês. O dado não é sutil.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'what_changed_my_mind',
        'category' => 'industry_tip',
        'name' => 'O que mudou minha cabeça',
        'description' => 'Momento honesto de mudar de ideia.',
        'content' => "Eu achava que [crença antiga sobre o setor].\n\nAí [evento/dado] aconteceu na {{brand_name}}. Hoje penso [nova visão]. Ainda me ajustando.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // event
    [
        'slug' => 'event_announcement',
        'category' => 'event',
        'name' => 'Anúncio de evento',
        'description' => 'Anúncio simples de evento.',
        'content' => "{{brand_name}} vai fazer [nome do evento] em [data] em [cidade].\n\n[Tópico]. Grátis, [vagas] vagas. Inscrição: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_recap',
        'category' => 'event',
        'name' => 'Recap de evento',
        'description' => 'Resumo curto depois de um evento.',
        'content' => "[Número] pessoas no [evento] da {{brand_name}} ontem.\n\nPergunta favorita: \"[pergunta real do público].\" Gravação sai sexta.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'webinar_reminder',
        'category' => 'event',
        'name' => 'Lembrete de webinar',
        'description' => 'Lembrete de que um webinar vai começar logo.',
        'content' => "Lembrete: webinar da {{brand_name}} sobre [tópico] começa em [tempo].\n\n[Palestrante] vai mostrar [coisa específica]. Última chance pra se inscrever: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // engagement
    [
        'slug' => 'open_question',
        'category' => 'engagement',
        'name' => 'Pergunta aberta',
        'description' => 'Faça uma pergunta real ao público.',
        'content' => "Pergunta sincera pra quem usa [ferramenta/categoria]:\n\nQual a única coisa que ela ainda não faz e você queria que fizesse?\n\nPergunto porque a {{brand_name}} tá trabalhando nisso.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'fill_in_the_blank',
        'category' => 'engagement',
        'name' => 'Complete a frase',
        'description' => 'Provocação leve do tipo complete a frase.',
        'content' => "Complete:\n\nA pior parte de [tarefa/tópico] é ______.\n\nLeio todas as respostas. Vamos usar pra planejar o próximo trimestre da {{brand_name}}.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'show_us_your_setup',
        'category' => 'engagement',
        'name' => 'Mostra seu setup',
        'description' => 'Peça pro pessoal compartilhar algo visual.',
        'content' => "Mostra seu [coisa, mesa, dashboard, rotina semanal].\n\nVamos destacar nossos três favoritos no perfil da {{brand_name}} semana que vem. Sem filtro.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
