<?php

declare(strict_types=1);

return [
    [
        'slug' => 'bluesky_now_live',
        'category' => 'product_launch',
        'name' => 'Now live',
        'description' => 'Announce a launch in the open, decentralized vibe of Bluesky.',
        'content' => "Now live: [feature/product] from {{brand_name}}.\n\nWhat changed: [one-line summary].\n\nWho it's for: [who benefits].\n\nLink → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_thought',
        'category' => 'industry_tip',
        'name' => 'Short thought',
        'description' => 'A concise observation that reads naturally on Bluesky.',
        'content' => "[Observation about your industry, told in one or two sentences.]\n\nSimple, but worth saying out loud.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_invite',
        'category' => 'engagement',
        'name' => 'Community invite',
        'description' => 'Invite the community into a topic or conversation.',
        'content' => "If you care about [topic], we'd love to hear from you.\n\nWhat's on your mind lately?\n\n- team {{brand_name}}",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_changelog_drop',
        'category' => 'product_launch',
        'name' => 'Changelog drop',
        'description' => 'Plain changelog post for a release.',
        'content' => "v[version] is out.\n\n• [change 1]\n• [change 2]\n• [bug fix]\n\nNo migrations needed. Full notes: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_open_beta',
        'category' => 'product_launch',
        'name' => 'Open beta',
        'description' => 'Invite users into a public beta.',
        'content' => "Open beta: [feature] is live for anyone who wants to try it.\n\nIt is rough in places. That is the point. Bug reports welcome.\n\nSign up: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_api_release',
        'category' => 'product_launch',
        'name' => 'API release',
        'description' => 'Announce a new API or developer feature.',
        'content' => "New: [endpoint/SDK] from {{brand_name}}.\n\nDocs: [link]\nExample repo: [link]\n\nIf the docs are missing something, tell us. We will fix it faster than you expect.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_promo_discount',
        'category' => 'promotion',
        'name' => 'Discount window',
        'description' => 'Time-bound promo, plainly stated.',
        'content' => "[X]% off [plan/product] until [date].\n\nNo email gate. No popup. Just the code: [CODE]\n\n[link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_promo_lifetime',
        'category' => 'promotion',
        'name' => 'Lifetime deal',
        'description' => 'Lifetime/early-bird offer aimed at builders.',
        'content' => "Lifetime deal on {{brand_name}}: [price] once, no subscription.\n\nLimited to [number] seats. After that we go back to monthly.\n\nGrab one: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_promo_referral',
        'category' => 'promotion',
        'name' => 'Referral perk',
        'description' => 'Plain referral offer.',
        'content' => "Refer a friend to {{brand_name}}, both of you get [reward].\n\nNo tiers. No leaderboard. Just send your link: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_one_thing',
        'category' => 'educational',
        'name' => 'One thing I learned',
        'description' => 'Single concrete lesson, told plainly.',
        'content' => "One thing I learned working on [topic]:\n\n[concrete lesson, one or two sentences].\n\nObvious in hindsight. Not obvious before.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_misconception',
        'category' => 'educational',
        'name' => 'Common misconception',
        'description' => 'Correct a widespread misconception in your space.',
        'content' => "Common belief: [misconception about your field].\n\nWhat is actually true: [correction].\n\nThe difference matters when [specific scenario].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_quick_how',
        'category' => 'educational',
        'name' => 'Quick how-to',
        'description' => 'Short how-to on one specific task.',
        'content' => "How to [specific task] in [tool]:\n\n1. [step]\n2. [step]\n3. [step]\n\nThat is the whole thing. No hidden config.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_tradeoff',
        'category' => 'educational',
        'name' => 'Tradeoff explainer',
        'description' => 'Walk through a real tradeoff in your domain.',
        'content' => "[Option A] vs [Option B] is mostly a tradeoff between [thing 1] and [thing 2].\n\nIf you care more about [thing 1], pick A. If [thing 2], pick B. Most teams pick A and regret it later.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_stack',
        'category' => 'behind_the_scenes',
        'name' => 'Our stack',
        'description' => 'Honest stack note from inside the team.',
        'content' => "Our stack at {{brand_name}}: [tech 1], [tech 2], [tech 3].\n\nWe picked [tech 1] for [reason]. We regret picking [tech] for [reason]. Will probably swap it next quarter.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_postmortem',
        'category' => 'behind_the_scenes',
        'name' => 'Mini postmortem',
        'description' => 'Short, transparent incident note.',
        'content' => "[Service/feature] was down for [duration] today.\n\nCause: [plain explanation].\nFix: [what we did].\n\nWe added [safeguard] so the same thing does not happen the same way again.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_decision',
        'category' => 'behind_the_scenes',
        'name' => 'Why we picked X',
        'description' => 'Explain a recent design or product decision.',
        'content' => "Why we picked [decision] over [alternative]:\n\n[reason in one sentence].\n\nIt is not the popular choice. It fits how our users actually work.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_numbers',
        'category' => 'behind_the_scenes',
        'name' => 'Numbers we watch',
        'description' => 'Share a real metric and what it means.',
        'content' => "A number we actually watch at {{brand_name}}: [metric].\n\nLast month it was [value]. The week before, [value].\n\nIt is the metric that tells us whether [outcome] is real.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_testimonial_quote',
        'category' => 'testimonial',
        'name' => 'Quote from a user',
        'description' => 'A short user quote, no fluff.',
        'content' => "From a user this week:\n\n\"[short, specific quote about the product].\"\n\n- [first name], [role]\n\nThis is the kind of feedback that keeps us building.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_testimonial_workflow',
        'category' => 'testimonial',
        'name' => 'How a customer uses it',
        'description' => 'Specific user workflow story.',
        'content' => "[Customer/team] uses {{brand_name}} to [specific job].\n\nBefore: [old way].\nNow: [new way].\n\nNot dramatic. Just less friction every day.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_testimonial_result',
        'category' => 'testimonial',
        'name' => 'Concrete result',
        'description' => 'A specific, measurable outcome from a customer.',
        'content' => "[Customer] cut [task] from [old time] to [new time] using {{brand_name}}.\n\nOne workflow change. No new hires.\n\nFull writeup: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_take',
        'category' => 'industry_tip',
        'name' => 'Hot-ish take',
        'description' => 'A real opinion on a thing in your industry.',
        'content' => "Mild take: [opinion about your industry].\n\nI know this is unpopular. I have changed my mind on it twice. Right now I think it holds up.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_pattern',
        'category' => 'industry_tip',
        'name' => 'Pattern I keep seeing',
        'description' => 'Pattern observed across teams or projects.',
        'content' => "A pattern I keep seeing in [industry/role]:\n\n[pattern in one sentence].\n\nUsually it works for the first [milestone] and then quietly stops.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_anti_advice',
        'category' => 'industry_tip',
        'name' => 'Advice I would skip',
        'description' => 'Anti-advice: common advice that does not hold up.',
        'content' => "Advice you hear a lot: [common advice].\n\nIn practice this falls apart when [scenario]. The version that actually works is [revised advice].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_link_share',
        'category' => 'industry_tip',
        'name' => 'Link with context',
        'description' => 'Share a link with a real reason to read it.',
        'content' => "Worth reading: [title of article/post].\n\nWhy: [one specific thing the piece nails].\n\n[link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_announce',
        'category' => 'event',
        'name' => 'Event announcement',
        'description' => 'Announce an upcoming event or talk.',
        'content' => "[Event name] on [date] at [time/timezone].\n\nTopic: [what we will cover].\nFormat: [talk / Q&A / demo].\n\nFree, no signup gate: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_speaking',
        'category' => 'event',
        'name' => 'Speaking somewhere',
        'description' => 'Tell people you are speaking at a conference.',
        'content' => "I am speaking at [event] on [date].\n\nTalk: [talk title or topic in plain words].\n\nIf you are around, say hi. Especially if you disagree with the talk.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_recap',
        'category' => 'event',
        'name' => 'Event recap',
        'description' => 'Short recap after an event or meetup.',
        'content' => "Quick recap of [event]:\n\n• [what worked]\n• [what surprised us]\n• [what we will do differently next time]\n\nThanks to everyone who showed up.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_office_hours',
        'category' => 'event',
        'name' => 'Office hours',
        'description' => 'Open office hours or AMA invite.',
        'content' => "Open office hours this [day] at [time/timezone].\n\nBring real questions about [topic]. I would rather answer hard ones than soft ones.\n\nLink to join: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_engagement_question',
        'category' => 'engagement',
        'name' => 'Real question',
        'description' => 'A genuine question, not engagement bait.',
        'content' => "Genuine question for people working on [topic]:\n\n[specific question].\n\nNot rhetorical. I am stuck on this and curious how others handle it.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_engagement_poll_lite',
        'category' => 'engagement',
        'name' => 'Two camps',
        'description' => 'Lightweight either/or to spark replies.',
        'content' => "Two camps on [topic]:\n\nA: [option A]\nB: [option B]\n\nWhich one do you actually use day to day, and what made you pick it?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_engagement_show_us',
        'category' => 'engagement',
        'name' => 'Show us your setup',
        'description' => 'Invite users to share their setup or workflow.',
        'content' => "Show us your [setup / workflow / config] for [task].\n\nReply with a screenshot or a one-liner. We are collecting good patterns to share back.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
