<?php

declare(strict_types=1);

return [
    [
        'slug' => 'fb_story_announcement',
        'category' => 'product_launch',
        'name' => 'Quick announcement',
        'description' => 'Drive attention to an update with a 24-hour Facebook story.',
        'content' => "Heads up from {{brand_name}}.\n\n[One-line highlight]\n\nLink in profile.",
        'image_count' => 1,
        'image_keywords' => ['announcement', 'launch'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_promo',
        'category' => 'promotion',
        'name' => 'Flash promo',
        'description' => 'Time-sensitive offer in story format.',
        'content' => "Today only.\n\n[Discount]% off at {{brand_name}}.\n\nTap to shop.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'urgency'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_question',
        'category' => 'engagement',
        'name' => 'Quick question',
        'description' => 'Ask followers a question to drive replies and reactions.',
        'content' => "Quick one.\n\n[Question for your audience]\n\nReply to this story.",
        'image_count' => 1,
        'image_keywords' => ['question', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_new_drop',
        'category' => 'product_launch',
        'name' => 'New drop',
        'description' => 'Tease a fresh product with a quick visual cue.',
        'content' => "It is here.\n\n[Product name] from {{brand_name}}.\n\nTap to see it.",
        'image_count' => 1,
        'image_keywords' => ['new product', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_preorder',
        'category' => 'product_launch',
        'name' => 'Preorder open',
        'description' => 'Open preorders with a short story prompt.',
        'content' => "Preorders open.\n\n[Product] ships [date].\n\nLink in bio.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_launch_day',
        'category' => 'product_launch',
        'name' => 'Launch day',
        'description' => 'Mark the live launch with a single tap CTA.',
        'content' => "Live now.\n\n[Product] is shipping today.\n\nTap to grab yours.",
        'image_count' => 1,
        'image_keywords' => ['launch', 'product reveal'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_back_in_stock',
        'category' => 'product_launch',
        'name' => 'Back in stock',
        'description' => 'Alert followers that a sold-out item is back.',
        'content' => "Back in stock.\n\n[Product] at {{brand_name}}.\n\nGoes fast. Tap to check.",
        'image_count' => 1,
        'image_keywords' => ['restock', 'available'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bogo',
        'category' => 'promotion',
        'name' => 'Buy one get one',
        'description' => 'Push a BOGO offer in story format.',
        'content' => "Buy 1, get 1.\n\nThis week at {{brand_name}}.\n\nTap to shop.",
        'image_count' => 1,
        'image_keywords' => ['bogo', 'sale'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_free_shipping',
        'category' => 'promotion',
        'name' => 'Free shipping',
        'description' => 'Promote a free shipping window.',
        'content' => "Free shipping.\n\n48 hours only at {{brand_name}}.\n\nUse code [CODE].",
        'image_count' => 1,
        'image_keywords' => ['shipping', 'delivery box'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_last_chance',
        'category' => 'promotion',
        'name' => 'Last chance sale',
        'description' => 'Final call for an ending discount.',
        'content' => "Last chance.\n\n[Discount]% off ends tonight.\n\nTap to shop {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'sale ending'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_coupon_drop',
        'category' => 'promotion',
        'name' => 'Coupon drop',
        'description' => 'Drop a coupon code in a 24h story.',
        'content' => "Code [CODE].\n\n[Discount]% off at {{brand_name}}.\n\nGone in 24h.",
        'image_count' => 1,
        'image_keywords' => ['coupon', 'promo code'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_quick_tip',
        'category' => 'educational',
        'name' => 'Quick tip',
        'description' => 'Share a single useful tip.',
        'content' => "Quick tip.\n\n[One actionable tip].\n\nSave this story.",
        'image_count' => 1,
        'image_keywords' => ['tip', 'advice'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_did_you_know',
        'category' => 'educational',
        'name' => 'Did you know',
        'description' => 'Surprise followers with a quick fact.',
        'content' => "Did you know?\n\n[Surprising fact].\n\nMore on the {{brand_name}} blog.",
        'image_count' => 1,
        'image_keywords' => ['fact', 'lightbulb'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_myth_buster',
        'category' => 'educational',
        'name' => 'Myth buster',
        'description' => 'Bust a common myth in a single hit.',
        'content' => "Myth: [common belief].\n\nReality: [truth].\n\nTap for the why.",
        'image_count' => 1,
        'image_keywords' => ['myth', 'truth'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_one_minute_lesson',
        'category' => 'educational',
        'name' => 'One minute lesson',
        'description' => 'A bite-sized lesson with a tap CTA.',
        'content' => "60-second lesson.\n\n[Topic] from {{brand_name}}.\n\nTap to watch.",
        'image_count' => 1,
        'image_keywords' => ['lesson', 'teaching'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_workspace',
        'category' => 'behind_the_scenes',
        'name' => 'Workspace BTS',
        'description' => 'Show the workspace where things happen.',
        'content' => "Today at {{brand_name}}.\n\n[What is happening right now].\n\nTap for more.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'office'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_team',
        'category' => 'behind_the_scenes',
        'name' => 'Meet the team',
        'description' => 'Introduce a team member quickly.',
        'content' => "Meet [name].\n\n[Role at {{brand_name}}].\n\nTap to say hi.",
        'image_count' => 1,
        'image_keywords' => ['team', 'employee'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_process',
        'category' => 'behind_the_scenes',
        'name' => 'How it is made',
        'description' => 'Quick peek at how something gets made.',
        'content' => "How [product] is made.\n\nStep [n] at {{brand_name}}.\n\nTap for the full clip.",
        'image_count' => 1,
        'image_keywords' => ['production', 'process'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_packing',
        'category' => 'behind_the_scenes',
        'name' => 'Packing orders',
        'description' => 'Show orders going out the door.',
        'content' => "Packing orders.\n\n[Number] going out today.\n\nThank you for the support.",
        'image_count' => 1,
        'image_keywords' => ['packing', 'shipping'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_customer_quote',
        'category' => 'testimonial',
        'name' => 'Customer quote',
        'description' => 'Showcase a short customer quote.',
        'content' => "\"[Customer quote].\"\n\n- [name]\n\nTap to read more.",
        'image_count' => 1,
        'image_keywords' => ['quote', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_five_star',
        'category' => 'testimonial',
        'name' => 'Five star review',
        'description' => 'Highlight a five star review.',
        'content' => "5 stars.\n\n\"[Short review]\", [name]\n\nMore at {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['five stars', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_before_after',
        'category' => 'testimonial',
        'name' => 'Before and after',
        'description' => 'Show a before/after with a single CTA.',
        'content' => "Before. After.\n\n[Customer name] using {{brand_name}}.\n\nTap for the story.",
        'image_count' => 1,
        'image_keywords' => ['before after', 'transformation'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_industry_trend',
        'category' => 'industry_tip',
        'name' => 'Industry trend',
        'description' => 'Drop a quick trend insight.',
        'content' => "Trend watch.\n\n[Industry trend in one line].\n\nTap for the take.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_pro_hack',
        'category' => 'industry_tip',
        'name' => 'Pro hack',
        'description' => 'Share a quick pro hack.',
        'content' => "Pro hack.\n\n[One-line hack].\n\nMore tips at {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['hack', 'shortcut'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_mistake_to_avoid',
        'category' => 'industry_tip',
        'name' => 'Mistake to avoid',
        'description' => 'Warn about a common mistake.',
        'content' => "Stop doing this.\n\n[Common mistake].\n\nTap for the fix.",
        'image_count' => 1,
        'image_keywords' => ['warning', 'mistake'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_save_date',
        'category' => 'event',
        'name' => 'Save the date',
        'description' => 'Plant a save-the-date in a 24h story.',
        'content' => "Save the date.\n\n[Event] on [date].\n\nRSVP in bio.",
        'image_count' => 1,
        'image_keywords' => ['calendar', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_today',
        'category' => 'event',
        'name' => 'Event today',
        'description' => 'Same-day event reminder.',
        'content' => "Today.\n\n[Event] at [time].\n\nTap for the link.",
        'image_count' => 1,
        'image_keywords' => ['event', 'live'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_live_starting',
        'category' => 'event',
        'name' => 'Going live',
        'description' => 'Push followers into a live stream.',
        'content' => "Going live.\n\n[Topic] in [minutes] minutes.\n\nTap to join {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['live stream', 'broadcast'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_recap',
        'category' => 'event',
        'name' => 'Event recap',
        'description' => 'A quick day-after recap.',
        'content' => "That was [event].\n\nThanks for showing up.\n\nFull recap on the page.",
        'image_count' => 1,
        'image_keywords' => ['event recap', 'crowd'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_poll_this_or_that',
        'category' => 'engagement',
        'name' => 'This or that',
        'description' => 'Poll-style story with two options.',
        'content' => "[Option A] or [Option B]?\n\nReply with your pick.\n\nWe read every one.",
        'image_count' => 1,
        'image_keywords' => ['poll', 'choice'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_dm_us',
        'category' => 'engagement',
        'name' => 'DM us',
        'description' => 'Invite followers to send a message.',
        'content' => "DM us.\n\n[Reason to message {{brand_name}}].\n\nWe reply fast.",
        'image_count' => 1,
        'image_keywords' => ['message', 'chat'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_caption_this',
        'category' => 'engagement',
        'name' => 'Caption this',
        'description' => 'Open-ended caption prompt.',
        'content' => "Caption this.\n\n[Image context].\n\nReply with your best.",
        'image_count' => 1,
        'image_keywords' => ['fun', 'reaction'],
        'slides' => null,
    ],
];
