<?php

declare(strict_types=1);

return [
    [
        'slug' => 'facebook_special_offer',
        'category' => 'promotion',
        'name' => 'Special offer',
        'description' => 'Promote a special offer on Facebook with a clear call to action.',
        'content' => "🎉 Special offer from {{brand_name}}.\n\n[Offer summary], only available through [date].\n\nClick the link to claim yours: [link]\n\nQuestions? Drop them in the comments, we read every one.",
        'image_count' => 1,
        'image_keywords' => ['offer', 'sale', 'promotion'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_community_story',
        'category' => 'behind_the_scenes',
        'name' => 'Community story',
        'description' => 'Share a story about a customer or team moment to build connection.',
        'content' => "Meet [name].\n\n[Short story, 2 to 4 sentences, about how they use {{brand_name}} or what they bring to our community.]\n\nThis is why we do what we do. ❤️",
        'image_count' => 1,
        'image_keywords' => ['people', 'story', 'community'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_event_invite',
        'category' => 'event',
        'name' => 'Event invite',
        'description' => 'Invite your followers to an upcoming event or webinar.',
        'content' => "📅 Save the date.\n\n{{brand_name}} is hosting [event name] on [date] at [time].\n\nWe'll cover:\n• [Topic 1]\n• [Topic 2]\n• [Topic 3]\n\nFree to attend. Save your spot → [link]",
        'image_count' => 1,
        'image_keywords' => ['event', 'calendar', 'invitation'],
        'slides' => null,
    ],

    // Product launch (4)
    [
        'slug' => 'facebook_new_product_reveal',
        'category' => 'product_launch',
        'name' => 'New product reveal',
        'description' => 'Announce a brand new product to your Facebook community.',
        'content' => "After [number] months of work, we can finally talk about it.\n\nMeet [product name], the [short description] we built because [reason]. Our team kept hearing the same thing from people in this community: [common request]. So we made it.\n\n{{brand_name}} is shipping the first batch on [date]. The link is in the first comment.\n\nWhat do you want to know about it? Drop your questions below and we'll answer every single one this week.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_product_restock',
        'category' => 'product_launch',
        'name' => 'Product restock announcement',
        'description' => 'Tell followers a sold-out product is back in stock.',
        'content' => "It's back.\n\n[Product name] sold out in [time period] last time, and a lot of you were on the waitlist. We restocked this morning with [quantity] units.\n\nIf you missed it before, this is your reminder: [link]\n\nFor anyone who already has one, what would you tell someone thinking about ordering?",
        'image_count' => 1,
        'image_keywords' => ['product', 'restock', 'shelf'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_feature_release',
        'category' => 'product_launch',
        'name' => 'New feature release',
        'description' => 'Announce a new feature added to an existing product.',
        'content' => "Small update, big difference.\n\n{{brand_name}} just rolled out [feature name]. You asked for it in the comments more times than we can count, so here it is: [one-sentence explanation of what it does].\n\nIt's live for everyone starting today. No upgrade needed.\n\nIf you try it this week, tell us what you think. We're already taking notes for what to build next.",
        'image_count' => 1,
        'image_keywords' => ['feature', 'update', 'screen'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_preorder_open',
        'category' => 'product_launch',
        'name' => 'Pre-order announcement',
        'description' => 'Open pre-orders for an upcoming product release.',
        'content' => "Pre-orders are open.\n\n[Product name] ships on [date], and we're letting this community order first. Pre-order pricing is [price] until [deadline], and there are only [quantity] spots in the first run.\n\nHere's the link: [link]\n\nIf you have questions about [common concern: shipping / sizing / specs], ask in the comments. We'll be here all afternoon.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product', 'package'],
        'slides' => null,
    ],

    // Promotion (3)
    [
        'slug' => 'facebook_flash_sale',
        'category' => 'promotion',
        'name' => 'Flash sale alert',
        'description' => 'Announce a short-term flash sale with urgency.',
        'content' => "Flash sale, today only.\n\n[Discount] off [product/category] until midnight. Use code [CODE] at checkout.\n\nThis is the lowest price we'll offer this season, and we're not running it again until [next date].\n\nLink in the first comment. Tag a friend who's been eyeing this.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_holiday_promo',
        'category' => 'promotion',
        'name' => 'Holiday promotion',
        'description' => 'Run a holiday-themed promotion with a friendly tone.',
        'content' => "Happy [holiday name] from everyone at {{brand_name}}.\n\nTo say thank you for being part of this year, we're taking [discount] off [product/category] from [start date] through [end date]. Use code [CODE].\n\nWhatever you're celebrating this week, we hope it's a good one. Tell us how you're spending the holiday in the comments.",
        'image_count' => 1,
        'image_keywords' => ['holiday', 'celebration', 'gift'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_bundle_deal',
        'category' => 'promotion',
        'name' => 'Bundle deal promotion',
        'description' => 'Promote a product bundle with savings.',
        'content' => "Two of our favorites, better together.\n\n[Product A] + [Product B] is now a bundle, and the bundle saves you [amount] vs. buying them separately. We put them together because customers kept ordering them in the same cart.\n\nGrab one here: [link]\n\nIf you already own one of these, the other is the missing piece. Trust us on that.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'products', 'package'],
        'slides' => null,
    ],

    // Educational (4)
    [
        'slug' => 'facebook_how_to_guide',
        'category' => 'educational',
        'name' => 'How-to guide',
        'description' => 'Teach your audience how to do something useful.',
        'content' => "Here's how to [task] in under [time].\n\n1. [Step 1 with a real detail, not a vague instruction]\n2. [Step 2]\n3. [Step 3]\n4. [Step 4]\n\nThe part most people skip is [step number]. If you only do one thing, do that one.\n\nWhat's the [topic] question you keep meaning to look up? Ask below and we'll cover it next week.",
        'image_count' => 1,
        'image_keywords' => ['tutorial', 'guide', 'how to'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_myth_buster',
        'category' => 'educational',
        'name' => 'Myth vs. fact',
        'description' => 'Bust a common myth in your industry.',
        'content' => "There's a myth about [topic] that won't go away.\n\nThe myth: [common belief].\n\nWhat actually happens: [accurate explanation, 2-3 sentences with a specific example or number].\n\nWe've heard this one for years. If you've believed it too, you're in good company, most people have. Now you know.\n\nWhat other [industry] myths drive you crazy?",
        'image_count' => 1,
        'image_keywords' => ['fact check', 'information', 'thinking'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_quick_tip',
        'category' => 'educational',
        'name' => 'Quick tip',
        'description' => 'Share one bite-sized tip your audience can use today.',
        'content' => "Quick tip you can use today.\n\nIf you [common situation], try [specific action] instead of [usual approach]. The reason: [one-sentence explanation of why it works].\n\nWe started doing this with [example] and it changed how we [outcome]. Small change, real difference.\n\nGive it a shot this week and tell us how it goes.",
        'image_count' => 1,
        'image_keywords' => ['tip', 'lightbulb', 'idea'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_common_mistake',
        'category' => 'educational',
        'name' => 'Common mistake to avoid',
        'description' => 'Help readers avoid a typical mistake in your field.',
        'content' => "The most common mistake we see with [topic]: [specific mistake].\n\nIt usually happens when [context]. The result is [consequence], and by the time you notice, [downside].\n\nWhat to do instead: [clear alternative]. It takes [time/effort] more up front and saves you [benefit] later.\n\nIf you've made this one before, you're not alone. We've made it too. What's a mistake you wish someone had warned you about?",
        'image_count' => 1,
        'image_keywords' => ['mistake', 'warning', 'lesson'],
        'slides' => null,
    ],

    // Behind the scenes (4)
    [
        'slug' => 'facebook_team_intro',
        'category' => 'behind_the_scenes',
        'name' => 'Team member intro',
        'description' => 'Introduce a team member to the community.',
        'content' => "Say hi to [name].\n\n[Name] is our [role] and has been with {{brand_name}} for [time]. They're the reason [specific thing they own or improved], and if you've ever emailed support, there's a good chance they're the person who wrote back.\n\nFun fact: [one human detail, hobby, weird skill, favorite snack].\n\nDrop a wave in the comments and say hello.",
        'image_count' => 1,
        'image_keywords' => ['team', 'portrait', 'workplace'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_workspace_tour',
        'category' => 'behind_the_scenes',
        'name' => 'Workspace tour',
        'description' => 'Show followers around your workspace or studio.',
        'content' => "A peek inside where the work happens.\n\nThis is [room/space name] at {{brand_name}}. [One specific detail about it, the lighting, the mess, the corner everyone fights over]. We spend most of our day here, and it shows.\n\n[Second detail, something visible in the photo that has a story behind it].\n\nWhat does your workspace look like right now? Honest answers only, coffee cups and all.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'office', 'studio'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_making_of',
        'category' => 'behind_the_scenes',
        'name' => 'Making-of post',
        'description' => 'Show how a product or piece of work gets made.',
        'content' => "Ever wonder how [product/service] actually gets made?\n\nIt starts with [first step] and ends with [last step]. In between there's a lot of [honest description, testing, redoing, second-guessing]. The version you eventually buy is usually the [number] attempt.\n\nHere's a snapshot from this week's batch. The [specific detail] is the part nobody sees but everyone notices when it's done right.\n\nQuestions about the process? Ask away.",
        'image_count' => 1,
        'image_keywords' => ['workshop', 'process', 'craft'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_milestone_celebration',
        'category' => 'behind_the_scenes',
        'name' => 'Milestone celebration',
        'description' => 'Celebrate a meaningful milestone with the community.',
        'content' => "Today is [milestone, anniversary, customer count, anything real].\n\nWe started {{brand_name}} [time ago] with [honest origin detail, a kitchen table, one customer, a borrowed laptop]. The plan was simple and a little naive: [original goal].\n\n[Milestone] later, we're still here, mostly because of the people in this community who kept showing up. Thank you. Genuinely.\n\nTell us in the comments, when did you first find us?",
        'image_count' => 1,
        'image_keywords' => ['celebration', 'milestone', 'anniversary'],
        'slides' => null,
    ],

    // Testimonial (3)
    [
        'slug' => 'facebook_customer_quote',
        'category' => 'testimonial',
        'name' => 'Customer quote',
        'description' => 'Share a customer testimonial in their own words.',
        'content' => "\"[Direct customer quote, keep it specific, in their voice, with a real result or feeling.]\"\n\n- [Customer name], [city or role]\n\nWe got this message last [time] and asked if we could share it. [Customer first name] said yes. We're grateful for words like these and for everyone who takes a minute to send them.\n\nIf {{brand_name}} has been part of your story too, we'd love to hear it in the comments.",
        'image_count' => 1,
        'image_keywords' => ['testimonial', 'happy customer', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_before_after_story',
        'category' => 'testimonial',
        'name' => 'Before and after story',
        'description' => 'Tell a customer transformation story.',
        'content' => "Before: [Customer's situation when they found {{brand_name}}, describe in 2-3 honest sentences].\n\nAfter: [What changed, with a specific outcome and timeframe].\n\n[Customer name] sent us this update last month, and it's the kind of thing that makes everyone in the office quiet for a second. We didn't do the work, they did. We just helped where we could.\n\nIf you've been on the fence about [common hesitation], stories like this might be why to start.",
        'image_count' => 1,
        'image_keywords' => ['transformation', 'progress', 'result'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_review_highlight',
        'category' => 'testimonial',
        'name' => 'Review highlight',
        'description' => 'Highlight a recent review with context.',
        'content' => "5-star review from [customer name] this week:\n\n\"[Pull a real, specific line from the review, not the generic praise, the part with the actual detail.]\"\n\nWe save reviews like this and re-read them on the hard days. Thank you, [first name].\n\nIf you've got a few minutes and {{brand_name}} has helped you, leaving a review here is the kindest thing you can do for us: [link]",
        'image_count' => 1,
        'image_keywords' => ['review', 'stars', 'feedback'],
        'slides' => null,
    ],

    // Industry tip (3)
    [
        'slug' => 'facebook_industry_insight',
        'category' => 'industry_tip',
        'name' => 'Industry insight',
        'description' => 'Share a useful insight from your industry.',
        'content' => "Something we noticed working in [industry] this year:\n\n[Specific observation, a shift, a pattern, a counterintuitive finding. 2-3 sentences with a number or example.]\n\nWe don't think this is going to reverse anytime soon, and the businesses who plan for it now will have an easier time than the ones who wait.\n\nAre you seeing the same thing? Curious what your experience has been.",
        'image_count' => 1,
        'image_keywords' => ['insight', 'industry', 'analysis'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_pro_tip',
        'category' => 'industry_tip',
        'name' => 'Pro tip from experience',
        'description' => 'Share a tip earned through experience.',
        'content' => "A pro tip we learned the hard way:\n\nWhen you [common scenario], always [specific action]. We used to skip this step because it felt like extra work, until [story, what went wrong].\n\nNow it's the first thing we do, every time. Takes [time] and prevents [problem].\n\nWhat's a tip you'd give someone just starting out in [field]?",
        'image_count' => 1,
        'image_keywords' => ['expertise', 'professional', 'advice'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_industry_trend',
        'category' => 'industry_tip',
        'name' => 'Industry trend explainer',
        'description' => 'Explain a trend in plain language.',
        'content' => "Everyone in [industry] is talking about [trend]. Here's what it actually means in plain English.\n\n[2-3 sentence explanation without jargon, with one concrete example.]\n\nWhether it lives up to the hype is another question. Our take: [honest opinion, what to take seriously, what to ignore].\n\nWhere do you stand on this one? Genuinely curious where the community lands.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry', 'explainer'],
        'slides' => null,
    ],

    // Event (3)
    [
        'slug' => 'facebook_event_recap',
        'category' => 'event',
        'name' => 'Event recap',
        'description' => 'Share a recap after an event ends.',
        'content' => "[Event name] just wrapped, and we're still recovering.\n\n[Number] of you showed up, asked good questions, and stayed late. Highlights: [moment 1], [moment 2], and the part where [specific funny or memorable thing].\n\nA huge thank you to everyone who came. If you missed it, we recorded the main session and the link is in the first comment.\n\nWhat was your favorite moment from the day? Tag someone you met there.",
        'image_count' => 1,
        'image_keywords' => ['event', 'recap', 'crowd'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_event_countdown',
        'category' => 'event',
        'name' => 'Event countdown',
        'description' => 'Build anticipation as an event approaches.',
        'content' => "[Number] days until [event name].\n\nIf you haven't grabbed your spot, now is the time. We've got [number] seats left, and they tend to go fast in the last week.\n\nWhat to expect on [date]: [one real detail], [another real detail], and time to actually talk to people instead of just watching slides.\n\nGet your ticket here: [link]\n\nWho's coming? Drop a comment so we know who to look for.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'event', 'tickets'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_workshop_announcement',
        'category' => 'event',
        'name' => 'Workshop announcement',
        'description' => 'Announce a hands-on workshop.',
        'content' => "We're running a workshop on [topic].\n\n[Date] at [time]. Limited to [number] people because it's hands-on, not a webinar. You'll leave with [specific outcome, a finished thing, a working setup, a written plan].\n\nWho it's for: [audience]. Who it's not for: [honest disclaimer].\n\nDetails and signup: [link]\n\nQuestions about whether it's right for you? Ask in the comments.",
        'image_count' => 1,
        'image_keywords' => ['workshop', 'learning', 'hands on'],
        'slides' => null,
    ],

    // Engagement (3)
    [
        'slug' => 'facebook_question_prompt',
        'category' => 'engagement',
        'name' => 'Community question',
        'description' => 'Ask the community a thoughtful question.',
        'content' => "Genuine question for the community.\n\nWhen you [common situation related to {{brand_name}}], how do you usually [specific decision]? We're asking because we keep seeing the same thing come up in DMs, and we have a hunch our answer isn't the only good one.\n\nNo wrong answers. We read every comment.",
        'image_count' => 1,
        'image_keywords' => ['question', 'conversation', 'people talking'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_this_or_that',
        'category' => 'engagement',
        'name' => 'This or that poll',
        'description' => 'Run a fun this-or-that style post.',
        'content' => "Settle a debate we've been having all week.\n\n[Option A] or [Option B]?\n\nNo overthinking it. First instinct, in the comments.\n\nFor what it's worth, the team is split [number] to [number]. We'll share the winning side on Friday.",
        'image_count' => 1,
        'image_keywords' => ['choice', 'comparison', 'options'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_fill_in_blank',
        'category' => 'engagement',
        'name' => 'Fill in the blank',
        'description' => 'Invite followers to complete a sentence.',
        'content' => "Fill in the blank:\n\nThe one thing I wish I'd known before [topic] is __________.\n\nWe'll go first: [your honest answer, with a real story attached].\n\nYour turn. The best answers we've gotten on prompts like this end up helping someone else who reads them later, so don't hold back.",
        'image_count' => 1,
        'image_keywords' => ['conversation', 'thinking', 'community'],
        'slides' => null,
    ],
];
