<?php

declare(strict_types=1);

return [
    [
        'slug' => 'limited_time_offer_feed',
        'category' => 'promotion',
        'name' => 'Limited-time offer',
        'description' => 'Promote a time-sensitive deal on Instagram Feed.',
        'content' => "⏰ Don't miss it. {{brand_name}} is offering [discount]% off [product/service], today only.\n\nTap the link in bio to grab yours before it's gone.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'offer', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'team_behind_the_scenes_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Team behind the scenes',
        'description' => 'Humanize your brand by showing the team at work.',
        'content' => "This is what a typical day at {{brand_name}} looks like. 👀\n\nWe believe great work happens when people feel at home. Here's a peek behind the curtain.\n\n#{{brand_name}} #BehindTheScenes",
        'image_count' => 1,
        'image_keywords' => ['office', 'team', 'workspace'],
        'slides' => null,
    ],

    // Product launch
    [
        'slug' => 'new_product_drop_feed',
        'category' => 'product_launch',
        'name' => 'New product drop',
        'description' => 'Announce a fresh product release on the feed.',
        'content' => "It's here. [Product name] just landed at {{brand_name}}.\n\nWe spent [months/weeks] on this one. Every detail was tested by the team before we let it out the door.\n\nTap the link in bio to be one of the first to try it.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'pre_order_announcement_feed',
        'category' => 'product_launch',
        'name' => 'Pre-order announcement',
        'description' => 'Open pre-orders for an upcoming product.',
        'content' => "Pre-orders are open. [Product name] ships [date].\n\nThe first batch is limited to [number] units. Once they're claimed, the next run won't ship until [later date].\n\nReserve yours through the link in bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'package', 'box'],
        'slides' => null,
    ],
    [
        'slug' => 'feature_highlight_launch_feed',
        'category' => 'product_launch',
        'name' => 'Feature highlight launch',
        'description' => 'Spotlight one specific feature of a new product.',
        'content' => "The one thing we're most proud of in [product name]: [specific feature].\n\nIt took [number] prototypes to get this right. The early testers told us it changed how they [use case], so we kept iterating until it felt obvious.\n\nSee it in action through the link in bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'detail', 'closeup'],
        'slides' => null,
    ],
    [
        'slug' => 'product_restock_feed',
        'category' => 'product_launch',
        'name' => 'Product restock',
        'description' => 'Announce a return-to-stock for a popular item.',
        'content' => "Back in stock. [Product name] sold out in [time period] last time, so we made more.\n\nIf you missed it before, now's the moment. Stock is limited again, and we expect another quick run.\n\nGrab yours via the link in bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'shelf', 'inventory'],
        'slides' => null,
    ],

    // Promotion
    [
        'slug' => 'flash_sale_feed',
        'category' => 'promotion',
        'name' => 'Flash sale',
        'description' => 'Drive urgency with a short flash sale.',
        'content' => "Flash sale. [Discount]% off everything for the next [hours] hours.\n\nNo code needed at checkout. The discount is already applied across the site.\n\nLink in bio. Set a timer.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'bundle_deal_feed',
        'category' => 'promotion',
        'name' => 'Bundle deal',
        'description' => 'Promote a multi-product bundle offer.',
        'content' => "Buy [item A] and [item B] together, save [amount].\n\nIt's the same combo our team uses every week, so we put it together as a set. Cheaper than buying each one on its own.\n\nLink in bio.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'products', 'gift'],
        'slides' => null,
    ],
    [
        'slug' => 'free_shipping_feed',
        'category' => 'promotion',
        'name' => 'Free shipping',
        'description' => 'Announce free shipping for a limited window.',
        'content' => "Free shipping on every order this week.\n\nNo minimum, no code, no fine print at the bottom you have to squint to read. Just pick what you want and we'll cover the delivery.\n\nLink in bio. Ends [day].",
        'image_count' => 1,
        'image_keywords' => ['shipping', 'package', 'delivery'],
        'slides' => null,
    ],
    [
        'slug' => 'first_order_discount_feed',
        'category' => 'promotion',
        'name' => 'First order discount',
        'description' => 'Welcome new customers with a first-purchase discount.',
        'content' => "First time at {{brand_name}}? Take [discount]% off your first order.\n\nUse code [CODE] at checkout. Works on anything in the shop, including the [bestseller name] people keep asking us about.\n\nLink in bio.",
        'image_count' => 1,
        'image_keywords' => ['welcome', 'shop', 'discount'],
        'slides' => null,
    ],

    // Educational
    [
        'slug' => 'quick_how_to_tip_feed',
        'category' => 'educational',
        'name' => 'Quick how-to tip',
        'description' => 'Share a single actionable tip from your niche.',
        'content' => "Here's a small thing that makes [task] easier: [tip in one sentence].\n\nWe started doing this after [reason or story]. Saved us [time/money/effort] within a week.\n\nSave this post for later. Link in bio for the full guide.",
        'image_count' => 1,
        'image_keywords' => ['notebook', 'desk', 'work'],
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake_feed',
        'category' => 'educational',
        'name' => 'Common mistake',
        'description' => 'Call out a frequent mistake and the fix.',
        'content' => "The mistake we see most often with [topic]: [the mistake].\n\nIt's easy to do. Most people don't realize it costs them [consequence] until someone points it out.\n\nThe fix is simple: [the fix]. Try it this week and see what changes.",
        'image_count' => 1,
        'image_keywords' => ['warning', 'thinking', 'desk'],
        'slides' => null,
    ],
    [
        'slug' => 'myth_vs_truth_feed',
        'category' => 'educational',
        'name' => 'Myth vs truth',
        'description' => 'Debunk a common myth in your industry.',
        'content' => "Myth: [common belief about your industry].\n\nTruth: [the reality, with one supporting detail].\n\nWe used to believe the myth too. Then we tracked it for [time period] and the data said otherwise. Save this if you've heard the same thing.",
        'image_count' => 1,
        'image_keywords' => ['question', 'thinking', 'idea'],
        'slides' => null,
    ],
    [
        'slug' => 'glossary_term_feed',
        'category' => 'educational',
        'name' => 'Glossary term explained',
        'description' => 'Explain one industry term in plain language.',
        'content' => "[Term]: what it actually means.\n\nMost guides explain it with more jargon. Here's the plain version: [one-sentence definition].\n\nA real example from our work: [short example]. Save the post if you've been nodding through meetings without asking.",
        'image_count' => 1,
        'image_keywords' => ['book', 'glossary', 'study'],
        'slides' => null,
    ],

    // Behind the scenes
    [
        'slug' => 'workspace_tour_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Workspace tour',
        'description' => 'Show where the work happens.',
        'content' => "Where the work happens.\n\nThis is [room/space] at {{brand_name}}. The plant in the corner has survived three office moves. The whiteboard hasn't been wiped since [month].\n\nNot polished, but it's ours.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'desk', 'studio'],
        'slides' => null,
    ],
    [
        'slug' => 'how_its_made_feed',
        'category' => 'behind_the_scenes',
        'name' => 'How it is made',
        'description' => 'Show one step of your production process.',
        'content' => "This is step [number] of how we make [product].\n\nIt takes about [time] and we do it by hand. No shortcuts here, mostly because we tried the shortcut once and it ruined a whole batch.\n\nMore on the process in the link in bio.",
        'image_count' => 1,
        'image_keywords' => ['craft', 'making', 'workshop'],
        'slides' => null,
    ],
    [
        'slug' => 'team_member_intro_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Team member intro',
        'description' => 'Introduce a single team member.',
        'content' => "Meet [name], our [role] at {{brand_name}}.\n\n[Name] joined us [time ago] and runs [area]. Outside work, you'll find them [hobby or interest].\n\nIf you've emailed support recently, there's a good chance [name] wrote back.",
        'image_count' => 1,
        'image_keywords' => ['portrait', 'team', 'person'],
        'slides' => null,
    ],
    [
        'slug' => 'a_day_in_the_life_feed',
        'category' => 'behind_the_scenes',
        'name' => 'A day in the life',
        'description' => 'Walk through a normal day at the company.',
        'content' => "A normal Tuesday at {{brand_name}}.\n\nMornings are quiet, mostly emails and one stand-up. Afternoons get loud once [activity] starts. By 5pm someone has usually broken something and someone else has fixed it.\n\nThat's the whole job, honestly.",
        'image_count' => 1,
        'image_keywords' => ['office', 'work', 'coffee'],
        'slides' => null,
    ],

    // Testimonial
    [
        'slug' => 'customer_quote_feed',
        'category' => 'testimonial',
        'name' => 'Customer quote',
        'description' => 'Share a single strong customer quote.',
        'content' => "\"[Customer quote in their own words].\", [Customer name], [city or role]\n\nThis came in last week and we had to share it. Thanks [first name].\n\nIf {{brand_name}} has helped you with [outcome], we'd love to hear about it. Reply or DM us.",
        'image_count' => 1,
        'image_keywords' => ['quote', 'happy', 'customer'],
        'slides' => null,
    ],
    [
        'slug' => 'before_after_result_feed',
        'category' => 'testimonial',
        'name' => 'Before and after result',
        'description' => 'Highlight a real customer transformation.',
        'content' => "Before: [starting point].\nAfter: [result with a number if possible].\n\n[Customer name] worked with us for [time period]. The change wasn't overnight, but you can see where things tipped.\n\nLink in bio if you want a similar look.",
        'image_count' => 1,
        'image_keywords' => ['transformation', 'result', 'progress'],
        'slides' => null,
    ],
    [
        'slug' => 'star_rating_review_feed',
        'category' => 'testimonial',
        'name' => 'Star rating review',
        'description' => 'Spotlight a recent five-star review.',
        'content' => "★★★★★\n\n\"[Pulled review text, two to three sentences].\"\n\n[Reviewer first name] left this one yesterday. We read every review that comes in, the kind ones and the rough ones.\n\nLeave yours in the link in bio.",
        'image_count' => 1,
        'image_keywords' => ['stars', 'review', 'rating'],
        'slides' => null,
    ],
    [
        'slug' => 'case_study_snapshot_feed',
        'category' => 'testimonial',
        'name' => 'Case study snapshot',
        'description' => 'Tease a longer customer success story.',
        'content' => "How [customer or company] used {{brand_name}} to [outcome].\n\nIn [time period], they went from [starting point] to [result]. The full breakdown covers what they tried first and what finally clicked.\n\nLink in bio for the case study.",
        'image_count' => 1,
        'image_keywords' => ['case study', 'meeting', 'results'],
        'slides' => null,
    ],

    // Industry tip
    [
        'slug' => 'one_tool_we_use_feed',
        'category' => 'industry_tip',
        'name' => 'One tool we use',
        'description' => 'Recommend a tool you actually use.',
        'content' => "One tool we use every week: [tool name].\n\nWe tried [number] alternatives before settling on this one. The thing that won us over was [specific feature], not the marketing on the homepage.\n\nNot sponsored. Just useful.",
        'image_count' => 1,
        'image_keywords' => ['tools', 'software', 'laptop'],
        'slides' => null,
    ],
    [
        'slug' => 'industry_trend_take_feed',
        'category' => 'industry_tip',
        'name' => 'Industry trend take',
        'description' => 'Give an honest opinion on a current trend.',
        'content' => "Everyone in [industry] is talking about [trend].\n\nHonest take: it's useful for [use case], not for [other use case]. We tested it on a small project before committing, and that's the version we'd recommend.\n\nWhat's been your experience? Tell us in the comments.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry', 'analysis'],
        'slides' => null,
    ],
    [
        'slug' => 'pricing_advice_feed',
        'category' => 'industry_tip',
        'name' => 'Pricing advice',
        'description' => 'Share a pricing lesson from experience.',
        'content' => "What we got wrong about pricing: [the mistake].\n\nWe undercharged for [period] before someone pointed out our numbers didn't add up. Raised prices [percent], lost [number] customers, kept the rest, made more.\n\nIf you're stuck on this too, the link in bio has our pricing breakdown.",
        'image_count' => 1,
        'image_keywords' => ['money', 'price', 'calculator'],
        'slides' => null,
    ],
    [
        'slug' => 'workflow_tip_feed',
        'category' => 'industry_tip',
        'name' => 'Workflow tip',
        'description' => 'Share a small workflow improvement.',
        'content' => "Small workflow change that saved us hours: [the change].\n\nBefore, [old way]. After, [new way]. Took about a week to get used to and we haven't gone back.\n\nIf you try it, let us know how it lands.",
        'image_count' => 1,
        'image_keywords' => ['workflow', 'productivity', 'planner'],
        'slides' => null,
    ],

    // Event
    [
        'slug' => 'event_announcement_feed',
        'category' => 'event',
        'name' => 'Event announcement',
        'description' => 'Announce an upcoming event.',
        'content' => "Save the date.\n\n{{brand_name}} is hosting [event name] on [date] at [location or online].\n\nWe've got [speakers, format, or what to expect]. Spots are limited to [number] this time.\n\nRSVP through the link in bio.",
        'image_count' => 1,
        'image_keywords' => ['event', 'invitation', 'calendar'],
        'slides' => null,
    ],
    [
        'slug' => 'webinar_invite_feed',
        'category' => 'event',
        'name' => 'Webinar invite',
        'description' => 'Promote an upcoming webinar.',
        'content' => "Free webinar: [topic]. [Date] at [time].\n\n[Host name] is going to walk through [main points] and then take live questions for the last [minutes].\n\nIf you can't make it, sign up anyway and we'll send the recording.\n\nLink in bio.",
        'image_count' => 1,
        'image_keywords' => ['webinar', 'laptop', 'presentation'],
        'slides' => null,
    ],
    [
        'slug' => 'meetup_recap_feed',
        'category' => 'event',
        'name' => 'Meetup recap',
        'description' => 'Recap a recent in-person event.',
        'content' => "[Number] people, [city], one room.\n\nLast night's meetup brought together folks working in [field]. The best conversation of the night was about [topic], started over coffee and never really ended.\n\nThanks to everyone who came out. Next one is [date].",
        'image_count' => 1,
        'image_keywords' => ['meetup', 'crowd', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'live_stream_reminder_feed',
        'category' => 'event',
        'name' => 'Live stream reminder',
        'description' => 'Remind followers about an upcoming live stream.',
        'content' => "Going live [day] at [time].\n\nWe're talking [topic]. No script, just questions and whatever the chat throws at us.\n\nTurn on notifications so you don't miss it. Or don't, the replay will be on the grid afterward.",
        'image_count' => 1,
        'image_keywords' => ['live', 'broadcast', 'camera'],
        'slides' => null,
    ],

    // Engagement
    [
        'slug' => 'this_or_that_feed',
        'category' => 'engagement',
        'name' => 'This or that',
        'description' => 'Ask a simple either/or question.',
        'content' => "[Option A] or [Option B]?\n\nWe argue about this in the office at least once a week. Curious which side wins here.\n\nVote in the comments. No wrong answer, but there's definitely a right one.",
        'image_count' => 1,
        'image_keywords' => ['choice', 'options', 'vote'],
        'slides' => null,
    ],
    [
        'slug' => 'fill_in_the_blank_feed',
        'category' => 'engagement',
        'name' => 'Fill in the blank',
        'description' => 'Prompt followers with a fill-in-the-blank question.',
        'content' => "Finish the sentence: \"The first thing I do every morning is ___.\"\n\nWe asked the team and got answers from \"check Slack\" to \"avoid checking Slack.\" Curious where you land.\n\nDrop yours in the comments.",
        'image_count' => 1,
        'image_keywords' => ['question', 'morning', 'coffee'],
        'slides' => null,
    ],
    [
        'slug' => 'comment_question_feed',
        'category' => 'engagement',
        'name' => 'Comment question',
        'description' => 'Ask an open question to spark comments.',
        'content' => "Question for the group: what's the best [topic-related thing] you've tried this year?\n\nWe're putting together a roundup and want real picks, not the same five everyone lists.\n\nDrop yours below. We'll share the favorites next week.",
        'image_count' => 1,
        'image_keywords' => ['conversation', 'community', 'chat'],
        'slides' => null,
    ],
    [
        'slug' => 'tag_a_friend_feed',
        'category' => 'engagement',
        'name' => 'Tag a friend',
        'description' => 'Encourage tagging with a relatable scenario.',
        'content' => "Tag the friend who [relatable scenario].\n\nWe all have one. Maybe you are one. Either way, this post is for them.\n\nBonus points if they tag you back.",
        'image_count' => 1,
        'image_keywords' => ['friends', 'people', 'fun'],
        'slides' => null,
    ],
];
