<?php

declare(strict_types=1);

return [
    [
        'slug' => 'feature_launch_carousel',
        'category' => 'product_launch',
        'name' => 'Feature launch',
        'description' => 'Announce a new product feature with a 5-slide story.',
        'content' => "{{brand_name}} just launched something we're excited about. Swipe to see what's new.",
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => "What's new", 'body' => 'A quick look at the latest update.', 'image_keywords' => ['product', 'launch']],
            ['title' => 'How it works', 'body' => 'Three steps and you are running.', 'image_keywords' => ['workflow']],
            ['title' => 'Why it matters', 'body' => 'Faster, simpler, fewer clicks.', 'image_keywords' => ['speed']],
            ['title' => 'Who is it for', 'body' => 'Built for teams who ship.', 'image_keywords' => ['team']],
            ['title' => 'Try it now', 'body' => 'Available today. Link in bio.', 'image_keywords' => ['phone', 'app']],
        ],
    ],
    [
        'slug' => 'five_tips_carousel',
        'category' => 'educational',
        'name' => '5 tips carousel',
        'description' => 'Share five actionable tips in a swipeable carousel.',
        'content' => '5 things I wish I knew about [topic] sooner. Save this for later. 👇',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Tip #1', 'body' => '[First tip, be specific and actionable.]', 'image_keywords' => ['idea', 'lightbulb']],
            ['title' => 'Tip #2', 'body' => '[Second tip, use a real example if you can.]', 'image_keywords' => ['notebook']],
            ['title' => 'Tip #3', 'body' => '[Third tip, keep it short.]', 'image_keywords' => ['focus']],
            ['title' => 'Tip #4', 'body' => '[Fourth tip, something surprising or counterintuitive.]', 'image_keywords' => ['surprise']],
            ['title' => 'Tip #5', 'body' => '[Fifth tip, finish strong with a takeaway.]', 'image_keywords' => ['success']],
        ],
    ],
    [
        'slug' => 'process_reveal_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Process reveal',
        'description' => 'Walk followers through how you create your product or service.',
        'content' => 'Ever wondered how [product/service] is made? Swipe to see every step. ✨',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'It starts with research', 'body' => 'Every project begins with understanding the problem deeply.', 'image_keywords' => ['research', 'desk']],
            ['title' => 'Design & iteration', 'body' => 'We prototype fast and test often.', 'image_keywords' => ['design', 'sketch']],
            ['title' => 'Building the real thing', 'body' => 'Craft and precision in every detail.', 'image_keywords' => ['craft', 'build']],
            ['title' => 'The final result', 'body' => 'Quality you can feel the moment you use it.', 'image_keywords' => ['product', 'final']],
        ],
    ],
    [
        'slug' => 'quick_stat_carousel',
        'category' => 'industry_tip',
        'name' => 'Quick stat carousel',
        'description' => 'Present industry stats in a visual carousel format.',
        'content' => "The [industry] numbers that should be on every marketer's radar this year. 📊",
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Stat #1', 'body' => '[X]% of [audience] say [finding]. Source: [source]', 'image_keywords' => ['chart', 'data']],
            ['title' => 'Stat #2', 'body' => '[Y]% increase in [metric] year over year.', 'image_keywords' => ['growth', 'graph']],
            ['title' => 'Stat #3', 'body' => 'By [year], [projection].', 'image_keywords' => ['future', 'trend']],
            ['title' => 'What this means for you', 'body' => '[Actionable takeaway based on the stats above.]', 'image_keywords' => ['action', 'plan']],
        ],
    ],
    [
        'slug' => 'event_recap_carousel',
        'category' => 'event',
        'name' => 'Event recap',
        'description' => 'Recap highlights from a recent event or conference.',
        'content' => 'We just wrapped [Event Name] and it was incredible. Here are the highlights. 🙌',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'It all started with…', 'body' => '[Opening moment or keynote highlight.]', 'image_keywords' => ['conference', 'stage']],
            ['title' => 'The session everyone talked about', 'body' => '[Key insight from the standout talk.]', 'image_keywords' => ['presentation', 'crowd']],
            ['title' => 'Connecting with the community', 'body' => '[Highlight networking or attendee moments.]', 'image_keywords' => ['networking', 'people']],
            ['title' => 'See you next time', 'body' => 'Follow {{brand_name}} for updates on our next event.', 'image_keywords' => ['celebration']],
        ],
    ],
    [
        'slug' => 'product_lineup_carousel',
        'category' => 'product_launch',
        'name' => 'Product lineup reveal',
        'description' => 'Reveal a full product lineup one item per slide.',
        'content' => "We made [number] new things. Here's the full lineup from {{brand_name}}.",
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'meet the lineup', 'body' => '[Number] new pieces, designed together. Each one solves a specific problem.', 'image_keywords' => ['products', 'lineup']],
            ['title' => 'piece one', 'body' => '[Product 1 name]. Best for [use case].', 'image_keywords' => ['product', 'studio']],
            ['title' => 'piece two', 'body' => '[Product 2 name]. Pairs well with piece one if you want [benefit].', 'image_keywords' => ['object', 'detail']],
            ['title' => 'piece three', 'body' => '[Product 3 name]. The one we kept iterating on until it felt right.', 'image_keywords' => ['craft', 'closeup']],
            ['title' => 'shop the drop', 'body' => 'Available [date]. Link in bio.', 'image_keywords' => ['shop', 'phone']],
        ],
    ],
    [
        'slug' => 'before_after_launch_carousel',
        'category' => 'product_launch',
        'name' => 'Before and after launch',
        'description' => 'Show the upgrade from old version to new version.',
        'content' => "Same idea, rebuilt. Here's what changed in the new {{brand_name}} [product].",
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'before', 'body' => '[The old version. What it did well, where it fell short.]', 'image_keywords' => ['old', 'product']],
            ['title' => 'after', 'body' => '[The new version. One sentence on the biggest change.]', 'image_keywords' => ['new', 'product']],
            ['title' => 'what we fixed', 'body' => '[Specific issue customers told us about, and how we addressed it.]', 'image_keywords' => ['detail', 'redesign']],
            ['title' => 'available now', 'body' => 'Find it in the shop. Link in bio.', 'image_keywords' => ['store', 'phone']],
        ],
    ],
    [
        'slug' => 'spec_breakdown_carousel',
        'category' => 'product_launch',
        'name' => 'Spec breakdown carousel',
        'description' => 'Break down product specs across multiple slides.',
        'content' => "The full spec sheet for [product]. Everything that's inside, on one swipe.",
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'meet [product]', 'body' => 'Built for [use case]. Available [date].', 'image_keywords' => ['product', 'reveal']],
            ['title' => 'materials', 'body' => '[Material details. Where it is sourced. Why it matters for the final feel.]', 'image_keywords' => ['materials', 'texture']],
            ['title' => 'dimensions', 'body' => '[Size, weight, fit notes. Numbers people will actually want before buying.]', 'image_keywords' => ['measurement', 'detail']],
            ['title' => 'how it performs', 'body' => '[Key performance number. Battery life, run time, hold strength, whatever fits.]', 'image_keywords' => ['performance', 'test']],
            ['title' => "what's in the box", 'body' => '[List items: product, accessories, manual, etc.]', 'image_keywords' => ['unboxing', 'box']],
            ['title' => 'order yours', 'body' => 'Link in bio. Ships [timeframe].', 'image_keywords' => ['shipping', 'parcel']],
        ],
    ],
    [
        'slug' => 'flash_sale_carousel',
        'category' => 'promotion',
        'name' => 'Flash sale',
        'description' => 'Promote a limited-time sale across slides.',
        'content' => "[Discount]% off for the next [hours] hours at {{brand_name}}. Read every slide so you don't miss it.",
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'flash sale is on', 'body' => '[Discount]% off until [end date and time]. No code needed.', 'image_keywords' => ['sale', 'tag']],
            ['title' => "what's included", 'body' => '[Categories on sale, exclusions if any. Be honest about what is not included.]', 'image_keywords' => ['products', 'shop']],
            ['title' => 'most loved picks', 'body' => '[Two or three bestsellers people grab first when sales drop.]', 'image_keywords' => ['favorites', 'shelf']],
            ['title' => 'shop before it ends', 'body' => 'Link in bio. Once stock is out, it is out.', 'image_keywords' => ['phone', 'cart']],
        ],
    ],
    [
        'slug' => 'bundle_deal_carousel',
        'category' => 'promotion',
        'name' => 'Bundle deal carousel',
        'description' => 'Explain a bundle offer slide by slide.',
        'content' => 'Three things, one price. Save [amount] when you buy them together at {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'the bundle', 'body' => '[Brief description of what is in the bundle and the total savings.]', 'image_keywords' => ['bundle', 'box']],
            ['title' => 'item one', 'body' => '[First item in the bundle and what it does on its own.]', 'image_keywords' => ['product', 'one']],
            ['title' => 'item two', 'body' => '[Second item and why it pairs with the first.]', 'image_keywords' => ['product', 'two']],
            ['title' => 'item three', 'body' => '[Third item. The one that ties the bundle together.]', 'image_keywords' => ['product', 'three']],
            ['title' => 'grab the bundle', 'body' => 'Save [amount]. Available while stock lasts.', 'image_keywords' => ['bag', 'shopping']],
        ],
    ],
    [
        'slug' => 'first_order_discount_carousel',
        'category' => 'promotion',
        'name' => 'First order discount',
        'description' => 'Welcome new customers with a first-order discount.',
        'content' => 'New here? Use code [CODE] for [discount]% off your first order at {{brand_name}}.',
        'image_count' => 3,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'welcome offer', 'body' => '[Discount]% off your first order. Code: [CODE]. Good for [duration].', 'image_keywords' => ['welcome', 'gift']],
            ['title' => 'what people start with', 'body' => '[One or two products that are good entry points for new customers.]', 'image_keywords' => ['bestseller', 'product']],
            ['title' => 'how to use it', 'body' => 'Add to cart, paste [CODE] at checkout. Link in bio.', 'image_keywords' => ['checkout', 'phone']],
        ],
    ],
    [
        'slug' => 'free_shipping_carousel',
        'category' => 'promotion',
        'name' => 'Free shipping weekend',
        'description' => 'Promote a limited free shipping window.',
        'content' => 'Free shipping at {{brand_name}} this weekend only. No minimum.',
        'image_count' => 3,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'free shipping weekend', 'body' => 'From [Friday] to [Sunday]. No code needed, no order minimum.', 'image_keywords' => ['shipping', 'box']],
            ['title' => 'where we ship', 'body' => '[Regions or countries included. Note any exclusions clearly.]', 'image_keywords' => ['map', 'globe']],
            ['title' => 'shop the weekend', 'body' => 'Tap the link in bio before [Sunday] midnight [timezone].', 'image_keywords' => ['cart', 'phone']],
        ],
    ],
    [
        'slug' => 'beginner_guide_carousel',
        'category' => 'educational',
        'name' => 'Beginner guide carousel',
        'description' => 'Teach a topic from zero to first usable result.',
        'content' => '[Topic] for absolute beginners. Save this for later. 👇',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'start here', 'body' => 'If [topic] feels overwhelming, this is the version that helped me when I was new.', 'image_keywords' => ['beginner', 'notes']],
            ['title' => 'what it actually is', 'body' => '[Plain definition. Skip jargon. One sentence is enough.]', 'image_keywords' => ['concept', 'sketch']],
            ['title' => 'why people care', 'body' => '[The concrete reason a beginner would bother learning this.]', 'image_keywords' => ['question', 'curious']],
            ['title' => 'first thing to try', 'body' => '[A small, specific action they can take in under 10 minutes.]', 'image_keywords' => ['hands', 'desk']],
            ['title' => 'common mistake', 'body' => '[The one trap most beginners fall into. Be specific.]', 'image_keywords' => ['mistake', 'fix']],
            ['title' => 'where to go next', 'body' => '[A book, channel, or {{brand_name}} resource for the next step.]', 'image_keywords' => ['library', 'resource']],
        ],
    ],
    [
        'slug' => 'common_mistakes_carousel',
        'category' => 'educational',
        'name' => 'Common mistakes',
        'description' => 'Highlight common mistakes and how to fix them.',
        'content' => '5 mistakes I see all the time with [topic]. Number 3 is the one I had to learn the hard way.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'the mistakes', 'body' => 'Five things people get wrong with [topic], and what to do instead.', 'image_keywords' => ['mistake', 'pen']],
            ['title' => 'mistake 1', 'body' => '[First mistake. Then the fix in one sentence.]', 'image_keywords' => ['error', 'paper']],
            ['title' => 'mistake 2', 'body' => '[Second mistake and the fix.]', 'image_keywords' => ['confused', 'desk']],
            ['title' => 'mistake 3', 'body' => '[Third mistake. The one that surprises people.]', 'image_keywords' => ['surprised', 'thought']],
            ['title' => 'mistake 4', 'body' => '[Fourth mistake and the fix.]', 'image_keywords' => ['process', 'workspace']],
            ['title' => 'mistake 5', 'body' => '[Final mistake. End with what you would do instead.]', 'image_keywords' => ['solution', 'check']],
        ],
    ],
    [
        'slug' => 'glossary_carousel',
        'category' => 'educational',
        'name' => 'Glossary carousel',
        'description' => 'Define five terms from your industry in plain language.',
        'content' => '5 [industry] terms explained without the jargon. Save this for later.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'jargon, decoded', 'body' => 'Five [industry] words people use as if everyone already knows them.', 'image_keywords' => ['dictionary', 'book']],
            ['title' => '[term 1]', 'body' => '[Plain definition. One example sentence.]', 'image_keywords' => ['letters', 'text']],
            ['title' => '[term 2]', 'body' => '[Plain definition. One example sentence.]', 'image_keywords' => ['letters', 'paper']],
            ['title' => '[term 3]', 'body' => '[Plain definition. One example sentence.]', 'image_keywords' => ['note', 'pen']],
            ['title' => '[term 4]', 'body' => '[Plain definition. One example sentence.]', 'image_keywords' => ['definition', 'page']],
            ['title' => '[term 5]', 'body' => '[Plain definition. One example sentence.]', 'image_keywords' => ['glossary', 'open book']],
        ],
    ],
    [
        'slug' => 'step_by_step_tutorial_carousel',
        'category' => 'educational',
        'name' => 'Step by step tutorial',
        'description' => 'Walk through a small how-to in clear steps.',
        'content' => 'How to [task] in [number] steps. Save it so you have it next time.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'what you need', 'body' => '[List the tools or supplies. Keep it short.]', 'image_keywords' => ['tools', 'supplies']],
            ['title' => 'step 1', 'body' => '[First step. Specific action, not a goal.]', 'image_keywords' => ['hands', 'work']],
            ['title' => 'step 2', 'body' => '[Second step. What it should look like before moving on.]', 'image_keywords' => ['progress', 'desk']],
            ['title' => 'step 3', 'body' => '[Third step. Mention the most common slip-up here.]', 'image_keywords' => ['focus', 'detail']],
            ['title' => 'done', 'body' => '[What the finished result should look like. One photo idea.]', 'image_keywords' => ['finished', 'result']],
        ],
    ],
    [
        'slug' => 'team_intro_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Meet the team',
        'description' => 'Introduce team members one slide at a time.',
        'content' => 'The faces behind {{brand_name}}. Swipe to meet the people who make it work.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'the team', 'body' => "We're [number] people across [locations]. Here's who does what.", 'image_keywords' => ['team', 'office']],
            ['title' => '[name 1]', 'body' => '[Role. One thing they own and one thing they like outside work.]', 'image_keywords' => ['portrait', 'work']],
            ['title' => '[name 2]', 'body' => '[Role. One detail that shows their personality, not just their job title.]', 'image_keywords' => ['portrait', 'desk']],
            ['title' => '[name 3]', 'body' => '[Role. Something specific they did this month.]', 'image_keywords' => ['portrait', 'studio']],
            ['title' => 'say hi', 'body' => 'DMs are open. We answer them ourselves.', 'image_keywords' => ['phone', 'chat']],
        ],
    ],
    [
        'slug' => 'workspace_tour_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Workspace tour',
        'description' => 'Tour your studio, kitchen, or office across slides.',
        'content' => 'A tour of where {{brand_name}} actually gets made. Less polished than you think.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'where it happens', 'body' => '[Location, size, what kind of space it is in one sentence.]', 'image_keywords' => ['studio', 'workshop']],
            ['title' => 'the workbench', 'body' => '[What lives on the main bench or desk most days.]', 'image_keywords' => ['workbench', 'tools']],
            ['title' => 'the corner nobody sees', 'body' => '[Honest detail: a messy shelf, a wall of sticky notes, the coffee station.]', 'image_keywords' => ['corner', 'mess']],
            ['title' => 'the favorite spot', 'body' => '[The chair, the window, the light that makes the day better.]', 'image_keywords' => ['light', 'window']],
            ['title' => 'come back soon', 'body' => 'More peeks coming. Follow {{brand_name}} for the next one.', 'image_keywords' => ['camera', 'door']],
        ],
    ],
    [
        'slug' => 'a_day_in_the_life_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'A day in the life',
        'description' => 'Show one workday from morning to evening.',
        'content' => 'A real day at {{brand_name}}, hour by hour. Not the highlight reel.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => '7:30am', 'body' => '[How the day actually starts. Coffee, walk, inbox, whatever it is.]', 'image_keywords' => ['morning', 'coffee']],
            ['title' => '9:00am', 'body' => '[First thing on the work calendar. Be specific about what gets done.]', 'image_keywords' => ['desk', 'laptop']],
            ['title' => '12:30pm', 'body' => '[Lunch. Where, with who, or alone with a podcast.]', 'image_keywords' => ['lunch', 'food']],
            ['title' => '2:00pm', 'body' => '[Afternoon block. The thing that takes the most focus that day.]', 'image_keywords' => ['focus', 'work']],
            ['title' => '5:30pm', 'body' => '[Wrapping up. What the last task usually is before signing off.]', 'image_keywords' => ['evening', 'office']],
            ['title' => 'after hours', 'body' => '[How the day ends. Run, dinner, kids, reading, whatever is true.]', 'image_keywords' => ['sunset', 'home']],
        ],
    ],
    [
        'slug' => 'mistakes_we_made_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Mistakes we made',
        'description' => 'Share three real mistakes and what you learned.',
        'content' => '3 things we got wrong this year at {{brand_name}}. Sharing because hiding it would feel weird.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'why post this', 'body' => 'Wins get plenty of attention. The misses are usually where the lessons live.', 'image_keywords' => ['notebook', 'writing']],
            ['title' => 'mistake 1', 'body' => '[What we tried. Why it did not work. What we did next.]', 'image_keywords' => ['error', 'desk']],
            ['title' => 'mistake 2', 'body' => '[The second one. Be honest about the cost, in money or time.]', 'image_keywords' => ['budget', 'paper']],
            ['title' => "mistake 3 + what's next", 'body' => '[Third mistake and one thing changing because of it.]', 'image_keywords' => ['plan', 'reset']],
        ],
    ],
    [
        'slug' => 'customer_story_carousel',
        'category' => 'testimonial',
        'name' => 'Customer story',
        'description' => 'Tell a single customer story across the slides.',
        'content' => "A story from one of {{brand_name}}'s customers. Posted with their permission.",
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'meet [name]', 'body' => '[Name, what they do, where they are. Two short sentences.]', 'image_keywords' => ['portrait', 'person']],
            ['title' => 'the problem', 'body' => '[The situation before they used {{brand_name}}. Specific, not abstract.]', 'image_keywords' => ['problem', 'thinking']],
            ['title' => 'what they tried', 'body' => '[How they found {{brand_name}} and what their first use looked like.]', 'image_keywords' => ['discover', 'try']],
            ['title' => 'what changed', 'body' => '[The result. A number if you have one, a story if you do not.]', 'image_keywords' => ['result', 'change']],
            ['title' => 'in their words', 'body' => '"[Direct quote from the customer. Short and real.]"', 'image_keywords' => ['quote', 'speech']],
        ],
    ],
    [
        'slug' => 'three_reviews_carousel',
        'category' => 'testimonial',
        'name' => 'Three reviews carousel',
        'description' => 'Pull three real reviews into a swipeable post.',
        'content' => 'Three reviews from real customers this month at {{brand_name}}.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'what people are saying', 'body' => 'Three unedited quotes from this month. Full names withheld where requested.', 'image_keywords' => ['stars', 'review']],
            ['title' => 'review 1', 'body' => '"[Direct customer quote.]", [first name, location]', 'image_keywords' => ['speech', 'quote']],
            ['title' => 'review 2', 'body' => '"[Direct customer quote.]", [first name, location]', 'image_keywords' => ['feedback', 'note']],
            ['title' => 'review 3', 'body' => '"[Direct customer quote.]", [first name, location]', 'image_keywords' => ['testimonial', 'paper']],
        ],
    ],
    [
        'slug' => 'before_after_results_carousel',
        'category' => 'testimonial',
        'name' => 'Before and after results',
        'description' => 'Show a customer outcome in before and after slides.',
        'content' => 'A real result from a customer using [product/service] at {{brand_name}}. Same person, [time period] apart.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'the starting point', 'body' => '[Where they were when they started. The honest version, not the shiny one.]', 'image_keywords' => ['before', 'start']],
            ['title' => 'what they did', 'body' => '[What they used and how often. Be specific about the routine.]', 'image_keywords' => ['process', 'routine']],
            ['title' => 'the result', 'body' => '[Where they are now. Numbers if relevant, photo if visual.]', 'image_keywords' => ['after', 'result']],
            ['title' => 'in their words', 'body' => '"[A short quote on what surprised them most.]"', 'image_keywords' => ['quote', 'smile']],
        ],
    ],
    [
        'slug' => 'industry_myth_busting_carousel',
        'category' => 'industry_tip',
        'name' => 'Industry myth busting',
        'description' => 'Bust three myths about your industry.',
        'content' => '3 things people still believe about [industry] that are not true.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'myths, picked apart', 'body' => 'Three [industry] beliefs that get repeated everywhere and still miss the mark.', 'image_keywords' => ['question', 'thinking']],
            ['title' => 'myth 1', 'body' => 'Myth: [common belief]. Truth: [what is actually the case, with one detail].', 'image_keywords' => ['truth', 'note']],
            ['title' => 'myth 2', 'body' => 'Myth: [common belief]. Truth: [the correction in one sentence].', 'image_keywords' => ['fact', 'paper']],
            ['title' => 'myth 3', 'body' => 'Myth: [common belief]. Truth: [the correction]. The why is in the comments.', 'image_keywords' => ['comment', 'phone']],
        ],
    ],
    [
        'slug' => 'industry_trend_carousel',
        'category' => 'industry_tip',
        'name' => 'Industry trend carousel',
        'description' => 'Walk through a trend shaping the industry this year.',
        'content' => "What's actually moving in [industry] this year, in plain language.",
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'the trend', 'body' => '[Name the trend in plain words. One sentence on what it is.]', 'image_keywords' => ['trend', 'graph']],
            ['title' => 'why now', 'body' => '[The specific cause. A regulation, a tech shift, a behavior change.]', 'image_keywords' => ['cause', 'news']],
            ['title' => 'who it hits first', 'body' => '[The audience or company type that feels it before everyone else.]', 'image_keywords' => ['audience', 'people']],
            ['title' => 'what to do', 'body' => '[One concrete thing to try this quarter, not a vague principle.]', 'image_keywords' => ['action', 'plan']],
            ['title' => 'one number to watch', 'body' => '[A specific metric, with a source.]', 'image_keywords' => ['metric', 'data']],
        ],
    ],
    [
        'slug' => 'pro_tip_carousel',
        'category' => 'industry_tip',
        'name' => 'Pro tip carousel',
        'description' => 'Share a single deep pro tip with context and steps.',
        'content' => "One thing I'd tell my younger self about [topic]. Save this if it helps.",
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'the tip', 'body' => '[The one-line version. Short enough to remember.]', 'image_keywords' => ['tip', 'note']],
            ['title' => 'why it works', 'body' => '[The reason. Use a small example, not a big claim.]', 'image_keywords' => ['idea', 'thought']],
            ['title' => 'how to use it', 'body' => '[The steps. Three at most. Specific.]', 'image_keywords' => ['steps', 'list']],
            ['title' => 'one thing to avoid', 'body' => '[The one mistake people make when applying this tip.]', 'image_keywords' => ['warning', 'caution']],
        ],
    ],
    [
        'slug' => 'event_announcement_carousel',
        'category' => 'event',
        'name' => 'Event announcement',
        'description' => 'Announce an upcoming event with the key details.',
        'content' => "We're hosting [Event Name] on [date]. Everything you need to know is in the slides.",
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => '[event name]', 'body' => '[Date, location or online, who it is for in one line.]', 'image_keywords' => ['event', 'invite']],
            ['title' => "what's planned", 'body' => '[The agenda in plain bullets, not marketing speak.]', 'image_keywords' => ['agenda', 'schedule']],
            ['title' => "who's speaking", 'body' => '[Names and one-line bios. No more than three.]', 'image_keywords' => ['speakers', 'panel']],
            ['title' => 'how to join', 'body' => '[Free or paid, link, deadline if any. Be specific.]', 'image_keywords' => ['ticket', 'register']],
            ['title' => 'reserve your spot', 'body' => '[Final reminder + the link in bio call to action.]', 'image_keywords' => ['phone', 'tap']],
        ],
    ],
    [
        'slug' => 'event_speakers_carousel',
        'category' => 'event',
        'name' => 'Event speakers reveal',
        'description' => 'Reveal speakers one slide each.',
        'content' => 'Speakers for [Event Name]. Tickets are open at {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'speakers, revealed', 'body' => 'The lineup for [Event Name] on [date]. Swipe to meet them.', 'image_keywords' => ['lineup', 'stage']],
            ['title' => '[speaker 1]', 'body' => '[Name, role. The one thing they will talk about.]', 'image_keywords' => ['portrait', 'speaker']],
            ['title' => '[speaker 2]', 'body' => '[Name, role. Their session topic in one line.]', 'image_keywords' => ['portrait', 'mic']],
            ['title' => '[speaker 3]', 'body' => '[Name, role. What attendees will leave with.]', 'image_keywords' => ['portrait', 'panel']],
            ['title' => 'tickets in bio', 'body' => '[Date, location, registration link.]', 'image_keywords' => ['ticket', 'register']],
        ],
    ],
    [
        'slug' => 'workshop_invitation_carousel',
        'category' => 'event',
        'name' => 'Workshop invitation',
        'description' => 'Invite people to a hands-on workshop.',
        'content' => "Hands-on workshop at {{brand_name}} on [date]. Limited seats. Here's what's inside.",
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'workshop on [date]', 'body' => '[Topic in one line. Online or in person, with location and time.]', 'image_keywords' => ['workshop', 'class']],
            ['title' => "what you'll do", 'body' => '[Three concrete activities. Use verbs, not adjectives.]', 'image_keywords' => ['hands', 'making']],
            ['title' => "what you'll leave with", 'body' => '[The output: a finished thing, a draft, a decision, a plan.]', 'image_keywords' => ['notebook', 'result']],
            ['title' => 'reserve a seat', 'body' => '[Number of seats left, price if any, link in bio.]', 'image_keywords' => ['chair', 'register']],
        ],
    ],
    [
        'slug' => 'this_or_that_carousel',
        'category' => 'engagement',
        'name' => 'This or that',
        'description' => 'Ask followers a series of either-or questions.',
        'content' => 'This or that, [topic] edition. Tell me your picks in the comments.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'pick one', 'body' => 'Five quick choices. Comment your answers in order.', 'image_keywords' => ['choice', 'fork']],
            ['title' => '[option a] or [option b]', 'body' => '[Brief context if needed.]', 'image_keywords' => ['split', 'options']],
            ['title' => '[option c] or [option d]', 'body' => '[Brief context if needed.]', 'image_keywords' => ['versus', 'choice']],
            ['title' => '[option e] or [option f]', 'body' => '[Brief context if needed.]', 'image_keywords' => ['compare', 'pick']],
            ['title' => 'your turn', 'body' => 'Drop your answers below. I read every comment.', 'image_keywords' => ['comment', 'phone']],
        ],
    ],
    [
        'slug' => 'unpopular_opinion_carousel',
        'category' => 'engagement',
        'name' => 'Unpopular opinion',
        'description' => 'Share a real opinion and invite disagreement.',
        'content' => 'An unpopular take on [topic]. Tell me where I am wrong in the comments.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'unpopular take', 'body' => '[The opinion in one short, clear sentence.]', 'image_keywords' => ['opinion', 'speech']],
            ['title' => 'why I think this', 'body' => '[The reason. A small story or a number, not just feelings.]', 'image_keywords' => ['reason', 'thinking']],
            ['title' => 'where I might be wrong', 'body' => '[Honest about the weakest part of the argument.]', 'image_keywords' => ['doubt', 'question']],
            ['title' => 'tell me', 'body' => 'Agree, disagree, mixed, drop it in the comments.', 'image_keywords' => ['comment', 'discussion']],
        ],
    ],
    [
        'slug' => 'fill_in_the_blank_carousel',
        'category' => 'engagement',
        'name' => 'Fill in the blank',
        'description' => 'Prompt followers with three blanks to complete.',
        'content' => 'Fill in the blanks. I want to read your answers.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'fill in the blanks', 'body' => 'Three quick prompts about [topic]. Comment your answers in order.', 'image_keywords' => ['blank', 'pen']],
            ['title' => 'prompt 1', 'body' => 'The best [thing] I [verb] this year was ____.', 'image_keywords' => ['idea', 'thought']],
            ['title' => 'prompt 2', 'body' => 'The thing I want to do more of in [topic] is ____.', 'image_keywords' => ['plan', 'goal']],
            ['title' => 'prompt 3', 'body' => 'One person who taught me about [topic] is ____.', 'image_keywords' => ['mentor', 'people']],
        ],
    ],
    [
        'slug' => 'q_and_a_carousel',
        'category' => 'engagement',
        'name' => 'Q and A carousel',
        'description' => 'Answer five real questions from your audience.',
        'content' => 'You asked, I answered. Five real questions from the DMs.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'questions answered', 'body' => 'Pulled five from this week. Anonymized where I needed to.', 'image_keywords' => ['questions', 'mail']],
            ['title' => 'q1', 'body' => 'Q: [paraphrased question]. A: [answer in one or two sentences].', 'image_keywords' => ['answer', 'note']],
            ['title' => 'q2', 'body' => 'Q: [paraphrased question]. A: [answer].', 'image_keywords' => ['reply', 'speech']],
            ['title' => 'q3', 'body' => 'Q: [paraphrased question]. A: [answer].', 'image_keywords' => ['question', 'mark']],
            ['title' => 'q4', 'body' => 'Q: [paraphrased question]. A: [answer].', 'image_keywords' => ['chat', 'bubble']],
            ['title' => 'q5', 'body' => 'Q: [paraphrased question]. A: [answer]. Drop more in the comments.', 'image_keywords' => ['comments', 'phone']],
        ],
    ],
];
