<?php

declare(strict_types=1);

return [
    [
        'slug' => 'story_announcement',
        'category' => 'product_launch',
        'name' => 'Quick announcement',
        'description' => 'Drive attention to a new launch or update with a 24-hour story.',
        'content' => "Big news at {{brand_name}}.\n\nTap the link to see what's new.",
        'image_count' => 1,
        'image_keywords' => ['announcement', 'launch'],
        'slides' => null,
    ],
    [
        'slug' => 'story_poll_question',
        'category' => 'engagement',
        'name' => 'Poll question',
        'description' => 'Use a story to ask a quick question and engage your audience.',
        'content' => "What matters most when you pick a [product/service]?\n\nTap to vote.",
        'image_count' => 1,
        'image_keywords' => ['question', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'story_flash_promo',
        'category' => 'promotion',
        'name' => 'Flash promo',
        'description' => 'Limited-time offer in story format with urgency.',
        'content' => "24 hours only.\n\n[Discount]% off at {{brand_name}}.\n\nSwipe up.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'urgency'],
        'slides' => null,
    ],

    // product_launch
    [
        'slug' => 'story_product_drop',
        'category' => 'product_launch',
        'name' => 'New product drop',
        'description' => 'Announce a new product going live today.',
        'content' => "It's live.\n\n[Product name] just dropped.\n\nLink in bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'new'],
        'slides' => null,
    ],
    [
        'slug' => 'story_feature_shipped',
        'category' => 'product_launch',
        'name' => 'Feature shipped',
        'description' => 'Tell followers about a new feature you just released.',
        'content' => "We just shipped [feature].\n\nGo try it.",
        'image_count' => 1,
        'image_keywords' => ['update', 'feature', 'app'],
        'slides' => null,
    ],
    [
        'slug' => 'story_waitlist_open',
        'category' => 'product_launch',
        'name' => 'Waitlist open',
        'description' => 'Invite followers to join a waitlist.',
        'content' => "Waitlist is open.\n\n[Spots] spots left.\n\nLink in bio.",
        'image_count' => 1,
        'image_keywords' => ['waitlist', 'signup'],
        'slides' => null,
    ],
    [
        'slug' => 'story_preorder_live',
        'category' => 'product_launch',
        'name' => 'Pre-order live',
        'description' => 'Drive pre-orders for an upcoming product.',
        'content' => "Pre-orders are open.\n\nShips [date].\n\nTap to claim yours.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product'],
        'slides' => null,
    ],

    // promotion
    [
        'slug' => 'story_weekend_sale',
        'category' => 'promotion',
        'name' => 'Weekend sale',
        'description' => 'Push a quick weekend sale.',
        'content' => "Weekend sale.\n\n[Discount]% off everything.\n\nEnds Sunday.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'weekend', 'discount'],
        'slides' => null,
    ],
    [
        'slug' => 'story_code_drop',
        'category' => 'promotion',
        'name' => 'Discount code drop',
        'description' => 'Share a code your followers can use at checkout.',
        'content' => "Use [CODE] at checkout.\n\n[Discount]% off.\n\nGood until [date].",
        'image_count' => 1,
        'image_keywords' => ['coupon', 'code', 'discount'],
        'slides' => null,
    ],
    [
        'slug' => 'story_last_chance',
        'category' => 'promotion',
        'name' => 'Last chance',
        'description' => 'Final reminder before a sale ends.',
        'content' => "Last chance.\n\n[Offer] ends at midnight.",
        'image_count' => 1,
        'image_keywords' => ['deadline', 'sale', 'urgent'],
        'slides' => null,
    ],
    [
        'slug' => 'story_bundle_deal',
        'category' => 'promotion',
        'name' => 'Bundle deal',
        'description' => 'Promote a bundle at a lower price.',
        'content' => "Bundle deal.\n\n[Item A] + [Item B] for [price].\n\nTap to grab it.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'deal', 'product'],
        'slides' => null,
    ],

    // educational
    [
        'slug' => 'story_quick_tip',
        'category' => 'educational',
        'name' => 'Quick tip',
        'description' => 'Share one short tip on the screen.',
        'content' => "Quick tip:\n\n[One short actionable tip].",
        'image_count' => 1,
        'image_keywords' => ['tip', 'advice', 'learning'],
        'slides' => null,
    ],
    [
        'slug' => 'story_did_you_know',
        'category' => 'educational',
        'name' => 'Did you know',
        'description' => 'Surface a surprising fact.',
        'content' => "Did you know?\n\n[Surprising fact about your niche].",
        'image_count' => 1,
        'image_keywords' => ['fact', 'knowledge'],
        'slides' => null,
    ],
    [
        'slug' => 'story_common_mistake',
        'category' => 'educational',
        'name' => 'Common mistake',
        'description' => 'Call out a mistake your audience tends to make.',
        'content' => "Stop doing [common mistake].\n\nDo [better approach] instead.",
        'image_count' => 1,
        'image_keywords' => ['mistake', 'advice', 'tip'],
        'slides' => null,
    ],
    [
        'slug' => 'story_one_word_lesson',
        'category' => 'educational',
        'name' => 'One-word lesson',
        'description' => 'A single word followed by a short why.',
        'content' => "[One word].\n\nThat's the difference between [outcome A] and [outcome B].",
        'image_count' => 1,
        'image_keywords' => ['lesson', 'word', 'idea'],
        'slides' => null,
    ],

    // behind_the_scenes
    [
        'slug' => 'story_workspace_peek',
        'category' => 'behind_the_scenes',
        'name' => 'Workspace peek',
        'description' => 'Quick shot of where the work happens.',
        'content' => "Where the work happens.\n\n[Short caption about your space].",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'desk', 'office'],
        'slides' => null,
    ],
    [
        'slug' => 'story_meet_the_team',
        'category' => 'behind_the_scenes',
        'name' => 'Meet the team',
        'description' => 'Introduce a team member with one line.',
        'content' => "Meet [name].\n\n[Their role at {{brand_name}}].",
        'image_count' => 1,
        'image_keywords' => ['team', 'people', 'portrait'],
        'slides' => null,
    ],
    [
        'slug' => 'story_in_progress',
        'category' => 'behind_the_scenes',
        'name' => 'In progress',
        'description' => 'Show something half-done.',
        'content' => "In progress.\n\n[What you are working on right now].",
        'image_count' => 1,
        'image_keywords' => ['process', 'work', 'progress'],
        'slides' => null,
    ],
    [
        'slug' => 'story_packing_orders',
        'category' => 'behind_the_scenes',
        'name' => 'Packing orders',
        'description' => 'Show orders going out the door.',
        'content' => "Today's orders.\n\nThank you for trusting {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['packaging', 'orders', 'shipping'],
        'slides' => null,
    ],

    // testimonial
    [
        'slug' => 'story_customer_quote',
        'category' => 'testimonial',
        'name' => 'Customer quote',
        'description' => 'Share a short customer quote on screen.',
        'content' => "\"[Short customer quote].\"\n\n- [Customer name]",
        'image_count' => 1,
        'image_keywords' => ['testimonial', 'review', 'quote'],
        'slides' => null,
    ],
    [
        'slug' => 'story_review_screenshot',
        'category' => 'testimonial',
        'name' => 'Review screenshot',
        'description' => 'Repost a glowing review screenshot.',
        'content' => "Reviews like this make our week.\n\nThank you, [customer first name].",
        'image_count' => 1,
        'image_keywords' => ['review', 'screenshot', 'feedback'],
        'slides' => null,
    ],
    [
        'slug' => 'story_before_after_user',
        'category' => 'testimonial',
        'name' => 'Customer before/after',
        'description' => 'Highlight a customer result.',
        'content' => '[Customer first name] went from [before] to [after] in [time].',
        'image_count' => 1,
        'image_keywords' => ['result', 'transformation', 'customer'],
        'slides' => null,
    ],

    // industry_tip
    [
        'slug' => 'story_industry_myth',
        'category' => 'industry_tip',
        'name' => 'Industry myth',
        'description' => 'Debunk a common belief in your space.',
        'content' => "Myth: [common belief].\n\nReality: [the truth].",
        'image_count' => 1,
        'image_keywords' => ['myth', 'industry', 'truth'],
        'slides' => null,
    ],
    [
        'slug' => 'story_industry_stat',
        'category' => 'industry_tip',
        'name' => 'Industry stat',
        'description' => 'Drop a single stat that grabs attention.',
        'content' => "[Stat].\n\nThat's why we built {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['statistic', 'data', 'industry'],
        'slides' => null,
    ],
    [
        'slug' => 'story_tool_we_use',
        'category' => 'industry_tip',
        'name' => 'Tool we use',
        'description' => 'Recommend a tool your audience can try.',
        'content' => "Tool we use every day:\n\n[Tool name].\n\nHere's why: [one short reason].",
        'image_count' => 1,
        'image_keywords' => ['tool', 'software', 'recommendation'],
        'slides' => null,
    ],
    [
        'slug' => 'story_red_flag',
        'category' => 'industry_tip',
        'name' => 'Red flag',
        'description' => 'Warn followers about a red flag in your industry.',
        'content' => "Red flag in [industry]:\n\n[The warning sign to watch for].",
        'image_count' => 1,
        'image_keywords' => ['warning', 'industry', 'advice'],
        'slides' => null,
    ],

    // event
    [
        'slug' => 'story_event_today',
        'category' => 'event',
        'name' => 'Event today',
        'description' => 'Last-minute reminder for a same-day event.',
        'content' => "Tonight.\n\n[Event name] at [time].\n\nTap for the link.",
        'image_count' => 1,
        'image_keywords' => ['event', 'reminder'],
        'slides' => null,
    ],
    [
        'slug' => 'story_event_countdown',
        'category' => 'event',
        'name' => 'Event countdown',
        'description' => 'Build anticipation with a countdown.',
        'content' => "[X] days until [event name].\n\nReply GO to get the reminder.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'story_live_now',
        'category' => 'event',
        'name' => 'Live now',
        'description' => 'Tell followers you are live or onstage.',
        'content' => "Live now.\n\n[Topic or location].\n\nCome say hi.",
        'image_count' => 1,
        'image_keywords' => ['live', 'streaming', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'story_event_recap',
        'category' => 'event',
        'name' => 'Event recap',
        'description' => 'Quick recap after the event ends.',
        'content' => "[Event name] is a wrap.\n\nThank you to everyone who showed up.",
        'image_count' => 1,
        'image_keywords' => ['event', 'recap', 'crowd'],
        'slides' => null,
    ],

    // engagement
    [
        'slug' => 'story_this_or_that',
        'category' => 'engagement',
        'name' => 'This or that',
        'description' => 'Two-option poll for fast taps.',
        'content' => "[Option A] or [Option B]?\n\nTap to vote.",
        'image_count' => 1,
        'image_keywords' => ['poll', 'choice', 'vote'],
        'slides' => null,
    ],
    [
        'slug' => 'story_question_box',
        'category' => 'engagement',
        'name' => 'Question box',
        'description' => 'Open the floor for questions.',
        'content' => "Ask me anything about [topic].\n\nReply with your question.",
        'image_count' => 1,
        'image_keywords' => ['questions', 'ama', 'conversation'],
        'slides' => null,
    ],
    [
        'slug' => 'story_emoji_slider',
        'category' => 'engagement',
        'name' => 'Emoji slider',
        'description' => 'Use the slider sticker to gauge a feeling.',
        'content' => "How excited are you for [thing]?\n\nMove the slider.",
        'image_count' => 1,
        'image_keywords' => ['slider', 'reaction', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'story_dm_prompt',
        'category' => 'engagement',
        'name' => 'DM prompt',
        'description' => 'Push followers to send a DM keyword.',
        'content' => "Want [resource]?\n\nReply [keyword] and I'll send it.",
        'image_count' => 1,
        'image_keywords' => ['dm', 'message', 'engagement'],
        'slides' => null,
    ],
];
