<?php

declare(strict_types=1);

return [
    [
        'slug' => 'product_launch_announcement',
        'category' => 'product_launch',
        'name' => 'Product launch announcement',
        'description' => 'Short LinkedIn post announcing a new product.',
        'content' => "Excited to share: {{brand_name}} just launched [Product Name].\n\nHere's why this matters for [your audience]:\n→ [Benefit 1]\n→ [Benefit 2]\n→ [Benefit 3]\n\nLearn more at [link]. We'd love your feedback.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'how_to_guide',
        'category' => 'educational',
        'name' => 'How-to guide',
        'description' => 'Step-by-step educational post for LinkedIn.',
        'content' => "How to [achieve X] in [timeframe], a step-by-step guide.\n\nStep 1: [Action]\nStep 2: [Action]\nStep 3: [Action]\nStep 4: [Action]\n\nThe key insight most people miss: [insight].\n\nWhich step do you find most challenging? Drop a comment below.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'customer_quote',
        'category' => 'testimonial',
        'name' => 'Customer quote',
        'description' => 'Share a compelling customer testimonial on LinkedIn.',
        'content' => "\"[Customer quote about the result they achieved with your product or service.]\"\n- [Customer Name], [Role] at [Company]\n\nThis is exactly why we built {{brand_name}}. Real results for real teams.\n\nRead the full story → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'industry_insight',
        'category' => 'industry_tip',
        'name' => 'Industry insight',
        'description' => 'Share a timely insight or hot take relevant to your industry.',
        'content' => "Here's something most people in [industry] get wrong:\n\n[Counterintuitive statement or hot take]\n\nWhy? Because [reason].\n\nThe smarter approach: [better way to do it].\n\nAt {{brand_name}}, we've seen this play out with hundreds of [customers/teams]. The data is clear.\n\nWhat's your take?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_announcement',
        'category' => 'event',
        'name' => 'Event announcement',
        'description' => 'Announce an upcoming webinar or live event.',
        'content' => "📅 Save the date: {{brand_name}} is hosting [Event Name] on [Date] at [Time].\n\nWhat to expect:\n✔ [Topic 1]\n✔ [Topic 2]\n✔ [Topic 3]\n\nSpots are limited. Register now → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'community_question',
        'category' => 'engagement',
        'name' => 'Community question',
        'description' => 'Spark discussion with an open-ended question to your network.',
        'content' => "If you could give one piece of advice to someone just starting out in [industry/role], what would it be?\n\nMine: [your answer, be honest and specific]\n\nDrop yours in the comments. Let's build a thread worth bookmarking.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Product launch (3) =====
    [
        'slug' => 'feature_release_notes',
        'category' => 'product_launch',
        'name' => 'New feature release notes',
        'description' => 'Walk your network through what shipped and why it matters.',
        'content' => "We shipped [Feature Name] today.\n\nThe short version: it does [what it does] for [who it's for]. Took us [timeframe] from first sketch to production.\n\nWhat's actually new:\n• [Capability one, in plain language]\n• [Capability two, with a real example]\n• [The thing we cut, and why]\n\nWe debated [tradeoff] for weeks. Ended up choosing [decision] because [reason]. If you'd have made the other call, I want to hear why.\n\nDocs and a 4-minute walkthrough are at [link]. Bug reports welcome, we read every one.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'beta_invitation',
        'category' => 'product_launch',
        'name' => 'Private beta invitation',
        'description' => 'Invite your network into a closed beta with clear expectations.',
        'content' => "We're opening up [Product/Feature] to a small private beta. Looking for around [N] testers.\n\nThe ideal fit:\n• You work in [role/industry]\n• You currently use [tool or workflow] and find [specific friction]\n• You have 30 minutes a week to break things and tell us about it\n\nWhat you get: early access, a direct line to the {{brand_name}} team, and a say in what we build next. What we get: honest feedback, even when it stings.\n\nIf this sounds like you, drop a comment or DM me. We'll send invites this [day/week].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'milestone_update',
        'category' => 'product_launch',
        'name' => 'Product milestone update',
        'description' => 'Share a meaningful product or company milestone with concrete numbers.',
        'content' => "Quiet milestone we hit this week: {{brand_name}} crossed [number / metric].\n\nFor context, when we started [timeframe] ago we had [starting number]. Most of the growth came from [specific channel or driver], not the thing we expected.\n\nA few things I learned along the way:\n1. [Lesson one, with the receipts]\n2. [Lesson two, what we'd do differently]\n3. [Lesson three about the team]\n\nThank you to the [N] people who took a chance on us when this was rough around the edges. Onward.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Promotion (3) =====
    [
        'slug' => 'limited_time_offer',
        'category' => 'promotion',
        'name' => 'Limited-time offer',
        'description' => 'Promote a time-bound discount or deal in a non-spammy way.',
        'content' => "Running a [discount %] promo on {{brand_name}} until [date].\n\nNot a Black Friday gimmick. We had a slow [month/quarter] and want to bring in [N] new [users/customers] before [end of period]. That's the honest reason.\n\nIf you've been on the fence: [link]. If you signed up in the last 30 days, email me and I'll apply the same discount retroactively. That's the right thing to do.\n\nOffer ends [date] at [time, timezone].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'free_resource_offer',
        'category' => 'promotion',
        'name' => 'Free resource giveaway',
        'description' => 'Offer a useful free download or template as a low-friction lead magnet.',
        'content' => "Spent the weekend turning our internal [resource type, checklist, template, playbook] into something I can share.\n\nIt's the same [document] our team uses to [specific use case]. Nothing fancy: [N] pages, no fluff, no email gate.\n\nDrop a comment with the word \"[keyword]\" and I'll DM you the link. If you'd rather grab it directly: [link].\n\nFair warning, it's opinionated. If you disagree with my take on [specific point], tell me. That's how I improve it for v2.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'partnership_announcement',
        'category' => 'promotion',
        'name' => 'Partnership announcement',
        'description' => 'Announce a partnership or integration with a clear customer benefit.',
        'content' => "{{brand_name}} is now integrated with [Partner Name].\n\nThe practical effect for [audience]: you can now [specific workflow or capability] without [the previous workaround]. Saves about [time/money figure] per [period] based on the early test group.\n\nWe picked [Partner] because their team obsesses over [shared value] the same way ours does. Not every integration request makes the cut, and most don't.\n\nSetup takes about [N] minutes. Walkthrough here: [link]. If you're already using both tools, we'd love to hear how it lands.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Educational (3) =====
    [
        'slug' => 'lesson_learned',
        'category' => 'educational',
        'name' => 'Lesson from a mistake',
        'description' => 'Teach by recounting a specific mistake and what changed because of it.',
        'content' => "Made a [N]-figure mistake last [year/quarter] that I want to write about while it still stings.\n\nThe setup: we were [situation]. The decision: [what you did]. The reasoning at the time: [why it seemed right].\n\nWhat actually happened: [the result, in concrete terms]. We lost [specific cost, money, time, customers, trust].\n\nWhat I should have done: [the better path], and the reason I didn't is [the honest reason, ego, hurry, missing data].\n\nThree things I changed in how I work because of it:\n1. [Change one]\n2. [Change two]\n3. [Change three]\n\nIf you've been there, you know. Tell me about yours in the comments.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'framework_breakdown',
        'category' => 'educational',
        'name' => 'Framework or mental model breakdown',
        'description' => 'Explain a specific framework or mental model with a concrete example.',
        'content' => "I keep coming back to one mental model when I think about [topic/problem]: [Framework Name].\n\nThe idea is simple. [One-sentence summary of the framework.]\n\nHow I actually use it: when I'm stuck on [specific situation], I ask [specific question the framework prompts]. Last week it pushed me to [decision you made because of it].\n\nWhere it breaks: [honest limitation]. It's not a universal answer for [type of problem], and treating it like one is how people end up [bad outcome].\n\nIf you want to read the original source, it's [author/book/link]. The version above is mine, with edits from a few hundred uses.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'tool_comparison',
        'category' => 'educational',
        'name' => 'Honest tool comparison',
        'description' => 'Compare two or three tools or approaches with real tradeoffs.',
        'content' => "I've used [Tool A], [Tool B], and [Tool C] for [task] over the past [timeframe]. Here's where each one actually wins.\n\n[Tool A] is the right call when [specific situation]. It's the fastest at [specific task] and the worst at [specific task]. We use it for [use case].\n\n[Tool B] feels less polished, but it does [thing] better than anything else I've tried. Worth the rough edges if [criteria].\n\n[Tool C] is the boring choice. That's a compliment. It's reliable, the docs are written by humans, and the team doesn't ship breaking changes on Fridays.\n\nMy current stack at {{brand_name}}: [actual answer]. Yours might differ if [reason].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Behind the scenes (3) =====
    [
        'slug' => 'team_culture_glimpse',
        'category' => 'behind_the_scenes',
        'name' => 'Team culture moment',
        'description' => 'Share a small, specific moment that shows how your team actually works.',
        'content' => "Small thing that happened at {{brand_name}} this week.\n\n[Team member or role] noticed [specific issue or detail]. Could have shipped anyway. Instead they [specific action], which delayed [thing] by [timeframe].\n\nNobody asked them to. There was no Jira ticket. The customer would not have known.\n\nThis is the part of building a company that doesn't fit on a careers page. The work that nobody sees, done well anyway, because that's how the people here are wired. I think about it a lot.\n\nIf you want to work with people like this: [link]. If you already do, send them a DM.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'how_we_built_it',
        'category' => 'behind_the_scenes',
        'name' => 'How we built it',
        'description' => 'Walk through the real story behind a recent build, including dead ends.',
        'content' => "How we built [Feature/Product] at {{brand_name}}, including the parts we usually leave out.\n\nWe started with [original plan]. It took [timeframe] to figure out that plan was wrong. The real problem was [actual problem], which only became visible after [trigger event].\n\nVersion 2 was [what we tried next]. It worked in the demo and fell over in production at [scale or condition]. We rewrote the [specific component] twice.\n\nWhat finally shipped: [current solution]. It is [specific tradeoff acknowledgment, slower, simpler, less elegant] than what we set out to build, and it's the version that actually solves the customer problem.\n\nFull writeup with the architecture diagrams: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'day_in_the_life',
        'category' => 'behind_the_scenes',
        'name' => 'A day on the team',
        'description' => 'Show what a real day looks like for someone on the team.',
        'content' => "Pulled the calendar for [day of week] and counted: [N] meetings, [N] hours of focused work, [N] interruptions I should have said no to.\n\nThe work that actually mattered:\n• [Specific task one, and why it mattered]\n• [Specific task two, including what surprised you]\n• [Specific task three]\n\nThe work that felt urgent and wasn't: [honest example]. I keep falling for this and I'm tired of it.\n\nI used to think the goal was a perfect day. Now I think the goal is a few real hours and the discipline to protect them. Curious how the rest of you handle [specific challenge from the post].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Testimonial (3) =====
    [
        'slug' => 'before_after_story',
        'category' => 'testimonial',
        'name' => 'Customer before-and-after',
        'description' => 'Tell a customer story with concrete numbers from before and after.',
        'content' => "Quick story from a {{brand_name}} customer worth sharing.\n\n[Customer/Company] came to us [timeframe] ago. The state of things then: [specific painful metric, hours per week, error rate, churn, cost]. They had tried [previous approach] and it didn't move the number.\n\n[Timeframe] in, the same metric is [new number]. The piece that mattered most, according to [Name, role]: [specific change in how they work].\n\nWhat I like about this one: it wasn't a magic feature. It was [boring fundamental, a process change, a default they flipped, a meeting they killed]. Most wins look like that and we don't talk about it enough.\n\nFull case study with the messy details: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'unsolicited_review',
        'category' => 'testimonial',
        'name' => 'Unsolicited customer review',
        'description' => 'Share an organic piece of customer feedback with a thoughtful reaction.',
        'content' => "Got this in our inbox yesterday from [Customer Name] at [Company]:\n\n\"[Honest, specific quote, including any small criticism or tradeoff they mentioned. Real reviews aren't pure praise.]\"\n\nA few honest reactions on my end. The part about [specific praise] is the thing we've worked hardest on, so that one hit. The part about [specific gripe or wish] is fair, and it's already on the roadmap for [timeframe].\n\nWe don't pay for reviews and we don't ask for them. When one shows up like this, I read it twice. Thank you, [Name].\n\nIf you have a {{brand_name}} story, good, bad, or mixed, I want to hear it.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'team_member_spotlight',
        'category' => 'testimonial',
        'name' => 'Team member spotlight',
        'description' => 'Highlight a specific person on the team with a concrete contribution.',
        'content' => "Want to talk about [Name], [role] at {{brand_name}}, for a minute.\n\n[Name] joined [timeframe] ago. The thing they own now: [specific area or system]. The thing they did that very few people would have done: [specific story, a tough call, an unglamorous fix, a tradeoff they pushed back on].\n\nThe result: [concrete outcome, with a number if you have one]. The reason it worked: [Name]'s instinct on [specific quality], which I'm still learning from.\n\nThis is not a humble brag. It's a thank-you, on a public platform, because that part of the job tends to happen quietly. [Name], the team is better with you in it.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Industry tip (3) =====
    [
        'slug' => 'data_point_take',
        'category' => 'industry_tip',
        'name' => 'Data point and what it means',
        'description' => 'Share a recent data point from a real source and your interpretation.',
        'content' => "[Source, report, study, public dataset] published this number last week: [specific stat].\n\nMost of the takes I've seen frame it as [common interpretation]. I think that misses the point.\n\nWhen you cut the same data by [dimension, segment, geography, company size, time period], the picture flips. [Specific subset] is [specific behavior], while [other subset] is [different behavior]. The headline number averages those two stories into something that describes neither.\n\nSo the practical implication for [audience]: [specific recommendation]. Not [common advice], because that one is built on the average that doesn't exist.\n\nLink to the raw data: [link]. Tell me where I'm wrong.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'contrarian_take',
        'category' => 'industry_tip',
        'name' => 'Contrarian take with receipts',
        'description' => 'Push back on a common belief in your industry with a specific argument.',
        'content' => "Unpopular opinion in [industry]: [contrarian claim].\n\nThe standard advice says [conventional wisdom]. I followed it for [timeframe] and the result was [specific bad or mediocre outcome].\n\nThe reason it doesn't work as well as people claim: [specific reason, incentive, hidden cost, survivorship bias, changed market]. The version that actually works for [audience] looks more like [alternative approach].\n\nFor what it's worth, this is the path we took at {{brand_name}} after [trigger event]. Numbers since: [specific result]. I'm not saying everyone should do it. I am saying \"because everyone says so\" is a bad reason to keep doing the thing.\n\nWhere are you on this?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'trend_watch',
        'category' => 'industry_tip',
        'name' => 'Trend worth watching',
        'description' => 'Spotlight a smaller industry trend before it goes mainstream.',
        'content' => "Quiet trend in [industry] that I think most people will be talking about in [timeframe]: [specific trend].\n\nThe signal I'm watching: [concrete evidence, hiring patterns, new entrants, pricing shifts, what customers are asking for]. Three different [companies/teams] in our network have done [specific thing] in the last [period], independently.\n\nWhy I think it actually matters and isn't just hype: [reason rooted in incentives, not vibes]. The thing that would make me wrong: [specific counter-signal you'd watch for].\n\nIf you're [audience], the practical move today is [specific action]. Not a bet-the-company pivot. Just enough that you're not caught flat-footed in [timeframe].\n\nWhat are you seeing?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Event (3) =====
    [
        'slug' => 'event_recap',
        'category' => 'event',
        'name' => 'Event recap with takeaways',
        'description' => 'Summarize an event you attended with specific takeaways.',
        'content' => "Back from [Event Name]. Three things stuck with me, and one I'm still arguing with.\n\nWhat held up: [Specific session or speaker], who made the case that [specific argument]. The part I hadn't considered: [specific insight].\n\nWhat I'm bringing back to {{brand_name}}: [concrete change you'll make based on the event]. Small enough to start next week, big enough to matter.\n\nThe thing I disagreed with: [specific take from a session]. The argument was clean, but it ignores [specific reality]. Going to write that one up properly.\n\nIf you were there, what did I miss? Always more in the hallway track than the main stage.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'speaking_announcement',
        'category' => 'event',
        'name' => 'Speaking engagement announcement',
        'description' => 'Announce that you or a teammate is speaking at an event.',
        'content' => "I'm speaking at [Event Name] on [date] in [location / online].\n\nThe talk: \"[Talk Title]\". The short pitch: [one or two sentences on what attendees will actually leave with].\n\nWhat I'm not going to do: walk through generic [topic] best practices. There are enough of those. What I am going to do: show the specific [data, framework, or case study] from {{brand_name}} that changed how we think about [specific problem], including the parts that didn't work.\n\nIf you're going to be there, find me, I'd rather have a real conversation than collect business cards. Registration: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'webinar_invitation',
        'category' => 'event',
        'name' => 'Webinar invitation',
        'description' => 'Invite your network to a webinar with a clear, honest agenda.',
        'content' => "Hosting a [length, e.g. 45-minute] webinar with [Co-host Name, role] on [date].\n\nTopic: [specific topic, framed as a question your audience is actually asking]. We're not doing a product demo. We are walking through [specific framework, dataset, or workflow] that we use at {{brand_name}}.\n\nRough agenda:\n• [Time], [Topic, with one detail that hints at the actual content]\n• [Time], [Topic]\n• [Time], Live Q&A. We answer everything, including the awkward ones.\n\nReplay goes out to everyone who registers, even if you can't make it live. Sign up: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Engagement (3) =====
    [
        'slug' => 'poll_post',
        'category' => 'engagement',
        'name' => 'Opinionated poll prompt',
        'description' => 'Ask a focused either/or question that surfaces real opinions.',
        'content' => "Curious how [audience] is splitting on this.\n\nWhen you're deciding [specific decision], do you lean toward:\n\nA) [Option A, described concretely]\nB) [Option B, described concretely]\n\nNo \"it depends\" answers in the comments, please. Pick one and tell me why in a sentence.\n\nMy answer: [your honest pick]. The reason: [one or two sentence reason from real experience]. I held the opposite view for [timeframe] before [thing that changed my mind].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'hot_take_invitation',
        'category' => 'engagement',
        'name' => 'Hot take invitation',
        'description' => 'Invite the network to share a controversial opinion in their domain.',
        'content' => "What's a [industry/role] take you hold that gets you weird looks at conferences?\n\nMine: [specific opinion that's mildly controversial in your field, stated plainly]. I've been wrong about a lot, but on this one I'm holding the line.\n\nNot looking for the safe takes that already have 500 LinkedIn carousels behind them. The ones you'd say at the dinner after the panel, when you've stopped performing.\n\nGo. I'll be in the comments arguing in good faith.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'crowdsourced_advice',
        'category' => 'engagement',
        'name' => 'Crowdsourced advice request',
        'description' => 'Ask your network for input on a real, specific problem.',
        'content' => "Asking for the crowd's brain on a real problem we're working through at {{brand_name}}.\n\nContext: [specific situation in 2-3 sentences, enough that someone qualified can actually help]. The constraint that makes the obvious answer not work: [specific constraint].\n\nWhat I've already tried: [option one, and why it didn't fit]; [option two, and what it taught me]. So I'm not looking for those.\n\nIf you've solved something close to this, what worked? Comments are best, but DMs are open if it's the kind of thing you'd rather not say in public. I'll write up what we end up doing and tag the people who shaped it.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
