<?php

declare(strict_types=1);

return [
    [
        'slug' => 'company_milestone',
        'category' => 'behind_the_scenes',
        'name' => 'Company milestone',
        'description' => 'Celebrate a company milestone from the brand page.',
        'content' => "Today {{brand_name}} hits [milestone, e.g. 1,000 customers, 5 years, \$X ARR].\n\nThis didn't happen because of any single person. It happened because [team / customers / community] showed up every day.\n\nThank you to everyone who's been part of this journey. We're just getting started.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'hiring_announcement',
        'category' => 'engagement',
        'name' => "We're hiring",
        'description' => 'Announce open roles and invite applications from the company page.',
        'content' => "{{brand_name}} is hiring.\n\nWe're looking for [role(s)] to join us on [team/mission].\n\nWhat we offer:\n→ [Highlight 1]\n→ [Highlight 2]\n→ [Highlight 3]\n\nIf this sounds like you (or someone you know), apply or share → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'thought_leadership_page',
        'category' => 'industry_tip',
        'name' => 'Industry POV',
        'description' => 'Share the company stance on an industry trend or shift.',
        'content' => "The [industry] landscape is shifting.\n\nHere's what we're seeing at {{brand_name}}:\n\n1. [Observation]\n2. [Observation]\n3. [Observation]\n\nWhat this means for [audience]: [implication].\n\nWhat are you noticing on your end?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== product_launch =====
    [
        'slug' => 'new_feature_release',
        'category' => 'product_launch',
        'name' => 'New feature release',
        'description' => 'Announce a specific new feature with the problem it solves.',
        'content' => "We shipped [feature name] today.\n\nThe short version: [one-line description of what it does].\n\nThe longer version: customers kept telling us [specific pain point]. We tried [previous workaround] for about [timeframe], and it never quite landed. So we rebuilt the [area] from scratch.\n\nA few things that changed:\n[Behavior before] is now [behavior after].\n[Manual step] runs automatically.\n[Limit] is gone.\n\nIf you want to try it, the docs are here: [link]. If you find something broken, our team is in the comments.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'beta_open_signups',
        'category' => 'product_launch',
        'name' => 'Beta open for signups',
        'description' => 'Invite customers and prospects into a public or private beta.',
        'content' => "Beta access for [product/feature] is now open.\n\nWe spent [timeframe] running it with [number] private testers. The feedback was good enough that we're widening the door.\n\nWho it's for: [specific user description, e.g. teams running >X campaigns/month].\nWho it's not for yet: [honest exclusion, e.g. enterprises needing SSO].\n\nWe're capping the next round at [number] companies so our team can stay close to every account. Spots go on a first-come basis.\n\nRequest access: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'integration_partnership',
        'category' => 'product_launch',
        'name' => 'Integration with partner',
        'description' => 'Announce a new integration or technical partnership.',
        'content' => "{{brand_name}} now connects with [partner].\n\nIf you use both, you can stop [manual step]. The integration handles [specific data flow] automatically.\n\nWhat changed for our shared customers:\nNo more exporting [data] and re-importing it on the other side.\n[Trigger] in [partner] now creates [action] in {{brand_name}}.\nField mapping is editable, so weird custom setups still work.\n\nThanks to the team at [partner] for the back-and-forth on the API. Setup guide: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'product_redesign',
        'category' => 'product_launch',
        'name' => 'Product redesign launch',
        'description' => 'Announce a significant UI or product refresh.',
        'content' => "We redesigned [product/area]. It's live for everyone today.\n\nOur design team has been quiet on here for a few months because of this. The old [area] grew organically and ended up with [specific issue, e.g. four different ways to start a new project]. Customers told us. We agreed.\n\nWhat's different:\nOne primary action per screen instead of three.\n[Old element] moved to [new location] so it stops getting in the way.\n[Specific pattern] that nobody used is gone.\n\nIf something feels off in the first few days, that's normal. Reply here or reach our team at [contact] and we'll get on it.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== promotion =====
    [
        'slug' => 'limited_time_offer',
        'category' => 'promotion',
        'name' => 'Limited-time offer',
        'description' => 'Announce a discount or pricing offer with a clear deadline.',
        'content' => "[Offer, e.g. 25% off the first year of {{brand_name}}] is open through [specific date].\n\nWe rarely run discounts. This one is tied to [reason, anniversary, end of quarter, product milestone] and we won't repeat it on the same terms in [timeframe].\n\nWho it applies to: [eligibility, new customers, annual plans, specific tier].\nWho it doesn't: [honest exclusion].\n\nUse [code] at checkout, or talk to our team if you want help picking a plan: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'free_resource_offer',
        'category' => 'promotion',
        'name' => 'Free resource giveaway',
        'description' => 'Promote a free guide, template, or report.',
        'content' => "We made a free [resource, guide, template, benchmark report] for [audience].\n\nIt covers [specific topic 1], [specific topic 2], and the [number] mistakes we see most often when working with [target customer type]. About [page count] pages, no email gate beyond a name and work address.\n\nWhy free: [honest reason, e.g. we built this for our own clients first, and it's the kind of thing that's more useful in more hands].\n\nDownload it here: [link]. Tell us what's missing and we'll update the next version.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'referral_program_launch',
        'category' => 'promotion',
        'name' => 'Referral program announcement',
        'description' => 'Promote a customer referral program from the company page.',
        'content' => "We launched a referral program for {{brand_name}} customers.\n\nIf you refer a company that becomes a paying customer, both sides get [specific benefit, e.g. one month free, \$X credit, a feature unlock]. No tiers. No leaderboard. No mug.\n\nWe spent a while resisting this because most referral programs feel like spam pyramids. We landed here because our biggest growth channel last year was customers telling other customers, and it felt strange not to share the upside.\n\nDetails and your referral link: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== educational =====
    [
        'slug' => 'how_we_solve_problem',
        'category' => 'educational',
        'name' => 'How we approach a problem',
        'description' => 'Walk through how the company tackles a recurring customer problem.',
        'content' => "A question we get every week: [specific question].\n\nHere's how we think about it at {{brand_name}}.\n\nMost teams start by [common first move]. That works until [specific failure point]. Once you hit that, you're stuck adding [workaround] every time something changes.\n\nA different way: [alternative approach]. The trade-off is [honest cost, e.g. slower setup, more upfront thinking, harder to explain to a new hire]. The upside is that [specific benefit] stops being a recurring fire.\n\nWe wrote up the long version here: [link]. Disagree? The comments are open.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'customer_data_insight',
        'category' => 'educational',
        'name' => 'Insight from customer data',
        'description' => 'Share a useful pattern observed across the customer base.',
        'content' => "We looked at [metric/behavior] across [number] {{brand_name}} accounts last quarter.\n\nOne thing stood out: [specific finding with a number, e.g. teams that did X within their first week were 3x more likely to still be active at month six].\n\nWe expected the opposite. Our hypothesis going in was [old assumption], partly because [reason]. The data didn't agree.\n\nA few caveats: this is correlation, not causation. The sample skews toward [segment]. And [time period] is short.\n\nStill, if you're new to {{brand_name}}, [practical recommendation] is probably worth doing in week one.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake_breakdown',
        'category' => 'educational',
        'name' => 'Common mistake breakdown',
        'description' => 'Explain a recurring mistake and how to avoid it.',
        'content' => "The single most common mistake we see when teams adopt [tool/process/practice]: [specific mistake].\n\nIt usually looks like this. A team starts with [setup]. Within a few weeks, they add [workaround] because [reason]. By month three, the workaround has become the system, and nobody remembers why.\n\nThe fix isn't [obvious answer]. The fix is to go back and ask whether [original assumption] was ever true for your use case. Half the time, it wasn't.\n\nWe wrote this up because we made the same mistake internally in [year]. Full breakdown: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'tool_comparison',
        'category' => 'educational',
        'name' => 'Honest tool comparison',
        'description' => 'Compare approaches or tools for a specific job, including where the company loses.',
        'content' => "When should you use {{brand_name}}, and when should you not?\n\nWe get the first half of that question constantly. Here's the second half.\n\nUse {{brand_name}} when [specific situation, e.g. you have more than X of Y, or you need Z capability].\n\nDon't use {{brand_name}} when [honest exclusion, e.g. you're a single user with fewer than X, or your workflow is fully [adjacent category]]. In those cases, [competitor or alternative approach] is genuinely a better fit, and we'll tell you that on a sales call.\n\nThe full breakdown, including a side-by-side: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== behind_the_scenes =====
    [
        'slug' => 'team_offsite_recap',
        'category' => 'behind_the_scenes',
        'name' => 'Team offsite recap',
        'description' => 'Recap a recent team offsite or all-hands.',
        'content' => "We wrapped our team offsite in [city] last week.\n\n[Number] people, [number] days, one whiteboard that took a beating. About a third of the company met in person for the first time, which is what happens when you grow [from X to Y] in a year.\n\nWe spent more time on [topic] than we planned and less on [other topic] than we expected. The hardest conversation was about [honest topic, e.g. what we stop doing in the second half of the year]. We didn't fully resolve it. That's fine.\n\nNext one is in [location] in [month]. By then we'll be [number] people. Not sure how that'll feel.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'office_or_remote_culture',
        'category' => 'behind_the_scenes',
        'name' => 'How we work',
        'description' => 'Share the company operating model or work style honestly.',
        'content' => "How {{brand_name}} actually works, since people ask.\n\nWe're [fully remote / hybrid / based in X with remote contributors] across [number] time zones. No mandatory office days. We do one all-hands a week and one async update on Fridays.\n\nThe parts we like: deep work blocks, hiring across geographies, quiet calendars.\n\nThe parts that are harder: onboarding new hires takes longer than it would in person. New ideas can stall in DMs. Time zone overlap with [region] is rough.\n\nWe're not claiming this is the right setup for every company. It's the one that fits ours right now.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'engineering_decision',
        'category' => 'behind_the_scenes',
        'name' => 'Engineering decision recap',
        'description' => 'Share an internal technical or product decision and the reasoning.',
        'content' => "Last month we [made a specific decision, e.g. moved off X, rewrote Y, killed feature Z].\n\nThe short version of why: [one-line reason].\n\nThe longer version. The old setup was fine when we had [number] customers. At [current scale], it started showing in [specific symptom]. We tried [intermediate fix] for about [timeframe] before agreeing it wasn't going to hold.\n\nThe trade-off we accepted: [honest cost, e.g. two weeks of slower releases, breaking change for some integrations].\n\nWriting this up because we wish other teams shared more of this kind of decision instead of only the wins.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mistake_postmortem',
        'category' => 'behind_the_scenes',
        'name' => 'Public postmortem',
        'description' => 'Share a recent mistake, outage, or failure honestly.',
        'content' => "On [date], {{brand_name}} had [specific issue, e.g. an outage, a billing bug, a data issue affecting X% of accounts] for about [duration].\n\nWhat happened: [one-paragraph technical or operational summary].\n\nWho was affected: [honest scope, including the customers who weren't].\n\nWhat we did: [immediate fix and mitigation].\n\nWhat we're changing so it doesn't happen the same way again: [specific change, not a generic 'we'll do better'].\n\nIf you were affected and we haven't reached out individually, please reply or email [contact]. We owe a few of you a longer conversation.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== testimonial =====
    [
        'slug' => 'customer_quote_short',
        'category' => 'testimonial',
        'name' => 'Short customer quote',
        'description' => 'Share a short, specific customer quote on the company page.',
        'content' => "From a recent conversation with [customer first name], [role] at [company]:\n\n\"[Customer quote, should reference a specific outcome, number, or change. Avoid 'great product' generic praise.]\"\n\nWe asked if we could share it. They said yes.\n\nThe context behind the quote: [one or two sentences on what they were trying to do and what changed].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'case_study_recap',
        'category' => 'testimonial',
        'name' => 'Case study recap',
        'description' => 'Summarize a published customer case study.',
        'content' => "New case study: [customer name].\n\nBefore {{brand_name}}, their team was [specific situation, e.g. running X manually, spending Y hours/week on Z]. After [timeframe] using {{brand_name}}, [specific outcome with a number].\n\nA few things they did that other customers don't always try:\n[Specific tactic from the customer].\n[Another tactic].\n[Honest note: something they're still figuring out].\n\nFull write-up with their team's actual workflow and screenshots: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'unexpected_use_case',
        'category' => 'testimonial',
        'name' => 'Unexpected customer use case',
        'description' => 'Highlight a creative or unexpected way customers use the product.',
        'content' => "We didn't build {{brand_name}} for [unexpected use case], but customers keep using it that way.\n\n[Customer or customer segment] started [specific behavior] about [timeframe] ago. We noticed because [signal, e.g. a usage spike in a specific feature, a support ticket asking for X]. When we asked them, the answer was: [paraphrased customer reasoning].\n\nIt's not on our roadmap. It might be soon. If you're doing something similar, our product team would genuinely like to hear about it. Reply here or email [contact].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== industry_tip =====
    [
        'slug' => 'contrarian_take',
        'category' => 'industry_tip',
        'name' => 'Contrarian take',
        'description' => 'Take a clear position against a popular industry idea.',
        'content' => "An opinion that gets us in trouble at conferences: [contrarian position, stated plainly].\n\nThe usual argument is [popular position]. It's not wrong in every case. It's wrong in most of the cases we see, and here's why.\n\n[Reason 1 with a specific example].\n[Reason 2 with a specific example].\n\nThe pushback we always get: [steelman the counter-argument]. That's fair, and we agree it applies when [specific condition]. Outside of that condition, the usual advice quietly costs teams a lot of money.\n\nHappy to be wrong about this. Tell us why in the comments.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'industry_benchmark',
        'category' => 'industry_tip',
        'name' => 'Industry benchmark',
        'description' => 'Share an aggregated benchmark or stat from the customer base.',
        'content' => "Quick benchmark for [audience].\n\nAcross [number] {{brand_name}} accounts in [industry/segment] last quarter, the median [metric] was [value]. The 90th percentile was [value]. The bottom 25% were under [value].\n\nIf you're below the median, the most common reason we see is [specific reason]. The fix is rarely [obvious answer]. It's usually [actual fix].\n\nIf you're above the 90th percentile, you're probably already doing [specific behavior], and we'd love to talk to you about it. Reply or DM the page.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'trend_we_disagree_with',
        'category' => 'industry_tip',
        'name' => 'Trend we disagree with',
        'description' => 'Push back on a trending industry practice with reasoning.',
        'content' => "Half the [industry] posts we see this month are about [trending practice].\n\nWe're not adopting it at {{brand_name}}, and probably won't.\n\nThe pitch is [popular framing]. The honest version, in our experience, is that it works in [narrow scenario] and quietly fails in [common scenario] because [specific reason]. We tested a version of it internally for [timeframe] and saw [specific outcome].\n\nNot saying nobody should do this. Saying that for [target audience], the time is better spent on [alternative].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'practical_framework',
        'category' => 'industry_tip',
        'name' => 'Practical framework',
        'description' => 'Share a simple internal framework or rule of thumb.',
        'content' => "A rule of thumb our team uses when deciding [specific decision]:\n\nIf [condition A], do [option 1].\nIf [condition B], do [option 2].\nIf you can't tell which you're in, you're probably in [option 1] and overthinking it.\n\nThis isn't a framework with a name. It came out of about [timeframe] of getting the same decision wrong in slightly different ways. It saves us an argument or two a week.\n\nUseful? Useless? Tell us how you decide.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== event =====
    [
        'slug' => 'event_announcement',
        'category' => 'event',
        'name' => 'Event announcement',
        'description' => 'Announce an upcoming company event, webinar, or workshop.',
        'content' => "We're hosting [event name] on [date] at [time/timezone].\n\nFormat: [virtual / in-person in city / hybrid].\nWho it's for: [specific audience, e.g. heads of marketing at B2B SaaS companies, 20-200 employees].\nWhat we'll cover: [topic 1] and [topic 2]. No keynote. No vendor parade.\n\nWe're capping registration at [number] so the Q&A actually works. If past events are a guide, the second half is where the useful stuff happens.\n\nSign up: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_recap',
        'category' => 'event',
        'name' => 'Event recap',
        'description' => 'Recap a recent event the company hosted or attended.',
        'content' => "[Event name] wrapped on [date]. A few things worth writing down before they fade.\n\nThe room got loudest during [specific moment or topic]. Our hypothesis going in was that [topic A] would dominate. It didn't. [Topic B] did, and we should have seen that coming.\n\nThe most useful question we got: [paraphrased question]. Our answer was honest but not great. If you asked it, we owe you a better one, reply here.\n\nThanks to [partner / venue / speakers] for making it work. Recordings up next week: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'conference_attendance',
        'category' => 'event',
        'name' => 'Conference attendance',
        'description' => 'Announce that the team will be at an upcoming conference.',
        'content' => "{{brand_name}} will be at [conference] in [city] from [date] to [date].\n\n[Number] of us are flying in. We're not doing a booth this year. We tried it last year and the most useful conversations happened nowhere near it.\n\nIf you want to meet:\n[Team member name] is around [days/times], mostly interested in [topic].\n[Another team member] is presenting on [topic] on [day].\nDinner on [date], small group, reply if you want in.\n\nBook a slot here: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== engagement =====
    [
        'slug' => 'open_question_to_audience',
        'category' => 'engagement',
        'name' => 'Open question to audience',
        'description' => 'Ask a real, specific question to the page audience.',
        'content' => "A real question for [audience] this week.\n\nWhen [specific situation, e.g. you're scoping a new project, picking a vendor, deciding what to cut], how do you actually decide?\n\nNot the version you'd put in a deck. The version that involves [honest factor, e.g. who's available that week, what the CFO is in a mood about, which tool your team already knows].\n\nWe've been running an internal version of this question at {{brand_name}} for a month and the answers are more interesting than any framework we've seen. Reply with yours and we'll share what we've heard.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'we_want_your_feedback',
        'category' => 'engagement',
        'name' => 'Feedback request',
        'description' => 'Ask the audience for input on a specific roadmap or decision.',
        'content' => "We're stuck on something and want your input.\n\nFor the next version of {{brand_name}}, we're choosing between two directions for [area].\n\nOption A: [specific direction, with the trade-off].\nOption B: [specific direction, with the trade-off].\n\nBoth are real. Neither is obviously right. Customers we've asked are split close to evenly, which is the worst possible outcome for a product team trying to ship.\n\nIf you have an opinion, especially a strong one, reply here or DM the page. Our product team reads everything.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'community_spotlight',
        'category' => 'engagement',
        'name' => 'Community spotlight',
        'description' => 'Highlight a customer, partner, or community member doing something interesting.',
        'content' => "Spotlight on [name], [role] at [company].\n\nWe noticed [their specific work or post] last week and ended up sending it around the {{brand_name}} team. The short version of why: [specific reason, what they did that was unusual, useful, or against the grain].\n\nGo follow them if you don't already. We have no business arrangement here. They're just doing the kind of work we wish more people in [industry] did publicly.\n\n[Link to their post / profile].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'year_in_review',
        'category' => 'engagement',
        'name' => 'Year in review',
        'description' => 'Honest year-end recap from the company page.',
        'content' => "A short year-in-review for {{brand_name}}.\n\nThe good: [specific win with a number]. [Another specific win, ideally a customer outcome, not a vanity metric].\n\nThe hard: [honest miss, e.g. a product bet that didn't work, a hiring goal we didn't hit, a goal we set in January and quietly dropped in June].\n\nThe surprising: [unexpected thing that mattered, a customer segment that took off, a feature nobody asked for that became important].\n\nThank you to the [number] customers, [number] team members, and the people who replied to our posts at 11pm asking us to ship things. Next year is going to be weirder than this one.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
