<?php

declare(strict_types=1);

return [
    [
        'slug' => 'mastodon_release_note',
        'category' => 'product_launch',
        'name' => 'Release note',
        'description' => 'Share an open, transparent update about a release.',
        'content' => "Release note from {{brand_name}}:\n\n→ [What shipped]\n→ [Why it matters]\n→ [What's next]\n\nFeedback welcome. Reply or open an issue.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_lessons_learned',
        'category' => 'educational',
        'name' => 'Lessons learned',
        'description' => 'Share something you learned, in the candid Mastodon style.',
        'content' => "Something we learned at {{brand_name}} this week:\n\n[Lesson, be specific.]\n\nThe takeaway: [principle].\n\nMaybe useful to someone else building [similar thing].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_open_question',
        'category' => 'engagement',
        'name' => 'Open question',
        'description' => 'Ask the fediverse a question and gather perspectives.',
        'content' => "Question for the fediverse:\n\n[Open-ended question relevant to your audience.]\n\nBoosts appreciated if your followers might have thoughts.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // product_launch
    [
        'slug' => 'mastodon_version_bump',
        'category' => 'product_launch',
        'name' => 'Version bump',
        'description' => 'Announce a new version with the actual diff that matters.',
        'content' => "{{brand_name}} [version] is out.\n\nWhat changed:\n- [Fix or feature]\n- [Fix or feature]\n- [Breaking change, if any]\n\nUpgrade notes: [link or short instruction].\n\nIf something breaks, please tell us. We read every reply.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_new_feature_in_public',
        'category' => 'product_launch',
        'name' => 'New feature in public',
        'description' => 'Ship a feature and explain why you built it that way.',
        'content' => "We added [feature] to {{brand_name}} today.\n\nWhy: [the actual reason, in one sentence].\n\nHow it works: [short concrete description].\n\nThe code is here: [link]. Pull requests welcome.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_beta_invite',
        'category' => 'product_launch',
        'name' => 'Beta invite',
        'description' => 'Invite the fediverse into a beta with honest expectations.',
        'content' => "Beta testers wanted for [feature] in {{brand_name}}.\n\nIt is rough. Some things will break. We want to know which ones.\n\nSign up: [link]\n\nNo NDA, no marketing list, no upsell. We just need real users.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_self_host_release',
        'category' => 'product_launch',
        'name' => 'Self-host release',
        'description' => 'Let self-hosters know about a release with the operational details.',
        'content' => "Heads-up to {{brand_name}} self-hosters: [version] is tagged.\n\nMigrations: [yes/no, runtime estimate]\nConfig changes: [list or none]\nBreaking: [list or none]\n\nDocs: [link]. Issues: [link]. Boosts appreciated.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // promotion
    [
        'slug' => 'mastodon_paid_plan_honest',
        'category' => 'promotion',
        'name' => 'Paid plan, honestly',
        'description' => 'Mention a paid plan without sounding like an ad.',
        'content' => "{{brand_name}} has a paid plan now. Here is what it gets you: [feature], [feature], [feature].\n\nThe free tier still does [what it always did]. We are not removing anything.\n\nDetails: [link]. Questions welcome.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_sponsor_us',
        'category' => 'promotion',
        'name' => 'Sponsor us',
        'description' => 'Ask for sponsorship or donations transparently.',
        'content' => "{{brand_name}} runs on [number] hours of volunteer work and [hosting cost] a month.\n\nIf you use it and want to chip in, sponsorship is here: [link].\n\nWe publish a spending breakdown every quarter. No tiers, no perks, just the work.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_discount_for_indies',
        'category' => 'promotion',
        'name' => 'Discount for indies',
        'description' => 'Offer a discount with no dark patterns.',
        'content' => "{{brand_name}} is [discount] off for solo developers and small co-ops until [date].\n\nNo coupon, no email gate. The price is just lower if you pick the [plan name] tier. Use it if it helps you.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // educational
    [
        'slug' => 'mastodon_quick_explainer',
        'category' => 'educational',
        'name' => 'Quick explainer',
        'description' => 'Explain a concept in plain language without padding.',
        'content' => "Quick explainer: [concept].\n\n[One sentence definition.]\n\n[One sentence about why it matters in practice.]\n\nIf you want the longer version, we wrote it up: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_misconception',
        'category' => 'educational',
        'name' => 'Common misconception',
        'description' => 'Correct a common misunderstanding with specifics.',
        'content' => "People often think [common belief about your topic].\n\nThat is not quite right. [The actual situation, with one specific example.]\n\nThis matters because [practical consequence].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_reading_list',
        'category' => 'educational',
        'name' => 'Reading list',
        'description' => 'Share a short, opinionated reading list.',
        'content' => "Things we have been reading at {{brand_name}}:\n\n- [Title], by [author]: [one-line reason].\n- [Title], by [author]: [one-line reason].\n- [Title], by [author]: [one-line reason].\n\nReply with what you have been reading. Always looking for new pointers.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_how_we_decided',
        'category' => 'educational',
        'name' => 'How we decided',
        'description' => 'Walk through a technical or product decision.',
        'content' => "How we picked [tool or approach] for {{brand_name}}:\n\nWe tried [option A]. It [problem]. We tried [option B]. It [tradeoff].\n\nWe went with [chosen option] because [reason]. It is not perfect. The thing that still bugs us is [downside].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // behind_the_scenes
    [
        'slug' => 'mastodon_dev_log',
        'category' => 'behind_the_scenes',
        'name' => 'Dev log',
        'description' => 'Share what you actually did this week.',
        'content' => "Dev log, week of [date]:\n\nMonday: [thing].\nTuesday: [thing].\nWednesday: [thing that went sideways].\nThursday: [fixed it].\nFriday: [shipped or punted].\n\nThis week is mostly [next focus].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_postmortem',
        'category' => 'behind_the_scenes',
        'name' => 'Short postmortem',
        'description' => 'Share a postmortem in plain language.',
        'content' => "{{brand_name}} had an outage on [date]. Here is the short version:\n\nWhat broke: [system].\nWhy: [root cause].\nDuration: [time].\nHow we fixed it: [action].\n\nFull writeup with timeline: [link]. Sorry for the disruption.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_tooling_setup',
        'category' => 'behind_the_scenes',
        'name' => 'Our tooling',
        'description' => 'Show the actual tools you use.',
        'content' => "What {{brand_name}} runs on, in case you are curious:\n\n- Editor: [editor]\n- Language: [language]\n- Database: [database]\n- Hosting: [host]\n- CI: [ci]\n\nNothing exotic. The boring stack is the productive stack.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_team_intro',
        'category' => 'behind_the_scenes',
        'name' => 'Who we are',
        'description' => 'Introduce the people behind the project.',
        'content' => "Quick intro: {{brand_name}} is [number] people.\n\n[Name] works on [area].\n[Name] works on [area].\n[Name] works on [area].\n\nWe are based across [regions]. We hire openly when we hire, which is rarely. Hi.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // testimonial
    [
        'slug' => 'mastodon_user_quote',
        'category' => 'testimonial',
        'name' => 'User quote',
        'description' => 'Share a real quote with permission and context.',
        'content' => "[Username] sent us this about {{brand_name}}, posted with permission:\n\n\"[Real quote.]\"\n\nThat one made our week. Thanks [@username] for taking the time to write.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_use_case_share',
        'category' => 'testimonial',
        'name' => 'How someone uses it',
        'description' => 'Highlight a specific way someone uses your tool.',
        'content' => "[Person or org] uses {{brand_name}} to [specific use case].\n\nWhat they told us: \"[short specific quote].\"\n\nIf you have a setup worth sharing, reply or DM. We like collecting these.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_thanks_contributor',
        'category' => 'testimonial',
        'name' => 'Thanks to a contributor',
        'description' => 'Credit a contributor by name.',
        'content' => "Shoutout to [@username] for [specific contribution] on {{brand_name}}.\n\nThis kind of work is not glamorous and it is the reason the project keeps moving. Thank you.\n\nPR is here: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // industry_tip
    [
        'slug' => 'mastodon_practical_tip',
        'category' => 'industry_tip',
        'name' => 'Practical tip',
        'description' => 'Share a real, specific tip.',
        'content' => "Tip if you work with [topic]:\n\n[One concrete tip in plain language.]\n\nWe figured this out the hard way after [brief context]. Maybe it saves someone else a few hours.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_unpopular_opinion',
        'category' => 'industry_tip',
        'name' => 'Unpopular opinion',
        'description' => 'Share a contrarian take you actually believe.',
        'content' => "Take that gets us in trouble: [contrarian belief about your field].\n\nReason: [the specific case where this holds].\n\nWe are open to being wrong. If you disagree, reply with the case and we will read it.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_anti_pattern',
        'category' => 'industry_tip',
        'name' => 'Anti-pattern',
        'description' => 'Call out a common anti-pattern with care.',
        'content' => "Anti-pattern we see a lot in [domain]: [the pattern].\n\nWhy it bites you: [specific failure mode].\n\nWhat to do instead: [alternative]. Not always, but most of the time.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_stop_doing_this',
        'category' => 'industry_tip',
        'name' => 'Stop doing this',
        'description' => 'Push back on a habit that costs people time.',
        'content' => "Friendly push: stop [common habit] when working on [domain].\n\nIt costs you [specific cost] and the alternative is [alternative], which takes [effort].\n\nWe did the same thing for years. The change is small and the payoff is real.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // event
    [
        'slug' => 'mastodon_event_announce',
        'category' => 'event',
        'name' => 'Event announce',
        'description' => 'Announce an event without hype.',
        'content' => "{{brand_name}} is at [event] on [date] in [city].\n\n[Speaker or team member] is talking about [topic] at [time].\n\nIf you are around, come say hi. Boosts appreciated for fediverse folks who might be local.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_meetup_call',
        'category' => 'event',
        'name' => 'Meetup call',
        'description' => 'Invite people to a community meetup.',
        'content' => "Community call for {{brand_name}} this [day] at [time UTC].\n\nAgenda: [topic], [topic], open Q&A.\n\nLink: [video link]. Notes go up after on [link]. No login wall.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_event_recap',
        'category' => 'event',
        'name' => 'Event recap',
        'description' => 'Recap an event with concrete takeaways.',
        'content' => "Back from [event]. Three things that stuck with us:\n\n1. [Specific takeaway].\n2. [Specific takeaway].\n3. [Specific takeaway].\n\nSlides from our talk are up: [link]. Thanks to everyone who came by the table.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // engagement
    [
        'slug' => 'mastodon_what_are_you_using',
        'category' => 'engagement',
        'name' => 'What are you using',
        'description' => 'Ask what tools or setups people use.',
        'content' => "Curious what the fediverse is using for [specific task] in [year].\n\nWe are on [current setup] and it is [honest assessment]. Looking for what you would replace it with and why.\n\nReply with the tool and one sentence on the tradeoff.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_show_your_work',
        'category' => 'engagement',
        'name' => 'Show your work',
        'description' => 'Invite people to share what they are building.',
        'content' => "Show-and-tell thread: what are you building this week?\n\nWe will go first. {{brand_name}} is working on [thing]. It is [stage] and we are stuck on [problem].\n\nReply with yours. Boosts welcome so others can find it.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
