<?php

declare(strict_types=1);

return [
    [
        'slug' => 'pinterest_how_to',
        'category' => 'educational',
        'name' => 'How-to pin',
        'description' => 'Step-by-step pin that drives saves and clicks.',
        'content' => "How to [achieve outcome] in [time/effort].\n\nA simple guide from {{brand_name}}.\n\nStep 1: [Action]\nStep 2: [Action]\nStep 3: [Action]\n\nFull tutorial → [link]",
        'image_count' => 1,
        'image_keywords' => ['tutorial', 'how-to', 'guide'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_inspiration',
        'category' => 'behind_the_scenes',
        'name' => 'Inspiration board',
        'description' => 'Inspirational pin around a theme or aesthetic.',
        'content' => "[Theme] inspiration, curated by {{brand_name}}.\n\nSave this for later.\n\nMore at → [link]",
        'image_count' => 1,
        'image_keywords' => ['inspiration', 'aesthetic', 'mood'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_product_showcase',
        'category' => 'product_launch',
        'name' => 'Product showcase',
        'description' => 'Highlight a product with a click-friendly description.',
        'content' => "[Product name] from {{brand_name}}.\n\n[Short benefit-led description, what it is, why it matters.]\n\nShop the look → [link]",
        'image_count' => 1,
        'image_keywords' => ['product', 'showcase', 'lifestyle'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_new_arrival',
        'category' => 'product_launch',
        'name' => 'New arrival pin',
        'description' => 'Announce a new product with searchable keywords.',
        'content' => "New from {{brand_name}}: [product name].\n\n[One sentence about what it is and who it is for.]\n\nKey features:\n- [Feature 1]\n- [Feature 2]\n- [Feature 3]\n\nAvailable in [colors/sizes/options].\n\nShop the [category] collection → [link]",
        'image_count' => 1,
        'image_keywords' => ['new product', 'launch', 'collection'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_collection_drop',
        'category' => 'product_launch',
        'name' => 'Collection drop pin',
        'description' => 'Introduce a curated product collection.',
        'content' => "The [collection name] collection is here.\n\n{{brand_name}} put together [number] pieces around [theme or season].\n\nWhat is inside:\n- [Item type 1]\n- [Item type 2]\n- [Item type 3]\n\nDesigned for [use case or audience].\n\nBrowse the full collection → [link]",
        'image_count' => 1,
        'image_keywords' => ['collection', 'lookbook', 'curated'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_pre_order',
        'category' => 'product_launch',
        'name' => 'Pre-order pin',
        'description' => 'Drive saves and pre-orders for an upcoming product.',
        'content' => "Pre-order is open: [product name].\n\nShipping starts [date]. {{brand_name}} pre-order customers get [perk: early access, bonus item, locked-in price].\n\nWhy pre-order:\n- [Reason 1]\n- [Reason 2]\n\nReserve yours → [link]",
        'image_count' => 1,
        'image_keywords' => ['pre-order', 'launch', 'early access'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_seasonal_sale',
        'category' => 'promotion',
        'name' => 'Seasonal sale pin',
        'description' => 'Promote a seasonal sale with clear savings.',
        'content' => "[Season] sale at {{brand_name}}: [discount]% off [category].\n\nGood through [end date].\n\nWhat is on sale:\n- [Category 1]\n- [Category 2]\n- [Category 3]\n\nUse code [CODE] at checkout.\n\nShop the sale → [link]",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'seasonal shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_bundle_deal',
        'category' => 'promotion',
        'name' => 'Bundle deal pin',
        'description' => 'Pin a value bundle with bullet pricing.',
        'content' => "The [bundle name] bundle from {{brand_name}}.\n\nBuy [item 1] + [item 2] + [item 3] together and save [amount].\n\nWhat is included:\n- [Item 1] (regularly [price])\n- [Item 2] (regularly [price])\n- [Item 3] (regularly [price])\n\nBundle price: [price].\n\nGrab the bundle → [link]",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'value pack', 'savings'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_free_shipping',
        'category' => 'promotion',
        'name' => 'Free shipping pin',
        'description' => 'Offer-led pin built around free shipping.',
        'content' => "Free shipping on every order at {{brand_name}}.\n\nNo minimum, no code. Through [end date].\n\nWhat to add to cart:\n- [Best seller 1]\n- [Best seller 2]\n- [Best seller 3]\n\nShop now → [link]",
        'image_count' => 1,
        'image_keywords' => ['free shipping', 'offer', 'deal'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_clearance',
        'category' => 'promotion',
        'name' => 'Clearance pin',
        'description' => 'Move clearance inventory with a save-worthy pin.',
        'content' => "Clearance at {{brand_name}}: up to [discount]% off.\n\nFinal markdowns on [category]. Once it is gone, it is gone.\n\nTop picks:\n- [Item 1], [price]\n- [Item 2], [price]\n- [Item 3], [price]\n\nShop clearance → [link]",
        'image_count' => 1,
        'image_keywords' => ['clearance', 'final sale', 'markdown'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_recipe',
        'category' => 'educational',
        'name' => 'Recipe pin',
        'description' => 'Save-worthy recipe pin with ingredients and steps.',
        'content' => "[Recipe name], ready in [time].\n\nFrom the {{brand_name}} kitchen.\n\nIngredients:\n- [Ingredient 1]\n- [Ingredient 2]\n- [Ingredient 3]\n- [Ingredient 4]\n\nMethod:\n1. [Step 1]\n2. [Step 2]\n3. [Step 3]\n\nServes [number]. Full recipe → [link]",
        'image_count' => 1,
        'image_keywords' => ['recipe', 'food', 'cooking'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_checklist',
        'category' => 'educational',
        'name' => 'Checklist pin',
        'description' => 'Practical checklist pin built for saves.',
        'content' => "The [topic] checklist from {{brand_name}}.\n\n[One sentence on who this is for.]\n\nThe checklist:\n- [Item 1]\n- [Item 2]\n- [Item 3]\n- [Item 4]\n- [Item 5]\n\nSave this pin so you have it when you need it.\n\nDownload the printable version → [link]",
        'image_count' => 1,
        'image_keywords' => ['checklist', 'planner', 'printable'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_beginners_guide',
        'category' => 'educational',
        'name' => 'Beginner guide pin',
        'description' => 'Beginner-friendly explainer pin.',
        'content' => "[Topic] for beginners.\n\nIf you are new to [topic], start here. {{brand_name}} put together the basics.\n\nWhat you need to know:\n1. [Concept 1]\n2. [Concept 2]\n3. [Concept 3]\n\nCommon beginner mistake: [mistake].\n\nRead the full guide → [link]",
        'image_count' => 1,
        'image_keywords' => ['beginner guide', 'basics', 'tutorial'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_diy_tutorial',
        'category' => 'educational',
        'name' => 'DIY tutorial pin',
        'description' => 'DIY project pin with a materials list.',
        'content' => "DIY [project name] in [time].\n\nA weekend project from {{brand_name}}.\n\nWhat you need:\n- [Material 1]\n- [Material 2]\n- [Material 3]\n- [Tool 1]\n\nThe steps:\n1. [Step 1]\n2. [Step 2]\n3. [Step 3]\n\nEstimated cost: [amount].\n\nFull tutorial with photos → [link]",
        'image_count' => 1,
        'image_keywords' => ['DIY', 'craft project', 'handmade'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_studio_tour',
        'category' => 'behind_the_scenes',
        'name' => 'Studio tour pin',
        'description' => 'Take followers inside the workspace.',
        'content' => "Inside the {{brand_name}} studio.\n\n[One sentence about what happens here.]\n\nThree things you will spot:\n- [Detail 1]\n- [Detail 2]\n- [Detail 3]\n\n[A note about the space, the team, or the routine.]\n\nMore studio photos → [link]",
        'image_count' => 1,
        'image_keywords' => ['studio', 'workspace', 'creative space'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_process_pin',
        'category' => 'behind_the_scenes',
        'name' => 'Making-of process pin',
        'description' => 'Show the craft behind a product.',
        'content' => "How {{brand_name}} makes [product].\n\nFrom [starting material] to finished piece, every step happens [where].\n\nThe process:\n1. [Stage 1]\n2. [Stage 2]\n3. [Stage 3]\n4. [Stage 4]\n\nTotal time per piece: [duration].\n\nSee the full process → [link]",
        'image_count' => 1,
        'image_keywords' => ['handmade', 'craft', 'process'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_founder_story',
        'category' => 'behind_the_scenes',
        'name' => 'Founder story pin',
        'description' => 'Personal pin about the brand origin.',
        'content' => "How {{brand_name}} started.\n\n[Founder name] launched [brand] in [year] after [origin moment].\n\n[Two short sentences on the why and the early days.]\n\nWhat is different about how we work:\n- [Value 1]\n- [Value 2]\n\nRead the full story → [link]",
        'image_count' => 1,
        'image_keywords' => ['founder story', 'small business', 'brand story'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_customer_review',
        'category' => 'testimonial',
        'name' => 'Customer review pin',
        'description' => 'Pull-quote pin from a real customer.',
        'content' => "\"[Customer quote about the product].\"\n- [Customer first name], [city or context]\n\n{{brand_name}} customers leave reviews like this every week.\n\nWhat [Customer first name] bought: [product name].\nWhy they bought it: [reason].\n\nRead more reviews → [link]",
        'image_count' => 1,
        'image_keywords' => ['customer review', 'testimonial', 'social proof'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_before_after',
        'category' => 'testimonial',
        'name' => 'Before and after pin',
        'description' => 'Visual transformation pin.',
        'content' => "Before and after with {{brand_name}} [product or service].\n\nBefore: [starting state].\nAfter: [end result].\nTime: [duration].\n\nWhat [customer name] used:\n- [Item 1]\n- [Item 2]\n\n[One sentence on the customer reaction.]\n\nSee more before and afters → [link]",
        'image_count' => 1,
        'image_keywords' => ['before and after', 'transformation', 'results'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_case_study',
        'category' => 'testimonial',
        'name' => 'Case study pin',
        'description' => 'Mini case study pin with concrete numbers.',
        'content' => "Case study: how [client name] used {{brand_name}} to [outcome].\n\nThe situation: [one sentence].\nWhat they tried: [product or service].\nThe result: [specific number or outcome] in [timeframe].\n\nWhy it worked:\n- [Reason 1]\n- [Reason 2]\n\nRead the full case study → [link]",
        'image_count' => 1,
        'image_keywords' => ['case study', 'results', 'success story'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_pro_tip',
        'category' => 'industry_tip',
        'name' => 'Pro tip pin',
        'description' => 'Single-tip pin with a clear payoff.',
        'content' => "Pro tip: [tip in one sentence].\n\nMost people [common mistake]. The fix is [the actual technique].\n\nWhy it works: [one sentence on the reason].\n\nWhen to use it: [context or scenario].\n\nMore [topic] tips from {{brand_name}} → [link]",
        'image_count' => 1,
        'image_keywords' => ['pro tip', 'expert advice', 'industry tips'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_common_mistakes',
        'category' => 'industry_tip',
        'name' => 'Common mistakes pin',
        'description' => 'List of mistakes readers can avoid.',
        'content' => "[Number] [topic] mistakes to skip.\n\n{{brand_name}} sees these every week. Save the pin so you do not repeat them.\n\nThe mistakes:\n1. [Mistake 1], do this instead: [fix]\n2. [Mistake 2], do this instead: [fix]\n3. [Mistake 3], do this instead: [fix]\n\nRead the full breakdown → [link]",
        'image_count' => 1,
        'image_keywords' => ['common mistakes', 'tips', 'expert advice'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_industry_stat',
        'category' => 'industry_tip',
        'name' => 'Industry statistic pin',
        'description' => 'Stat-led pin that anchors a useful insight.',
        'content' => "[Statistic with number]% of [audience] [behavior].\nSource: [source, year].\n\nWhat that means for you: [one sentence on the implication].\n\nThree ways {{brand_name}} customers respond:\n- [Tactic 1]\n- [Tactic 2]\n- [Tactic 3]\n\nRead the full report → [link]",
        'image_count' => 1,
        'image_keywords' => ['industry data', 'statistics', 'research'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_workshop',
        'category' => 'event',
        'name' => 'Workshop pin',
        'description' => 'Pin promoting an in-person or online workshop.',
        'content' => "[Workshop name] with {{brand_name}}.\n\n[Date] · [time] · [location or online].\n\nWhat you will learn:\n- [Learning 1]\n- [Learning 2]\n- [Learning 3]\n\nWho it is for: [audience].\nSpots: [number] limited.\nPrice: [amount].\n\nReserve a seat → [link]",
        'image_count' => 1,
        'image_keywords' => ['workshop', 'class', 'learning event'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_pop_up',
        'category' => 'event',
        'name' => 'Pop-up shop pin',
        'description' => 'Drive foot traffic to a pop-up.',
        'content' => "{{brand_name}} pop-up shop in [city].\n\n[Date range] · [address] · [hours].\n\nWhat you will find:\n- [Category 1]\n- [Category 2]\n- [In-store exclusive]\n\n[One sentence on what makes the day worth the trip.]\n\nGet directions and full details → [link]",
        'image_count' => 1,
        'image_keywords' => ['pop-up shop', 'event', 'in-person shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_webinar',
        'category' => 'event',
        'name' => 'Webinar pin',
        'description' => 'Promote a free or paid webinar.',
        'content' => "Free webinar: [topic].\n\nHosted by {{brand_name}} on [date] at [time, timezone].\n\nWhat we cover:\n- [Point 1]\n- [Point 2]\n- [Point 3]\n\nWho should attend: [audience].\nReplay: sent to everyone who registers.\n\nSave your spot → [link]",
        'image_count' => 1,
        'image_keywords' => ['webinar', 'online event', 'training'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_holiday_event',
        'category' => 'event',
        'name' => 'Holiday event pin',
        'description' => 'Holiday-themed event or promotion pin.',
        'content' => "{{brand_name}} [holiday name] event.\n\n[Date] · [location or online].\n\nOn the schedule:\n- [Activity 1]\n- [Activity 2]\n- [Activity 3]\n\nWhat to expect: [one sentence].\nRSVP by [date].\n\nFull schedule and RSVP → [link]",
        'image_count' => 1,
        'image_keywords' => ['holiday event', 'seasonal', 'celebration'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_question_pin',
        'category' => 'engagement',
        'name' => 'Question pin',
        'description' => 'Question-led pin that invites comments.',
        'content' => "[Open-ended question for the audience].\n\n{{brand_name}} is curious. Drop your answer in the comments.\n\nA few prompts to get you thinking:\n- [Prompt 1]\n- [Prompt 2]\n- [Prompt 3]\n\nWe will share the most interesting answers next week.\n\nJoin the conversation → [link]",
        'image_count' => 1,
        'image_keywords' => ['question', 'community', 'discussion'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_this_or_that',
        'category' => 'engagement',
        'name' => 'This or that pin',
        'description' => 'Side-by-side preference pin.',
        'content' => "This or that: [option A] or [option B].\n\n{{brand_name}} wants to know which side you are on. No wrong answer.\n\nThe case for [option A]: [one sentence].\nThe case for [option B]: [one sentence].\n\nVote in the comments. We will tally the results.\n\nMore polls → [link]",
        'image_count' => 1,
        'image_keywords' => ['poll', 'this or that', 'preference'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_giveaway',
        'category' => 'engagement',
        'name' => 'Giveaway pin',
        'description' => 'Pin announcing a giveaway with clear rules.',
        'content' => "{{brand_name}} giveaway: win [prize].\n\nOne winner picked on [date].\n\nHow to enter:\n1. Save this pin.\n2. Follow {{brand_name}} on Pinterest.\n3. Comment with [prompt].\n\nOpen to: [region].\nValue: [amount].\n\nFull rules → [link]",
        'image_count' => 1,
        'image_keywords' => ['giveaway', 'contest', 'prize'],
        'slides' => null,
    ],
];
