<?php

declare(strict_types=1);

return [
    [
        'slug' => 'threads_hot_take',
        'category' => 'industry_tip',
        'name' => 'Hot take',
        'description' => 'A short, opinionated post designed to spark replies.',
        'content' => "Unpopular opinion: [counterintuitive statement about your industry].\n\nHere's why I think this →\n\n[Brief reasoning in 1–2 sentences.]\n\nAm I wrong?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_quick_tip',
        'category' => 'educational',
        'name' => 'Quick tip',
        'description' => 'One actionable tip in a short, friendly tone.',
        'content' => "Quick tip from {{brand_name}}:\n\n[Single, specific, actionable tip.]\n\nIt sounds simple. It changes everything.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_question',
        'category' => 'engagement',
        'name' => 'Open question',
        'description' => 'Ask the community a question to drive conversation.',
        'content' => "Genuine question for the {{brand_name}} community:\n\n[Question, open-ended and specific enough to answer.]\n\nNo wrong answers. Curious to read yours.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // PRODUCT LAUNCH
    [
        'slug' => 'threads_product_launch_soft',
        'category' => 'product_launch',
        'name' => 'Soft launch announcement',
        'description' => 'Casual, low-key announcement that something new is out.',
        'content' => "ok so. we shipped [product name] today.\n\nbeen working on it for [length of time] and i kind of can't believe it's actually live.\n\n[one specific thing it does that you're proud of].\n\nif you try it, tell me what breaks.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_product_launch_story',
        'category' => 'product_launch',
        'name' => 'Why we built it',
        'description' => 'Personal story behind the new product or feature.',
        'content' => "started building [product name] because [specific personal frustration].\n\nthought it would take a weekend. it took [actual time].\n\nit's live now at {{brand_name}}. honestly still surprised it works.\n\nwould love to hear what you think after you poke at it.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_product_launch_feature',
        'category' => 'product_launch',
        'name' => 'New feature drop',
        'description' => 'Announce a single feature within an existing product.',
        'content' => "small thing but i'm weirdly excited about it.\n\n{{brand_name}} now [does this specific thing].\n\nthe reason: people kept asking for [the underlying need]. so we did it.\n\nit's live. go try it and let me know if it's actually useful or just a thing now.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // PROMOTION
    [
        'slug' => 'threads_promo_discount',
        'category' => 'promotion',
        'name' => 'Casual discount post',
        'description' => 'Low-pressure way to mention a sale or discount.',
        'content' => "running [discount amount] off [product or plan] this week at {{brand_name}}.\n\nnot doing the whole countdown timer thing. just figured i'd mention it once and let people decide.\n\ncode: [code]. ends [date].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_promo_bundle',
        'category' => 'promotion',
        'name' => 'Bundle offer',
        'description' => 'Promote a bundled deal in a relaxed tone.',
        'content' => "bundled [item one] and [item two] together because people kept buying them in the same order anyway.\n\nthe pair is [price] at {{brand_name}}, which is about [savings] less than buying them separate.\n\nthat's it. that's the post.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_promo_last_chance',
        'category' => 'promotion',
        'name' => 'Last chance reminder',
        'description' => 'Friendly nudge that an offer is ending.',
        'content' => "fair warning: [offer name] ends [date or time].\n\nnot trying to be pushy. some of you said you wanted me to remind you, so consider this the reminder.\n\nlink in bio if you want it. zero hard feelings if you don't.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // EDUCATIONAL
    [
        'slug' => 'threads_edu_mistake',
        'category' => 'educational',
        'name' => 'Mistake I made',
        'description' => 'Teach by sharing a personal mistake.',
        'content' => "made the same mistake [number] times before i figured this out:\n\n[the mistake in one sentence].\n\nthe fix is [the actual fix in plain words]. nothing fancy. just had to stop doing the thing.\n\nposting in case you're stuck on the same loop.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_misconception',
        'category' => 'educational',
        'name' => 'Common misconception',
        'description' => 'Correct a widely held but wrong belief.',
        'content' => "people keep telling me [common belief in your field].\n\nthat is not how it works.\n\n[what actually happens, in plain words].\n\nmight be obvious to some of you. apparently not to most of the people who emailed me last week.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_resource',
        'category' => 'educational',
        'name' => 'Resource share',
        'description' => 'Recommend a useful resource with personal context.',
        'content' => "if you're trying to learn [topic], stop watching 4 hour youtube videos and just read [specific resource].\n\ni put it off for months because the title is boring. it's the only thing that actually clicked for me.\n\nthat's the recommendation.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_step_breakdown',
        'category' => 'educational',
        'name' => 'Quick how-to',
        'description' => 'Tiny step-by-step in conversational tone.',
        'content' => "the [task] thing in 4 lines for anyone who keeps asking:\n\n1. [step one]\n2. [step two]\n3. [step three]\n4. [step four]\n\nthat is the whole process. you don't need a course for it.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // BEHIND THE SCENES
    [
        'slug' => 'threads_bts_morning',
        'category' => 'behind_the_scenes',
        'name' => 'Morning routine',
        'description' => 'Casual peek at how a workday starts.',
        'content' => "today at {{brand_name}}:\n\n- coffee\n- stared at [specific problem] for an hour\n- realized the bug was on line [number]\n- fixed it in 4 minutes\n\nthe ratio of thinking to doing in this job is genuinely cursed.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_decision',
        'category' => 'behind_the_scenes',
        'name' => 'Decision we made',
        'description' => 'Share an internal decision and the reasoning.',
        'content' => "we decided to [specific decision] this week.\n\nthe other option was [alternative]. half the team wanted that one. i still kind of do.\n\nbut [the actual reason this decision won].\n\nask me in 3 months if it was the right call.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_messy_progress',
        'category' => 'behind_the_scenes',
        'name' => 'Messy progress shot',
        'description' => 'Honest mid-project update.',
        'content' => "current state of [project name]:\n\n- [percent] done\n- [specific thing that is working]\n- [specific thing that is not working]\n- [number] open tabs i'm afraid to close\n\nwill ship when it stops embarrassing me.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_team_moment',
        'category' => 'behind_the_scenes',
        'name' => 'Team moment',
        'description' => 'Small human moment from the team.',
        'content' => "[name on the team] just sent a slack message that said \"[short funny or insightful quote]\" and now we can't stop quoting it.\n\nbuilding {{brand_name}} with these people is half the reason i still like the job.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // TESTIMONIAL
    [
        'slug' => 'threads_testimonial_quote',
        'category' => 'testimonial',
        'name' => 'Customer quote',
        'description' => 'Share a real customer line with light context.',
        'content' => "got this email from [first name or initials] yesterday:\n\n\"[direct customer quote, 1-2 sentences]\"\n\ni read it twice. this is the part of the job that doesn't show up in the metrics.\n\nthank you for using {{brand_name}}. genuinely.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_testimonial_outcome',
        'category' => 'testimonial',
        'name' => 'Customer outcome',
        'description' => 'Talk about a real customer result without bragging.',
        'content' => "[customer first name] told me yesterday they [specific outcome] after using {{brand_name}} for [time period].\n\ni didn't ask them to share it. they just sent the screenshot and said \"thought you'd want to see this.\"\n\nyeah. i did.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_testimonial_unexpected',
        'category' => 'testimonial',
        'name' => 'Unexpected use case',
        'description' => 'Highlight a surprising way someone uses the product.',
        'content' => "didn't see this coming.\n\nsomeone using {{brand_name}} for [unexpected use case]. wasn't what we built it for. apparently it works.\n\nfavorite part of shipping things is finding out what people actually do with them.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // INDUSTRY TIP
    [
        'slug' => 'threads_industry_observation',
        'category' => 'industry_tip',
        'name' => 'Industry observation',
        'description' => 'Share a pattern you keep noticing in your field.',
        'content' => "thing i keep noticing in [industry]:\n\n[specific observation in one sentence].\n\ncould be a real shift. could be selection bias from who i talk to. tell me if you're seeing it too.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_lesson',
        'category' => 'industry_tip',
        'name' => 'Lesson from experience',
        'description' => 'Single hard-won lesson, no fluff.',
        'content' => "[number] years in [industry] and the lesson that took me longest to actually believe:\n\n[the lesson in one sentence].\n\nstill catch myself ignoring it. then something breaks. then i remember.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_pushback',
        'category' => 'industry_tip',
        'name' => 'Pushback on conventional wisdom',
        'description' => 'Politely disagree with a common piece of advice.',
        'content' => "the standard advice in [industry] is [common advice].\n\ni've been doing the opposite for [time period]. it works better for me, anyway.\n\n[brief reason why].\n\nnot saying everyone should. just that the rule isn't a rule.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_prediction',
        'category' => 'industry_tip',
        'name' => 'Quiet prediction',
        'description' => 'Make a prediction without grandstanding.',
        'content' => "small prediction:\n\nin [time frame], [specific change in your industry] will be normal.\n\ncould absolutely be wrong. saving this so i can come back and laugh at myself later.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // EVENT
    [
        'slug' => 'threads_event_announcement',
        'category' => 'event',
        'name' => 'Event announcement',
        'description' => 'Casually announce an upcoming event.',
        'content' => "{{brand_name}} is doing [event name] on [date].\n\n[one or two sentences on what it actually is and who would care about it].\n\n[location or link]. tell a friend if it sounds like their thing.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_event_recap',
        'category' => 'event',
        'name' => 'Event recap',
        'description' => 'Honest recap after an event.',
        'content' => "back from [event name].\n\nthe best part was [specific moment or conversation].\n\nthe weirdest part was [honest observation].\n\nif you were there and we didn't get to talk, message me. there's always more to say after the panel ends.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_event_invite',
        'category' => 'event',
        'name' => 'Personal invite',
        'description' => 'Direct invite that feels personal.',
        'content' => "doing a small [event type] for {{brand_name}} on [date] and i actually want you there.\n\nit's [duration] and we'll be talking about [specific topic].\n\nrsvp at [link] if you want in. capping it at [number] so it stays a real conversation.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ENGAGEMENT
    [
        'slug' => 'threads_engagement_recommendation',
        'category' => 'engagement',
        'name' => 'Recommendation request',
        'description' => 'Ask the audience for recommendations.',
        'content' => "looking for recommendations:\n\n[specific thing you need recommendations for].\n\ni've already tried [option a] and [option b]. need something that [specific constraint].\n\nbest reply gets my eternal gratitude. that is the prize.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_engagement_this_or_that',
        'category' => 'engagement',
        'name' => 'This or that',
        'description' => 'Quick binary question to drive replies.',
        'content' => "[option a] or [option b].\n\nno middle ground. no \"it depends.\" pick one and tell me why.\n\nrunning the {{brand_name}} version of this debate in our team chat and we are deeply, deeply split.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_engagement_confession',
        'category' => 'engagement',
        'name' => 'Tiny confession',
        'description' => 'Share something small and relatable.',
        'content' => "small confession.\n\ni still [slightly embarrassing habit related to your work or life].\n\ntell me i'm not the only one. or do tell me i'm the only one. either way i'd like to know.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
