<?php

declare(strict_types=1);

return [
    [
        'slug' => 'flash_sale',
        'category' => 'promotion',
        'name' => 'Flash sale',
        'description' => 'Short X post for a flash sale with urgency.',
        'content' => "🔥 Flash sale at {{brand_name}}!\n\n[Discount]% off [product/service], ends in 24 hours.\n\nNo code needed → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'success_story',
        'category' => 'testimonial',
        'name' => 'Success story',
        'description' => 'Brief success-story format for X.',
        'content' => "\"[Short customer quote.]\"\n- @[handle]\n\nThis is why we do what we do at {{brand_name}}. 🙌",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'this_or_that_poll',
        'category' => 'engagement',
        'name' => 'This or that',
        'description' => 'Drive engagement with a simple binary choice question.',
        'content' => "Quick question for the {{brand_name}} community:\n\n[Option A] or [Option B]?\n\nReply with your pick and why 👇",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // product_launch
    [
        'slug' => 'shipped_today',
        'category' => 'product_launch',
        'name' => 'Shipped today',
        'description' => 'Casual ship announcement with one concrete change.',
        'content' => "Shipped today: [feature].\n\nIt does [one specific thing] so you can stop [annoying workaround].\n\nLive now in {{brand_name}}.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'new_feature_one_liner',
        'category' => 'product_launch',
        'name' => 'New feature one-liner',
        'description' => 'One-sentence pitch for a new feature.',
        'content' => "{{brand_name}} now [does specific thing].\n\nIf you've been [doing painful workaround], try it: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'beta_invite',
        'category' => 'product_launch',
        'name' => 'Beta invite',
        'description' => 'Open call for beta testers.',
        'content' => "We're opening beta for [feature] this week.\n\nLooking for [number] people who [specific use case].\n\nReply if that's you.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'finally_built_it',
        'category' => 'product_launch',
        'name' => 'Finally built it',
        'description' => 'Honest "we got around to it" launch tone.',
        'content' => "Finally built [feature]. People have been asking for it since [time period].\n\nIt's live in {{brand_name}} today. Sorry it took so long.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // promotion
    [
        'slug' => 'weekend_deal',
        'category' => 'promotion',
        'name' => 'Weekend deal',
        'description' => 'Weekend-only discount post.',
        'content' => "Weekend only: [discount] off [product] at {{brand_name}}.\n\nCode [CODE]. Expires Sunday at midnight. That's the whole post.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'free_shipping',
        'category' => 'promotion',
        'name' => 'Free shipping',
        'description' => 'Free shipping window announcement.',
        'content' => "Free shipping on every {{brand_name}} order over $[amount] this week.\n\nNo code, no minimum tricks. Goes back to normal Monday.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'last_call',
        'category' => 'promotion',
        'name' => 'Last call',
        'description' => 'Final hours of a sale.',
        'content' => "Last call. [Sale name] ends tonight at [time].\n\nIf you've had {{brand_name}} in your cart, this is the cheapest it gets this year: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bundle_offer',
        'category' => 'promotion',
        'name' => 'Bundle offer',
        'description' => 'Pitches a bundle as a saver deal.',
        'content' => "New bundle at {{brand_name}}: [Product A] + [Product B] for [price].\n\nThat's [amount] less than buying them separately. Limited to [quantity] units.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // educational
    [
        'slug' => 'one_thing_we_learned',
        'category' => 'educational',
        'name' => 'One thing we learned',
        'description' => 'Share a single concrete lesson.',
        'content' => "One thing we learned at {{brand_name}} this month:\n\n[Specific finding]. We thought [old assumption], but [data point] proved otherwise.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake',
        'category' => 'educational',
        'name' => 'Common mistake',
        'description' => 'Call out a single mistake people make.',
        'content' => "Most people get [topic] wrong because they [common mistake].\n\nWhat actually works: [counter-approach]. We tested it on [number] customers.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'quick_tip',
        'category' => 'educational',
        'name' => 'Quick tip',
        'description' => 'Tiny actionable tip.',
        'content' => "Quick tip if you're using {{brand_name}}:\n\n[Specific action] before [step]. Saves about [time/result] for most people.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'myth_vs_reality',
        'category' => 'educational',
        'name' => 'Myth vs reality',
        'description' => 'Dispel one industry myth.',
        'content' => "Myth: [common belief about topic].\n\nReality: [counter-fact with number]. We see it in {{brand_name}} data every week.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // behind_the_scenes
    [
        'slug' => 'how_we_built_it',
        'category' => 'behind_the_scenes',
        'name' => 'How we built it',
        'description' => 'Casual behind-the-scenes peek.',
        'content' => "How we built [feature] at {{brand_name}}:\n\nStarted with [first attempt]. It broke. Switched to [approach 2]. Shipped that.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'team_at_work',
        'category' => 'behind_the_scenes',
        'name' => 'Team at work',
        'description' => 'Snapshot of what the team is doing right now.',
        'content' => "What the {{brand_name}} team is working on right now:\n\n[Person/role] is debugging [specific issue]. [Person/role] is on [other project]. Coffee count: high.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mistake_we_made',
        'category' => 'behind_the_scenes',
        'name' => 'Mistake we made',
        'description' => 'Honest postmortem in one tweet.',
        'content' => "We messed up at {{brand_name}} last week.\n\n[What broke]. Caused [impact] for [number] customers. Fixed it [how]. Sorry to anyone affected.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'office_moment',
        'category' => 'behind_the_scenes',
        'name' => 'Office moment',
        'description' => 'Small, human office snapshot.',
        'content' => "Random {{brand_name}} office moment:\n\n[Specific scene, e.g. designer arguing with engineer over a 2px button radius]. This is most days, honestly.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // testimonial
    [
        'slug' => 'customer_dm',
        'category' => 'testimonial',
        'name' => 'Customer DM',
        'description' => 'Share a real customer message.',
        'content' => "Got this DM from a {{brand_name}} customer today:\n\n\"[Short quote about what changed for them].\"\n\nThis is the part of the job that doesn't get old.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'before_and_after',
        'category' => 'testimonial',
        'name' => 'Before and after',
        'description' => 'Concrete before/after numbers from a customer.',
        'content' => "[Customer name] before {{brand_name}}: [metric].\n\n[Customer name] after [time period]: [new metric].\n\nNothing else changed in their setup.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'one_line_review',
        'category' => 'testimonial',
        'name' => 'One-line review',
        'description' => 'Single short customer line.',
        'content' => "\"[Specific customer line, max 12 words.]\"\n\n- [Customer name], [role] at [company]\n\nWe didn't ask them to write that.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // industry_tip
    [
        'slug' => 'hot_take',
        'category' => 'industry_tip',
        'name' => 'Hot take',
        'description' => 'Opinionated take on the industry.',
        'content' => "Hot take: most people in [industry] think [common belief].\n\nAfter [time] running {{brand_name}}, I think the opposite. [Specific reason].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'overrated_underrated',
        'category' => 'industry_tip',
        'name' => 'Overrated underrated',
        'description' => 'Pair an overrated and underrated thing.',
        'content' => "Overrated in [industry]: [common practice].\n\nUnderrated: [overlooked practice].\n\nWe stopped doing the first at {{brand_name}} a year ago.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'unpopular_opinion',
        'category' => 'industry_tip',
        'name' => 'Unpopular opinion',
        'description' => 'Share a contrarian observation.',
        'content' => "Unpopular opinion: [contrarian statement about industry].\n\n{{brand_name}} customers prove this every month. The data isn't subtle.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'what_changed_my_mind',
        'category' => 'industry_tip',
        'name' => 'What changed my mind',
        'description' => 'Honest mind-change moment.',
        'content' => "I used to think [old belief about industry].\n\nThen [specific event/data] happened at {{brand_name}}. Now I think [new view]. Still adjusting.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // event
    [
        'slug' => 'event_announcement',
        'category' => 'event',
        'name' => 'Event announcement',
        'description' => 'Plain event announcement.',
        'content' => "{{brand_name}} is hosting [event name] on [date] in [city].\n\n[Specific topic]. Free, [capacity] seats. Sign up: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_recap',
        'category' => 'event',
        'name' => 'Event recap',
        'description' => 'Short recap after an event.',
        'content' => "[Number] people showed up at the {{brand_name}} [event] last night.\n\nFavorite question: \"[real audience question].\" Recording goes up Friday.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'webinar_reminder',
        'category' => 'event',
        'name' => 'Webinar reminder',
        'description' => 'Reminder a webinar is happening soon.',
        'content' => "Reminder: {{brand_name}} webinar on [topic] starts in [time].\n\n[Speaker] is going to walk through [specific thing]. Last chance to register: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // engagement
    [
        'slug' => 'open_question',
        'category' => 'engagement',
        'name' => 'Open question',
        'description' => 'Ask the audience a real question.',
        'content' => "Genuine question for anyone using [tool/category]:\n\nWhat's the one thing it still can't do that you wish it could?\n\nAsking because we're working on it at {{brand_name}}.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'fill_in_the_blank',
        'category' => 'engagement',
        'name' => 'Fill in the blank',
        'description' => 'Light fill-in-the-blank prompt.',
        'content' => "Fill in the blank:\n\nThe worst part of [task/topic] is ______.\n\nReading every reply. We're using them to plan {{brand_name}}'s next quarter.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'show_us_your_setup',
        'category' => 'engagement',
        'name' => 'Show us your setup',
        'description' => 'Ask people to share something visual.',
        'content' => "Show us your [thing, desk, dashboard, weekly routine].\n\nWe'll feature our favorite three on the {{brand_name}} account next week. No filter required.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
