<?php

declare(strict_types=1);

return [
    [
        'slug' => 'bluesky_now_live',
        'category' => 'product_launch',
        'name' => 'Ya disponible',
        'description' => 'Anuncia un lanzamiento con la onda abierta y descentralizada de Bluesky.',
        'content' => "Ya disponible: [feature/producto] de {{brand_name}}.\n\nQué cambió: [resumen en una línea].\n\nPara quién: [quién se beneficia].\n\nLink → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_thought',
        'category' => 'industry_tip',
        'name' => 'Pensamiento corto',
        'description' => 'Una observación concisa que se lee natural en Bluesky.',
        'content' => "[Observación sobre tu industria, contada en una o dos frases.]\n\nSimple, pero vale decirlo en voz alta.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_invite',
        'category' => 'engagement',
        'name' => 'Invitación a la comunidad',
        'description' => 'Invita a la comunidad a un tema o conversación.',
        'content' => "Si te importa [tema], queremos escucharte.\n\n¿Qué te ronda la cabeza últimamente?\n\n- equipo {{brand_name}}",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_changelog_drop',
        'category' => 'product_launch',
        'name' => 'Changelog nuevo',
        'description' => 'Post de changelog directo para un release.',
        'content' => "v[versión] salió.\n\n• [cambio 1]\n• [cambio 2]\n• [bug fix]\n\nSin migrations. Notas completas: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_open_beta',
        'category' => 'product_launch',
        'name' => 'Beta abierta',
        'description' => 'Invita a los usuarios a una beta pública.',
        'content' => "Beta abierta: [feature] está disponible para quien quiera probarlo.\n\nTiene partes ásperas. Es justamente el punto. Bug reports bienvenidos.\n\nRegistrate: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_api_release',
        'category' => 'product_launch',
        'name' => 'Release de API',
        'description' => 'Anuncia una nueva API o feature para developers.',
        'content' => "Nuevo: [endpoint/SDK] de {{brand_name}}.\n\nDocs: [link]\nRepo de ejemplo: [link]\n\nSi falta algo en las docs, avisanos. Lo arreglamos más rápido de lo que esperás.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_promo_discount',
        'category' => 'promotion',
        'name' => 'Ventana de descuento',
        'description' => 'Promo con plazo, dicha de forma directa.',
        'content' => "[X]% off en [plan/producto] hasta [fecha].\n\nSin registro de email. Sin popup. Solo el código: [CÓDIGO]\n\n[link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_promo_lifetime',
        'category' => 'promotion',
        'name' => 'Lifetime deal',
        'description' => 'Oferta lifetime/early-bird pensada para builders.',
        'content' => "Lifetime deal en {{brand_name}}: [precio] una vez, sin suscripción.\n\nLimitado a [número] lugares. Después volvemos al mensual.\n\nLlevate uno: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_promo_referral',
        'category' => 'promotion',
        'name' => 'Bonus por referido',
        'description' => 'Oferta de referidos directa.',
        'content' => "Referí a un amigo a {{brand_name}}, los dos reciben [recompensa].\n\nSin niveles. Sin ranking. Solo mandá tu link: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_one_thing',
        'category' => 'educational',
        'name' => 'Una cosa que aprendí',
        'description' => 'Una lección concreta, contada de forma simple.',
        'content' => "Una cosa que aprendí trabajando en [tema]:\n\n[lección concreta, una o dos frases].\n\nObvio en retrospectiva. No era obvio antes.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_misconception',
        'category' => 'educational',
        'name' => 'Mito común',
        'description' => 'Corregí un mito difundido en tu área.',
        'content' => "Creencia común: [mito sobre tu área].\n\nLo que es verdad de hecho: [corrección].\n\nLa diferencia importa cuando [escenario específico].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_quick_how',
        'category' => 'educational',
        'name' => 'Tutorial rápido',
        'description' => 'Tutorial corto sobre una tarea específica.',
        'content' => "Cómo [tarea específica] en [herramienta]:\n\n1. [paso]\n2. [paso]\n3. [paso]\n\nEs todo. Sin config oculta.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_edu_tradeoff',
        'category' => 'educational',
        'name' => 'Explicación de un tradeoff',
        'description' => 'Mostrá un tradeoff real de tu dominio.',
        'content' => "[Opción A] vs [Opción B] es básicamente un tradeoff entre [cosa 1] y [cosa 2].\n\nSi te importa más [cosa 1], elegí A. Si [cosa 2], elegí B. La mayoría de los equipos eligen A y se arrepienten después.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_stack',
        'category' => 'behind_the_scenes',
        'name' => 'Nuestra stack',
        'description' => 'Nota honesta sobre la stack desde dentro del equipo.',
        'content' => "Nuestra stack en {{brand_name}}: [tech 1], [tech 2], [tech 3].\n\nElegimos [tech 1] por [motivo]. Nos arrepentimos de haber elegido [tech] por [motivo]. Probablemente lo cambiamos el próximo trimestre.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_postmortem',
        'category' => 'behind_the_scenes',
        'name' => 'Mini postmortem',
        'description' => 'Nota corta y transparente sobre un incidente.',
        'content' => "[Servicio/feature] estuvo caído por [duración] hoy.\n\nCausa: [explicación simple].\nFix: [lo que hicimos].\n\nAgregamos [protección] para que la misma cosa no pase de la misma forma de nuevo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_decision',
        'category' => 'behind_the_scenes',
        'name' => 'Por qué elegimos X',
        'description' => 'Explicá una decisión reciente de diseño o producto.',
        'content' => "Por qué elegimos [decisión] en lugar de [alternativa]:\n\n[motivo en una frase].\n\nNo es la elección popular. Pero encaja con cómo trabajan nuestros usuarios de verdad.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_bts_numbers',
        'category' => 'behind_the_scenes',
        'name' => 'Números que miramos',
        'description' => 'Compartí una métrica real y qué significa.',
        'content' => "Un número que miramos de verdad en {{brand_name}}: [métrica].\n\nEl mes pasado fue [valor]. La semana anterior, [valor].\n\nEs la métrica que nos dice si [resultado] es real.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_testimonial_quote',
        'category' => 'testimonial',
        'name' => 'Cita de un usuario',
        'description' => 'Cita corta de un usuario, sin adornos.',
        'content' => "De un usuario esta semana:\n\n\"[cita corta y específica sobre el producto].\"\n\n- [nombre], [rol]\n\nEs ese tipo de feedback el que nos mantiene construyendo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_testimonial_workflow',
        'category' => 'testimonial',
        'name' => 'Cómo lo usa un cliente',
        'description' => 'Historia específica del workflow de un usuario.',
        'content' => "[Cliente/equipo] usa {{brand_name}} para [tarea específica].\n\nAntes: [forma vieja].\nAhora: [forma nueva].\n\nNo es dramático. Solo menos fricción todos los días.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_testimonial_result',
        'category' => 'testimonial',
        'name' => 'Resultado concreto',
        'description' => 'Un resultado específico y medible de un cliente.',
        'content' => "[Cliente] redujo [tarea] de [tiempo viejo] a [tiempo nuevo] usando {{brand_name}}.\n\nUn cambio de workflow. Sin nuevas contrataciones.\n\nNota completa: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_take',
        'category' => 'industry_tip',
        'name' => 'Opinión medio impopular',
        'description' => 'Una opinión real sobre algo de tu industria.',
        'content' => "Opinión moderada: [opinión sobre tu industria].\n\nSé que es impopular. Cambié de idea sobre esto dos veces. Por ahora creo que se sostiene.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_pattern',
        'category' => 'industry_tip',
        'name' => 'Un patrón que veo seguido',
        'description' => 'Patrón observado entre equipos o proyectos.',
        'content' => "Un patrón que veo seguido en [industria/rol]:\n\n[patrón en una frase].\n\nGeneralmente funciona hasta [hito] y después deja de funcionar en silencio.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_anti_advice',
        'category' => 'industry_tip',
        'name' => 'Consejo que saltearía',
        'description' => 'Anti-consejo: consejo común que no se sostiene.',
        'content' => "Consejo que se escucha mucho: [consejo común].\n\nEn la práctica esto se cae cuando [escenario]. La versión que funciona de verdad es [consejo revisado].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_industry_link_share',
        'category' => 'industry_tip',
        'name' => 'Link con contexto',
        'description' => 'Compartí un link con un motivo real para leerlo.',
        'content' => "Vale la lectura: [título del artículo/post].\n\nPor qué: [una cosa específica que el texto acierta].\n\n[link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_announce',
        'category' => 'event',
        'name' => 'Anuncio de evento',
        'description' => 'Anunciá un evento o talk próximo.',
        'content' => "[Nombre del evento] el [fecha] a las [hora/timezone].\n\nTema: [qué vamos a cubrir].\nFormato: [talk / Q&A / demo].\n\nGratis, sin registro: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_speaking',
        'category' => 'event',
        'name' => 'Voy a hablar',
        'description' => 'Avisá que vas a hablar en una conferencia.',
        'content' => "Voy a hablar en [evento] el [fecha].\n\nTalk: [título o tema de la talk en palabras simples].\n\nSi andás por ahí, saludá. Especialmente si no estás de acuerdo con la talk.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_recap',
        'category' => 'event',
        'name' => 'Recap del evento',
        'description' => 'Recap corto después de un evento o meetup.',
        'content' => "Recap rápido del [evento]:\n\n• [qué funcionó]\n• [qué nos sorprendió]\n• [qué vamos a hacer distinto la próxima vez]\n\nGracias a todos los que aparecieron.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_event_office_hours',
        'category' => 'event',
        'name' => 'Office hours',
        'description' => 'Invitación a office hours abiertas o AMA.',
        'content' => "Office hours abiertas este [día] a las [hora/timezone].\n\nTraé preguntas reales sobre [tema]. Prefiero responder las difíciles antes que las fáciles.\n\nLink para entrar: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_engagement_question',
        'category' => 'engagement',
        'name' => 'Pregunta real',
        'description' => 'Una pregunta genuina, no engagement bait.',
        'content' => "Pregunta genuina para quien trabaja en [tema]:\n\n[pregunta específica].\n\nNo es retórica. Estoy trabado con esto y curioso por saber cómo lo manejan los demás.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_engagement_poll_lite',
        'category' => 'engagement',
        'name' => 'Dos lados',
        'description' => 'Un o/o liviano para tirar respuestas.',
        'content' => "Dos lados sobre [tema]:\n\nA: [opción A]\nB: [opción B]\n\n¿Cuál usás de verdad en el día a día, y qué te hizo elegirlo?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bluesky_engagement_show_us',
        'category' => 'engagement',
        'name' => 'Mostranos tu setup',
        'description' => 'Invitá a los usuarios a compartir su setup o workflow.',
        'content' => "Mostranos tu [setup / workflow / config] para [tarea].\n\nRespondé con un screenshot o una línea. Estamos juntando buenos patrones para devolver al grupo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
