<?php

declare(strict_types=1);

return [
    [
        'slug' => 'fb_story_announcement',
        'category' => 'product_launch',
        'name' => 'Aviso rápido',
        'description' => 'Atrae atención a una novedad con un Story de 24h en Facebook.',
        'content' => "Aviso de {{brand_name}}.\n\n[Destaque en una línea]\n\nLink en el perfil.",
        'image_count' => 1,
        'image_keywords' => ['announcement', 'launch'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_promo',
        'category' => 'promotion',
        'name' => 'Promo flash',
        'description' => 'Oferta por tiempo limitado en formato Story.',
        'content' => "Solo hoy.\n\n[Descuento]% off en {{brand_name}}.\n\nToca para comprar.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'urgency'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_question',
        'category' => 'engagement',
        'name' => 'Pregunta rápida',
        'description' => 'Pregunta algo a tus seguidores para generar respuestas.',
        'content' => "Rapidito.\n\n[Pregunta para tu audiencia]\n\nResponde este Story.",
        'image_count' => 1,
        'image_keywords' => ['question', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_new_drop',
        'category' => 'product_launch',
        'name' => 'Novedad',
        'description' => 'Presenta un producto nuevo con un toque visual.',
        'content' => "Llegó.\n\n[Nombre del producto] de {{brand_name}}.\n\nToca para verlo.",
        'image_count' => 1,
        'image_keywords' => ['new product', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_preorder',
        'category' => 'product_launch',
        'name' => 'Preventa abierta',
        'description' => 'Abre la preventa con un Story corto.',
        'content' => "Preventa abierta.\n\n[Producto] se envía el [fecha].\n\nLink en bio.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_launch_day',
        'category' => 'product_launch',
        'name' => 'Día del lanzamiento',
        'description' => 'Marca el lanzamiento en vivo con CTA de un toque.',
        'content' => "En vivo ahora.\n\n[Producto] sale hoy.\n\nToca para llevarlo.",
        'image_count' => 1,
        'image_keywords' => ['launch', 'product reveal'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_back_in_stock',
        'category' => 'product_launch',
        'name' => 'Volvió al stock',
        'description' => 'Avisa que un producto agotado volvió.',
        'content' => "Volvió al stock.\n\n[Producto] en {{brand_name}}.\n\nSe va rápido. Toca para ver.",
        'image_count' => 1,
        'image_keywords' => ['restock', 'available'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bogo',
        'category' => 'promotion',
        'name' => 'Lleva 2 paga 1',
        'description' => 'Empuja una oferta lleva 2 paga 1 en Story.',
        'content' => "Lleva 2, paga 1.\n\nEsta semana en {{brand_name}}.\n\nToca para comprar.",
        'image_count' => 1,
        'image_keywords' => ['bogo', 'sale'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_free_shipping',
        'category' => 'promotion',
        'name' => 'Envío gratis',
        'description' => 'Promociona una ventana de envío gratis.',
        'content' => "Envío gratis.\n\n48h solo en {{brand_name}}.\n\nUsa el código [CODE].",
        'image_count' => 1,
        'image_keywords' => ['shipping', 'delivery box'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_last_chance',
        'category' => 'promotion',
        'name' => 'Última oportunidad',
        'description' => 'Aviso final de un descuento que termina.',
        'content' => "Última oportunidad.\n\n[Descuento]% off acaba esta noche.\n\nToca en {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'sale ending'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_coupon_drop',
        'category' => 'promotion',
        'name' => 'Cupón liberado',
        'description' => 'Suelta un código de cupón en un Story de 24h.',
        'content' => "Código [CODE].\n\n[Descuento]% off en {{brand_name}}.\n\nSe va en 24h.",
        'image_count' => 1,
        'image_keywords' => ['coupon', 'promo code'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_quick_tip',
        'category' => 'educational',
        'name' => 'Tip rápido',
        'description' => 'Comparte un tip útil.',
        'content' => "Tip rápido.\n\n[Un tip práctico].\n\nGuarda este Story.",
        'image_count' => 1,
        'image_keywords' => ['tip', 'advice'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_did_you_know',
        'category' => 'educational',
        'name' => 'Sabías que',
        'description' => 'Sorprende a tus seguidores con un dato rápido.',
        'content' => "¿Sabías que?\n\n[Dato curioso].\n\nMás en el blog de {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['fact', 'lightbulb'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_myth_buster',
        'category' => 'educational',
        'name' => 'Mito o verdad',
        'description' => 'Derriba un mito común de un solo golpe.',
        'content' => "Mito: [creencia común].\n\nReal: [verdad].\n\nToca para entender.",
        'image_count' => 1,
        'image_keywords' => ['myth', 'truth'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_one_minute_lesson',
        'category' => 'educational',
        'name' => 'Lección de 1 minuto',
        'description' => 'Lección corta con CTA de toque.',
        'content' => "Lección de 60 segundos.\n\n[Tema] de {{brand_name}}.\n\nToca para verla.",
        'image_count' => 1,
        'image_keywords' => ['lesson', 'teaching'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_workspace',
        'category' => 'behind_the_scenes',
        'name' => 'Detrás de cámaras',
        'description' => 'Muestra el lugar donde todo pasa.',
        'content' => "Hoy en {{brand_name}}.\n\n[Lo que pasa ahora].\n\nToca para ver más.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'office'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_team',
        'category' => 'behind_the_scenes',
        'name' => 'Conoce al equipo',
        'description' => 'Presenta a un miembro del equipo rápido.',
        'content' => "Conoce a [nombre].\n\n[Rol en {{brand_name}}].\n\nToca para saludar.",
        'image_count' => 1,
        'image_keywords' => ['team', 'employee'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_process',
        'category' => 'behind_the_scenes',
        'name' => 'Cómo se hace',
        'description' => 'Vistazo rápido a cómo se produce algo.',
        'content' => "Cómo se hace [producto].\n\nPaso [n] en {{brand_name}}.\n\nToca por el video completo.",
        'image_count' => 1,
        'image_keywords' => ['production', 'process'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_bts_packing',
        'category' => 'behind_the_scenes',
        'name' => 'Empacando pedidos',
        'description' => 'Muestra los pedidos saliendo.',
        'content' => "Empacando pedidos.\n\n[Número] salen hoy.\n\nGracias por el apoyo.",
        'image_count' => 1,
        'image_keywords' => ['packing', 'shipping'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_customer_quote',
        'category' => 'testimonial',
        'name' => 'Frase de cliente',
        'description' => 'Muestra una frase corta de un cliente.',
        'content' => "\"[Frase del cliente].\"\n\n- [nombre]\n\nToca para leer más.",
        'image_count' => 1,
        'image_keywords' => ['quote', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_five_star',
        'category' => 'testimonial',
        'name' => 'Reseña 5 estrellas',
        'description' => 'Destaca una reseña de 5 estrellas.',
        'content' => "5 estrellas.\n\n\"[Reseña corta]\", [nombre]\n\nMás en {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['five stars', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_before_after',
        'category' => 'testimonial',
        'name' => 'Antes y después',
        'description' => 'Muestra un antes/después con un solo CTA.',
        'content' => "Antes. Después.\n\n[Nombre del cliente] usando {{brand_name}}.\n\nToca por la historia.",
        'image_count' => 1,
        'image_keywords' => ['before after', 'transformation'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_industry_trend',
        'category' => 'industry_tip',
        'name' => 'Tendencia del sector',
        'description' => 'Suelta una idea rápida de tendencia.',
        'content' => "Tendencia.\n\n[Tendencia del sector en una línea].\n\nToca por nuestra visión.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_pro_hack',
        'category' => 'industry_tip',
        'name' => 'Hack pro',
        'description' => 'Comparte un hack rápido de profesional.',
        'content' => "Hack pro.\n\n[Truco en una línea].\n\nMás tips en {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['hack', 'shortcut'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_mistake_to_avoid',
        'category' => 'industry_tip',
        'name' => 'Error a evitar',
        'description' => 'Advierte sobre un error común.',
        'content' => "Deja de hacer esto.\n\n[Error común].\n\nToca por la solución.",
        'image_count' => 1,
        'image_keywords' => ['warning', 'mistake'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_save_date',
        'category' => 'event',
        'name' => 'Aparta la fecha',
        'description' => 'Planta un save the date en un Story de 24h.',
        'content' => "Aparta la fecha.\n\n[Evento] el [fecha].\n\nRSVP en bio.",
        'image_count' => 1,
        'image_keywords' => ['calendar', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_today',
        'category' => 'event',
        'name' => 'Evento hoy',
        'description' => 'Recordatorio de evento del mismo día.',
        'content' => "Hoy.\n\n[Evento] a las [hora].\n\nToca por el link.",
        'image_count' => 1,
        'image_keywords' => ['event', 'live'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_live_starting',
        'category' => 'event',
        'name' => 'Vamos en vivo',
        'description' => 'Lleva a tus seguidores a la transmisión.',
        'content' => "Vamos en vivo.\n\n[Tema] en [minutos] minutos.\n\nToca para entrar a {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['live stream', 'broadcast'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_event_recap',
        'category' => 'event',
        'name' => 'Resumen del evento',
        'description' => 'Resumen rápido al día siguiente.',
        'content' => "Eso fue [evento].\n\nGracias por venir.\n\nResumen completo en la página.",
        'image_count' => 1,
        'image_keywords' => ['event recap', 'crowd'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_poll_this_or_that',
        'category' => 'engagement',
        'name' => 'Esta o esa',
        'description' => 'Story tipo encuesta con dos opciones.',
        'content' => "[Opción A] o [Opción B]?\n\nResponde con tu elección.\n\nLeemos todas.",
        'image_count' => 1,
        'image_keywords' => ['poll', 'choice'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_dm_us',
        'category' => 'engagement',
        'name' => 'Mándanos DM',
        'description' => 'Invita a seguidores a mandar mensaje.',
        'content' => "Mándanos DM.\n\n[Motivo para escribir a {{brand_name}}].\n\nRespondemos rápido.",
        'image_count' => 1,
        'image_keywords' => ['message', 'chat'],
        'slides' => null,
    ],
    [
        'slug' => 'fb_story_caption_this',
        'category' => 'engagement',
        'name' => 'Ponle caption',
        'description' => 'Pedido de caption en abierto.',
        'content' => "Ponle caption.\n\n[Contexto de la imagen].\n\nManda el mejor.",
        'image_count' => 1,
        'image_keywords' => ['fun', 'reaction'],
        'slides' => null,
    ],
];
