<?php

declare(strict_types=1);

return [
    [
        'slug' => 'facebook_special_offer',
        'category' => 'promotion',
        'name' => 'Oferta especial',
        'description' => 'Promociona una oferta especial en Facebook con una llamada a la acción clara.',
        'content' => "🎉 Oferta especial de {{brand_name}}.\n\n[Resumen de la oferta], disponible solo hasta [fecha].\n\nHaz clic en el enlace para aprovecharla: [link]\n\n¿Tienes preguntas? Déjalas en los comentarios, leemos cada una.",
        'image_count' => 1,
        'image_keywords' => ['offer', 'sale', 'promotion'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_community_story',
        'category' => 'behind_the_scenes',
        'name' => 'Historia de la comunidad',
        'description' => 'Comparte la historia de un cliente o un momento del equipo para crear conexión.',
        'content' => "Te presentamos a [nombre].\n\n[Historia corta, 2 a 4 frases, sobre cómo usa {{brand_name}} o lo que aporta a nuestra comunidad.]\n\nPor esto hacemos lo que hacemos. ❤️",
        'image_count' => 1,
        'image_keywords' => ['people', 'story', 'community'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_event_invite',
        'category' => 'event',
        'name' => 'Invitación a un evento',
        'description' => 'Invita a tus seguidores a un próximo evento o webinar.',
        'content' => "📅 Aparta la fecha.\n\n{{brand_name}} organiza [nombre del evento] el [fecha] a las [hora].\n\nVamos a hablar de:\n• [Tema 1]\n• [Tema 2]\n• [Tema 3]\n\nLa entrada es gratis. Reserva tu lugar → [link]",
        'image_count' => 1,
        'image_keywords' => ['event', 'calendar', 'invitation'],
        'slides' => null,
    ],

    // Product launch (4)
    [
        'slug' => 'facebook_new_product_reveal',
        'category' => 'product_launch',
        'name' => 'Revelación de nuevo producto',
        'description' => 'Anuncia un producto nuevo a tu comunidad de Facebook.',
        'content' => "Después de [número] meses de trabajo, por fin podemos contarlo.\n\nTe presentamos [nombre del producto], el/la [descripción corta] que creamos porque [motivo]. Nuestro equipo escuchaba lo mismo de la gente de esta comunidad: [pedido frecuente]. Así que lo hicimos.\n\n{{brand_name}} envía el primer lote el [fecha]. El enlace está en el primer comentario.\n\n¿Qué quieres saber sobre él? Deja tu pregunta abajo y respondemos cada una esta semana.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_product_restock',
        'category' => 'product_launch',
        'name' => 'Anuncio de reposición de producto',
        'description' => 'Avisa a tus seguidores que un producto agotado volvió al stock.',
        'content' => "Volvió.\n\n[Nombre del producto] se agotó en [periodo] la última vez, y mucha gente quedó en lista de espera. Repusimos esta mañana con [cantidad] unidades.\n\nSi te lo perdiste antes, este es tu recordatorio: [link]\n\nPara quienes ya tienen uno, ¿qué le dirían a alguien que está pensando en pedirlo?",
        'image_count' => 1,
        'image_keywords' => ['product', 'restock', 'shelf'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_feature_release',
        'category' => 'product_launch',
        'name' => 'Lanzamiento de nueva función',
        'description' => 'Anuncia una nueva función agregada a un producto existente.',
        'content' => "Cambio pequeño, gran diferencia.\n\n{{brand_name}} acaba de liberar [nombre de la función]. Lo pidieron en los comentarios más veces de las que podemos contar, así que aquí está: [explicación en una frase de lo que hace].\n\nYa está disponible para todos a partir de hoy. No hay que actualizar nada.\n\nSi la pruebas esta semana, cuéntanos qué te parece. Ya estamos tomando notas para lo próximo.",
        'image_count' => 1,
        'image_keywords' => ['feature', 'update', 'screen'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_preorder_open',
        'category' => 'product_launch',
        'name' => 'Anuncio de preventa',
        'description' => 'Abre la preventa de un producto que está por lanzarse.',
        'content' => "La preventa está abierta.\n\n[Nombre del producto] se envía el [fecha], y dejamos que esta comunidad ordene primero. El precio de preventa es [precio] hasta [fecha límite], y solo hay [cantidad] lugares en la primera tanda.\n\nAquí está el enlace: [link]\n\nSi tienes dudas sobre [tema común: envío / talla / especificaciones], pregunta en los comentarios. Estamos por aquí toda la tarde.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product', 'package'],
        'slides' => null,
    ],

    // Promotion (3)
    [
        'slug' => 'facebook_flash_sale',
        'category' => 'promotion',
        'name' => 'Alerta de oferta relámpago',
        'description' => 'Anuncia una oferta relámpago de corta duración con sentido de urgencia.',
        'content' => "Oferta relámpago, solo hoy.\n\n[Descuento] en [producto/categoría] hasta medianoche. Usa el código [CÓDIGO] al pagar.\n\nEs el precio más bajo que vamos a ofrecer esta temporada, y no la repetimos hasta [próxima fecha].\n\nEnlace en el primer comentario. Etiqueta a alguien que la tenga en la mira.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_holiday_promo',
        'category' => 'promotion',
        'name' => 'Promoción por fechas especiales',
        'description' => 'Lanza una promoción temática de fechas especiales con tono cercano.',
        'content' => "Feliz [nombre de la fecha] de parte de todos en {{brand_name}}.\n\nPara agradecerte por ser parte de este año, estamos dando [descuento] en [producto/categoría] desde [fecha inicial] hasta [fecha final]. Usa el código [CÓDIGO].\n\nSea lo que sea que estés celebrando esta semana, esperamos que la pases lindo. Cuéntanos en los comentarios cómo vas a vivirla.",
        'image_count' => 1,
        'image_keywords' => ['holiday', 'celebration', 'gift'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_bundle_deal',
        'category' => 'promotion',
        'name' => 'Promoción de combo',
        'description' => 'Promociona un combo de productos con ahorro.',
        'content' => "Dos de nuestros favoritos, mejores juntos.\n\n[Producto A] + [Producto B] ahora son combo, y el combo te ahorra [monto] frente a comprarlos por separado. Los juntamos porque los clientes los pedían en el mismo carrito una y otra vez.\n\nLlévate el tuyo aquí: [link]\n\nSi ya tienes uno de los dos, el otro es la pieza que falta. Confía en nosotros.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'products', 'package'],
        'slides' => null,
    ],

    // Educational (4)
    [
        'slug' => 'facebook_how_to_guide',
        'category' => 'educational',
        'name' => 'Guía paso a paso',
        'description' => 'Enseña a tu audiencia a hacer algo útil.',
        'content' => "Cómo [tarea] en menos de [tiempo].\n\n1. [Paso 1 con un detalle real, no una instrucción vaga]\n2. [Paso 2]\n3. [Paso 3]\n4. [Paso 4]\n\nLa parte que la mayoría se salta es el [número de paso]. Si solo haces una cosa, que sea esa.\n\n¿Cuál es la duda sobre [tema] que siempre dejas para después? Pregunta abajo y la respondemos la próxima semana.",
        'image_count' => 1,
        'image_keywords' => ['tutorial', 'guide', 'how to'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_myth_buster',
        'category' => 'educational',
        'name' => 'Mito vs. realidad',
        'description' => 'Desmonta un mito común de tu industria.',
        'content' => "Hay un mito sobre [tema] que no se va.\n\nEl mito: [creencia común].\n\nLo que pasa en realidad: [explicación correcta, 2 a 3 frases con un ejemplo o número específico].\n\nLo escuchamos hace años. Si tú también lo creías, estás en buena compañía, la mayoría lo creía. Ahora ya lo sabes.\n\n¿Qué otros mitos de [industria] te sacan de quicio?",
        'image_count' => 1,
        'image_keywords' => ['fact check', 'information', 'thinking'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_quick_tip',
        'category' => 'educational',
        'name' => 'Tip rápido',
        'description' => 'Comparte un consejo corto que tu audiencia pueda usar hoy.',
        'content' => "Tip rápido que puedes usar hoy.\n\nSi [situación común], prueba [acción específica] en lugar de [enfoque habitual]. La razón: [explicación en una frase de por qué funciona].\n\nEmpezamos a hacerlo con [ejemplo] y cambió la forma en que [resultado]. Cambio chico, diferencia real.\n\nPruébalo esta semana y cuéntanos cómo te fue.",
        'image_count' => 1,
        'image_keywords' => ['tip', 'lightbulb', 'idea'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_common_mistake',
        'category' => 'educational',
        'name' => 'Error común a evitar',
        'description' => 'Ayuda a tus lectores a evitar un error común en tu campo.',
        'content' => "El error más común que vemos en [tema]: [error específico].\n\nSuele pasar cuando [contexto]. El resultado es [consecuencia], y para cuando te das cuenta, [perjuicio].\n\nQué hacer en lugar de eso: [alternativa clara]. Toma [tiempo/esfuerzo] más al principio y te ahorra [beneficio] después.\n\nSi ya lo cometiste, no estás solo. Nosotros también. ¿Cuál es un error sobre el que te gustaría que alguien te hubiera avisado antes?",
        'image_count' => 1,
        'image_keywords' => ['mistake', 'warning', 'lesson'],
        'slides' => null,
    ],

    // Behind the scenes (4)
    [
        'slug' => 'facebook_team_intro',
        'category' => 'behind_the_scenes',
        'name' => 'Presentación de un miembro del equipo',
        'description' => 'Presenta a un miembro del equipo a la comunidad.',
        'content' => "Saluda a [nombre].\n\n[Nombre] es nuestro/a [puesto] y lleva en {{brand_name}} desde hace [tiempo]. Es la razón por la que [cosa específica que cuida o mejoró], y si alguna vez escribiste a soporte, hay buenas chances de que te haya respondido.\n\nDato curioso: [un detalle humano, hobby, talento raro, snack favorito].\n\nDéjale un saludo en los comentarios.",
        'image_count' => 1,
        'image_keywords' => ['team', 'portrait', 'workplace'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_workspace_tour',
        'category' => 'behind_the_scenes',
        'name' => 'Tour por el espacio de trabajo',
        'description' => 'Muestra a tus seguidores cómo es tu espacio o estudio.',
        'content' => "Un vistazo al lugar donde pasa todo.\n\nEste es [nombre del lugar] de {{brand_name}}. [Un detalle específico, la luz, el desorden, el rincón que todos quieren]. Pasamos casi todo el día aquí, y se nota.\n\n[Segundo detalle, algo visible en la foto que tiene una historia detrás].\n\n¿Cómo está tu espacio de trabajo ahora mismo? Respuesta honesta, con tazas de café incluidas.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'office', 'studio'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_making_of',
        'category' => 'behind_the_scenes',
        'name' => 'Detrás del proceso',
        'description' => 'Muestra cómo se hace un producto o un trabajo.',
        'content' => "¿Te has preguntado cómo se hace de verdad [producto/servicio]?\n\nEmpieza con [primer paso] y termina con [último paso]. En el medio hay mucho de [descripción honesta, prueba, rehacer, dudar]. La versión que terminas comprando suele ser el intento [número].\n\nAquí va una foto del lote de esta semana. El/la [detalle específico] es la parte que nadie ve pero todos notan cuando está bien hecha.\n\n¿Preguntas sobre el proceso? Adelante.",
        'image_count' => 1,
        'image_keywords' => ['workshop', 'process', 'craft'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_milestone_celebration',
        'category' => 'behind_the_scenes',
        'name' => 'Celebración de un hito',
        'description' => 'Celebra un hito importante con la comunidad.',
        'content' => "Hoy es [hito, aniversario, número de clientes, lo que sea real].\n\nArrancamos {{brand_name}} hace [tiempo] con [detalle honesto del origen, una mesa de cocina, un cliente, una laptop prestada]. El plan era simple y un poco ingenuo: [objetivo original].\n\n[Hito] después, seguimos aquí, sobre todo gracias a la gente de esta comunidad que siguió apareciendo. Gracias, en serio.\n\nCuéntanos en los comentarios, ¿cuándo nos descubriste por primera vez?",
        'image_count' => 1,
        'image_keywords' => ['celebration', 'milestone', 'anniversary'],
        'slides' => null,
    ],

    // Testimonial (3)
    [
        'slug' => 'facebook_customer_quote',
        'category' => 'testimonial',
        'name' => 'Testimonio de cliente',
        'description' => 'Comparte un testimonio de cliente con sus propias palabras.',
        'content' => "\"[Cita directa del cliente, mantenla específica, con su voz, con un resultado o sentimiento real.]\"\n\n- [Nombre del cliente], [ciudad o rol]\n\nRecibimos este mensaje hace [tiempo] y le preguntamos si podíamos compartirlo. [Primer nombre] dijo que sí. Estamos agradecidos por palabras así y por todos los que se toman un minuto para mandarlas.\n\nSi {{brand_name}} también fue parte de tu historia, nos encantaría leerte en los comentarios.",
        'image_count' => 1,
        'image_keywords' => ['testimonial', 'happy customer', 'review'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_before_after_story',
        'category' => 'testimonial',
        'name' => 'Historia de antes y después',
        'description' => 'Cuenta una historia de transformación de un cliente.',
        'content' => "Antes: [situación del cliente cuando encontró {{brand_name}}, descríbela en 2 a 3 frases honestas].\n\nDespués: [qué cambió, con un resultado específico y un plazo].\n\n[Nombre del cliente] nos mandó esta actualización el mes pasado, y es de esas cosas que dejan a toda la oficina en silencio un segundo. El trabajo no lo hicimos nosotros, lo hizo él/ella. Solo ayudamos donde podíamos.\n\nSi estás dudando por [duda común], historias así pueden ser la razón para empezar.",
        'image_count' => 1,
        'image_keywords' => ['transformation', 'progress', 'result'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_review_highlight',
        'category' => 'testimonial',
        'name' => 'Reseña destacada',
        'description' => 'Destaca una reseña reciente con contexto.',
        'content' => "Reseña de 5 estrellas de [nombre del cliente] esta semana:\n\n\"[Saca una frase real y concreta de la reseña, no el elogio genérico, la parte con el detalle de verdad.]\"\n\nGuardamos reseñas así y las releemos en los días difíciles. Gracias, [primer nombre].\n\nSi tienes unos minutos y {{brand_name}} te ayudó, dejar una reseña aquí es la cosa más linda que puedes hacer por nosotros: [link]",
        'image_count' => 1,
        'image_keywords' => ['review', 'stars', 'feedback'],
        'slides' => null,
    ],

    // Industry tip (3)
    [
        'slug' => 'facebook_industry_insight',
        'category' => 'industry_tip',
        'name' => 'Insight de la industria',
        'description' => 'Comparte un insight útil de tu industria.',
        'content' => "Algo que notamos trabajando en [industria] este año:\n\n[Observación específica, un cambio, un patrón, un hallazgo contraintuitivo. 2 a 3 frases con un número o ejemplo.]\n\nNo creemos que se revierta pronto, y los negocios que se preparen ahora la van a tener más fácil que los que esperen.\n\n¿Estás viendo lo mismo? Nos da curiosidad cómo lo estás viviendo.",
        'image_count' => 1,
        'image_keywords' => ['insight', 'industry', 'analysis'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_pro_tip',
        'category' => 'industry_tip',
        'name' => 'Consejo de la experiencia',
        'description' => 'Comparte un consejo aprendido en la práctica.',
        'content' => "Un consejo de pro que aprendimos a la mala:\n\nCuando [situación común], siempre [acción específica]. Antes nos saltábamos este paso porque parecía trabajo extra, hasta que [historia, qué salió mal].\n\nAhora es lo primero que hacemos, sin falta. Toma [tiempo] y evita [problema].\n\n¿Qué consejo le darías a alguien que recién empieza en [área]?",
        'image_count' => 1,
        'image_keywords' => ['expertise', 'professional', 'advice'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_industry_trend',
        'category' => 'industry_tip',
        'name' => 'Explicación de una tendencia',
        'description' => 'Explica una tendencia en lenguaje sencillo.',
        'content' => "Todos en [industria] están hablando de [tendencia]. Aquí va lo que significa de verdad, en palabras simples.\n\n[Explicación en 2 a 3 frases sin tecnicismos, con un ejemplo concreto.]\n\nSi cumple lo que promete, ya es otra historia. Nuestra opinión: [opinión honesta, qué tomarse en serio, qué ignorar].\n\n¿Y tú qué piensas? Tenemos curiosidad por saber dónde queda parada la comunidad.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry', 'explainer'],
        'slides' => null,
    ],

    // Event (3)
    [
        'slug' => 'facebook_event_recap',
        'category' => 'event',
        'name' => 'Resumen del evento',
        'description' => 'Comparte un resumen después de que el evento terminó.',
        'content' => "[Nombre del evento] acaba de terminar y todavía nos estamos recuperando.\n\nFueron [número] de ustedes los que se sumaron, hicieron buenas preguntas y se quedaron hasta tarde. Momentos destacados: [momento 1], [momento 2] y la parte donde [cosa graciosa o memorable específica].\n\nGracias enormes a todos los que vinieron. Si te lo perdiste, grabamos la sesión principal y el enlace está en el primer comentario.\n\n¿Cuál fue tu momento favorito del día? Etiqueta a alguien que conociste allí.",
        'image_count' => 1,
        'image_keywords' => ['event', 'recap', 'crowd'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_event_countdown',
        'category' => 'event',
        'name' => 'Cuenta regresiva del evento',
        'description' => 'Genera expectativa a medida que el evento se acerca.',
        'content' => "Faltan [número] días para [nombre del evento].\n\nSi todavía no apartaste tu lugar, ahora es el momento. Quedan [número] cupos, y en la última semana suelen volar.\n\nQué esperar el [fecha]: [un detalle real], [otro detalle real] y tiempo para hablar de verdad con la gente, no solo ver diapositivas.\n\nConsigue tu entrada aquí: [link]\n\n¿Quién va? Comenta para saber a quién buscar.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'event', 'tickets'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_workshop_announcement',
        'category' => 'event',
        'name' => 'Anuncio de taller',
        'description' => 'Anuncia un taller práctico.',
        'content' => "Vamos a hacer un taller sobre [tema].\n\n[Fecha] a las [hora]. Cupos limitados a [número] personas porque es práctico, no un webinar. Te vas con [resultado específico, algo terminado, una configuración funcionando, un plan escrito].\n\nPara quién es: [audiencia]. Para quién no es: [aclaración honesta].\n\nDetalles e inscripción: [link]\n\n¿Dudas sobre si te conviene? Pregunta en los comentarios.",
        'image_count' => 1,
        'image_keywords' => ['workshop', 'learning', 'hands on'],
        'slides' => null,
    ],

    // Engagement (3)
    [
        'slug' => 'facebook_question_prompt',
        'category' => 'engagement',
        'name' => 'Pregunta para la comunidad',
        'description' => 'Hazle una pregunta reflexiva a la comunidad.',
        'content' => "Pregunta sincera para la comunidad.\n\nCuando [situación común relacionada con {{brand_name}}], ¿cómo sueles [decisión específica]? Te preguntamos porque seguimos viendo el mismo tema en los DMs, y tenemos la corazonada de que nuestra respuesta no es la única buena.\n\nNo hay respuestas equivocadas. Leemos cada comentario.",
        'image_count' => 1,
        'image_keywords' => ['question', 'conversation', 'people talking'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_this_or_that',
        'category' => 'engagement',
        'name' => 'Encuesta esto o aquello',
        'description' => 'Lanza una publicación divertida estilo esto o aquello.',
        'content' => "Resuelve un debate que tenemos toda la semana.\n\n¿[Opción A] o [Opción B]?\n\nSin pensarlo mucho. Primer instinto, en los comentarios.\n\nPara que sepas, el equipo está dividido [número] a [número]. Contamos el lado ganador el viernes.",
        'image_count' => 1,
        'image_keywords' => ['choice', 'comparison', 'options'],
        'slides' => null,
    ],
    [
        'slug' => 'facebook_fill_in_blank',
        'category' => 'engagement',
        'name' => 'Completa la frase',
        'description' => 'Invita a tus seguidores a completar una frase.',
        'content' => "Completa la frase:\n\nLo que ojalá hubiera sabido antes de [tema] es __________.\n\nEmpezamos nosotros: [tu respuesta honesta, con una historia real al lado].\n\nTu turno. Las mejores respuestas que recibimos en estas preguntas terminan ayudando a alguien que las lee después, así que no te guardes nada.",
        'image_count' => 1,
        'image_keywords' => ['conversation', 'thinking', 'community'],
        'slides' => null,
    ],
];
