<?php

declare(strict_types=1);

return [
    [
        'slug' => 'story_announcement',
        'category' => 'product_launch',
        'name' => 'Aviso rápido',
        'description' => 'Llama la atención sobre un lanzamiento o novedad con un Story de 24 horas.',
        'content' => "Novedad en {{brand_name}}.\n\nToca el enlace para ver lo nuevo.",
        'image_count' => 1,
        'image_keywords' => ['announcement', 'launch'],
        'slides' => null,
    ],
    [
        'slug' => 'story_poll_question',
        'category' => 'engagement',
        'name' => 'Encuesta rápida',
        'description' => 'Usa un Story para hacer una pregunta rápida y enganchar a tu audiencia.',
        'content' => "¿Qué es lo más importante al elegir un [producto/servicio]?\n\nToca para votar.",
        'image_count' => 1,
        'image_keywords' => ['question', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'story_flash_promo',
        'category' => 'promotion',
        'name' => 'Promo relámpago',
        'description' => 'Oferta por tiempo limitado en formato Story con urgencia.',
        'content' => "Solo por 24 horas.\n\n[Descuento]% off en {{brand_name}}.\n\nDesliza hacia arriba.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'urgency'],
        'slides' => null,
    ],

    // product_launch
    [
        'slug' => 'story_product_drop',
        'category' => 'product_launch',
        'name' => 'Lanzamiento de producto',
        'description' => 'Anuncia un producto nuevo que sale hoy.',
        'content' => "Ya está.\n\n[Nombre del producto] acaba de salir.\n\nEnlace en la bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'new'],
        'slides' => null,
    ],
    [
        'slug' => 'story_feature_shipped',
        'category' => 'product_launch',
        'name' => 'Función publicada',
        'description' => 'Cuéntales a tus seguidores sobre una función que acabas de lanzar.',
        'content' => "Acabamos de lanzar [función].\n\nPruébala.",
        'image_count' => 1,
        'image_keywords' => ['update', 'feature', 'app'],
        'slides' => null,
    ],
    [
        'slug' => 'story_waitlist_open',
        'category' => 'product_launch',
        'name' => 'Lista de espera abierta',
        'description' => 'Invita a tus seguidores a unirse a la lista de espera.',
        'content' => "Lista de espera abierta.\n\nQuedan [Cupos] cupos.\n\nEnlace en la bio.",
        'image_count' => 1,
        'image_keywords' => ['waitlist', 'signup'],
        'slides' => null,
    ],
    [
        'slug' => 'story_preorder_live',
        'category' => 'product_launch',
        'name' => 'Preventa activa',
        'description' => 'Impulsa las preventas de un producto que viene en camino.',
        'content' => "Preventa abierta.\n\nEnvíos el [fecha].\n\nToca para reservar el tuyo.",
        'image_count' => 1,
        'image_keywords' => ['preorder', 'product'],
        'slides' => null,
    ],

    // promotion
    [
        'slug' => 'story_weekend_sale',
        'category' => 'promotion',
        'name' => 'Promo de fin de semana',
        'description' => 'Impulsa una promo rápida de fin de semana.',
        'content' => "Promo de fin de semana.\n\n[Descuento]% off en todo.\n\nTermina el domingo.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'weekend', 'discount'],
        'slides' => null,
    ],
    [
        'slug' => 'story_code_drop',
        'category' => 'promotion',
        'name' => 'Código de descuento',
        'description' => 'Comparte un código que tus seguidores pueden usar al pagar.',
        'content' => "Usa [CÓDIGO] al pagar.\n\n[Descuento]% off.\n\nVálido hasta [fecha].",
        'image_count' => 1,
        'image_keywords' => ['coupon', 'code', 'discount'],
        'slides' => null,
    ],
    [
        'slug' => 'story_last_chance',
        'category' => 'promotion',
        'name' => 'Última oportunidad',
        'description' => 'Recordatorio final antes de que termine la promo.',
        'content' => "Última oportunidad.\n\n[Oferta] termina a medianoche.",
        'image_count' => 1,
        'image_keywords' => ['deadline', 'sale', 'urgent'],
        'slides' => null,
    ],
    [
        'slug' => 'story_bundle_deal',
        'category' => 'promotion',
        'name' => 'Combo promocional',
        'description' => 'Promociona un combo a un precio menor.',
        'content' => "Combo promocional.\n\n[Ítem A] + [Ítem B] por [precio].\n\nToca para llevarlo.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'deal', 'product'],
        'slides' => null,
    ],

    // educational
    [
        'slug' => 'story_quick_tip',
        'category' => 'educational',
        'name' => 'Tip rápido',
        'description' => 'Comparte un tip corto en pantalla.',
        'content' => "Tip rápido:\n\n[Un tip corto y práctico].",
        'image_count' => 1,
        'image_keywords' => ['tip', 'advice', 'learning'],
        'slides' => null,
    ],
    [
        'slug' => 'story_did_you_know',
        'category' => 'educational',
        'name' => 'Sabías que',
        'description' => 'Suelta un dato sorprendente.',
        'content' => "¿Sabías que…?\n\n[Dato sorprendente sobre tu nicho].",
        'image_count' => 1,
        'image_keywords' => ['fact', 'knowledge'],
        'slides' => null,
    ],
    [
        'slug' => 'story_common_mistake',
        'category' => 'educational',
        'name' => 'Error común',
        'description' => 'Señala un error que tu audiencia suele cometer.',
        'content' => "Deja de [error común].\n\nHaz [mejor enfoque] en su lugar.",
        'image_count' => 1,
        'image_keywords' => ['mistake', 'advice', 'tip'],
        'slides' => null,
    ],
    [
        'slug' => 'story_one_word_lesson',
        'category' => 'educational',
        'name' => 'Lección en una palabra',
        'description' => 'Una sola palabra seguida de un porqué corto.',
        'content' => "[Una palabra].\n\nEsa es la diferencia entre [resultado A] y [resultado B].",
        'image_count' => 1,
        'image_keywords' => ['lesson', 'word', 'idea'],
        'slides' => null,
    ],

    // behind_the_scenes
    [
        'slug' => 'story_workspace_peek',
        'category' => 'behind_the_scenes',
        'name' => 'Vistazo al espacio',
        'description' => 'Foto rápida de donde sucede el trabajo.',
        'content' => "Donde sucede el trabajo.\n\n[Pie corto sobre tu espacio].",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'desk', 'office'],
        'slides' => null,
    ],
    [
        'slug' => 'story_meet_the_team',
        'category' => 'behind_the_scenes',
        'name' => 'Conoce al equipo',
        'description' => 'Presenta a alguien del equipo en una línea.',
        'content' => "Conoce a [nombre].\n\n[Su rol en {{brand_name}}].",
        'image_count' => 1,
        'image_keywords' => ['team', 'people', 'portrait'],
        'slides' => null,
    ],
    [
        'slug' => 'story_in_progress',
        'category' => 'behind_the_scenes',
        'name' => 'En proceso',
        'description' => 'Muestra algo a medio hacer.',
        'content' => "En proceso.\n\n[En qué estás trabajando ahora].",
        'image_count' => 1,
        'image_keywords' => ['process', 'work', 'progress'],
        'slides' => null,
    ],
    [
        'slug' => 'story_packing_orders',
        'category' => 'behind_the_scenes',
        'name' => 'Pedidos saliendo',
        'description' => 'Muestra los pedidos saliendo a la calle.',
        'content' => "Pedidos de hoy.\n\nGracias por confiar en {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['packaging', 'orders', 'shipping'],
        'slides' => null,
    ],

    // testimonial
    [
        'slug' => 'story_customer_quote',
        'category' => 'testimonial',
        'name' => 'Cita de cliente',
        'description' => 'Comparte una cita corta de un cliente en pantalla.',
        'content' => "\"[Cita corta del cliente].\"\n\n- [Nombre del cliente]",
        'image_count' => 1,
        'image_keywords' => ['testimonial', 'review', 'quote'],
        'slides' => null,
    ],
    [
        'slug' => 'story_review_screenshot',
        'category' => 'testimonial',
        'name' => 'Captura de reseña',
        'description' => 'Repostea una captura de una reseña genial.',
        'content' => "Reseñas así nos alegran la semana.\n\nGracias, [primer nombre del cliente].",
        'image_count' => 1,
        'image_keywords' => ['review', 'screenshot', 'feedback'],
        'slides' => null,
    ],
    [
        'slug' => 'story_before_after_user',
        'category' => 'testimonial',
        'name' => 'Antes y después del cliente',
        'description' => 'Destaca el resultado de un cliente.',
        'content' => '[Primer nombre del cliente] pasó de [antes] a [después] en [tiempo].',
        'image_count' => 1,
        'image_keywords' => ['result', 'transformation', 'customer'],
        'slides' => null,
    ],

    // industry_tip
    [
        'slug' => 'story_industry_myth',
        'category' => 'industry_tip',
        'name' => 'Mito del sector',
        'description' => 'Derriba una creencia común en tu rubro.',
        'content' => "Mito: [creencia común].\n\nRealidad: [la verdad].",
        'image_count' => 1,
        'image_keywords' => ['myth', 'industry', 'truth'],
        'slides' => null,
    ],
    [
        'slug' => 'story_industry_stat',
        'category' => 'industry_tip',
        'name' => 'Dato del sector',
        'description' => 'Suelta un dato que llama la atención.',
        'content' => "[Dato].\n\nPor eso creamos {{brand_name}}.",
        'image_count' => 1,
        'image_keywords' => ['statistic', 'data', 'industry'],
        'slides' => null,
    ],
    [
        'slug' => 'story_tool_we_use',
        'category' => 'industry_tip',
        'name' => 'Herramienta que usamos',
        'description' => 'Recomienda una herramienta que tu audiencia puede probar.',
        'content' => "Herramienta que usamos a diario:\n\n[Nombre de la herramienta].\n\nPor qué: [un motivo corto].",
        'image_count' => 1,
        'image_keywords' => ['tool', 'software', 'recommendation'],
        'slides' => null,
    ],
    [
        'slug' => 'story_red_flag',
        'category' => 'industry_tip',
        'name' => 'Señal de alerta',
        'description' => 'Avisa a tus seguidores sobre una señal de alerta en tu sector.',
        'content' => "Señal de alerta en [sector]:\n\n[La señal a la que prestar atención].",
        'image_count' => 1,
        'image_keywords' => ['warning', 'industry', 'advice'],
        'slides' => null,
    ],

    // event
    [
        'slug' => 'story_event_today',
        'category' => 'event',
        'name' => 'Evento hoy',
        'description' => 'Recordatorio de último momento para un evento del mismo día.',
        'content' => "Esta noche.\n\n[Nombre del evento] a las [hora].\n\nToca el enlace.",
        'image_count' => 1,
        'image_keywords' => ['event', 'reminder'],
        'slides' => null,
    ],
    [
        'slug' => 'story_event_countdown',
        'category' => 'event',
        'name' => 'Cuenta regresiva',
        'description' => 'Genera expectativa con una cuenta regresiva.',
        'content' => "[X] días para [nombre del evento].\n\nResponde VOY para recibir el recordatorio.",
        'image_count' => 1,
        'image_keywords' => ['countdown', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'story_live_now',
        'category' => 'event',
        'name' => 'En vivo ahora',
        'description' => 'Avisa a tus seguidores que estás en vivo o en escenario.',
        'content' => "En vivo ahora.\n\n[Tema o lugar].\n\nVen a saludar.",
        'image_count' => 1,
        'image_keywords' => ['live', 'streaming', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'story_event_recap',
        'category' => 'event',
        'name' => 'Resumen del evento',
        'description' => 'Resumen rápido cuando termina el evento.',
        'content' => "[Nombre del evento] terminó.\n\nGracias a quienes nos acompañaron.",
        'image_count' => 1,
        'image_keywords' => ['event', 'recap', 'crowd'],
        'slides' => null,
    ],

    // engagement
    [
        'slug' => 'story_this_or_that',
        'category' => 'engagement',
        'name' => 'Esto o aquello',
        'description' => 'Encuesta de dos opciones para toques rápidos.',
        'content' => "¿[Opción A] u [Opción B]?\n\nToca para votar.",
        'image_count' => 1,
        'image_keywords' => ['poll', 'choice', 'vote'],
        'slides' => null,
    ],
    [
        'slug' => 'story_question_box',
        'category' => 'engagement',
        'name' => 'Caja de preguntas',
        'description' => 'Abre el espacio a preguntas.',
        'content' => "Pregúntame lo que quieras sobre [tema].\n\nResponde con tu pregunta.",
        'image_count' => 1,
        'image_keywords' => ['questions', 'ama', 'conversation'],
        'slides' => null,
    ],
    [
        'slug' => 'story_emoji_slider',
        'category' => 'engagement',
        'name' => 'Slider de emoji',
        'description' => 'Usa el sticker de slider para medir una sensación.',
        'content' => "¿Qué tan emocionado estás con [cosa]?\n\nMueve el slider.",
        'image_count' => 1,
        'image_keywords' => ['slider', 'reaction', 'engagement'],
        'slides' => null,
    ],
    [
        'slug' => 'story_dm_prompt',
        'category' => 'engagement',
        'name' => 'Llamada al DM',
        'description' => 'Anima a tus seguidores a enviar una palabra clave por DM.',
        'content' => "¿Quieres [recurso]?\n\nResponde [palabra clave] y te lo envío.",
        'image_count' => 1,
        'image_keywords' => ['dm', 'message', 'engagement'],
        'slides' => null,
    ],
];
