<?php

declare(strict_types=1);

return [
    [
        'slug' => 'feature_launch_carousel',
        'category' => 'product_launch',
        'name' => 'Lanzamiento de funcionalidad',
        'description' => 'Anuncia una nueva funcionalidad del producto en un carrusel de 5 slides.',
        'content' => '{{brand_name}} acaba de lanzar algo que nos tiene entusiasmados. Desliza para ver lo nuevo.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Lo nuevo', 'body' => 'Un vistazo rápido a la última actualización.', 'image_keywords' => ['product', 'launch']],
            ['title' => 'Cómo funciona', 'body' => 'Tres pasos y ya estás usándolo.', 'image_keywords' => ['workflow']],
            ['title' => 'Por qué importa', 'body' => 'Más rápido, más simple, con menos clics.', 'image_keywords' => ['speed']],
            ['title' => 'Para quién es', 'body' => 'Hecho para equipos que entregan.', 'image_keywords' => ['team']],
            ['title' => 'Pruébalo ya', 'body' => 'Disponible hoy. Link en bio.', 'image_keywords' => ['phone', 'app']],
        ],
    ],
    [
        'slug' => 'five_tips_carousel',
        'category' => 'educational',
        'name' => 'Carrusel de 5 consejos',
        'description' => 'Comparte cinco consejos prácticos en un carrusel deslizable.',
        'content' => '5 cosas que me hubiera gustado saber antes sobre [tema]. Guárdalo para después. 👇',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Consejo #1', 'body' => '[Primer consejo, sé específico y práctico.]', 'image_keywords' => ['idea', 'lightbulb']],
            ['title' => 'Consejo #2', 'body' => '[Segundo consejo, usa un ejemplo real si puedes.]', 'image_keywords' => ['notebook']],
            ['title' => 'Consejo #3', 'body' => '[Tercer consejo, sé breve.]', 'image_keywords' => ['focus']],
            ['title' => 'Consejo #4', 'body' => '[Cuarto consejo, algo sorprendente o que va contra la intuición.]', 'image_keywords' => ['surprise']],
            ['title' => 'Consejo #5', 'body' => '[Quinto consejo, cierra fuerte con una conclusión.]', 'image_keywords' => ['success']],
        ],
    ],
    [
        'slug' => 'process_reveal_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Mostrando el proceso',
        'description' => 'Lleva a tus seguidores por el proceso de cómo creas tu producto o servicio.',
        'content' => '¿Te has preguntado cómo se hace [producto/servicio]? Desliza para ver cada paso. ✨',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Todo empieza con investigación', 'body' => 'Cada proyecto arranca entendiendo el problema a fondo.', 'image_keywords' => ['research', 'desk']],
            ['title' => 'Diseño e iteración', 'body' => 'Prototipamos rápido y probamos seguido.', 'image_keywords' => ['design', 'sketch']],
            ['title' => 'Construyendo lo real', 'body' => 'Oficio y precisión en cada detalle.', 'image_keywords' => ['craft', 'build']],
            ['title' => 'El resultado final', 'body' => 'Una calidad que se siente desde que lo usas.', 'image_keywords' => ['product', 'final']],
        ],
    ],
    [
        'slug' => 'quick_stat_carousel',
        'category' => 'industry_tip',
        'name' => 'Carrusel de estadísticas rápidas',
        'description' => 'Presenta datos del sector en formato de carrusel visual.',
        'content' => 'Los números de [sector] que cualquier persona de marketing debería tener en el radar este año. 📊',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Dato #1', 'body' => '[X]% de [audiencia] dice [hallazgo]. Fuente: [fuente]', 'image_keywords' => ['chart', 'data']],
            ['title' => 'Dato #2', 'body' => '[Y]% de aumento en [métrica] año contra año.', 'image_keywords' => ['growth', 'graph']],
            ['title' => 'Dato #3', 'body' => 'Para [año], [proyección].', 'image_keywords' => ['future', 'trend']],
            ['title' => 'Qué significa esto para ti', 'body' => '[Conclusión práctica con base en los datos de arriba.]', 'image_keywords' => ['action', 'plan']],
        ],
    ],
    [
        'slug' => 'event_recap_carousel',
        'category' => 'event',
        'name' => 'Resumen del evento',
        'description' => 'Recapitula los mejores momentos de un evento o conferencia reciente.',
        'content' => 'Acabamos de cerrar [Nombre del Evento] y fue increíble. Aquí los destacados. 🙌',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'Todo empezó con…', 'body' => '[Momento de apertura o destacado de la charla principal.]', 'image_keywords' => ['conference', 'stage']],
            ['title' => 'La charla de la que todos hablaron', 'body' => '[Idea clave de la charla más comentada.]', 'image_keywords' => ['presentation', 'crowd']],
            ['title' => 'Conectando con la comunidad', 'body' => '[Destaca momentos de networking o con asistentes.]', 'image_keywords' => ['networking', 'people']],
            ['title' => 'Hasta la próxima', 'body' => 'Sigue a {{brand_name}} para novedades sobre nuestro próximo evento.', 'image_keywords' => ['celebration']],
        ],
    ],
    [
        'slug' => 'product_lineup_carousel',
        'category' => 'product_launch',
        'name' => 'Revelación de la línea de productos',
        'description' => 'Muestra una línea completa de productos, uno por slide.',
        'content' => 'Hicimos [número] cosas nuevas. Aquí va la línea completa de {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'conoce la línea', 'body' => '[Número] piezas nuevas, pensadas en conjunto. Cada una resuelve un problema específico.', 'image_keywords' => ['products', 'lineup']],
            ['title' => 'pieza uno', 'body' => '[Nombre del producto 1]. Ideal para [caso de uso].', 'image_keywords' => ['product', 'studio']],
            ['title' => 'pieza dos', 'body' => '[Nombre del producto 2]. Va bien con la pieza uno si buscas [beneficio].', 'image_keywords' => ['object', 'detail']],
            ['title' => 'pieza tres', 'body' => '[Nombre del producto 3]. La que seguimos iterando hasta que quedó como queríamos.', 'image_keywords' => ['craft', 'closeup']],
            ['title' => 'compra el lanzamiento', 'body' => 'Disponible [fecha]. Link en bio.', 'image_keywords' => ['shop', 'phone']],
        ],
    ],
    [
        'slug' => 'before_after_launch_carousel',
        'category' => 'product_launch',
        'name' => 'Antes y después del lanzamiento',
        'description' => 'Muestra el cambio de la versión vieja a la nueva.',
        'content' => 'La misma idea, reconstruida. Esto fue lo que cambió en el nuevo [producto] de {{brand_name}}.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'antes', 'body' => '[La versión vieja. Lo que hacía bien y dónde se quedaba corta.]', 'image_keywords' => ['old', 'product']],
            ['title' => 'después', 'body' => '[La nueva versión. Una frase sobre el mayor cambio.]', 'image_keywords' => ['new', 'product']],
            ['title' => 'qué arreglamos', 'body' => '[Problema concreto que nos contaron los clientes y cómo lo resolvimos.]', 'image_keywords' => ['detail', 'redesign']],
            ['title' => 'ya disponible', 'body' => 'Encuéntralo en la tienda. Link en bio.', 'image_keywords' => ['store', 'phone']],
        ],
    ],
    [
        'slug' => 'spec_breakdown_carousel',
        'category' => 'product_launch',
        'name' => 'Carrusel con la ficha técnica',
        'description' => 'Desglosa las especificaciones del producto en varios slides.',
        'content' => 'La ficha técnica completa de [producto]. Todo lo que trae adentro, en un solo carrusel.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'conoce [producto]', 'body' => 'Hecho para [caso de uso]. Disponible [fecha].', 'image_keywords' => ['product', 'reveal']],
            ['title' => 'materiales', 'body' => '[Detalles del material. De dónde viene. Por qué importa para el tacto final.]', 'image_keywords' => ['materials', 'texture']],
            ['title' => 'dimensiones', 'body' => '[Tamaño, peso, notas de calce. Los números que la gente quiere antes de comprar.]', 'image_keywords' => ['measurement', 'detail']],
            ['title' => 'cómo rinde', 'body' => '[Número de desempeño clave. Batería, autonomía, fuerza de agarre, lo que aplique.]', 'image_keywords' => ['performance', 'test']],
            ['title' => 'qué viene en la caja', 'body' => '[Lista los items: producto, accesorios, manual, etc.]', 'image_keywords' => ['unboxing', 'box']],
            ['title' => 'pide el tuyo', 'body' => 'Link en bio. Envío en [plazo].', 'image_keywords' => ['shipping', 'parcel']],
        ],
    ],
    [
        'slug' => 'flash_sale_carousel',
        'category' => 'promotion',
        'name' => 'Promoción flash',
        'description' => 'Promociona una oferta por tiempo limitado en varios slides.',
        'content' => '[Descuento]% de descuento en las próximas [horas] horas en {{brand_name}}. Lee cada slide para no perdértelo.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'promoción flash activa', 'body' => '[Descuento]% off hasta [fecha y hora final]. Sin código.', 'image_keywords' => ['sale', 'tag']],
            ['title' => 'qué incluye', 'body' => '[Categorías en oferta y exclusiones si las hay. Sé honesto sobre lo que no entra.]', 'image_keywords' => ['products', 'shop']],
            ['title' => 'los más queridos', 'body' => '[Dos o tres bestsellers que la gente agarra primero cuando hay ofertas.]', 'image_keywords' => ['favorites', 'shelf']],
            ['title' => 'compra antes que termine', 'body' => 'Link en bio. Cuando se acaba el stock, se acabó.', 'image_keywords' => ['phone', 'cart']],
        ],
    ],
    [
        'slug' => 'bundle_deal_carousel',
        'category' => 'promotion',
        'name' => 'Carrusel del combo',
        'description' => 'Explica una oferta de combo slide por slide.',
        'content' => 'Tres cosas, un solo precio. Ahorra [monto] llevándolas juntas en {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'el combo', 'body' => '[Descripción breve de lo que trae el combo y cuánto ahorras en total.]', 'image_keywords' => ['bundle', 'box']],
            ['title' => 'item uno', 'body' => '[Primer item del combo y qué hace por sí solo.]', 'image_keywords' => ['product', 'one']],
            ['title' => 'item dos', 'body' => '[Segundo item y por qué combina con el primero.]', 'image_keywords' => ['product', 'two']],
            ['title' => 'item tres', 'body' => '[Tercer item. El que termina de armar el combo.]', 'image_keywords' => ['product', 'three']],
            ['title' => 'llévate el combo', 'body' => 'Ahorra [monto]. Disponible mientras dure el stock.', 'image_keywords' => ['bag', 'shopping']],
        ],
    ],
    [
        'slug' => 'first_order_discount_carousel',
        'category' => 'promotion',
        'name' => 'Descuento en la primera compra',
        'description' => 'Da la bienvenida a clientes nuevos con un descuento en la primera compra.',
        'content' => '¿Nuevo por aquí? Usa el código [CÓDIGO] para [descuento]% off en tu primera compra en {{brand_name}}.',
        'image_count' => 3,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'oferta de bienvenida', 'body' => '[Descuento]% off en tu primera compra. Código: [CÓDIGO]. Válido por [duración].', 'image_keywords' => ['welcome', 'gift']],
            ['title' => 'por dónde empieza la gente', 'body' => '[Uno o dos productos que son buenos puntos de entrada para clientes nuevos.]', 'image_keywords' => ['bestseller', 'product']],
            ['title' => 'cómo usarlo', 'body' => 'Agrega al carrito, pega [CÓDIGO] al pagar. Link en bio.', 'image_keywords' => ['checkout', 'phone']],
        ],
    ],
    [
        'slug' => 'free_shipping_carousel',
        'category' => 'promotion',
        'name' => 'Fin de semana con envío gratis',
        'description' => 'Promociona una ventana limitada de envío gratis.',
        'content' => 'Envío gratis en {{brand_name}} solo este fin de semana. Sin monto mínimo.',
        'image_count' => 3,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'fin de semana con envío gratis', 'body' => 'De [viernes] a [domingo]. Sin código y sin pedido mínimo.', 'image_keywords' => ['shipping', 'box']],
            ['title' => 'a dónde enviamos', 'body' => '[Regiones o países incluidos. Aclara cualquier exclusión.]', 'image_keywords' => ['map', 'globe']],
            ['title' => 'aprovecha el fin de semana', 'body' => 'Toca el link en bio antes de la medianoche del [domingo] [zona horaria].', 'image_keywords' => ['cart', 'phone']],
        ],
    ],
    [
        'slug' => 'beginner_guide_carousel',
        'category' => 'educational',
        'name' => 'Carrusel guía para principiantes',
        'description' => 'Enseña un tema desde cero hasta el primer resultado útil.',
        'content' => '[Tema] para principiantes absolutos. Guárdalo para después. 👇',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'empieza aquí', 'body' => 'Si [tema] te parece abrumador, esta es la versión que me ayudó cuando recién empezaba.', 'image_keywords' => ['beginner', 'notes']],
            ['title' => 'qué es en realidad', 'body' => '[Definición simple. Sin jerga. Una frase basta.]', 'image_keywords' => ['concept', 'sketch']],
            ['title' => 'por qué le importa a la gente', 'body' => '[La razón concreta por la que un principiante se molestaría en aprender esto.]', 'image_keywords' => ['question', 'curious']],
            ['title' => 'lo primero para probar', 'body' => '[Una acción pequeña y específica que puedan hacer en menos de 10 minutos.]', 'image_keywords' => ['hands', 'desk']],
            ['title' => 'error común', 'body' => '[La trampa en la que cae la mayoría de los principiantes. Sé específico.]', 'image_keywords' => ['mistake', 'fix']],
            ['title' => 'a dónde ir después', 'body' => '[Un libro, canal o recurso de {{brand_name}} para el siguiente paso.]', 'image_keywords' => ['library', 'resource']],
        ],
    ],
    [
        'slug' => 'common_mistakes_carousel',
        'category' => 'educational',
        'name' => 'Errores comunes',
        'description' => 'Resalta errores comunes y cómo corregirlos.',
        'content' => '5 errores que veo todo el tiempo con [tema]. El número 3 me tocó aprenderlo a las malas.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'los errores', 'body' => 'Cinco cosas que la gente hace mal con [tema] y qué hacer en su lugar.', 'image_keywords' => ['mistake', 'pen']],
            ['title' => 'error 1', 'body' => '[Primer error. Después la solución en una frase.]', 'image_keywords' => ['error', 'paper']],
            ['title' => 'error 2', 'body' => '[Segundo error y la solución.]', 'image_keywords' => ['confused', 'desk']],
            ['title' => 'error 3', 'body' => '[Tercer error. El que sorprende a la gente.]', 'image_keywords' => ['surprised', 'thought']],
            ['title' => 'error 4', 'body' => '[Cuarto error y la solución.]', 'image_keywords' => ['process', 'workspace']],
            ['title' => 'error 5', 'body' => '[Último error. Cierra con lo que harías en su lugar.]', 'image_keywords' => ['solution', 'check']],
        ],
    ],
    [
        'slug' => 'glossary_carousel',
        'category' => 'educational',
        'name' => 'Carrusel glosario',
        'description' => 'Define cinco términos de tu sector en lenguaje simple.',
        'content' => '5 términos de [sector] explicados sin jerga. Guárdalo para después.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'jerga decodificada', 'body' => 'Cinco palabras de [sector] que la gente usa como si todos las conocieran.', 'image_keywords' => ['dictionary', 'book']],
            ['title' => '[término 1]', 'body' => '[Definición simple. Una frase de ejemplo.]', 'image_keywords' => ['letters', 'text']],
            ['title' => '[término 2]', 'body' => '[Definición simple. Una frase de ejemplo.]', 'image_keywords' => ['letters', 'paper']],
            ['title' => '[término 3]', 'body' => '[Definición simple. Una frase de ejemplo.]', 'image_keywords' => ['note', 'pen']],
            ['title' => '[término 4]', 'body' => '[Definición simple. Una frase de ejemplo.]', 'image_keywords' => ['definition', 'page']],
            ['title' => '[término 5]', 'body' => '[Definición simple. Una frase de ejemplo.]', 'image_keywords' => ['glossary', 'open book']],
        ],
    ],
    [
        'slug' => 'step_by_step_tutorial_carousel',
        'category' => 'educational',
        'name' => 'Tutorial paso a paso',
        'description' => 'Guía a través de un cómo-hacer breve en pasos claros.',
        'content' => 'Cómo [tarea] en [número] pasos. Guárdalo para tenerlo a mano la próxima.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'qué necesitas', 'body' => '[Lista las herramientas o materiales. Mantenlo breve.]', 'image_keywords' => ['tools', 'supplies']],
            ['title' => 'paso 1', 'body' => '[Primer paso. Una acción específica, no un objetivo.]', 'image_keywords' => ['hands', 'work']],
            ['title' => 'paso 2', 'body' => '[Segundo paso. Cómo debería verse antes de avanzar.]', 'image_keywords' => ['progress', 'desk']],
            ['title' => 'paso 3', 'body' => '[Tercer paso. Menciona aquí el desliz más común.]', 'image_keywords' => ['focus', 'detail']],
            ['title' => 'listo', 'body' => '[Cómo debería verse el resultado final. Una idea de foto.]', 'image_keywords' => ['finished', 'result']],
        ],
    ],
    [
        'slug' => 'team_intro_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Conoce al equipo',
        'description' => 'Presenta a los miembros del equipo de a uno por slide.',
        'content' => 'Las caras detrás de {{brand_name}}. Desliza para conocer a quienes hacen que esto funcione.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'el equipo', 'body' => 'Somos [número] personas en [ubicaciones]. Aquí va quién hace qué.', 'image_keywords' => ['team', 'office']],
            ['title' => '[nombre 1]', 'body' => '[Rol. Algo que tiene a su cargo y algo que disfruta fuera del trabajo.]', 'image_keywords' => ['portrait', 'work']],
            ['title' => '[nombre 2]', 'body' => '[Rol. Un detalle que muestra su personalidad, no solo su cargo.]', 'image_keywords' => ['portrait', 'desk']],
            ['title' => '[nombre 3]', 'body' => '[Rol. Algo concreto que hizo este mes.]', 'image_keywords' => ['portrait', 'studio']],
            ['title' => 'salúdanos', 'body' => 'Los DM están abiertos. Los respondemos nosotros mismos.', 'image_keywords' => ['phone', 'chat']],
        ],
    ],
    [
        'slug' => 'workspace_tour_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Recorrido por el espacio de trabajo',
        'description' => 'Muestra tu estudio, cocina u oficina en varios slides.',
        'content' => 'Un recorrido por donde {{brand_name}} se hace de verdad. Menos pulido de lo que piensas.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'donde pasa todo', 'body' => '[Ubicación, tamaño, qué tipo de espacio es, en una frase.]', 'image_keywords' => ['studio', 'workshop']],
            ['title' => 'la mesa de trabajo', 'body' => '[Lo que vive en la mesa principal la mayoría de los días.]', 'image_keywords' => ['workbench', 'tools']],
            ['title' => 'el rincón que nadie ve', 'body' => '[Detalle honesto: una repisa desordenada, una pared con notas, la cafetera.]', 'image_keywords' => ['corner', 'mess']],
            ['title' => 'el lugar favorito', 'body' => '[La silla, la ventana, la luz que mejora el día.]', 'image_keywords' => ['light', 'window']],
            ['title' => 'vuelve pronto', 'body' => 'Vienen más vistazos. Sigue a {{brand_name}} para el próximo.', 'image_keywords' => ['camera', 'door']],
        ],
    ],
    [
        'slug' => 'a_day_in_the_life_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Un día en la rutina',
        'description' => 'Muestra una jornada de trabajo de la mañana a la noche.',
        'content' => 'Un día real en {{brand_name}}, hora por hora. Sin la versión maquillada.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => '7:30 a. m.', 'body' => '[Cómo arranca el día de verdad. Café, caminata, correo, lo que sea.]', 'image_keywords' => ['morning', 'coffee']],
            ['title' => '9:00 a. m.', 'body' => '[Lo primero en la agenda. Sé específico sobre qué se hace.]', 'image_keywords' => ['desk', 'laptop']],
            ['title' => '12:30 p. m.', 'body' => '[Almuerzo. Dónde, con quién, o solo con un podcast.]', 'image_keywords' => ['lunch', 'food']],
            ['title' => '2:00 p. m.', 'body' => '[Bloque de la tarde. Lo que más concentración pide ese día.]', 'image_keywords' => ['focus', 'work']],
            ['title' => '5:30 p. m.', 'body' => '[Cerrando. Cuál suele ser la última tarea antes de desconectar.]', 'image_keywords' => ['evening', 'office']],
            ['title' => 'fuera de horario', 'body' => '[Cómo termina el día. Correr, cenar, hijos, lectura, lo que sea cierto.]', 'image_keywords' => ['sunset', 'home']],
        ],
    ],
    [
        'slug' => 'mistakes_we_made_carousel',
        'category' => 'behind_the_scenes',
        'name' => 'Errores que cometimos',
        'description' => 'Comparte tres errores reales y lo que aprendiste.',
        'content' => '3 cosas que hicimos mal este año en {{brand_name}}. Lo cuento porque ocultarlo se sentiría raro.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'por qué publicar esto', 'body' => 'Las victorias se llevan toda la atención. Los errores suelen ser donde están las lecciones.', 'image_keywords' => ['notebook', 'writing']],
            ['title' => 'error 1', 'body' => '[Lo que probamos. Por qué no funcionó. Qué hicimos después.]', 'image_keywords' => ['error', 'desk']],
            ['title' => 'error 2', 'body' => '[El segundo. Sé honesto sobre el costo en dinero o tiempo.]', 'image_keywords' => ['budget', 'paper']],
            ['title' => 'error 3 + qué sigue', 'body' => '[Tercer error y una cosa que está cambiando por eso.]', 'image_keywords' => ['plan', 'reset']],
        ],
    ],
    [
        'slug' => 'customer_story_carousel',
        'category' => 'testimonial',
        'name' => 'Historia de cliente',
        'description' => 'Cuenta una sola historia de cliente a lo largo de los slides.',
        'content' => 'Una historia de uno de los clientes de {{brand_name}}. Publicada con su permiso.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'conoce a [nombre]', 'body' => '[Nombre, qué hace, dónde vive. Dos frases cortas.]', 'image_keywords' => ['portrait', 'person']],
            ['title' => 'el problema', 'body' => '[La situación antes de usar {{brand_name}}. Concreta, no abstracta.]', 'image_keywords' => ['problem', 'thinking']],
            ['title' => 'qué probó', 'body' => '[Cómo encontró {{brand_name}} y cómo fue su primer uso.]', 'image_keywords' => ['discover', 'try']],
            ['title' => 'qué cambió', 'body' => '[El resultado. Un número si lo tienes, una historia si no.]', 'image_keywords' => ['result', 'change']],
            ['title' => 'en sus palabras', 'body' => '"[Cita directa del cliente. Corta y real.]"', 'image_keywords' => ['quote', 'speech']],
        ],
    ],
    [
        'slug' => 'three_reviews_carousel',
        'category' => 'testimonial',
        'name' => 'Carrusel con tres reseñas',
        'description' => 'Reúne tres reseñas reales en un post deslizable.',
        'content' => 'Tres reseñas de clientes reales este mes en {{brand_name}}.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'lo que dice la gente', 'body' => 'Tres citas sin editar de este mes. Apellidos reservados cuando se pidió.', 'image_keywords' => ['stars', 'review']],
            ['title' => 'reseña 1', 'body' => '"[Cita directa del cliente.]", [primer nombre, ubicación]', 'image_keywords' => ['speech', 'quote']],
            ['title' => 'reseña 2', 'body' => '"[Cita directa del cliente.]", [primer nombre, ubicación]', 'image_keywords' => ['feedback', 'note']],
            ['title' => 'reseña 3', 'body' => '"[Cita directa del cliente.]", [primer nombre, ubicación]', 'image_keywords' => ['testimonial', 'paper']],
        ],
    ],
    [
        'slug' => 'before_after_results_carousel',
        'category' => 'testimonial',
        'name' => 'Resultados antes y después',
        'description' => 'Muestra el resultado de un cliente en slides de antes y después.',
        'content' => 'Un resultado real de un cliente usando [producto/servicio] en {{brand_name}}. La misma persona, [período] de diferencia.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'el punto de partida', 'body' => '[Dónde estaba al empezar. La versión honesta, no la maquillada.]', 'image_keywords' => ['before', 'start']],
            ['title' => 'qué hizo', 'body' => '[Qué usó y con qué frecuencia. Sé específico sobre la rutina.]', 'image_keywords' => ['process', 'routine']],
            ['title' => 'el resultado', 'body' => '[Dónde está ahora. Números si aplica, foto si es visual.]', 'image_keywords' => ['after', 'result']],
            ['title' => 'en sus palabras', 'body' => '"[Una cita corta sobre lo que más le sorprendió.]"', 'image_keywords' => ['quote', 'smile']],
        ],
    ],
    [
        'slug' => 'industry_myth_busting_carousel',
        'category' => 'industry_tip',
        'name' => 'Derribando mitos del sector',
        'description' => 'Derriba tres mitos sobre tu sector.',
        'content' => '3 cosas que la gente sigue creyendo sobre [sector] y que no son ciertas.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'mitos, desarmados', 'body' => 'Tres creencias sobre [sector] que se repiten en todos lados y siguen errando.', 'image_keywords' => ['question', 'thinking']],
            ['title' => 'mito 1', 'body' => 'Mito: [creencia común]. Realidad: [cómo es en verdad, con un detalle].', 'image_keywords' => ['truth', 'note']],
            ['title' => 'mito 2', 'body' => 'Mito: [creencia común]. Realidad: [la corrección en una frase].', 'image_keywords' => ['fact', 'paper']],
            ['title' => 'mito 3', 'body' => 'Mito: [creencia común]. Realidad: [la corrección]. El porqué está en los comentarios.', 'image_keywords' => ['comment', 'phone']],
        ],
    ],
    [
        'slug' => 'industry_trend_carousel',
        'category' => 'industry_tip',
        'name' => 'Carrusel de tendencias del sector',
        'description' => 'Recorre una tendencia que está marcando el sector este año.',
        'content' => 'Lo que se está moviendo de verdad en [sector] este año, en lenguaje simple.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'la tendencia', 'body' => '[Nombra la tendencia en palabras simples. Una frase sobre qué es.]', 'image_keywords' => ['trend', 'graph']],
            ['title' => 'por qué ahora', 'body' => '[La causa concreta. Una regulación, un cambio técnico, un cambio de comportamiento.]', 'image_keywords' => ['cause', 'news']],
            ['title' => 'a quién le pega primero', 'body' => '[La audiencia o tipo de empresa que la siente antes que el resto.]', 'image_keywords' => ['audience', 'people']],
            ['title' => 'qué hacer', 'body' => '[Una cosa concreta para probar este trimestre, no un principio vago.]', 'image_keywords' => ['action', 'plan']],
            ['title' => 'un número para mirar', 'body' => '[Una métrica específica, con fuente.]', 'image_keywords' => ['metric', 'data']],
        ],
    ],
    [
        'slug' => 'pro_tip_carousel',
        'category' => 'industry_tip',
        'name' => 'Carrusel de consejo pro',
        'description' => 'Comparte un solo consejo profesional con contexto y pasos.',
        'content' => 'Una cosa que le diría a mi yo más joven sobre [tema]. Guárdalo si te sirve.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'el consejo', 'body' => '[La versión de una línea. Lo bastante corto para recordarlo.]', 'image_keywords' => ['tip', 'note']],
            ['title' => 'por qué funciona', 'body' => '[La razón. Usa un ejemplo pequeño, no una afirmación grande.]', 'image_keywords' => ['idea', 'thought']],
            ['title' => 'cómo aplicarlo', 'body' => '[Los pasos. Tres como mucho. Específicos.]', 'image_keywords' => ['steps', 'list']],
            ['title' => 'una cosa que evitar', 'body' => '[El error que comete la gente al aplicar este consejo.]', 'image_keywords' => ['warning', 'caution']],
        ],
    ],
    [
        'slug' => 'event_announcement_carousel',
        'category' => 'event',
        'name' => 'Anuncio de evento',
        'description' => 'Anuncia un evento próximo con los detalles clave.',
        'content' => 'Vamos a organizar [Nombre del Evento] el [fecha]. Todo lo que necesitas saber está en los slides.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => '[nombre del evento]', 'body' => '[Fecha, lugar u online, para quién es, en una línea.]', 'image_keywords' => ['event', 'invite']],
            ['title' => 'qué hay planeado', 'body' => '[La agenda en bullets directos, sin lenguaje de marketing.]', 'image_keywords' => ['agenda', 'schedule']],
            ['title' => 'quién habla', 'body' => '[Nombres y bios de una línea. No más de tres.]', 'image_keywords' => ['speakers', 'panel']],
            ['title' => 'cómo unirte', 'body' => '[Gratis o pago, link, fecha límite si la hay. Sé específico.]', 'image_keywords' => ['ticket', 'register']],
            ['title' => 'reserva tu lugar', 'body' => '[Recordatorio final + llamada al link en bio.]', 'image_keywords' => ['phone', 'tap']],
        ],
    ],
    [
        'slug' => 'event_speakers_carousel',
        'category' => 'event',
        'name' => 'Revelación de oradores',
        'description' => 'Revela a los oradores, uno por slide.',
        'content' => 'Oradores de [Nombre del Evento]. Las entradas están abiertas en {{brand_name}}.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'oradores revelados', 'body' => 'El lineup de [Nombre del Evento] el [fecha]. Desliza para conocerlos.', 'image_keywords' => ['lineup', 'stage']],
            ['title' => '[orador 1]', 'body' => '[Nombre, rol. La cosa puntual sobre la que va a hablar.]', 'image_keywords' => ['portrait', 'speaker']],
            ['title' => '[orador 2]', 'body' => '[Nombre, rol. El tema de su charla en una línea.]', 'image_keywords' => ['portrait', 'mic']],
            ['title' => '[orador 3]', 'body' => '[Nombre, rol. Con qué se irán los asistentes.]', 'image_keywords' => ['portrait', 'panel']],
            ['title' => 'entradas en bio', 'body' => '[Fecha, lugar, link de inscripción.]', 'image_keywords' => ['ticket', 'register']],
        ],
    ],
    [
        'slug' => 'workshop_invitation_carousel',
        'category' => 'event',
        'name' => 'Invitación al taller',
        'description' => 'Invita a la gente a un taller práctico.',
        'content' => 'Taller práctico en {{brand_name}} el [fecha]. Cupos limitados. Esto es lo que trae.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'taller el [fecha]', 'body' => '[Tema en una línea. Online o presencial, con lugar y horario.]', 'image_keywords' => ['workshop', 'class']],
            ['title' => 'qué vas a hacer', 'body' => '[Tres actividades concretas. Usa verbos, no adjetivos.]', 'image_keywords' => ['hands', 'making']],
            ['title' => 'con qué te vas a ir', 'body' => '[El resultado: algo terminado, un borrador, una decisión, un plan.]', 'image_keywords' => ['notebook', 'result']],
            ['title' => 'reserva un cupo', 'body' => '[Cupos disponibles, precio si lo hay, link en bio.]', 'image_keywords' => ['chair', 'register']],
        ],
    ],
    [
        'slug' => 'this_or_that_carousel',
        'category' => 'engagement',
        'name' => 'Esto o aquello',
        'description' => 'Hazle a tus seguidores una serie de preguntas de elección.',
        'content' => 'Esto o aquello, edición [tema]. Cuéntame tus elecciones en los comentarios.',
        'image_count' => 5,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'elige uno', 'body' => 'Cinco elecciones rápidas. Comenta tus respuestas en orden.', 'image_keywords' => ['choice', 'fork']],
            ['title' => '[opción a] o [opción b]', 'body' => '[Contexto breve si hace falta.]', 'image_keywords' => ['split', 'options']],
            ['title' => '[opción c] o [opción d]', 'body' => '[Contexto breve si hace falta.]', 'image_keywords' => ['versus', 'choice']],
            ['title' => '[opción e] o [opción f]', 'body' => '[Contexto breve si hace falta.]', 'image_keywords' => ['compare', 'pick']],
            ['title' => 'tu turno', 'body' => 'Deja tus respuestas abajo. Leo cada comentario.', 'image_keywords' => ['comment', 'phone']],
        ],
    ],
    [
        'slug' => 'unpopular_opinion_carousel',
        'category' => 'engagement',
        'name' => 'Opinión impopular',
        'description' => 'Comparte una opinión real e invita al desacuerdo.',
        'content' => 'Una opinión impopular sobre [tema]. Dime en los comentarios dónde me equivoco.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'opinión impopular', 'body' => '[La opinión en una frase corta y clara.]', 'image_keywords' => ['opinion', 'speech']],
            ['title' => 'por qué pienso esto', 'body' => '[La razón. Una historia pequeña o un número, no solo sentimientos.]', 'image_keywords' => ['reason', 'thinking']],
            ['title' => 'dónde podría equivocarme', 'body' => '[Honesto sobre la parte más débil del argumento.]', 'image_keywords' => ['doubt', 'question']],
            ['title' => 'cuéntame', 'body' => 'De acuerdo, en desacuerdo, mixto, déjalo en los comentarios.', 'image_keywords' => ['comment', 'discussion']],
        ],
    ],
    [
        'slug' => 'fill_in_the_blank_carousel',
        'category' => 'engagement',
        'name' => 'Completa la frase',
        'description' => 'Lanza a los seguidores tres frases para completar.',
        'content' => 'Completa las frases. Quiero leer tus respuestas.',
        'image_count' => 4,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'completa las frases', 'body' => 'Tres provocaciones rápidas sobre [tema]. Comenta tus respuestas en orden.', 'image_keywords' => ['blank', 'pen']],
            ['title' => 'frase 1', 'body' => 'La mejor [cosa] que [verbo] este año fue ____.', 'image_keywords' => ['idea', 'thought']],
            ['title' => 'frase 2', 'body' => 'Lo que quiero hacer más en [tema] es ____.', 'image_keywords' => ['plan', 'goal']],
            ['title' => 'frase 3', 'body' => 'Una persona que me enseñó sobre [tema] es ____.', 'image_keywords' => ['mentor', 'people']],
        ],
    ],
    [
        'slug' => 'q_and_a_carousel',
        'category' => 'engagement',
        'name' => 'Carrusel de preguntas y respuestas',
        'description' => 'Responde cinco preguntas reales de tu audiencia.',
        'content' => 'Tú preguntaste, yo respondo. Cinco preguntas reales que llegaron por DM.',
        'image_count' => 6,
        'image_keywords' => null,
        'slides' => [
            ['title' => 'preguntas respondidas', 'body' => 'Tomé cinco de esta semana. Anonimizadas donde hizo falta.', 'image_keywords' => ['questions', 'mail']],
            ['title' => 'p1', 'body' => 'P: [pregunta parafraseada]. R: [respuesta en una o dos frases].', 'image_keywords' => ['answer', 'note']],
            ['title' => 'p2', 'body' => 'P: [pregunta parafraseada]. R: [respuesta].', 'image_keywords' => ['reply', 'speech']],
            ['title' => 'p3', 'body' => 'P: [pregunta parafraseada]. R: [respuesta].', 'image_keywords' => ['question', 'mark']],
            ['title' => 'p4', 'body' => 'P: [pregunta parafraseada]. R: [respuesta].', 'image_keywords' => ['chat', 'bubble']],
            ['title' => 'p5', 'body' => 'P: [pregunta parafraseada]. R: [respuesta]. Manda más en los comentarios.', 'image_keywords' => ['comments', 'phone']],
        ],
    ],
];
