<?php

declare(strict_types=1);

return [
    [
        'slug' => 'limited_time_offer_feed',
        'category' => 'promotion',
        'name' => 'Oferta por tiempo limitado',
        'description' => 'Promociona una oferta con plazo en Instagram Feed.',
        'content' => "⏰ No te lo pierdas. {{brand_name}} ofrece [descuento]% off en [producto/servicio], solo hoy.\n\nToca el link en la bio para conseguir el tuyo antes de que se acabe.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'offer', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'team_behind_the_scenes_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Bastidores del equipo',
        'description' => 'Humaniza tu marca mostrando al equipo en acción.',
        'content' => "Así se ve un día normal en {{brand_name}}. 👀\n\nCreemos que el buen trabajo pasa cuando la gente se siente en casa. Aquí va una mirada detrás del telón.\n\n#{{brand_name}} #BehindTheScenes",
        'image_count' => 1,
        'image_keywords' => ['office', 'team', 'workspace'],
        'slides' => null,
    ],

    // Product launch
    [
        'slug' => 'new_product_drop_feed',
        'category' => 'product_launch',
        'name' => 'Lanzamiento de nuevo producto',
        'description' => 'Anuncia el lanzamiento de un producto fresco en el feed.',
        'content' => "Ya está. [Nombre del producto] acaba de llegar a {{brand_name}}.\n\nLe dedicamos [meses/semanas] a este. Cada detalle fue probado por el equipo antes de soltarlo al público.\n\nToca el link en la bio para ser de los primeros en probarlo.",
        'image_count' => 1,
        'image_keywords' => ['product', 'launch', 'unboxing'],
        'slides' => null,
    ],
    [
        'slug' => 'pre_order_announcement_feed',
        'category' => 'product_launch',
        'name' => 'Anuncio de preventa',
        'description' => 'Abre preventas para un producto que viene en camino.',
        'content' => "Preventas abiertas. [Nombre del producto] se envía el [fecha].\n\nEl primer lote tiene [número] unidades. Cuando se agoten, la siguiente tanda no sale hasta [fecha posterior].\n\nReserva el tuyo por el link en la bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'package', 'box'],
        'slides' => null,
    ],
    [
        'slug' => 'feature_highlight_launch_feed',
        'category' => 'product_launch',
        'name' => 'Destaque de funcionalidad',
        'description' => 'Resalta una función específica de un producto nuevo.',
        'content' => "Lo que más nos enorgullece de [nombre del producto]: [función específica].\n\nNos costó [número] prototipos llegar a esto. Los testers iniciales nos dijeron que cambió la forma en que [caso de uso], así que seguimos iterando hasta que se sintió obvio.\n\nMíralo en acción por el link en la bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'detail', 'closeup'],
        'slides' => null,
    ],
    [
        'slug' => 'product_restock_feed',
        'category' => 'product_launch',
        'name' => 'Producto reabastecido',
        'description' => 'Anuncia la vuelta al stock de un producto popular.',
        'content' => "De vuelta en stock. [Nombre del producto] se agotó en [tiempo] la última vez, así que hicimos más.\n\nSi te lo perdiste antes, este es el momento. El stock vuelve a ser limitado y esperamos otra corrida rápida.\n\nConsigue el tuyo por el link en la bio.",
        'image_count' => 1,
        'image_keywords' => ['product', 'shelf', 'inventory'],
        'slides' => null,
    ],

    // Promotion
    [
        'slug' => 'flash_sale_feed',
        'category' => 'promotion',
        'name' => 'Flash sale',
        'description' => 'Genera urgencia con un flash sale corto.',
        'content' => "Flash sale. [Descuento]% off en todo durante las próximas [horas] horas.\n\nNo necesitas código en el checkout. El descuento ya está aplicado en todo el sitio.\n\nLink en la bio. Pon un cronómetro.",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'bundle_deal_feed',
        'category' => 'promotion',
        'name' => 'Oferta de combo',
        'description' => 'Promociona una oferta de combo con varios productos.',
        'content' => "Compra [item A] y [item B] juntos y ahorra [monto].\n\nEs la misma combinación que nuestro equipo usa cada semana, así que la armamos como kit. Sale más barato que comprar cada uno por separado.\n\nLink en la bio.",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'products', 'gift'],
        'slides' => null,
    ],
    [
        'slug' => 'free_shipping_feed',
        'category' => 'promotion',
        'name' => 'Envío gratis',
        'description' => 'Anuncia envío gratis por una ventana limitada.',
        'content' => "Envío gratis en todos los pedidos esta semana.\n\nSin mínimo, sin código, sin letra chica al pie que haya que entrecerrar los ojos para leer. Eliges lo que quieres y nosotros cubrimos la entrega.\n\nLink en la bio. Termina el [día].",
        'image_count' => 1,
        'image_keywords' => ['shipping', 'package', 'delivery'],
        'slides' => null,
    ],
    [
        'slug' => 'first_order_discount_feed',
        'category' => 'promotion',
        'name' => 'Descuento en la primera compra',
        'description' => 'Recibe a clientes nuevos con descuento en la primera compra.',
        'content' => "¿Primera vez en {{brand_name}}? Llévate [descuento]% off en tu primer pedido.\n\nUsa el código [CÓDIGO] en el checkout. Funciona con cualquier producto de la tienda, incluido el [nombre del bestseller] que la gente nos sigue preguntando.\n\nLink en la bio.",
        'image_count' => 1,
        'image_keywords' => ['welcome', 'shop', 'discount'],
        'slides' => null,
    ],

    // Educational
    [
        'slug' => 'quick_how_to_tip_feed',
        'category' => 'educational',
        'name' => 'Tip rápido de cómo hacer',
        'description' => 'Comparte un tip accionable de tu nicho.',
        'content' => "Algo pequeño que hace [tarea] más fácil: [tip en una frase].\n\nEmpezamos a hacer esto después de [motivo o historia]. Nos ahorró [tiempo/dinero/esfuerzo] en una semana.\n\nGuarda este post para después. Link en la bio para la guía completa.",
        'image_count' => 1,
        'image_keywords' => ['notebook', 'desk', 'work'],
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake_feed',
        'category' => 'educational',
        'name' => 'Error común',
        'description' => 'Señala un error frecuente y la solución.',
        'content' => "El error que más vemos con [tema]: [el error].\n\nEs fácil de cometer. La mayoría no se da cuenta de que cuesta [consecuencia] hasta que alguien lo señala.\n\nLa solución es simple: [la solución]. Pruébalo esta semana y mira qué cambia.",
        'image_count' => 1,
        'image_keywords' => ['warning', 'thinking', 'desk'],
        'slides' => null,
    ],
    [
        'slug' => 'myth_vs_truth_feed',
        'category' => 'educational',
        'name' => 'Mito vs verdad',
        'description' => 'Desmiente un mito común de tu industria.',
        'content' => "Mito: [creencia común sobre tu industria].\n\nVerdad: [la realidad, con un detalle que la respalda].\n\nNosotros también creíamos en el mito. Después lo medimos por [periodo] y los datos dijeron otra cosa. Guarda esto si has oído lo mismo.",
        'image_count' => 1,
        'image_keywords' => ['question', 'thinking', 'idea'],
        'slides' => null,
    ],
    [
        'slug' => 'glossary_term_feed',
        'category' => 'educational',
        'name' => 'Término del glosario explicado',
        'description' => 'Explica un término del rubro en lenguaje claro.',
        'content' => "[Término]: lo que significa de verdad.\n\nLa mayoría de las guías lo explican con más jerga. Aquí va la versión directa: [definición en una frase].\n\nUn ejemplo real de nuestro trabajo: [ejemplo corto]. Guarda el post si has estado asintiendo en reuniones sin preguntar.",
        'image_count' => 1,
        'image_keywords' => ['book', 'glossary', 'study'],
        'slides' => null,
    ],

    // Behind the scenes
    [
        'slug' => 'workspace_tour_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Tour por el espacio de trabajo',
        'description' => 'Muestra el lugar donde pasa el trabajo.',
        'content' => "Donde pasa el trabajo.\n\nEsto es [sala/espacio] en {{brand_name}}. La planta del rincón sobrevivió a tres mudanzas de oficina. La pizarra no se ha borrado desde [mes].\n\nNo es pulido, pero es nuestro.",
        'image_count' => 1,
        'image_keywords' => ['workspace', 'desk', 'studio'],
        'slides' => null,
    ],
    [
        'slug' => 'how_its_made_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Cómo se hace',
        'description' => 'Muestra un paso de tu proceso de producción.',
        'content' => "Este es el paso [número] de cómo hacemos [producto].\n\nLleva como [tiempo] y lo hacemos a mano. Sin atajos por aquí, sobre todo porque probamos un atajo una vez y arruinó un lote entero.\n\nMás del proceso en el link en la bio.",
        'image_count' => 1,
        'image_keywords' => ['craft', 'making', 'workshop'],
        'slides' => null,
    ],
    [
        'slug' => 'team_member_intro_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Presentación de un miembro del equipo',
        'description' => 'Presenta a un integrante del equipo.',
        'content' => "Conoce a [nombre], nuestro/a [rol] en {{brand_name}}.\n\n[Nombre] se sumó hace [tiempo] y lleva [área]. Fuera del trabajo, lo/la encuentras [hobby o interés].\n\nSi escribiste a soporte hace poco, hay buenas chances de que [nombre] te haya respondido.",
        'image_count' => 1,
        'image_keywords' => ['portrait', 'team', 'person'],
        'slides' => null,
    ],
    [
        'slug' => 'a_day_in_the_life_feed',
        'category' => 'behind_the_scenes',
        'name' => 'Un día en la vida',
        'description' => 'Cuenta cómo es un día normal en la empresa.',
        'content' => "Un martes normal en {{brand_name}}.\n\nLas mañanas son tranquilas, sobre todo correos y una daily. Las tardes se vuelven ruidosas cuando arranca [actividad]. Para las 5pm alguien ya rompió algo y otra persona ya lo arregló.\n\nEse es todo el trabajo, sinceramente.",
        'image_count' => 1,
        'image_keywords' => ['office', 'work', 'coffee'],
        'slides' => null,
    ],

    // Testimonial
    [
        'slug' => 'customer_quote_feed',
        'category' => 'testimonial',
        'name' => 'Cita de cliente',
        'description' => 'Comparte una cita potente de un cliente.',
        'content' => "\"[Cita del cliente con sus propias palabras].\", [Nombre del cliente], [ciudad o rol]\n\nEsta llegó la semana pasada y teníamos que compartirla. Gracias [nombre].\n\nSi {{brand_name}} te ayudó con [resultado], nos encantaría saberlo. Responde o mándanos un DM.",
        'image_count' => 1,
        'image_keywords' => ['quote', 'happy', 'customer'],
        'slides' => null,
    ],
    [
        'slug' => 'before_after_result_feed',
        'category' => 'testimonial',
        'name' => 'Resultado antes y después',
        'description' => 'Resalta una transformación real de cliente.',
        'content' => "Antes: [punto de partida].\nDespués: [resultado, con un número si es posible].\n\n[Nombre del cliente] trabajó con nosotros por [periodo]. El cambio no fue de un día para otro, pero se ve dónde se inclinó la balanza.\n\nLink en la bio si quieres un resultado parecido.",
        'image_count' => 1,
        'image_keywords' => ['transformation', 'result', 'progress'],
        'slides' => null,
    ],
    [
        'slug' => 'star_rating_review_feed',
        'category' => 'testimonial',
        'name' => 'Reseña de cinco estrellas',
        'description' => 'Resalta una reseña reciente de cinco estrellas.',
        'content' => "★★★★★\n\n\"[Texto de la reseña, dos o tres frases].\"\n\n[Nombre] dejó esta ayer. Leemos cada reseña que llega, las amables y las duras.\n\nDeja la tuya por el link en la bio.",
        'image_count' => 1,
        'image_keywords' => ['stars', 'review', 'rating'],
        'slides' => null,
    ],
    [
        'slug' => 'case_study_snapshot_feed',
        'category' => 'testimonial',
        'name' => 'Resumen de case study',
        'description' => 'Adelanta un case de éxito de cliente.',
        'content' => "Cómo [cliente o empresa] usó {{brand_name}} para [resultado].\n\nEn [periodo], pasaron de [punto inicial] a [resultado]. El análisis completo cuenta lo que probaron primero y lo que finalmente encajó.\n\nLink en la bio para el case study.",
        'image_count' => 1,
        'image_keywords' => ['case study', 'meeting', 'results'],
        'slides' => null,
    ],

    // Industry tip
    [
        'slug' => 'one_tool_we_use_feed',
        'category' => 'industry_tip',
        'name' => 'Una herramienta que usamos',
        'description' => 'Recomienda una herramienta que usas de verdad.',
        'content' => "Una herramienta que usamos cada semana: [nombre de la herramienta].\n\nProbamos [número] alternativas antes de quedarnos con esta. Lo que nos convenció fue [función específica], no el marketing de la página principal.\n\nNo es publicidad. Solo es útil.",
        'image_count' => 1,
        'image_keywords' => ['tools', 'software', 'laptop'],
        'slides' => null,
    ],
    [
        'slug' => 'industry_trend_take_feed',
        'category' => 'industry_tip',
        'name' => 'Opinión sobre tendencia del rubro',
        'description' => 'Da una opinión honesta sobre una tendencia actual.',
        'content' => "Todo el mundo en [rubro] habla de [tendencia].\n\nOpinión honesta: sirve para [caso de uso], no sirve para [otro caso de uso]. Lo probamos en un proyecto pequeño antes de comprometernos, y esa es la versión que recomendamos.\n\n¿Cuál ha sido tu experiencia? Cuéntanos en los comentarios.",
        'image_count' => 1,
        'image_keywords' => ['trend', 'industry', 'analysis'],
        'slides' => null,
    ],
    [
        'slug' => 'pricing_advice_feed',
        'category' => 'industry_tip',
        'name' => 'Consejo de precios',
        'description' => 'Comparte una lección de precios desde la experiencia.',
        'content' => "Lo que nos equivocamos en precios: [el error].\n\nCobramos poco por [periodo] hasta que alguien nos hizo notar que los números no cerraban. Subimos los precios [porcentaje], perdimos [número] clientes, mantuvimos al resto y ganamos más.\n\nSi tú también estás trancado/a con esto, el link en la bio tiene nuestro desglose de precios.",
        'image_count' => 1,
        'image_keywords' => ['money', 'price', 'calculator'],
        'slides' => null,
    ],
    [
        'slug' => 'workflow_tip_feed',
        'category' => 'industry_tip',
        'name' => 'Tip de flujo de trabajo',
        'description' => 'Comparte una mejora pequeña en el flujo de trabajo.',
        'content' => "Un cambio pequeño en el flujo que nos ahorró horas: [el cambio].\n\nAntes, [forma vieja]. Después, [forma nueva]. Tomó como una semana acostumbrarse y no volvimos atrás.\n\nSi lo pruebas, cuéntanos qué tal te fue.",
        'image_count' => 1,
        'image_keywords' => ['workflow', 'productivity', 'planner'],
        'slides' => null,
    ],

    // Event
    [
        'slug' => 'event_announcement_feed',
        'category' => 'event',
        'name' => 'Anuncio de evento',
        'description' => 'Anuncia un evento que viene en camino.',
        'content' => "Aparta la fecha.\n\n{{brand_name}} organiza [nombre del evento] el [fecha] en [lugar u online].\n\nVamos a tener [oradores, formato o qué esperar]. Los lugares están limitados a [número] esta vez.\n\nConfirma asistencia por el link en la bio.",
        'image_count' => 1,
        'image_keywords' => ['event', 'invitation', 'calendar'],
        'slides' => null,
    ],
    [
        'slug' => 'webinar_invite_feed',
        'category' => 'event',
        'name' => 'Invitación a webinar',
        'description' => 'Promociona un webinar que viene en camino.',
        'content' => "Webinar gratis: [tema]. [Fecha] a las [hora].\n\n[Nombre del host] va a recorrer [puntos principales] y después responder preguntas en vivo en los últimos [minutos].\n\nSi no puedes asistir, regístrate igual y te enviamos la grabación.\n\nLink en la bio.",
        'image_count' => 1,
        'image_keywords' => ['webinar', 'laptop', 'presentation'],
        'slides' => null,
    ],
    [
        'slug' => 'meetup_recap_feed',
        'category' => 'event',
        'name' => 'Recap del meetup',
        'description' => 'Recapitula un evento presencial reciente.',
        'content' => "[Número] personas, [ciudad], una sala.\n\nEl meetup de anoche juntó a gente que trabaja en [área]. La mejor conversación de la noche fue sobre [tema], empezó con un café y nunca terminó del todo.\n\nGracias a todos los que vinieron. El próximo es el [fecha].",
        'image_count' => 1,
        'image_keywords' => ['meetup', 'crowd', 'event'],
        'slides' => null,
    ],
    [
        'slug' => 'live_stream_reminder_feed',
        'category' => 'event',
        'name' => 'Recordatorio de live',
        'description' => 'Recuerda a tus seguidores sobre un live que viene.',
        'content' => "Live el [día] a las [hora].\n\nVamos a hablar de [tema]. Sin guion, solo preguntas y lo que tire el chat.\n\nActiva las notificaciones para no perdértelo. O no, el replay queda en el perfil después.",
        'image_count' => 1,
        'image_keywords' => ['live', 'broadcast', 'camera'],
        'slides' => null,
    ],

    // Engagement
    [
        'slug' => 'this_or_that_feed',
        'category' => 'engagement',
        'name' => 'Esto o aquello',
        'description' => 'Haz una pregunta simple de elegir entre dos.',
        'content' => "¿[Opción A] u [Opción B]?\n\nDiscutimos esto en la oficina al menos una vez por semana. Curioso por ver qué lado gana aquí.\n\nVota en los comentarios. No hay respuesta incorrecta, pero hay una correcta.",
        'image_count' => 1,
        'image_keywords' => ['choice', 'options', 'vote'],
        'slides' => null,
    ],
    [
        'slug' => 'fill_in_the_blank_feed',
        'category' => 'engagement',
        'name' => 'Completa la frase',
        'description' => 'Reta a tus seguidores con una frase para completar.',
        'content' => "Termina la frase: \"Lo primero que hago cada mañana es ___.\"\n\nLe preguntamos al equipo y nos dijeron desde \"revisar Slack\" hasta \"evitar revisar Slack\". Curioso por saber dónde te ubicas tú.\n\nDeja la tuya en los comentarios.",
        'image_count' => 1,
        'image_keywords' => ['question', 'morning', 'coffee'],
        'slides' => null,
    ],
    [
        'slug' => 'comment_question_feed',
        'category' => 'engagement',
        'name' => 'Pregunta para comentarios',
        'description' => 'Haz una pregunta abierta para generar comentarios.',
        'content' => "Pregunta para el grupo: ¿cuál es el mejor [item relacionado al tema] que probaste este año?\n\nEstamos armando un compilado y queremos elecciones reales, no las cinco que todos listan.\n\nDeja la tuya abajo. Compartimos las favoritas la próxima semana.",
        'image_count' => 1,
        'image_keywords' => ['conversation', 'community', 'chat'],
        'slides' => null,
    ],
    [
        'slug' => 'tag_a_friend_feed',
        'category' => 'engagement',
        'name' => 'Etiqueta a un amigo',
        'description' => 'Anima a etiquetar con un escenario identificable.',
        'content' => "Etiqueta al amigo que [escenario identificable].\n\nTodos tenemos uno. Tal vez tú eres uno. Como sea, este post es para esa persona.\n\nPuntos extra si te etiqueta de vuelta.",
        'image_count' => 1,
        'image_keywords' => ['friends', 'people', 'fun'],
        'slides' => null,
    ],
];
