<?php

declare(strict_types=1);

return [
    [
        'slug' => 'company_milestone',
        'category' => 'behind_the_scenes',
        'name' => 'Hito de la empresa',
        'description' => 'Celebra un hito de la empresa desde la página de la marca.',
        'content' => "Hoy {{brand_name}} llega a [hito, ej.: 1.000 clientes, 5 años, \$X de ARR].\n\nEsto no pasó por una sola persona. Pasó porque [equipo / clientes / comunidad] aparecieron todos los días.\n\nGracias a todos los que estuvieron en este camino. Recién estamos empezando.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'hiring_announcement',
        'category' => 'engagement',
        'name' => 'Estamos contratando',
        'description' => 'Anuncia vacantes abiertas e invita postulaciones desde la página de la empresa.',
        'content' => "{{brand_name}} está contratando.\n\nBuscamos [puesto(s)] para sumarse a nosotros en [equipo/misión].\n\nLo que ofrecemos:\n→ [Punto 1]\n→ [Punto 2]\n→ [Punto 3]\n\nSi te suena (o conoces a alguien), postula o comparte → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'thought_leadership_page',
        'category' => 'industry_tip',
        'name' => 'Mirada del sector',
        'description' => 'Comparte la postura de la empresa sobre una tendencia o cambio del sector.',
        'content' => "El panorama de [sector] está cambiando.\n\nEsto es lo que vemos en {{brand_name}}:\n\n1. [Observación]\n2. [Observación]\n3. [Observación]\n\nLo que esto significa para [audiencia]: [implicación].\n\n¿Qué están viendo ustedes?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== product_launch =====
    [
        'slug' => 'new_feature_release',
        'category' => 'product_launch',
        'name' => 'Lanzamiento de nueva función',
        'description' => 'Anuncia una función nueva específica y el problema que resuelve.',
        'content' => "Hoy lanzamos [nombre de la función].\n\nLa versión corta: [descripción en una línea de lo que hace].\n\nLa versión larga: los clientes nos repetían [dolor específico]. Probamos [solución previa] durante unos [periodo de tiempo] y nunca terminó de funcionar. Así que rehicimos [área] desde cero.\n\nAlgunos cambios:\n[Comportamiento antes] ahora es [comportamiento después].\n[Paso manual] corre solo.\n[Límite] ya no existe.\n\nSi quieres probarlo, la documentación está aquí: [link]. Si encuentras algo roto, nuestro equipo está en los comentarios.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'beta_open_signups',
        'category' => 'product_launch',
        'name' => 'Beta abierta para inscripciones',
        'description' => 'Invita a clientes y prospectos a un beta público o privado.',
        'content' => "El acceso beta a [producto/función] ya está abierto.\n\nPasamos [periodo de tiempo] probándolo con [número] testers privados. La devolución fue lo bastante buena como para abrir más la puerta.\n\nPara quién es: [descripción específica del usuario, ej.: equipos que corren más de X campañas/mes].\nPara quién todavía no: [exclusión honesta, ej.: empresas que necesitan SSO].\n\nLimitamos esta ronda a [número] empresas para que el equipo pueda acompañar cada cuenta de cerca. Los lugares se asignan por orden de llegada.\n\nPide acceso: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'integration_partnership',
        'category' => 'product_launch',
        'name' => 'Integración con socio',
        'description' => 'Anuncia una nueva integración o alianza técnica.',
        'content' => "{{brand_name}} ahora se conecta con [socio].\n\nSi usas las dos, puedes dejar de [paso manual]. La integración se encarga de [flujo de datos específico] de forma automática.\n\nLo que cambió para nuestros clientes en común:\nNada de exportar [datos] y reimportar del otro lado.\n[Disparador] en [socio] ahora crea [acción] en {{brand_name}}.\nEl mapeo de campos se puede editar, así que las configuraciones raras siguen funcionando.\n\nGracias al equipo de [socio] por las idas y vueltas con la API. Guía de configuración: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'product_redesign',
        'category' => 'product_launch',
        'name' => 'Lanzamiento de rediseño del producto',
        'description' => 'Anuncia un rediseño relevante de UI o producto.',
        'content' => "Rediseñamos [producto/área]. Está disponible para todos hoy.\n\nNuestro equipo de diseño estuvo bastante callado por aquí los últimos meses por esto. La [área] anterior creció de forma orgánica y terminó con [problema específico, ej.: cuatro maneras distintas de empezar un proyecto nuevo]. Los clientes nos lo dijeron. Estuvimos de acuerdo.\n\nLo que cambió:\nUna acción principal por pantalla, en vez de tres.\n[Elemento anterior] pasó a [nueva ubicación] para dejar de estorbar.\n[Patrón específico] que nadie usaba se fue.\n\nSi algo se siente raro los primeros días, es normal. Responde aquí o escríbele al equipo a [contacto] y lo miramos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== promotion =====
    [
        'slug' => 'limited_time_offer',
        'category' => 'promotion',
        'name' => 'Oferta por tiempo limitado',
        'description' => 'Anuncia un descuento u oferta de precio con fecha límite clara.',
        'content' => "[Oferta, ej.: 25% de descuento en el primer año de {{brand_name}}] está abierta hasta [fecha específica].\n\nCasi nunca hacemos descuentos. Este está atado a [motivo, aniversario, cierre de trimestre, hito de producto] y no lo vamos a repetir en las mismas condiciones en [periodo de tiempo].\n\nA quién aplica: [elegibilidad, clientes nuevos, planes anuales, plan específico].\nA quién no: [exclusión honesta].\n\nUsa [código] en el checkout, o habla con nuestro equipo si quieres ayuda para elegir un plan: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'free_resource_offer',
        'category' => 'promotion',
        'name' => 'Recurso gratuito',
        'description' => 'Promociona una guía, plantilla o reporte gratuito.',
        'content' => "Hicimos un [recurso, guía, plantilla, reporte de benchmark] gratuito para [audiencia].\n\nCubre [tema específico 1], [tema específico 2] y los [número] errores que más vemos al trabajar con [tipo de cliente objetivo]. Unas [número] páginas, sin pedir más que nombre y mail laboral.\n\nPor qué es gratis: [motivo honesto, ej.: lo armamos primero para nuestros clientes y es el tipo de cosa que rinde más cuanta más gente la tiene].\n\nDescárgalo aquí: [link]. Cuéntanos qué falta y lo actualizamos en la próxima versión.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'referral_program_launch',
        'category' => 'promotion',
        'name' => 'Anuncio de programa de referidos',
        'description' => 'Promociona un programa de referidos para clientes desde la página de la empresa.',
        'content' => "Lanzamos un programa de referidos para clientes de {{brand_name}}.\n\nSi recomiendas una empresa que termina pagando, las dos partes reciben [beneficio específico, ej.: un mes gratis, \$X de crédito, una función desbloqueada]. Sin niveles. Sin ranking. Sin tazas.\n\nResistimos un buen tiempo a hacer esto porque la mayoría de los programas de referidos parece pirámide encubierta. Llegamos acá porque nuestro mayor canal de crecimiento el año pasado fue cliente contándole a cliente, y se sintió raro no compartir el beneficio.\n\nDetalles y tu link de referidos: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== educational =====
    [
        'slug' => 'how_we_solve_problem',
        'category' => 'educational',
        'name' => 'Cómo abordamos un problema',
        'description' => 'Muestra cómo la empresa enfrenta un problema recurrente de los clientes.',
        'content' => "Una pregunta que nos llega cada semana: [pregunta específica].\n\nAsí lo pensamos en {{brand_name}}.\n\nLa mayoría de los equipos arranca con [primer movimiento común]. Funciona hasta que se topa con [punto específico de falla]. Ahí te quedas pegado agregando [solución parche] cada vez que algo cambia.\n\nUn camino distinto: [enfoque alternativo]. El precio es [costo honesto, ej.: un setup más lento, más cabeza al inicio, más difícil de explicarle a alguien nuevo]. La ganancia es que [beneficio específico] deja de ser un incendio recurrente.\n\nEscribimos la versión larga aquí: [link]. ¿No estás de acuerdo? Los comentarios están abiertos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'customer_data_insight',
        'category' => 'educational',
        'name' => 'Insight de datos de clientes',
        'description' => 'Comparte un patrón útil que se observa en la base de clientes.',
        'content' => "Miramos [métrica/comportamiento] en [número] cuentas de {{brand_name}} el último trimestre.\n\nUna cosa saltó a la vista: [hallazgo específico con número, ej.: los equipos que hicieron X en su primera semana tuvieron 3x más probabilidad de seguir activos al sexto mes].\n\nEsperábamos lo contrario. Nuestra hipótesis inicial era [supuesto viejo], en parte por [motivo]. Los datos no estuvieron de acuerdo.\n\nAlgunos detalles: esto es correlación, no causa. La muestra está sesgada hacia [segmento]. Y [periodo de tiempo] es corto.\n\nAun así, si recién empiezas con {{brand_name}}, [recomendación práctica] probablemente vale la pena en la primera semana.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake_breakdown',
        'category' => 'educational',
        'name' => 'Desglose de error común',
        'description' => 'Explica un error recurrente y cómo evitarlo.',
        'content' => "El error más común que vemos cuando los equipos adoptan [herramienta/proceso/práctica]: [error específico].\n\nSuele verse así. Un equipo arranca con [setup]. En unas semanas, agregan [solución parche] porque [motivo]. Para el tercer mes, el parche ya es el sistema y nadie recuerda por qué.\n\nLa solución no es [respuesta obvia]. La solución es volver atrás y preguntarse si [supuesto original] alguna vez fue cierto en su caso. La mitad de las veces, no lo era.\n\nEscribimos esto porque cometimos el mismo error puertas adentro en [año]. Detalle completo: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'tool_comparison',
        'category' => 'educational',
        'name' => 'Comparación honesta de herramientas',
        'description' => 'Compara enfoques o herramientas para una tarea específica, incluyendo dónde la empresa pierde.',
        'content' => "¿Cuándo usar {{brand_name}} y cuándo no?\n\nLa primera mitad de la pregunta nos llega todo el tiempo. Esta es la segunda.\n\nUsa {{brand_name}} cuando [situación específica, ej.: tienes más de X de Y, o necesitas la capacidad Z].\n\nNo uses {{brand_name}} cuando [exclusión honesta, ej.: eres un solo usuario con menos de X, o tu flujo es totalmente [categoría adyacente]]. En esos casos, [competidor o enfoque alternativo] encaja mejor de verdad, y eso te lo decimos en una llamada de ventas.\n\nDesglose completo, con comparativa al lado: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== behind_the_scenes =====
    [
        'slug' => 'team_offsite_recap',
        'category' => 'behind_the_scenes',
        'name' => 'Recap del offsite del equipo',
        'description' => 'Resume un offsite o all-hands reciente del equipo.',
        'content' => "Cerramos nuestro offsite en [ciudad] la semana pasada.\n\n[Número] personas, [número] días, una pizarra que la pasó mal. Más o menos un tercio de la empresa se vio en persona por primera vez, lo que pasa cuando creces [de X a Y] en un año.\n\nGastamos más tiempo en [tema] del que habíamos planeado y menos en [otro tema] de lo que esperábamos. La conversación más difícil fue sobre [tema honesto, ej.: qué dejamos de hacer en la segunda mitad del año]. No la cerramos del todo. Está bien.\n\nEl próximo es en [lugar] en [mes]. Para entonces seremos [número] personas. No tengo idea cómo va a ser.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'office_or_remote_culture',
        'category' => 'behind_the_scenes',
        'name' => 'Cómo trabajamos',
        'description' => 'Comparte el modelo de trabajo de la empresa de forma honesta.',
        'content' => "Cómo trabaja {{brand_name}} de verdad, ya que nos preguntan.\n\nSomos [totalmente remotos / híbridos / con base en X y colaboradores remotos] en [número] zonas horarias. Sin días obligatorios en oficina. Hacemos un all-hands por semana y un update asíncrono los viernes.\n\nLo que nos gusta: bloques de trabajo profundo, contratar en distintas geografías, agendas más limpias.\n\nLo difícil: el onboarding lleva más tiempo del que llevaría en persona. Las ideas nuevas a veces se quedan trabadas en mensajes directos. La superposición horaria con [región] es complicada.\n\nNo decimos que sea el setup correcto para toda empresa. Es el que nos sirve a nosotros hoy.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'engineering_decision',
        'category' => 'behind_the_scenes',
        'name' => 'Recap de decisión de ingeniería',
        'description' => 'Comparte una decisión técnica o de producto interna y el porqué.',
        'content' => "El mes pasado [tomamos una decisión específica, ej.: salimos de X, reescribimos Y, matamos la función Z].\n\nLa versión corta del porqué: [motivo en una línea].\n\nLa versión larga. El setup viejo estaba bien cuando teníamos [número] clientes. En [escala actual], empezó a notarse en [síntoma específico]. Probamos [arreglo intermedio] durante unos [periodo de tiempo] hasta que aceptamos que no iba a aguantar.\n\nEl precio que aceptamos: [costo honesto, ej.: dos semanas con releases más lentos, breaking change para algunas integraciones].\n\nLo escribimos porque ojalá otros equipos compartan más de este tipo de decisión y no solo las victorias.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mistake_postmortem',
        'category' => 'behind_the_scenes',
        'name' => 'Postmortem público',
        'description' => 'Comparte un error, caída o falla reciente de forma honesta.',
        'content' => "El [fecha], {{brand_name}} tuvo [problema específico, ej.: una caída, un bug de cobro, un problema de datos que afectó al X% de las cuentas] durante unos [duración].\n\nQué pasó: [resumen técnico u operativo en un párrafo].\n\nA quién afectó: [alcance honesto, incluyendo a los clientes que no se vieron afectados].\n\nQué hicimos: [arreglo inmediato y mitigación].\n\nQué estamos cambiando para que no vuelva a pasar igual: [cambio específico, no un genérico 'lo haremos mejor'].\n\nSi te afectó y no te contactamos directamente, responde o escribe a [contacto]. Le debemos a varios una conversación más larga.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== testimonial =====
    [
        'slug' => 'customer_quote_short',
        'category' => 'testimonial',
        'name' => 'Cita corta de cliente',
        'description' => 'Comparte una cita corta y específica de cliente en la página de la empresa.',
        'content' => "De una conversación reciente con [primer nombre del cliente], [puesto] en [empresa]:\n\n\"[Cita del cliente, debe mencionar un resultado, número o cambio específico. Evita elogios genéricos del tipo 'gran producto'.]\"\n\nLes preguntamos si podíamos compartirla. Dijeron que sí.\n\nEl contexto detrás de la cita: [una o dos frases sobre lo que estaban tratando de hacer y qué cambió].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'case_study_recap',
        'category' => 'testimonial',
        'name' => 'Resumen de caso de éxito',
        'description' => 'Resume un caso de éxito de cliente publicado.',
        'content' => "Nuevo caso: [nombre del cliente].\n\nAntes de {{brand_name}}, su equipo estaba [situación específica, ej.: corriendo X manualmente, gastando Y horas/semana en Z]. Después de [periodo de tiempo] usando {{brand_name}}, [resultado específico con número].\n\nAlgunas cosas que ellos hicieron y que otros clientes no siempre prueban:\n[Táctica específica del cliente].\n[Otra táctica].\n[Nota honesta: algo que todavía están afinando].\n\nVersión completa con el flujo real del equipo y capturas: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'unexpected_use_case',
        'category' => 'testimonial',
        'name' => 'Uso inesperado del producto',
        'description' => 'Resalta una manera creativa o inesperada en que los clientes usan el producto.',
        'content' => "No construimos {{brand_name}} pensando en [caso de uso inesperado], pero los clientes lo siguen usando así.\n\n[Cliente o segmento de clientes] empezó a [comportamiento específico] hace unos [periodo de tiempo]. Lo notamos por [señal, ej.: un pico de uso en una función específica, un ticket de soporte pidiendo X]. Cuando les preguntamos, la respuesta fue: [razonamiento del cliente parafraseado].\n\nNo está en nuestro roadmap. Quizá entre pronto. Si estás haciendo algo parecido, a nuestro equipo de producto le encantaría escucharte. Responde aquí o escribe a [contacto].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== industry_tip =====
    [
        'slug' => 'contrarian_take',
        'category' => 'industry_tip',
        'name' => 'Opinión a contracorriente',
        'description' => 'Defiende una postura clara contra una idea popular del sector.',
        'content' => "Una opinión que nos mete en problemas en conferencias: [postura contraria, dicha sin vueltas].\n\nEl argumento de siempre es [postura popular]. No está mal en todos los casos. Está mal en la mayoría de los casos que vemos, y aquí va el porqué.\n\n[Razón 1 con ejemplo específico].\n[Razón 2 con ejemplo específico].\n\nLa contra que siempre nos ponen: [contraargumento bien hecho]. Es justo, y aceptamos que aplica cuando [condición específica]. Fuera de esa condición, el consejo de siempre les sale caro a los equipos sin que nadie se dé cuenta.\n\nFelices de estar equivocados acá. Cuéntenos en los comentarios por qué.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'industry_benchmark',
        'category' => 'industry_tip',
        'name' => 'Benchmark del sector',
        'description' => 'Comparte un benchmark o métrica agregada de la base de clientes.',
        'content' => "Benchmark rápido para [audiencia].\n\nEntre [número] cuentas {{brand_name}} de [sector/segmento] el último trimestre, la mediana de [métrica] fue [valor]. El percentil 90 fue [valor]. El 25% más bajo quedó por debajo de [valor].\n\nSi estás bajo la mediana, el motivo más común que vemos es [motivo específico]. La solución casi nunca es [respuesta obvia]. Suele ser [solución real].\n\nSi estás arriba del percentil 90, probablemente ya haces [comportamiento específico], y nos encantaría hablar contigo de eso. Responde o manda un DM a la página.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'trend_we_disagree_with',
        'category' => 'industry_tip',
        'name' => 'Tendencia con la que no estamos de acuerdo',
        'description' => 'Cuestiona una práctica de moda en el sector con argumentos.',
        'content' => "La mitad de los posts de [sector] que vemos este mes son sobre [práctica de moda].\n\nNosotros no la vamos a adoptar en {{brand_name}}, y es probable que no lo hagamos.\n\nEl pitch es [encuadre popular]. La versión honesta, según nuestra experiencia, es que funciona en [escenario acotado] y falla sin hacer ruido en [escenario común] por [motivo específico]. Probamos una versión interna durante [periodo de tiempo] y vimos [resultado específico].\n\nNo digo que nadie deba hacerlo. Digo que para [audiencia objetivo], el tiempo rinde más en [alternativa].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'practical_framework',
        'category' => 'industry_tip',
        'name' => 'Framework práctico',
        'description' => 'Comparte una regla simple o framework interno del equipo.',
        'content' => "Una regla de bolsillo que usa nuestro equipo para decidir [decisión específica]:\n\nSi [condición A], haz [opción 1].\nSi [condición B], haz [opción 2].\nSi no sabes en cuál estás, probablemente estás en [opción 1] complicándolo de más.\n\nNo es un framework con nombre. Salió de unos [periodo de tiempo] de equivocarnos en la misma decisión de maneras un poco distintas. Nos ahorra una o dos discusiones por semana.\n\n¿Útil? ¿Inútil? Cuéntennos cómo deciden ustedes.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== event =====
    [
        'slug' => 'event_announcement',
        'category' => 'event',
        'name' => 'Anuncio de evento',
        'description' => 'Anuncia un evento, webinar o workshop de la empresa.',
        'content' => "Vamos a hacer [nombre del evento] el [fecha] a las [hora/zona horaria].\n\nFormato: [virtual / presencial en ciudad / híbrido].\nPara quién es: [audiencia específica, ej.: heads de marketing en SaaS B2B, 20-200 empleados].\nDe qué vamos a hablar: [tema 1] y [tema 2]. Sin keynote. Sin desfile de proveedores.\n\nLimitamos las inscripciones a [número] para que el Q&A funcione de verdad. Si los eventos pasados sirven de guía, la segunda mitad es donde aparece lo bueno.\n\nInscríbete: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_recap',
        'category' => 'event',
        'name' => 'Recap del evento',
        'description' => 'Resume un evento reciente que la empresa organizó o donde participó.',
        'content' => "[Nombre del evento] cerró el [fecha]. Algunas cosas para anotar antes de que se borren.\n\nLa sala se prendió más en [momento o tema específico]. Nuestra hipótesis era que [tema A] iba a dominar. No fue así. Dominó [tema B], y deberíamos haberlo anticipado.\n\nLa pregunta más útil que recibimos: [pregunta parafraseada]. La contestamos con honestidad pero no muy bien. Si fuiste vos, te debemos una mejor, responde aquí.\n\nGracias a [socio / espacio / oradores] por hacer que pasara. Las grabaciones suben la semana que viene: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'conference_attendance',
        'category' => 'event',
        'name' => 'Participación en conferencia',
        'description' => 'Anuncia que el equipo va a estar en una conferencia próxima.',
        'content' => "{{brand_name}} va a estar en [conferencia] en [ciudad] del [fecha] al [fecha].\n\nVamos [número] personas. Este año no tenemos stand. Lo probamos el año pasado y las conversaciones más útiles pasaron lejos del stand.\n\nSi quieres encontrarte con nosotros:\n[Nombre del miembro del equipo] anda por ahí [días/horarios], con interés sobre todo en [tema].\n[Otro miembro del equipo] presenta sobre [tema] el [día].\nCena el [fecha], grupo chico, responde si quieres entrar.\n\nReserva un horario aquí: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== engagement =====
    [
        'slug' => 'open_question_to_audience',
        'category' => 'engagement',
        'name' => 'Pregunta abierta a la audiencia',
        'description' => 'Haz una pregunta real y específica a la audiencia de la página.',
        'content' => "Una pregunta de verdad para [audiencia] esta semana.\n\nCuando [situación específica, ej.: estás armando un proyecto nuevo, eligiendo un proveedor, decidiendo qué cortar], ¿cómo decides en la práctica?\n\nNo la versión que pondrías en un slide. La versión que incluye [factor honesto, ej.: quién está disponible esa semana, de qué humor está el CFO, qué herramienta ya conoce el equipo].\n\nVenimos haciendo una versión interna de esta pregunta en {{brand_name}} desde hace un mes y las respuestas son más interesantes que cualquier framework que vimos. Manda la tuya y compartimos lo que escuchamos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'we_want_your_feedback',
        'category' => 'engagement',
        'name' => 'Pedido de feedback',
        'description' => 'Pide la opinión de la audiencia sobre una decisión de roadmap específica.',
        'content' => "Estamos trabados con algo y queremos tu opinión.\n\nPara la próxima versión de {{brand_name}}, estamos eligiendo entre dos caminos para [área].\n\nOpción A: [dirección específica, con el trade-off].\nOpción B: [dirección específica, con el trade-off].\n\nLas dos son reales. Ninguna es claramente la correcta. Los clientes a los que preguntamos están divididos casi mitad y mitad, que es el peor resultado posible para un equipo de producto que quiere entregar.\n\nSi tienes una opinión, sobre todo si es fuerte, responde aquí o manda DM a la página. Nuestro equipo de producto lee todo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'community_spotlight',
        'category' => 'engagement',
        'name' => 'Spotlight de la comunidad',
        'description' => 'Resalta a un cliente, socio o miembro de la comunidad que está haciendo algo interesante.',
        'content' => "Spotlight para [nombre], [puesto] en [empresa].\n\nVimos [su trabajo o post específico] la semana pasada y terminó circulando dentro del equipo de {{brand_name}}. La versión corta del porqué: [motivo específico, qué hizo que fue distinto, útil o a contramano].\n\nVe a seguirle, si todavía no lo haces. No tenemos ningún acuerdo comercial. Sólo está haciendo el tipo de trabajo que nos gustaría ver más en [sector] de forma pública.\n\n[Link a su post / perfil].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'year_in_review',
        'category' => 'engagement',
        'name' => 'Resumen del año',
        'description' => 'Resumen de fin de año honesto desde la página de la empresa.',
        'content' => "Un resumen corto del año de {{brand_name}}.\n\nLo bueno: [logro específico con número]. [Otro logro específico, idealmente un resultado de cliente y no una métrica de vanidad].\n\nLo difícil: [error honesto, ej.: una apuesta de producto que no funcionó, un objetivo de contratación que no alcanzamos, un objetivo que pusimos en enero y soltamos sin ruido en junio].\n\nLo sorpresivo: [algo inesperado que importó, un segmento de cliente que despegó, una función que nadie pidió y se volvió clave].\n\nGracias a los [número] clientes, las [número] personas del equipo y a quienes nos respondían a las 23 h pidiendo que entregáramos cosas. El año que viene va a ser más raro que este.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
