<?php

declare(strict_types=1);

return [
    [
        'slug' => 'product_launch_announcement',
        'category' => 'product_launch',
        'name' => 'Anuncio de lanzamiento de producto',
        'description' => 'Publicación corta en LinkedIn anunciando un nuevo producto.',
        'content' => "Tenemos algo que contarte: {{brand_name}} acaba de lanzar [Nombre del Producto].\n\nPor qué importa para [tu audiencia]:\n→ [Beneficio 1]\n→ [Beneficio 2]\n→ [Beneficio 3]\n\nMás info en [link]. Nos encantaría escuchar tu opinión.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'how_to_guide',
        'category' => 'educational',
        'name' => 'Guía paso a paso',
        'description' => 'Publicación educativa paso a paso para LinkedIn.',
        'content' => "Cómo [lograr X] en [plazo], una guía paso a paso.\n\nPaso 1: [Acción]\nPaso 2: [Acción]\nPaso 3: [Acción]\nPaso 4: [Acción]\n\nLo que la mayoría no ve: [insight].\n\n¿Qué paso se te complica más? Cuéntame en los comentarios.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'customer_quote',
        'category' => 'testimonial',
        'name' => 'Testimonio de cliente',
        'description' => 'Comparte un testimonio potente de un cliente en LinkedIn.',
        'content' => "\"[Frase del cliente sobre el resultado que logró con tu producto o servicio.]\"\n- [Nombre del Cliente], [Cargo] en [Empresa]\n\nPor esto construimos {{brand_name}}. Resultados reales para equipos reales.\n\nLee la historia completa → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'industry_insight',
        'category' => 'industry_tip',
        'name' => 'Insight del sector',
        'description' => 'Comparte una visión actual u opinión fuerte sobre tu industria.',
        'content' => "Algo que la mayoría en [industria] entiende mal:\n\n[Afirmación contraintuitiva u opinión fuerte]\n\n¿Por qué? Porque [razón].\n\nLo que sí funciona: [mejor camino].\n\nEn {{brand_name}} lo vimos pasar con cientos de [clientes/equipos]. Los datos son claros.\n\n¿Cuál es tu postura?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_announcement',
        'category' => 'event',
        'name' => 'Anuncio de evento',
        'description' => 'Anuncia un webinar o evento en vivo próximo.',
        'content' => "📅 Aparta la fecha: {{brand_name}} organiza [Nombre del Evento] el [Fecha] a las [Hora].\n\nQué esperar:\n✔ [Tema 1]\n✔ [Tema 2]\n✔ [Tema 3]\n\nCupos limitados. Regístrate ya → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'community_question',
        'category' => 'engagement',
        'name' => 'Pregunta para la comunidad',
        'description' => 'Provoca conversación con una pregunta abierta a tu red.',
        'content' => "Si pudieras dar un solo consejo a alguien que recién empieza en [industria/rol], ¿cuál sería?\n\nEl mío: [tu respuesta, sé honesto y específico]\n\nDeja el tuyo en los comentarios. Armemos un hilo que valga la pena guardar.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Product launch (3) =====
    [
        'slug' => 'feature_release_notes',
        'category' => 'product_launch',
        'name' => 'Notas de lanzamiento de feature',
        'description' => 'Cuéntale a tu red qué se publicó y por qué importa.',
        'content' => "Hoy publicamos [Nombre de la Feature].\n\nLa versión corta: hace [lo que hace] para [a quién está dirigida]. Nos llevó [plazo] del primer boceto a producción.\n\nLo que cambia de verdad:\n• [Capacidad uno, en lenguaje claro]\n• [Capacidad dos, con un ejemplo real]\n• [Lo que cortamos y por qué]\n\nDebatimos [tradeoff] durante semanas. Al final elegimos [decisión] porque [razón]. Si tú habrías tomado la otra decisión, quiero entender por qué.\n\nDocs y un recorrido de 4 minutos en [link]. Los reportes de bugs son bienvenidos, leemos cada uno.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'beta_invitation',
        'category' => 'product_launch',
        'name' => 'Invitación a beta privada',
        'description' => 'Invita a tu red a una beta cerrada con expectativas claras.',
        'content' => "Estamos abriendo [Producto/Feature] en beta privada para un grupo pequeño. Buscamos unos [N] testers.\n\nEl perfil ideal:\n• Trabajas en [rol/industria]\n• Hoy usas [herramienta o flujo] y sientes [fricción específica]\n• Tienes 30 minutos a la semana para romper cosas y contarnos\n\nLo que recibes: acceso anticipado, línea directa con el equipo de {{brand_name}} y voz en lo que construyamos después. Lo que recibimos: feedback honesto, aunque duela.\n\nSi te calza, comenta o escríbeme por DM. Mandamos las invitaciones esta [día/semana].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'milestone_update',
        'category' => 'product_launch',
        'name' => 'Hito del producto',
        'description' => 'Comparte un hito relevante del producto o la empresa con números concretos.',
        'content' => "Hito discreto que cumplimos esta semana: {{brand_name}} pasó de [número / métrica].\n\nPara contexto, cuando arrancamos hace [plazo] teníamos [número inicial]. La mayor parte del crecimiento vino de [canal o motor específico], no de lo que esperábamos.\n\nAlgunas cosas que aprendí en el camino:\n1. [Lección uno, con los números]\n2. [Lección dos, qué haríamos distinto]\n3. [Lección tres sobre el equipo]\n\nGracias a las [N] personas que apostaron por nosotros cuando esto estaba muy crudo. Seguimos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Promotion (3) =====
    [
        'slug' => 'limited_time_offer',
        'category' => 'promotion',
        'name' => 'Oferta por tiempo limitado',
        'description' => 'Promueve un descuento u oferta con plazo, sin caer en spam.',
        'content' => "Estamos corriendo una promo de [% de descuento] en {{brand_name}} hasta el [fecha].\n\nNo es un truco de Black Friday. Tuvimos un [mes/trimestre] flojo y queremos sumar [N] nuevos [usuarios/clientes] antes de [fin del periodo]. Esa es la razón honesta.\n\nSi venías dudando: [link]. Si te suscribiste en los últimos 30 días, escríbeme y aplico el mismo descuento de forma retroactiva. Es lo correcto.\n\nLa oferta termina el [fecha] a las [hora, zona horaria].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'free_resource_offer',
        'category' => 'promotion',
        'name' => 'Recurso gratuito',
        'description' => 'Ofrece una descarga o plantilla útil como recurso de baja fricción.',
        'content' => "Pasé el fin de semana convirtiendo nuestro [tipo de recurso, checklist, plantilla, playbook] interno en algo que se puede compartir.\n\nEs el mismo [documento] que usa nuestro equipo para [caso de uso específico]. Sin adornos: [N] páginas, sin relleno, sin formulario de email.\n\nDeja un comentario con la palabra \"[palabra clave]\" y te paso el link por DM. Si prefieres tomarlo directo: [link].\n\nAviso: tiene opinión. Si discrepas con mi postura sobre [punto específico], dímelo. Así lo mejoro para la v2.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'partnership_announcement',
        'category' => 'promotion',
        'name' => 'Anuncio de alianza',
        'description' => 'Anuncia una alianza o integración con un beneficio claro para el cliente.',
        'content' => "{{brand_name}} ya está integrado con [Nombre del Partner].\n\nEl efecto práctico para [audiencia]: ahora puedes [flujo o capacidad específica] sin [el rodeo anterior]. Ahorra cerca de [tiempo/dinero] por [periodo] según el grupo de prueba inicial.\n\nElegimos [Partner] porque su equipo se obsesiona con [valor compartido] igual que el nuestro. No toda solicitud de integración pasa el filtro, y la mayoría no pasa.\n\nLa configuración toma unos [N] minutos. Tutorial aquí: [link]. Si ya usas ambas herramientas, queremos saber cómo te fue.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Educational (3) =====
    [
        'slug' => 'lesson_learned',
        'category' => 'educational',
        'name' => 'Lección de un error',
        'description' => 'Enseña contando un error específico y lo que cambió por él.',
        'content' => "Cometí un error de [N] cifras el [año/trimestre] pasado y quiero escribir sobre él mientras todavía duele.\n\nEl contexto: estábamos en [situación]. La decisión: [lo que hiciste]. La lógica en ese momento: [por qué parecía lo correcto].\n\nLo que pasó en realidad: [resultado, en términos concretos]. Perdimos [costo específico, dinero, tiempo, clientes, confianza].\n\nLo que debí haber hecho: [mejor camino], y la razón por la que no lo hice fue [razón honesta, ego, prisa, faltaba data].\n\nTres cosas que cambié en mi forma de trabajar por esto:\n1. [Cambio uno]\n2. [Cambio dos]\n3. [Cambio tres]\n\nSi pasaste por algo así, sabes de qué hablo. Cuéntame el tuyo en los comentarios.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'framework_breakdown',
        'category' => 'educational',
        'name' => 'Framework o modelo mental al detalle',
        'description' => 'Explica un framework o modelo mental específico con un ejemplo concreto.',
        'content' => "Vuelvo siempre a un modelo mental cuando pienso en [tema/problema]: [Nombre del Framework].\n\nLa idea es simple. [Resumen del framework en una frase.]\n\nCómo lo uso de verdad: cuando me trabo en [situación específica], me pregunto [pregunta específica que dispara el framework]. La semana pasada me empujó a [decisión que tomaste por él].\n\nDónde se rompe: [limitación honesta]. No es respuesta universal para [tipo de problema], y tratarlo como si lo fuera lleva a [mal resultado].\n\nSi quieres leer la fuente original, es [autor/libro/link]. La versión de arriba es la mía, ajustada con cientos de usos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'tool_comparison',
        'category' => 'educational',
        'name' => 'Comparación honesta de herramientas',
        'description' => 'Compara dos o tres herramientas o enfoques con tradeoffs reales.',
        'content' => "Usé [Herramienta A], [Herramienta B] y [Herramienta C] para [tarea] durante los últimos [plazo]. Aquí dónde gana cada una de verdad.\n\n[Herramienta A] es la elección correcta cuando [situación específica]. Es la más rápida en [tarea específica] y la peor en [tarea específica]. La usamos para [caso de uso].\n\n[Herramienta B] se siente menos pulida, pero hace [cosa] mejor que cualquier otra que probé. Vale la incomodidad si [criterio].\n\n[Herramienta C] es la opción aburrida. Eso es un cumplido. Es confiable, la documentación la escribieron humanos, y el equipo no publica breaking changes los viernes.\n\nMi stack actual en {{brand_name}}: [respuesta real]. El tuyo puede ser distinto si [razón].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Behind the scenes (3) =====
    [
        'slug' => 'team_culture_glimpse',
        'category' => 'behind_the_scenes',
        'name' => 'Momento de cultura del equipo',
        'description' => 'Comparte un momento pequeño y específico que muestra cómo trabaja el equipo de verdad.',
        'content' => "Cosa pequeña que pasó en {{brand_name}} esta semana.\n\n[Persona o rol del equipo] notó [problema o detalle específico]. Podía haberse publicado igual. En vez de eso, [acción específica], lo que retrasó [cosa] en [plazo].\n\nNadie lo pidió. No había ticket en Jira. El cliente nunca se habría enterado.\n\nEsta es la parte de construir una empresa que no entra en una página de carreras. El trabajo que nadie ve, hecho bien igual, porque así son las personas de aquí. Pienso bastante en eso.\n\nSi quieres trabajar con gente así: [link]. Si ya lo haces, mándale un DM.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'how_we_built_it',
        'category' => 'behind_the_scenes',
        'name' => 'Cómo lo construimos',
        'description' => 'Cuenta la historia real de una entrega reciente, incluyendo los callejones sin salida.',
        'content' => "Cómo construimos [Feature/Producto] en {{brand_name}}, incluyendo las partes que solemos dejar fuera.\n\nArrancamos con [plan original]. Tardamos [plazo] en darnos cuenta de que el plan estaba equivocado. El problema real era [problema real], y solo se hizo visible después de [evento gatillo].\n\nLa versión 2 fue [lo que probamos después]. Funcionó en la demo y se cayó en producción a [escala o condición]. Reescribimos el [componente específico] dos veces.\n\nLo que finalmente salió: [solución actual]. Es [reconocimiento honesto del tradeoff, más lenta, más simple, menos elegante] que lo que queríamos construir, y es la versión que sí resuelve el problema del cliente.\n\nWriteup completo con los diagramas de arquitectura: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'day_in_the_life',
        'category' => 'behind_the_scenes',
        'name' => 'Un día en el equipo',
        'description' => 'Muestra cómo es un día real para alguien del equipo.',
        'content' => "Saqué la agenda del [día de la semana] y conté: [N] reuniones, [N] horas de trabajo concentrado, [N] interrupciones a las que debí decir que no.\n\nEl trabajo que sí importó:\n• [Tarea uno, y por qué importó]\n• [Tarea dos, incluyendo lo que te sorprendió]\n• [Tarea tres]\n\nEl trabajo que parecía urgente y no lo era: [ejemplo honesto]. Sigo cayendo en eso y ya estoy cansado.\n\nAntes pensaba que la meta era un día perfecto. Ahora creo que la meta son unas pocas horas reales y la disciplina para protegerlas. Curioso cómo lo manejan ustedes con [desafío específico del post].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Testimonial (3) =====
    [
        'slug' => 'before_after_story',
        'category' => 'testimonial',
        'name' => 'Antes y después de un cliente',
        'description' => 'Cuenta la historia de un cliente con números concretos del antes y el después.',
        'content' => "Historia rápida de un cliente de {{brand_name}} que vale la pena compartir.\n\n[Cliente/Empresa] llegó a nosotros hace [plazo]. El estado de las cosas entonces: [métrica dolorosa específica, horas por semana, tasa de error, churn, costo]. Habían probado [enfoque anterior] y el número no se movió.\n\n[Plazo] después, esa misma métrica está en [nuevo número]. La pieza que más pesó, según [Nombre, cargo]: [cambio específico en cómo trabajan].\n\nLo que me gusta de esta historia: no fue una feature mágica. Fue [fundamento aburrido, cambio de proceso, default que invirtieron, reunión que eliminaron]. La mayoría de las victorias se ven así y no lo hablamos lo suficiente.\n\nCaso completo con los detalles desordenados: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'unsolicited_review',
        'category' => 'testimonial',
        'name' => 'Reseña espontánea de cliente',
        'description' => 'Comparte un feedback orgánico de un cliente con una reacción reflexiva.',
        'content' => "Esto llegó ayer a nuestra bandeja, de [Nombre del Cliente] en [Empresa]:\n\n\"[Cita honesta y específica, incluyendo cualquier crítica pequeña o tradeoff que mencione. Las reseñas reales no son solo elogio.]\"\n\nAlgunas reacciones honestas de mi lado. La parte sobre [elogio específico] es en lo que más hemos trabajado, así que esa pegó. La parte sobre [queja o deseo específico] es justa, y ya está en el roadmap para [plazo].\n\nNo pagamos por reseñas y no las pedimos. Cuando aparece una así, la leo dos veces. Gracias, [Nombre].\n\nSi tienes una historia con {{brand_name}}, buena, mala o mixta, quiero escucharla.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'team_member_spotlight',
        'category' => 'testimonial',
        'name' => 'Reflector sobre alguien del equipo',
        'description' => 'Destaca a una persona del equipo por una contribución concreta.',
        'content' => "Quiero hablar un momento de [Nombre], [cargo] en {{brand_name}}.\n\n[Nombre] entró hace [plazo]. Lo que tiene a su cargo hoy: [área o sistema específico]. Lo que hizo y poca gente habría hecho: [historia específica, decisión dura, arreglo poco glamoroso, tradeoff que defendió].\n\nEl resultado: [resultado concreto, con un número si lo tienes]. Por qué funcionó: el instinto de [Nombre] sobre [cualidad específica], del que sigo aprendiendo.\n\nEsto no es falsa modestia. Es un gracias, en plataforma pública, porque esa parte del trabajo suele pasar en silencio. [Nombre], el equipo es mejor contigo dentro.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Industry tip (3) =====
    [
        'slug' => 'data_point_take',
        'category' => 'industry_tip',
        'name' => 'Dato y lo que significa',
        'description' => 'Comparte un dato reciente de una fuente real con tu interpretación.',
        'content' => "[Fuente, reporte, estudio, dataset público] publicó este número la semana pasada: [estadística específica].\n\nLa mayoría de las lecturas que vi lo enmarcan como [interpretación común]. Creo que se pierde el punto.\n\nCuando cortas los mismos datos por [dimensión, segmento, geografía, tamaño de empresa, periodo], el cuadro cambia. [Subgrupo específico] está [comportamiento específico], mientras que [otro subgrupo] está [comportamiento distinto]. El número titular promedia esas dos historias en algo que no describe a ninguna.\n\nLa implicación práctica para [audiencia]: [recomendación específica]. No [consejo común], porque se apoya en un promedio que no existe.\n\nLink a los datos en bruto: [link]. Dime dónde estoy equivocado.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'contrarian_take',
        'category' => 'industry_tip',
        'name' => 'Postura contraria con argumentos',
        'description' => 'Cuestiona una creencia común de tu industria con un argumento específico.',
        'content' => "Opinión impopular en [industria]: [tesis contraria].\n\nEl consejo estándar dice [sabiduría convencional]. Lo seguí durante [plazo] y el resultado fue [resultado específico, malo o mediocre].\n\nPor qué no funciona tan bien como dicen: [razón específica, incentivo, costo oculto, sesgo de supervivencia, mercado cambió]. La versión que sí funciona para [audiencia] se parece más a [enfoque alternativo].\n\nPara que conste, ese fue el camino que tomamos en {{brand_name}} después de [evento gatillo]. Números desde entonces: [resultado específico]. No digo que todos deban hacerlo. Sí digo que \"porque todos lo dicen\" es una mala razón para seguir haciendo lo mismo.\n\n¿Dónde estás tú en esto?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'trend_watch',
        'category' => 'industry_tip',
        'name' => 'Tendencia para vigilar',
        'description' => 'Pon foco en una tendencia menor antes de que se vuelva mainstream.',
        'content' => "Tendencia silenciosa en [industria] que creo que la mayoría discutirá en [plazo]: [tendencia específica].\n\nLa señal que estoy mirando: [evidencia concreta, patrones de contratación, nuevos jugadores, cambios de precio, qué piden los clientes]. Tres [empresas/equipos] distintos en nuestra red hicieron [cosa específica] en el último [periodo], cada uno por su cuenta.\n\nPor qué creo que sí importa y no es solo hype: [razón anclada en incentivos, no en vibras]. Lo que me haría cambiar de idea: [contraseñal específica que vigilaría].\n\nSi eres [audiencia], el movimiento práctico hoy es [acción específica]. No un giro que apuesta la empresa. Solo lo justo para no quedar fuera de juego en [plazo].\n\n¿Qué estás viendo tú?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Event (3) =====
    [
        'slug' => 'event_recap',
        'category' => 'event',
        'name' => 'Resumen de evento con aprendizajes',
        'description' => 'Resume un evento al que asististe con aprendizajes específicos.',
        'content' => "Vuelvo de [Nombre del Evento]. Tres cosas se me quedaron, y una con la que sigo discutiendo.\n\nLo que se sostuvo: [sesión o ponente específico], que defendió que [argumento específico]. La parte que no había considerado: [insight específico].\n\nLo que me llevo a {{brand_name}}: [cambio concreto que harás por el evento]. Lo bastante chico para empezar la próxima semana, lo bastante grande para importar.\n\nCon lo que no estuve de acuerdo: [postura específica de una sesión]. El argumento estaba bien armado, pero ignora [realidad específica]. Voy a escribir eso aparte, en serio.\n\nSi estuviste ahí, ¿qué se me escapó? Siempre hay más en los pasillos que en el escenario principal.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'speaking_announcement',
        'category' => 'event',
        'name' => 'Anuncio de ponencia',
        'description' => 'Anuncia que tú o alguien del equipo va a dar una charla en un evento.',
        'content' => "Voy a dar una charla en [Nombre del Evento] el [fecha] en [lugar / online].\n\nLa charla: \"[Título de la Charla]\". El pitch corto: [una o dos frases sobre lo que el público se llevará de verdad].\n\nLo que no voy a hacer: pasar buenas prácticas genéricas de [tema]. Ya hay suficientes. Lo que sí voy a hacer: mostrar [dato, framework o caso] específico de {{brand_name}} que cambió cómo pensamos [problema específico], incluyendo las partes que no funcionaron.\n\nSi vas a estar, búscame, prefiero una conversación de verdad antes que juntar tarjetas. Registro: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'webinar_invitation',
        'category' => 'event',
        'name' => 'Invitación a webinar',
        'description' => 'Invita a tu red a un webinar con una agenda clara y honesta.',
        'content' => "Voy a hacer un webinar de [duración, ej. 45 minutos] con [Nombre del co-host, cargo] el [fecha].\n\nTema: [tema específico, como una pregunta que tu audiencia se está haciendo]. No vamos a hacer una demo de producto. Vamos a recorrer [framework, dataset o flujo específico] que usamos en {{brand_name}}.\n\nAgenda preliminar:\n• [Hora], [Tema, con un detalle que muestra el contenido real]\n• [Hora], [Tema]\n• [Hora], Q&A en vivo. Respondemos todo, incluyendo las preguntas incómodas.\n\nLa repetición llega a quien se registre, aunque no puedas conectarte en vivo. Inscripción: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ===== Engagement (3) =====
    [
        'slug' => 'poll_post',
        'category' => 'engagement',
        'name' => 'Encuesta con opinión',
        'description' => 'Haz una pregunta directa de A o B que saque opiniones reales.',
        'content' => "Curioso por ver cómo se está partiendo [audiencia] en esto.\n\nCuando decides [decisión específica], ¿te inclinas por:\n\nA) [Opción A, descrita concretamente]\nB) [Opción B, descrita concretamente]\n\nNada de \"depende\" en los comentarios, por favor. Elige una y dime por qué en una frase.\n\nMi respuesta: [tu elección honesta]. La razón: [una o dos frases desde experiencia real]. Sostuve la postura contraria durante [plazo] hasta que [cosa que me hizo cambiar de idea].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'hot_take_invitation',
        'category' => 'engagement',
        'name' => 'Invitación a opinión polémica',
        'description' => 'Invita a la red a compartir una opinión controversial de su área.',
        'content' => "¿Cuál es una opinión sobre [industria/rol] que te hace ganar miradas raras en una conferencia?\n\nLa mía: [opinión tuya levemente polémica en tu campo, dicha sin rodeos]. Me he equivocado en muchas cosas, pero en esta sostengo la postura.\n\nNo busco las opiniones seguras que ya tienen 500 carruseles de LinkedIn detrás. Las que dirías en la cena después del panel, cuando ya dejaste de actuar.\n\nDispara. Voy a estar en los comentarios discutiendo de buena fe.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'crowdsourced_advice',
        'category' => 'engagement',
        'name' => 'Pedido de consejo colectivo',
        'description' => 'Pide a tu red su opinión sobre un problema real y específico.',
        'content' => "Pido el cerebro colectivo en un problema real que estamos resolviendo en {{brand_name}}.\n\nContexto: [situación específica en 2-3 frases, suficiente para que alguien calificado pueda ayudar]. La restricción que hace que la respuesta obvia no sirva: [restricción específica].\n\nLo que ya probé: [opción uno, y por qué no encajó]; [opción dos, y lo que me enseñó]. Así que esas no las busco.\n\nSi resolviste algo parecido, ¿qué funcionó? Comentarios son lo mejor, pero el DM está abierto si es de esas cosas que prefieres no decir en público. Voy a escribir lo que terminemos haciendo y etiquetar a quien aporte.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
