<?php

declare(strict_types=1);

return [
    [
        'slug' => 'mastodon_release_note',
        'category' => 'product_launch',
        'name' => 'Notas de la release',
        'description' => 'Comparte una actualización abierta y transparente sobre una release.',
        'content' => "Notas de la release de {{brand_name}}:\n\n→ [Qué se entregó]\n→ [Por qué importa]\n→ [Qué viene después]\n\nFeedback bienvenido. Responde o abre un issue.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_lessons_learned',
        'category' => 'educational',
        'name' => 'Lecciones aprendidas',
        'description' => 'Comparte algo que aprendiste, en el estilo directo de Mastodon.',
        'content' => "Algo que aprendimos en {{brand_name}} esta semana:\n\n[Lección, sé específico.]\n\nLa conclusión: [principio].\n\nQuizás le sirva a alguien más que esté construyendo [algo parecido].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_open_question',
        'category' => 'engagement',
        'name' => 'Pregunta abierta',
        'description' => 'Haz una pregunta al fediverso y recoge perspectivas.',
        'content' => "Pregunta para el fediverso:\n\n[Pregunta abierta relevante para tu audiencia.]\n\nBoosts bienvenidos si tus seguidores podrían tener algo que decir.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // product_launch
    [
        'slug' => 'mastodon_version_bump',
        'category' => 'product_launch',
        'name' => 'Nueva versión',
        'description' => 'Anuncia una nueva versión con el diff que de verdad importa.',
        'content' => "{{brand_name}} [versión] ya salió.\n\nQué cambió:\n- [Fix o feature]\n- [Fix o feature]\n- [Breaking change, si lo hay]\n\nNotas de upgrade: [link o instrucción corta].\n\nSi algo se rompe, cuéntanos. Leemos cada respuesta.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_new_feature_in_public',
        'category' => 'product_launch',
        'name' => 'Feature nuevo en público',
        'description' => 'Lanza un feature y explica por qué lo construiste así.',
        'content' => "Hoy agregamos [feature] a {{brand_name}}.\n\nPor qué: [el motivo real, en una frase].\n\nCómo funciona: [descripción corta y concreta].\n\nEl código está aquí: [link]. Pull requests bienvenidos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_beta_invite',
        'category' => 'product_launch',
        'name' => 'Invitación a beta',
        'description' => 'Invita al fediverso a un beta con expectativas honestas.',
        'content' => "Buscamos beta testers para [feature] en {{brand_name}}.\n\nEstá rústico. Algunas cosas se van a romper. Queremos saber cuáles.\n\nRegistro: [link]\n\nSin NDA, sin lista de marketing, sin upsell. Solo necesitamos usuarios reales.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_self_host_release',
        'category' => 'product_launch',
        'name' => 'Release para self-host',
        'description' => 'Avisa a quienes hacen self-host sobre una release con los detalles operativos.',
        'content' => "Aviso para quienes hacen self-host de {{brand_name}}: [versión] está taggeada.\n\nMigraciones: [sí/no, tiempo estimado]\nCambios de config: [lista o ninguno]\nBreaking: [lista o ninguno]\n\nDocs: [link]. Issues: [link]. Boosts bienvenidos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // promotion
    [
        'slug' => 'mastodon_paid_plan_honest',
        'category' => 'promotion',
        'name' => 'Plan pago, sin vueltas',
        'description' => 'Menciona un plan pago sin sonar a anuncio.',
        'content' => "{{brand_name}} ahora tiene plan pago. Esto es lo que te da: [feature], [feature], [feature].\n\nEl tier gratis sigue haciendo [lo que siempre hizo]. No estamos quitando nada.\n\nDetalles: [link]. Las preguntas son bienvenidas.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_sponsor_us',
        'category' => 'promotion',
        'name' => 'Patrocínanos',
        'description' => 'Pide patrocinio o donaciones de forma transparente.',
        'content' => "{{brand_name}} se sostiene con [número] horas de trabajo voluntario y [costo de hosting] al mes.\n\nSi lo usas y quieres aportar, el patrocinio está aquí: [link].\n\nPublicamos un desglose de gastos cada trimestre. Sin tiers, sin perks, solo el trabajo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_discount_for_indies',
        'category' => 'promotion',
        'name' => 'Descuento para indies',
        'description' => 'Ofrece un descuento sin dark patterns.',
        'content' => "{{brand_name}} tiene [descuento] de descuento para devs solo y cooperativas pequeñas hasta [fecha].\n\nSin cupón, sin registro de email. El precio es más bajo si eliges el tier [nombre del plan]. Úsalo si te ayuda.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // educational
    [
        'slug' => 'mastodon_quick_explainer',
        'category' => 'educational',
        'name' => 'Explicación rápida',
        'description' => 'Explica un concepto en lenguaje simple, sin relleno.',
        'content' => "Explicación rápida: [concepto].\n\n[Definición en una frase.]\n\n[Una frase sobre por qué importa en la práctica.]\n\nSi quieres la versión larga, la escribimos aquí: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_misconception',
        'category' => 'educational',
        'name' => 'Malentendido común',
        'description' => 'Corrige un malentendido común con detalles específicos.',
        'content' => "Mucha gente piensa que [creencia común sobre tu tema].\n\nNo es del todo así. [La situación real, con un ejemplo específico.]\n\nImporta porque [consecuencia práctica].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_reading_list',
        'category' => 'educational',
        'name' => 'Lista de lectura',
        'description' => 'Comparte una lista de lectura corta y con opinión.',
        'content' => "Cosas que estamos leyendo en {{brand_name}}:\n\n- [Título], de [autor]: [motivo en una línea].\n- [Título], de [autor]: [motivo en una línea].\n- [Título], de [autor]: [motivo en una línea].\n\nResponde con lo que tú estás leyendo. Siempre buscamos nuevas referencias.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_how_we_decided',
        'category' => 'educational',
        'name' => 'Cómo decidimos',
        'description' => 'Repasa una decisión técnica o de producto.',
        'content' => "Cómo elegimos [herramienta o enfoque] para {{brand_name}}:\n\nProbamos [opción A]. Tuvo [problema]. Probamos [opción B]. Tenía [tradeoff].\n\nElegimos [opción elegida] porque [razón]. No es perfecto. Lo que aún nos molesta es [punto débil].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // behind_the_scenes
    [
        'slug' => 'mastodon_dev_log',
        'category' => 'behind_the_scenes',
        'name' => 'Dev log',
        'description' => 'Comparte lo que de verdad hiciste esta semana.',
        'content' => "Dev log, semana del [fecha]:\n\nLunes: [cosa].\nMartes: [cosa].\nMiércoles: [cosa que salió mal].\nJueves: [arreglo].\nViernes: [salió o se pospuso].\n\nEsta semana es sobre todo [próximo foco].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_postmortem',
        'category' => 'behind_the_scenes',
        'name' => 'Postmortem corto',
        'description' => 'Comparte un postmortem en lenguaje simple.',
        'content' => "{{brand_name}} tuvo una caída el [fecha]. La versión corta:\n\nQué se rompió: [sistema].\nPor qué: [causa raíz].\nDuración: [tiempo].\nCómo lo arreglamos: [acción].\n\nWriteup completo con timeline: [link]. Disculpa la molestia.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_tooling_setup',
        'category' => 'behind_the_scenes',
        'name' => 'Nuestro stack',
        'description' => 'Muestra las herramientas que usas de verdad.',
        'content' => "Lo que usa {{brand_name}}, por si te da curiosidad:\n\n- Editor: [editor]\n- Lenguaje: [lenguaje]\n- Base de datos: [base de datos]\n- Hosting: [host]\n- CI: [ci]\n\nNada exótico. Stack aburrido es stack productivo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_team_intro',
        'category' => 'behind_the_scenes',
        'name' => 'Quiénes somos',
        'description' => 'Presenta a las personas detrás del proyecto.',
        'content' => "Presentación rápida: {{brand_name}} somos [número] personas.\n\n[Nombre] trabaja en [área].\n[Nombre] trabaja en [área].\n[Nombre] trabaja en [área].\n\nEstamos repartidos por [regiones]. Contratamos abiertamente cuando contratamos, lo que es raro. Hola.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // testimonial
    [
        'slug' => 'mastodon_user_quote',
        'category' => 'testimonial',
        'name' => 'Cita de usuario',
        'description' => 'Comparte una cita real, con permiso y contexto.',
        'content' => "[Username] nos mandó esto sobre {{brand_name}}, publicado con permiso:\n\n\"[Cita real.]\"\n\nNos hizo la semana. Gracias [@username] por tomarte el tiempo de escribir.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_use_case_share',
        'category' => 'testimonial',
        'name' => 'Cómo lo usa alguien',
        'description' => 'Destaca una forma específica en que alguien usa tu herramienta.',
        'content' => "[Persona u organización] usa {{brand_name}} para [caso de uso específico].\n\nLo que nos contaron: \"[cita corta y específica].\"\n\nSi tienes un setup que vale la pena compartir, responde o manda un DM. Nos gusta coleccionar estos casos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_thanks_contributor',
        'category' => 'testimonial',
        'name' => 'Gracias a un contribuidor',
        'description' => 'Da crédito a un contribuidor por su nombre.',
        'content' => "Shoutout a [@username] por [contribución específica] en {{brand_name}}.\n\nEste tipo de trabajo no es glamoroso y es la razón por la que el proyecto sigue avanzando. Gracias.\n\nEl PR está aquí: [link].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // industry_tip
    [
        'slug' => 'mastodon_practical_tip',
        'category' => 'industry_tip',
        'name' => 'Tip práctico',
        'description' => 'Comparte un tip real y específico.',
        'content' => "Tip si trabajas con [tema]:\n\n[Un tip concreto en lenguaje simple.]\n\nLo descubrimos a la mala después de [contexto breve]. Quizás le ahorre unas horas a alguien más.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_unpopular_opinion',
        'category' => 'industry_tip',
        'name' => 'Opinión impopular',
        'description' => 'Comparte una postura contraria en la que de verdad crees.',
        'content' => "Postura que nos mete en problemas: [creencia contraria sobre tu campo].\n\nMotivo: [el caso específico donde aplica].\n\nEstamos abiertos a estar equivocados. Si no estás de acuerdo, responde con el caso y lo leemos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_anti_pattern',
        'category' => 'industry_tip',
        'name' => 'Antipatrón',
        'description' => 'Señala un antipatrón común con cuidado.',
        'content' => "Antipatrón que vemos mucho en [dominio]: [el patrón].\n\nPor qué te muerde: [modo de falla específico].\n\nQué hacer en su lugar: [alternativa]. No siempre, pero la mayoría de las veces.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_stop_doing_this',
        'category' => 'industry_tip',
        'name' => 'Deja de hacer esto',
        'description' => 'Empuja contra un hábito que le cuesta tiempo a la gente.',
        'content' => "Empujón amigable: deja de [hábito común] cuando trabajes con [dominio].\n\nTe cuesta [costo específico] y la alternativa es [alternativa], que toma [esfuerzo].\n\nNosotros hicimos lo mismo durante años. El cambio es chico y el retorno es real.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // event
    [
        'slug' => 'mastodon_event_announce',
        'category' => 'event',
        'name' => 'Anuncio de evento',
        'description' => 'Anuncia un evento sin hype.',
        'content' => "{{brand_name}} estará en [evento] el [fecha] en [ciudad].\n\n[Speaker o miembro del equipo] va a hablar de [tema] a las [hora].\n\nSi andas por ahí, pasa a saludar. Boosts bienvenidos para gente del fediverso que pueda estar cerca.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_meetup_call',
        'category' => 'event',
        'name' => 'Llamada para meetup',
        'description' => 'Invita a la gente a un encuentro de la comunidad.',
        'content' => "Llamada de la comunidad de {{brand_name}} este [día] a las [hora UTC].\n\nAgenda: [tema], [tema], Q&A abierto.\n\nLink: [link del video]. Las notas suben después en [link]. Sin login obligatorio.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_event_recap',
        'category' => 'event',
        'name' => 'Recap del evento',
        'description' => 'Resume un evento con aprendizajes concretos.',
        'content' => "De vuelta de [evento]. Tres cosas que se nos quedaron:\n\n1. [Aprendizaje específico].\n2. [Aprendizaje específico].\n3. [Aprendizaje específico].\n\nLas slides de nuestra charla están arriba: [link]. Gracias a quienes pasaron por la mesa.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // engagement
    [
        'slug' => 'mastodon_what_are_you_using',
        'category' => 'engagement',
        'name' => 'Qué estás usando',
        'description' => 'Pregunta qué herramientas o setups usa la gente.',
        'content' => "Curiosidad: qué está usando el fediverso para [tarea específica] en [año].\n\nNosotros estamos en [setup actual] y es [evaluación honesta]. Quiero saber por qué lo cambiarías y por qué.\n\nResponde con la herramienta y una frase sobre el tradeoff.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mastodon_show_your_work',
        'category' => 'engagement',
        'name' => 'Muestra tu trabajo',
        'description' => 'Invita a la gente a mostrar lo que está construyendo.',
        'content' => "Hilo de muestra-y-cuenta: ¿qué estás construyendo esta semana?\n\nEmpezamos. {{brand_name}} está trabajando en [cosa]. Está en [etapa] y estamos atascados en [problema].\n\nResponde con el tuyo. Boosts bienvenidos para que otros lo encuentren.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
