<?php

declare(strict_types=1);

return [
    [
        'slug' => 'pinterest_how_to',
        'category' => 'educational',
        'name' => 'Pin de tutorial',
        'description' => 'Pin paso a paso que genera guardados y clics.',
        'content' => "Cómo [lograr resultado] en [tiempo/esfuerzo].\n\nUna guía simple de {{brand_name}}.\n\nPaso 1: [Acción]\nPaso 2: [Acción]\nPaso 3: [Acción]\n\nTutorial completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['tutorial', 'how-to', 'guide'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_inspiration',
        'category' => 'behind_the_scenes',
        'name' => 'Tablero de inspiración',
        'description' => 'Pin inspirador en torno a un tema o estética.',
        'content' => "Inspiración de [tema], curada por {{brand_name}}.\n\nGuarda este pin para después.\n\nMás en → [link]",
        'image_count' => 1,
        'image_keywords' => ['inspiration', 'aesthetic', 'mood'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_product_showcase',
        'category' => 'product_launch',
        'name' => 'Vitrina de producto',
        'description' => 'Destaca un producto con una descripción que invita al clic.',
        'content' => "[Nombre del producto] de {{brand_name}}.\n\n[Descripción corta enfocada en beneficio, qué es, por qué importa.]\n\nCompra el look → [link]",
        'image_count' => 1,
        'image_keywords' => ['product', 'showcase', 'lifestyle'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_new_arrival',
        'category' => 'product_launch',
        'name' => 'Pin de novedad',
        'description' => 'Anuncia un producto nuevo con palabras clave de búsqueda.',
        'content' => "Novedad de {{brand_name}}: [nombre del producto].\n\n[Una frase sobre qué es y para quién es.]\n\nCaracterísticas principales:\n- [Característica 1]\n- [Característica 2]\n- [Característica 3]\n\nDisponible en [colores/tallas/opciones].\n\nCompra la colección [categoría] → [link]",
        'image_count' => 1,
        'image_keywords' => ['new product', 'launch', 'collection'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_collection_drop',
        'category' => 'product_launch',
        'name' => 'Pin de lanzamiento de colección',
        'description' => 'Presenta una colección curada de productos.',
        'content' => "Llegó la colección [nombre de la colección].\n\n{{brand_name}} reunió [número] piezas en torno a [tema o temporada].\n\nQué hay dentro:\n- [Tipo de artículo 1]\n- [Tipo de artículo 2]\n- [Tipo de artículo 3]\n\nPensada para [uso o público].\n\nMira la colección completa → [link]",
        'image_count' => 1,
        'image_keywords' => ['collection', 'lookbook', 'curated'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_pre_order',
        'category' => 'product_launch',
        'name' => 'Pin de preventa',
        'description' => 'Genera guardados y preventas para un producto que viene.',
        'content' => "Preventa abierta: [nombre del producto].\n\nLos envíos empiezan el [fecha]. Quienes compren en preventa de {{brand_name}} reciben [beneficio: acceso anticipado, regalo extra, precio fijo].\n\nPor qué comprar en preventa:\n- [Razón 1]\n- [Razón 2]\n\nReserva el tuyo → [link]",
        'image_count' => 1,
        'image_keywords' => ['pre-order', 'launch', 'early access'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_seasonal_sale',
        'category' => 'promotion',
        'name' => 'Pin de oferta de temporada',
        'description' => 'Promociona una oferta de temporada con descuento claro.',
        'content' => "Oferta de [temporada] en {{brand_name}}: [descuento]% off en [categoría].\n\nVálido hasta [fecha final].\n\nQué está en oferta:\n- [Categoría 1]\n- [Categoría 2]\n- [Categoría 3]\n\nUsa el código [CÓDIGO] al pagar.\n\nAprovecha la oferta → [link]",
        'image_count' => 1,
        'image_keywords' => ['sale', 'discount', 'seasonal shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_bundle_deal',
        'category' => 'promotion',
        'name' => 'Pin de combo',
        'description' => 'Pin de combo con precios en lista.',
        'content' => "El combo [nombre del combo] de {{brand_name}}.\n\nLleva [artículo 1] + [artículo 2] + [artículo 3] juntos y ahorra [monto].\n\nQué incluye:\n- [Artículo 1] (normalmente [precio])\n- [Artículo 2] (normalmente [precio])\n- [Artículo 3] (normalmente [precio])\n\nPrecio del combo: [precio].\n\nLlévate el combo → [link]",
        'image_count' => 1,
        'image_keywords' => ['bundle', 'value pack', 'savings'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_free_shipping',
        'category' => 'promotion',
        'name' => 'Pin de envío gratis',
        'description' => 'Pin con oferta centrada en envío gratis.',
        'content' => "Envío gratis en cada pedido de {{brand_name}}.\n\nSin mínimo, sin código. Hasta [fecha final].\n\nQué agregar al carrito:\n- [Más vendido 1]\n- [Más vendido 2]\n- [Más vendido 3]\n\nCompra ahora → [link]",
        'image_count' => 1,
        'image_keywords' => ['free shipping', 'offer', 'deal'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_clearance',
        'category' => 'promotion',
        'name' => 'Pin de liquidación',
        'description' => 'Mueve el inventario de liquidación con un pin que vale guardar.',
        'content' => "Liquidación en {{brand_name}}: hasta [descuento]% off.\n\nÚltimas rebajas en [categoría]. Cuando se acabe, se acabó.\n\nDestacados:\n- [Artículo 1], [precio]\n- [Artículo 2], [precio]\n- [Artículo 3], [precio]\n\nMira la liquidación → [link]",
        'image_count' => 1,
        'image_keywords' => ['clearance', 'final sale', 'markdown'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_recipe',
        'category' => 'educational',
        'name' => 'Pin de receta',
        'description' => 'Pin de receta que vale guardar, con ingredientes y pasos.',
        'content' => "[Nombre de la receta], lista en [tiempo].\n\nDirecto de la cocina de {{brand_name}}.\n\nIngredientes:\n- [Ingrediente 1]\n- [Ingrediente 2]\n- [Ingrediente 3]\n- [Ingrediente 4]\n\nPreparación:\n1. [Paso 1]\n2. [Paso 2]\n3. [Paso 3]\n\nRinde [número] porciones. Receta completa → [link]",
        'image_count' => 1,
        'image_keywords' => ['recipe', 'food', 'cooking'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_checklist',
        'category' => 'educational',
        'name' => 'Pin de checklist',
        'description' => 'Pin práctico de checklist hecho para guardar.',
        'content' => "El checklist de [tema] de {{brand_name}}.\n\n[Una frase sobre para quién es.]\n\nEl checklist:\n- [Ítem 1]\n- [Ítem 2]\n- [Ítem 3]\n- [Ítem 4]\n- [Ítem 5]\n\nGuarda este pin para tenerlo cuando lo necesites.\n\nDescarga la versión imprimible → [link]",
        'image_count' => 1,
        'image_keywords' => ['checklist', 'planner', 'printable'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_beginners_guide',
        'category' => 'educational',
        'name' => 'Pin de guía para principiantes',
        'description' => 'Pin explicativo amigable para quien empieza.',
        'content' => "[Tema] para principiantes.\n\nSi eres nuevo en [tema], empieza aquí. {{brand_name}} reunió lo básico.\n\nLo que tienes que saber:\n1. [Concepto 1]\n2. [Concepto 2]\n3. [Concepto 3]\n\nError común de principiante: [error].\n\nLee la guía completa → [link]",
        'image_count' => 1,
        'image_keywords' => ['beginner guide', 'basics', 'tutorial'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_diy_tutorial',
        'category' => 'educational',
        'name' => 'Pin de tutorial DIY',
        'description' => 'Pin de proyecto hazlo tú mismo con lista de materiales.',
        'content' => "DIY [nombre del proyecto] en [tiempo].\n\nUn proyecto de fin de semana de {{brand_name}}.\n\nQué necesitas:\n- [Material 1]\n- [Material 2]\n- [Material 3]\n- [Herramienta 1]\n\nLos pasos:\n1. [Paso 1]\n2. [Paso 2]\n3. [Paso 3]\n\nCosto estimado: [monto].\n\nTutorial completo con fotos → [link]",
        'image_count' => 1,
        'image_keywords' => ['DIY', 'craft project', 'handmade'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_studio_tour',
        'category' => 'behind_the_scenes',
        'name' => 'Pin de tour por el estudio',
        'description' => 'Lleva a los seguidores dentro del espacio de trabajo.',
        'content' => "Dentro del estudio de {{brand_name}}.\n\n[Una frase sobre lo que pasa aquí.]\n\nTres cosas que vas a notar:\n- [Detalle 1]\n- [Detalle 2]\n- [Detalle 3]\n\n[Una nota sobre el espacio, el equipo o la rutina.]\n\nMás fotos del estudio → [link]",
        'image_count' => 1,
        'image_keywords' => ['studio', 'workspace', 'creative space'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_process_pin',
        'category' => 'behind_the_scenes',
        'name' => 'Pin de proceso de producción',
        'description' => 'Muestra el oficio detrás del producto.',
        'content' => "Cómo {{brand_name}} hace [producto].\n\nDe [materia prima] a la pieza terminada, cada paso ocurre [dónde].\n\nEl proceso:\n1. [Etapa 1]\n2. [Etapa 2]\n3. [Etapa 3]\n4. [Etapa 4]\n\nTiempo total por pieza: [duración].\n\nMira el proceso completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['handmade', 'craft', 'process'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_founder_story',
        'category' => 'behind_the_scenes',
        'name' => 'Pin de historia del fundador',
        'description' => 'Pin personal sobre el origen de la marca.',
        'content' => "Cómo empezó {{brand_name}}.\n\n[Nombre del fundador] lanzó [marca] en [año] después de [momento de origen].\n\n[Dos frases cortas sobre el porqué y los primeros días.]\n\nQué hace diferente nuestra forma de trabajar:\n- [Valor 1]\n- [Valor 2]\n\nLee la historia completa → [link]",
        'image_count' => 1,
        'image_keywords' => ['founder story', 'small business', 'brand story'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_customer_review',
        'category' => 'testimonial',
        'name' => 'Pin de reseña de cliente',
        'description' => 'Pin con cita directa de un cliente real.',
        'content' => "\"[Reseña del cliente sobre el producto].\"\n- [Nombre del cliente], [ciudad o contexto]\n\nLos clientes de {{brand_name}} dejan reseñas así cada semana.\n\nQué compró [nombre del cliente]: [nombre del producto].\nPor qué lo compró: [razón].\n\nLee más reseñas → [link]",
        'image_count' => 1,
        'image_keywords' => ['customer review', 'testimonial', 'social proof'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_before_after',
        'category' => 'testimonial',
        'name' => 'Pin de antes y después',
        'description' => 'Pin de transformación visual.',
        'content' => "Antes y después con [producto o servicio] de {{brand_name}}.\n\nAntes: [estado inicial].\nDespués: [resultado final].\nTiempo: [duración].\n\nQué usó [nombre del cliente]:\n- [Artículo 1]\n- [Artículo 2]\n\n[Una frase sobre la reacción del cliente.]\n\nMira más antes y después → [link]",
        'image_count' => 1,
        'image_keywords' => ['before and after', 'transformation', 'results'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_case_study',
        'category' => 'testimonial',
        'name' => 'Pin de caso de éxito',
        'description' => 'Mini caso de éxito con números concretos.',
        'content' => "Caso de éxito: cómo [nombre del cliente] usó {{brand_name}} para [resultado].\n\nLa situación: [una frase].\nQué probaron: [producto o servicio].\nEl resultado: [número o resultado específico] en [periodo].\n\nPor qué funcionó:\n- [Razón 1]\n- [Razón 2]\n\nLee el caso de éxito completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['case study', 'results', 'success story'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_pro_tip',
        'category' => 'industry_tip',
        'name' => 'Pin de consejo profesional',
        'description' => 'Pin con un solo consejo y beneficio claro.',
        'content' => "Consejo profesional: [consejo en una frase].\n\nLa mayoría [error común]. La solución es [la técnica real].\n\nPor qué funciona: [una frase con la razón].\n\nCuándo usarlo: [contexto o escenario].\n\nMás consejos de [tema] de {{brand_name}} → [link]",
        'image_count' => 1,
        'image_keywords' => ['pro tip', 'expert advice', 'industry tips'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_common_mistakes',
        'category' => 'industry_tip',
        'name' => 'Pin de errores comunes',
        'description' => 'Lista de errores que el lector puede evitar.',
        'content' => "[Número] errores de [tema] que evitar.\n\n{{brand_name}} los ve cada semana. Guarda el pin para no repetirlos.\n\nLos errores:\n1. [Error 1], haz esto en su lugar: [solución]\n2. [Error 2], haz esto en su lugar: [solución]\n3. [Error 3], haz esto en su lugar: [solución]\n\nLee el análisis completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['common mistakes', 'tips', 'expert advice'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_industry_stat',
        'category' => 'industry_tip',
        'name' => 'Pin de estadística del sector',
        'description' => 'Pin basado en dato que ancla un insight útil.',
        'content' => "[Estadística con número]% de [público] [comportamiento].\nFuente: [fuente, año].\n\nQué significa para ti: [una frase sobre la implicación].\n\nTres formas en que los clientes de {{brand_name}} responden:\n- [Táctica 1]\n- [Táctica 2]\n- [Táctica 3]\n\nLee el reporte completo → [link]",
        'image_count' => 1,
        'image_keywords' => ['industry data', 'statistics', 'research'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_workshop',
        'category' => 'event',
        'name' => 'Pin de taller',
        'description' => 'Pin para promocionar un taller presencial u online.',
        'content' => "[Nombre del taller] con {{brand_name}}.\n\n[Fecha] · [hora] · [lugar u online].\n\nQué vas a aprender:\n- [Aprendizaje 1]\n- [Aprendizaje 2]\n- [Aprendizaje 3]\n\nPara quién es: [público].\nCupos: [número] limitados.\nPrecio: [monto].\n\nReserva tu lugar → [link]",
        'image_count' => 1,
        'image_keywords' => ['workshop', 'class', 'learning event'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_pop_up',
        'category' => 'event',
        'name' => 'Pin de tienda pop-up',
        'description' => 'Atrae público a una tienda pop-up.',
        'content' => "Tienda pop-up de {{brand_name}} en [ciudad].\n\n[Periodo] · [dirección] · [horario].\n\nQué vas a encontrar:\n- [Categoría 1]\n- [Categoría 2]\n- [Exclusivo en tienda]\n\n[Una frase sobre lo que hace que el día valga la pena.]\n\nMira cómo llegar y los detalles → [link]",
        'image_count' => 1,
        'image_keywords' => ['pop-up shop', 'event', 'in-person shopping'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_webinar',
        'category' => 'event',
        'name' => 'Pin de webinar',
        'description' => 'Promociona un webinar gratuito o pago.',
        'content' => "Webinar gratuito: [tema].\n\nPresentado por {{brand_name}} el [fecha] a las [hora, zona horaria].\n\nQué vamos a cubrir:\n- [Punto 1]\n- [Punto 2]\n- [Punto 3]\n\nPara quién es: [público].\nGrabación: enviada a todos los inscritos.\n\nReserva tu lugar → [link]",
        'image_count' => 1,
        'image_keywords' => ['webinar', 'online event', 'training'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_holiday_event',
        'category' => 'event',
        'name' => 'Pin de evento festivo',
        'description' => 'Pin de evento o promoción con tema festivo.',
        'content' => "Evento de [festividad] de {{brand_name}}.\n\n[Fecha] · [lugar u online].\n\nEn la agenda:\n- [Actividad 1]\n- [Actividad 2]\n- [Actividad 3]\n\nQué esperar: [una frase].\nConfirma asistencia antes del [fecha].\n\nAgenda completa y RSVP → [link]",
        'image_count' => 1,
        'image_keywords' => ['holiday event', 'seasonal', 'celebration'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_question_pin',
        'category' => 'engagement',
        'name' => 'Pin de pregunta',
        'description' => 'Pin con pregunta que invita a comentar.',
        'content' => "[Pregunta abierta para el público].\n\n{{brand_name}} tiene curiosidad. Deja tu respuesta en los comentarios.\n\nAlgunas pistas para pensar:\n- [Pista 1]\n- [Pista 2]\n- [Pista 3]\n\nVamos a compartir las respuestas más interesantes la próxima semana.\n\nÚnete a la conversación → [link]",
        'image_count' => 1,
        'image_keywords' => ['question', 'community', 'discussion'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_this_or_that',
        'category' => 'engagement',
        'name' => 'Pin de esto o aquello',
        'description' => 'Pin de preferencia lado a lado.',
        'content' => "Esto o aquello: [opción A] u [opción B].\n\n{{brand_name}} quiere saber de qué lado estás. No hay respuesta incorrecta.\n\nA favor de [opción A]: [una frase].\nA favor de [opción B]: [una frase].\n\nVota en los comentarios. Vamos a contar los votos.\n\nMás encuestas → [link]",
        'image_count' => 1,
        'image_keywords' => ['poll', 'this or that', 'preference'],
        'slides' => null,
    ],
    [
        'slug' => 'pinterest_giveaway',
        'category' => 'engagement',
        'name' => 'Pin de sorteo',
        'description' => 'Pin que anuncia un sorteo con reglas claras.',
        'content' => "Sorteo de {{brand_name}}: gana [premio].\n\nUn ganador elegido el [fecha].\n\nCómo participar:\n1. Guarda este pin.\n2. Sigue a {{brand_name}} en Pinterest.\n3. Comenta con [pista].\n\nAbierto a: [región].\nValor: [monto].\n\nReglas completas → [link]",
        'image_count' => 1,
        'image_keywords' => ['giveaway', 'contest', 'prize'],
        'slides' => null,
    ],
];
