<?php

declare(strict_types=1);

return [
    [
        'slug' => 'threads_hot_take',
        'category' => 'industry_tip',
        'name' => 'Opinión polémica',
        'description' => 'Un post corto y opinado pensado para generar respuestas.',
        'content' => "Opinión impopular: [afirmación contraintuitiva sobre tu industria].\n\nPor qué pienso esto →\n\n[Razonamiento breve en 1 o 2 oraciones.]\n\n¿Estoy equivocado?",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_quick_tip',
        'category' => 'educational',
        'name' => 'Tip rápido',
        'description' => 'Un tip accionable, en tono corto y amigable.',
        'content' => "Tip rápido de {{brand_name}}:\n\n[Un tip único, específico y accionable.]\n\nSuena simple. Lo cambia todo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_question',
        'category' => 'engagement',
        'name' => 'Pregunta abierta',
        'description' => 'Hacele una pregunta a la comunidad para mover conversación.',
        'content' => "Pregunta sincera para la comunidad de {{brand_name}}:\n\n[Pregunta, abierta y suficientemente específica para responder.]\n\nNo hay respuestas equivocadas. Tengo curiosidad por leer las tuyas.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // PRODUCT LAUNCH
    [
        'slug' => 'threads_product_launch_soft',
        'category' => 'product_launch',
        'name' => 'Lanzamiento tranqui',
        'description' => 'Anuncio casual y discreto de algo nuevo.',
        'content' => "ok bueno. lanzamos [nombre del producto] hoy.\n\nllevo trabajando en esto [duración] y medio que no puedo creer que esté en vivo.\n\n[una cosa específica que hace y de la que estás orgulloso].\n\nsi lo probás, contame qué se rompe.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_product_launch_story',
        'category' => 'product_launch',
        'name' => 'Por qué lo construimos',
        'description' => 'Historia personal detrás del producto o feature nuevo.',
        'content' => "empecé a construir [nombre del producto] porque [frustración personal específica].\n\npensé que iba a llevar un fin de semana. llevó [tiempo real].\n\nestá en vivo ahora en {{brand_name}}. honestamente sigo sorprendido de que funcione.\n\nme encantaría escuchar qué pensás después de probarlo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_product_launch_feature',
        'category' => 'product_launch',
        'name' => 'Feature nuevo',
        'description' => 'Anuncia un solo feature dentro de un producto existente.',
        'content' => "cosa chica pero estoy raramente entusiasmado con esto.\n\n{{brand_name}} ahora [hace esta cosa específica].\n\nel motivo: la gente seguía pidiendo [la necesidad de fondo]. así que lo hicimos.\n\nestá en vivo. probalo y contame si es realmente útil o solo una cosa más ahora.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // PROMOTION
    [
        'slug' => 'threads_promo_discount',
        'category' => 'promotion',
        'name' => 'Descuento casual',
        'description' => 'Forma relajada de mencionar una promo o descuento.',
        'content' => "tenemos [monto de descuento] off en [producto o plan] esta semana en {{brand_name}}.\n\nno voy a hacer toda la cosa del contador. solo me pareció mencionarlo una vez y dejar que la gente decida.\n\ncódigo: [código]. termina [fecha].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_promo_bundle',
        'category' => 'promotion',
        'name' => 'Combo',
        'description' => 'Promociona un combo en tono relajado.',
        'content' => "combiné [item uno] e [item dos] juntos porque la gente igual los compraba en el mismo pedido.\n\nel par sale [precio] en {{brand_name}}, que son como [ahorro] menos que comprarlos por separado.\n\neso es. ese es el post.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_promo_last_chance',
        'category' => 'promotion',
        'name' => 'Último aviso',
        'description' => 'Empujoncito amigable de que una oferta termina.',
        'content' => "aviso amigable: [nombre de la oferta] termina [fecha o hora].\n\nno trato de ser pesado. algunos me pidieron que les recordara, así que considerá esto el recordatorio.\n\nlink en bio si lo querés. cero rencor si no.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // EDUCATIONAL
    [
        'slug' => 'threads_edu_mistake',
        'category' => 'educational',
        'name' => 'Error que cometí',
        'description' => 'Enseñar compartiendo un error personal.',
        'content' => "cometí el mismo error [número] veces antes de darme cuenta:\n\n[el error en una oración].\n\nla solución es [la solución real en palabras simples]. nada elegante. solo tuve que dejar de hacer la cosa.\n\nposteo por si estás trabado en el mismo loop.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_misconception',
        'category' => 'educational',
        'name' => 'Mito común',
        'description' => 'Corrige una creencia común pero equivocada.',
        'content' => "la gente me sigue diciendo [creencia común en tu rubro].\n\nasí no funciona.\n\n[lo que pasa de verdad, en palabras simples].\n\npuede ser obvio para algunos. aparentemente no para la mayoría de los que me escribieron la semana pasada.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_resource',
        'category' => 'educational',
        'name' => 'Recurso recomendado',
        'description' => 'Recomienda un recurso útil con contexto personal.',
        'content' => "si estás tratando de aprender [tema], dejá de mirar videos de 4 horas en youtube y leé [recurso específico].\n\nlo postergué meses porque el título es aburrido. es la única cosa que realmente me hizo clic.\n\nesa es la recomendación.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_edu_step_breakdown',
        'category' => 'educational',
        'name' => 'Cómo hacerlo rápido',
        'description' => 'Mini paso a paso en tono conversacional.',
        'content' => "el tema de [tarea] en 4 líneas para los que siguen preguntando:\n\n1. [paso uno]\n2. [paso dos]\n3. [paso tres]\n4. [paso cuatro]\n\nese es todo el proceso. no necesitás un curso para esto.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // BEHIND THE SCENES
    [
        'slug' => 'threads_bts_morning',
        'category' => 'behind_the_scenes',
        'name' => 'Rutina de mañana',
        'description' => 'Vistazo casual a cómo arranca un día de trabajo.',
        'content' => "hoy en {{brand_name}}:\n\n- café\n- miré [problema específico] por una hora\n- me di cuenta que el bug estaba en la línea [número]\n- lo arreglé en 4 minutos\n\nla proporción de pensar versus hacer en este trabajo está genuinamente maldita.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_decision',
        'category' => 'behind_the_scenes',
        'name' => 'Decisión que tomamos',
        'description' => 'Comparte una decisión interna y el razonamiento.',
        'content' => "decidimos [decisión específica] esta semana.\n\nla otra opción era [alternativa]. medio equipo quería esa. medio que yo sigo queriendo.\n\npero [el motivo real por el que ganó esta decisión].\n\npreguntame en 3 meses si fue la decisión correcta.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_messy_progress',
        'category' => 'behind_the_scenes',
        'name' => 'Avance desprolijo',
        'description' => 'Update honesto a mitad de proyecto.',
        'content' => "estado actual de [nombre del proyecto]:\n\n- [porcentaje] hecho\n- [cosa específica que está funcionando]\n- [cosa específica que no está funcionando]\n- [número] pestañas abiertas que tengo miedo de cerrar\n\nlo lanzo cuando deje de hacerme pasar vergüenza.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_bts_team_moment',
        'category' => 'behind_the_scenes',
        'name' => 'Momento del equipo',
        'description' => 'Pequeño momento humano del equipo.',
        'content' => "[nombre de alguien del equipo] mandó un mensaje en slack que decía \"[cita corta graciosa o ingeniosa]\" y ahora no podemos parar de citarla.\n\nconstruir {{brand_name}} con esta gente es la mitad del motivo por el que sigo gustándome el trabajo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // TESTIMONIAL
    [
        'slug' => 'threads_testimonial_quote',
        'category' => 'testimonial',
        'name' => 'Frase de cliente',
        'description' => 'Comparte una frase real de un cliente con contexto liviano.',
        'content' => "recibí este mail de [primer nombre o iniciales] ayer:\n\n\"[cita directa del cliente, 1 o 2 oraciones]\"\n\nlo leí dos veces. esta es la parte del trabajo que no aparece en las métricas.\n\ngracias por usar {{brand_name}}. de verdad.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_testimonial_outcome',
        'category' => 'testimonial',
        'name' => 'Resultado de cliente',
        'description' => 'Habla de un resultado real de un cliente sin alardear.',
        'content' => "[primer nombre del cliente] me dijo ayer que [resultado específico] después de usar {{brand_name}} por [período de tiempo].\n\nno le pedí que lo compartiera. solo mandó la captura y dijo \"pensé que querrías ver esto.\"\n\nsí. quería.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_testimonial_unexpected',
        'category' => 'testimonial',
        'name' => 'Uso inesperado',
        'description' => 'Resalta una forma sorprendente de usar el producto.',
        'content' => "no me lo esperaba.\n\nalguien usando {{brand_name}} para [uso inesperado]. no era para lo que lo construimos. aparentemente funciona.\n\nparte favorita de lanzar cosas es enterarse qué hace la gente con ellas.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // INDUSTRY TIP
    [
        'slug' => 'threads_industry_observation',
        'category' => 'industry_tip',
        'name' => 'Observación del rubro',
        'description' => 'Comparte un patrón que venís notando en tu campo.',
        'content' => "cosa que vengo notando en [industria]:\n\n[observación específica en una oración].\n\npodría ser un cambio real. podría ser sesgo de selección de con quién hablo. contame si lo estás viendo también.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_lesson',
        'category' => 'industry_tip',
        'name' => 'Lección de la experiencia',
        'description' => 'Una lección difícilmente aprendida, sin relleno.',
        'content' => "[número] años en [industria] y la lección que más me costó creer:\n\n[la lección en una oración].\n\ntodavía me pesco ignorándola. después algo se rompe. después me acuerdo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_pushback',
        'category' => 'industry_tip',
        'name' => 'Contra el saber común',
        'description' => 'Discrepa educadamente con un consejo común.',
        'content' => "el consejo estándar en [industria] es [consejo común].\n\nvengo haciendo lo opuesto desde hace [período de tiempo]. funciona mejor para mí, al menos.\n\n[motivo breve].\n\nno digo que todos deberían. solo que la regla no es una regla.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_industry_prediction',
        'category' => 'industry_tip',
        'name' => 'Predicción tranqui',
        'description' => 'Hace una predicción sin pavonearse.',
        'content' => "predicción chica:\n\nen [horizonte de tiempo], [cambio específico en tu industria] va a ser normal.\n\npuedo estar totalmente equivocado. guardo esto para volver y reírme de mí mismo después.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // EVENT
    [
        'slug' => 'threads_event_announcement',
        'category' => 'event',
        'name' => 'Anuncio de evento',
        'description' => 'Anuncia casualmente un evento próximo.',
        'content' => "{{brand_name}} va a hacer [nombre del evento] el [fecha].\n\n[una o dos oraciones sobre qué es realmente y a quién le interesaría].\n\n[lugar o link]. avisale a un amigo si parece su tipo de cosa.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_event_recap',
        'category' => 'event',
        'name' => 'Resumen de evento',
        'description' => 'Resumen honesto después de un evento.',
        'content' => "volví de [nombre del evento].\n\nla mejor parte fue [momento o conversación específica].\n\nla parte más rara fue [observación honesta].\n\nsi estuviste y no llegamos a hablar, escribime. siempre hay más para decir cuando termina el panel.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_event_invite',
        'category' => 'event',
        'name' => 'Invitación personal',
        'description' => 'Invitación directa que se siente personal.',
        'content' => "voy a hacer un [tipo de evento] chico para {{brand_name}} el [fecha] y realmente quiero que estés.\n\nes [duración] y vamos a hablar de [tema específico].\n\nconfirmá en [link] si querés entrar. lo limito a [número] para que sea una conversación de verdad.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // ENGAGEMENT
    [
        'slug' => 'threads_engagement_recommendation',
        'category' => 'engagement',
        'name' => 'Pedido de recomendación',
        'description' => 'Pedile recomendaciones a tu audiencia.',
        'content' => "buscando recomendaciones:\n\n[cosa específica para la que necesitás recomendaciones].\n\nya probé [opción a] y [opción b]. necesito algo que [restricción específica].\n\nla mejor respuesta se gana mi gratitud eterna. ese es el premio.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_engagement_this_or_that',
        'category' => 'engagement',
        'name' => 'Esto o aquello',
        'description' => 'Pregunta binaria rápida para mover respuestas.',
        'content' => "[opción a] u [opción b].\n\nsin término medio. sin \"depende\". elegí una y contame por qué.\n\nestamos teniendo la versión {{brand_name}} de este debate en el chat del equipo y estamos profunda, profundamente divididos.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'threads_engagement_confession',
        'category' => 'engagement',
        'name' => 'Pequeña confesión',
        'description' => 'Comparte algo chico y con el que la gente se identifica.',
        'content' => "pequeña confesión.\n\ntodavía [costumbre algo vergonzosa relacionada a tu trabajo o vida].\n\ndecime que no soy el único. o decime que soy el único. de cualquier forma me gustaría saber.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
