<?php

declare(strict_types=1);

return [
    [
        'slug' => 'flash_sale',
        'category' => 'promotion',
        'name' => 'Oferta relámpago',
        'description' => 'Post corto en X para una oferta relámpago con urgencia.',
        'content' => "🔥 ¡Oferta relámpago en {{brand_name}}!\n\n[Descuento]% off en [producto/servicio], termina en 24 horas.\n\nSin código → [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'success_story',
        'category' => 'testimonial',
        'name' => 'Caso de éxito',
        'description' => 'Formato breve de caso de éxito para X.',
        'content' => "\"[Cita corta del cliente.]\"\n- @[handle]\n\nPor esto hacemos lo que hacemos en {{brand_name}}. 🙌",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'this_or_that_poll',
        'category' => 'engagement',
        'name' => 'Esto o aquello',
        'description' => 'Genera engagement con una elección binaria simple.',
        'content' => "Pregunta rápida para la comunidad de {{brand_name}}:\n\n¿[Opción A] o [Opción B]?\n\nResponde con tu elección y por qué 👇",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // product_launch
    [
        'slug' => 'shipped_today',
        'category' => 'product_launch',
        'name' => 'Lanzado hoy',
        'description' => 'Anuncio casual de release con un cambio concreto.',
        'content' => "Lanzado hoy: [feature].\n\nHace [cosa específica] para que dejes de [solución incómoda].\n\nYa está activo en {{brand_name}}.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'new_feature_one_liner',
        'category' => 'product_launch',
        'name' => 'Feature en una línea',
        'description' => 'Pitch de una frase para una nueva feature.',
        'content' => "{{brand_name}} ahora [hace cosa específica].\n\nSi has estado [haciendo solución dolorosa], pruébalo: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'beta_invite',
        'category' => 'product_launch',
        'name' => 'Invitación al beta',
        'description' => 'Llamada abierta para testers del beta.',
        'content' => "Abrimos beta de [feature] esta semana.\n\nBuscamos [número] personas que [caso de uso].\n\nResponde si eres tú.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'finally_built_it',
        'category' => 'product_launch',
        'name' => 'Por fin lo hicimos',
        'description' => 'Tono honesto de "tardamos pero salió".',
        'content' => "Por fin construimos [feature]. La gente lo pedía desde [período].\n\nYa está activo en {{brand_name}} hoy. Perdón por la demora.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // promotion
    [
        'slug' => 'weekend_deal',
        'category' => 'promotion',
        'name' => 'Oferta de fin de semana',
        'description' => 'Post de descuento solo en fin de semana.',
        'content' => "Solo el fin de semana: [descuento] off en [producto] en {{brand_name}}.\n\nCódigo [CODE]. Termina domingo a medianoche. Eso es todo.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'free_shipping',
        'category' => 'promotion',
        'name' => 'Envío gratis',
        'description' => 'Anuncio de ventana de envío gratis.',
        'content' => "Envío gratis en pedidos de {{brand_name}} sobre $[monto] esta semana.\n\nSin código, sin trampas. Vuelve a lo normal el lunes.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'last_call',
        'category' => 'promotion',
        'name' => 'Última llamada',
        'description' => 'Últimas horas de una oferta.',
        'content' => "Última llamada. [Nombre de la oferta] termina hoy a las [hora].\n\nSi tienes {{brand_name}} en el carrito, es el precio más bajo del año: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'bundle_offer',
        'category' => 'promotion',
        'name' => 'Oferta combo',
        'description' => 'Presenta un combo como oferta económica.',
        'content' => "Nuevo combo en {{brand_name}}: [Producto A] + [Producto B] por [precio].\n\nSon [monto] menos que comprarlos por separado. Solo [cantidad] unidades.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // educational
    [
        'slug' => 'one_thing_we_learned',
        'category' => 'educational',
        'name' => 'Algo que aprendimos',
        'description' => 'Comparte una lección concreta.',
        'content' => "Algo que aprendimos en {{brand_name}} este mes:\n\n[Hallazgo]. Pensábamos [suposición vieja], pero [dato] probó lo contrario.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'common_mistake',
        'category' => 'educational',
        'name' => 'Error común',
        'description' => 'Señala un error que comete la gente.',
        'content' => "La mayoría se equivoca en [tema] porque [error común].\n\nLo que sí funciona: [contra-enfoque]. Lo probamos con [número] clientes.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'quick_tip',
        'category' => 'educational',
        'name' => 'Tip rápido',
        'description' => 'Tip corto y accionable.',
        'content' => "Tip rápido si usas {{brand_name}}:\n\n[Acción] antes de [paso]. Te ahorra unos [tiempo/resultado] a la mayoría.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'myth_vs_reality',
        'category' => 'educational',
        'name' => 'Mito vs realidad',
        'description' => 'Derriba un mito del sector.',
        'content' => "Mito: [creencia común sobre el tema].\n\nRealidad: [contra-dato con número]. Lo vemos en datos de {{brand_name}} cada semana.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // behind_the_scenes
    [
        'slug' => 'how_we_built_it',
        'category' => 'behind_the_scenes',
        'name' => 'Cómo lo construimos',
        'description' => 'Vistazo casual detrás de cámaras.',
        'content' => "Cómo construimos [feature] en {{brand_name}}:\n\nEmpezamos con [primer intento]. Se rompió. Cambiamos a [enfoque 2]. Eso fue lo que salió.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'team_at_work',
        'category' => 'behind_the_scenes',
        'name' => 'Equipo trabajando',
        'description' => 'Foto de lo que el equipo está haciendo ahora.',
        'content' => "Lo que el equipo de {{brand_name}} está haciendo ahora:\n\n[Persona/rol] debugueando [problema]. [Persona/rol] en [otro proyecto]. Nivel de café: alto.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'mistake_we_made',
        'category' => 'behind_the_scenes',
        'name' => 'Error que cometimos',
        'description' => 'Postmortem honesto en un tweet.',
        'content' => "La regamos en {{brand_name}} la semana pasada.\n\n[Qué se rompió]. Afectó a [número] clientes con [impacto]. Lo arreglamos [cómo]. Perdón a los afectados.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'office_moment',
        'category' => 'behind_the_scenes',
        'name' => 'Momento de oficina',
        'description' => 'Escena pequeña y humana de oficina.',
        'content' => "Momento aleatorio en la oficina de {{brand_name}}:\n\n[Escena, ej.: diseñador peleando con dev por 2px de border-radius]. Es así casi todos los días.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // testimonial
    [
        'slug' => 'customer_dm',
        'category' => 'testimonial',
        'name' => 'DM de cliente',
        'description' => 'Comparte un mensaje real de cliente.',
        'content' => "Me llegó este DM de un cliente de {{brand_name}} hoy:\n\n\"[Cita corta sobre lo que cambió para él].\"\n\nEs la parte del trabajo que no cansa.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'before_and_after',
        'category' => 'testimonial',
        'name' => 'Antes y después',
        'description' => 'Números concretos de antes/después de un cliente.',
        'content' => "[Cliente] antes de {{brand_name}}: [métrica].\n\n[Cliente] después de [período]: [nueva métrica].\n\nNada más cambió en su setup.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'one_line_review',
        'category' => 'testimonial',
        'name' => 'Reseña de una línea',
        'description' => 'Frase corta de un cliente.',
        'content' => "\"[Frase específica del cliente, máximo 12 palabras.]\"\n\n- [Cliente], [cargo] en [empresa]\n\nNo le pedimos que escribiera eso.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // industry_tip
    [
        'slug' => 'hot_take',
        'category' => 'industry_tip',
        'name' => 'Opinión fuerte',
        'description' => 'Opinión con punto de vista sobre el sector.',
        'content' => "Opinión fuerte: la mayoría en [sector] cree que [creencia común].\n\nDespués de [tiempo] con {{brand_name}}, pienso lo opuesto. [Razón].",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'overrated_underrated',
        'category' => 'industry_tip',
        'name' => 'Sobrevalorado subvalorado',
        'description' => 'Junta algo sobrevalorado y algo subvalorado.',
        'content' => "Sobrevalorado en [sector]: [práctica común].\n\nSubvalorado: [práctica ignorada].\n\nDejamos la primera en {{brand_name}} hace un año.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'unpopular_opinion',
        'category' => 'industry_tip',
        'name' => 'Opinión impopular',
        'description' => 'Comparte una observación contraria.',
        'content' => "Opinión impopular: [afirmación contraria sobre el sector].\n\nLos clientes de {{brand_name}} lo prueban cada mes. Los datos no son sutiles.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'what_changed_my_mind',
        'category' => 'industry_tip',
        'name' => 'Lo que me hizo cambiar',
        'description' => 'Momento honesto de cambiar de opinión.',
        'content' => "Antes pensaba [creencia vieja sobre el sector].\n\nLuego pasó [evento/dato] en {{brand_name}}. Ahora creo [nueva visión]. Todavía ajustando.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // event
    [
        'slug' => 'event_announcement',
        'category' => 'event',
        'name' => 'Anuncio de evento',
        'description' => 'Anuncio simple de evento.',
        'content' => "{{brand_name}} organiza [nombre del evento] el [fecha] en [ciudad].\n\n[Tema]. Gratis, [capacidad] cupos. Regístrate: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'event_recap',
        'category' => 'event',
        'name' => 'Recap del evento',
        'description' => 'Resumen corto después de un evento.',
        'content' => "[Número] personas en el [evento] de {{brand_name}} anoche.\n\nPregunta favorita: \"[pregunta real del público].\" La grabación sale el viernes.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'webinar_reminder',
        'category' => 'event',
        'name' => 'Recordatorio de webinar',
        'description' => 'Recordatorio de que un webinar empieza pronto.',
        'content' => "Recordatorio: webinar de {{brand_name}} sobre [tema] empieza en [tiempo].\n\n[Speaker] va a mostrar [cosa específica]. Última chance para registrarte: [link]",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],

    // engagement
    [
        'slug' => 'open_question',
        'category' => 'engagement',
        'name' => 'Pregunta abierta',
        'description' => 'Hazle una pregunta real al público.',
        'content' => "Pregunta sincera para quien usa [herramienta/categoría]:\n\n¿Qué es lo único que aún no hace y te gustaría que hiciera?\n\nPregunto porque {{brand_name}} está trabajando en eso.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'fill_in_the_blank',
        'category' => 'engagement',
        'name' => 'Completa la frase',
        'description' => 'Provocación ligera tipo completa la frase.',
        'content' => "Completa:\n\nLo peor de [tarea/tema] es ______.\n\nLeo cada respuesta. Vamos a usarlas para planear el próximo trimestre de {{brand_name}}.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
    [
        'slug' => 'show_us_your_setup',
        'category' => 'engagement',
        'name' => 'Muéstranos tu setup',
        'description' => 'Pide a la gente que comparta algo visual.',
        'content' => "Muéstranos tu [cosa, escritorio, dashboard, rutina semanal].\n\nVamos a destacar nuestros tres favoritos en la cuenta de {{brand_name}} la próxima semana. Sin filtro.",
        'image_count' => 0,
        'image_keywords' => null,
        'slides' => null,
    ],
];
